lablup/backend.ai-webui

react/src/pages/EndpointListPage.tsx
Improved the delete functionality for endpoints in the EndpointListPage component.
- **Replaced the Popconfirm component with a modal confirmation dialog for deleting endpoints.**
- Removed the `terminatingModelService` state and directly used the row data for deletion.
- Updated the error handling and success messages for the terminate mutation.
- Simplified the delete button's onClick handler.
1. Navigate to the EndpointListPage.
2. Attempt to delete an endpoint by clicking the delete button.
3. Verify that a modal confirmation dialog appears.
4. Confirm the deletion and check if the endpoint is removed successfully.
5. Test error scenarios by mocking a failed deletion and verify error messages.
This change enhances the user experience by providing a more robust and consistent deletion …
=> feat: show confirm modal instead of popconfirm when deleting endpoint

react/src/App.tsx, react/src/components/ServiceLauncherPageContent.tsx, react/src/pages/EndpointDetailPage.tsx, react/src/pages/EndpointListPage.tsx
=> pagination and filter with deferred values

react/src/components/AgentList.tsx
Refactored the AgentList component to improve type safety and code readability.
- Improved type safety by explicitly defining types for `parsedOccupiedSlots` and `parsedAvailableSlots`.
- Refactored the rendering logic for resource allocation to use a more consistent approach across different resource types.
- Simplified calculations for percentage values and improved variable naming.
- Consolidated duplicate code into reusable logic for CPU, memory, and other resource types.
1. Navigate to the Agent List view in the application.
2. Verify that the allocation information for CPU, memory, and other resources is displayed correctly.
3. Check that the progress bars accurately reflect the resource usage percentages.
4. Ensure that the color coding (red for high usage, green for normal usage) …
=> refactor: percent calcuation and typescript deifinition in agent list

react/src/components/ResourceAllocationFormItems.tsx, react/src/components/ServiceLauncherPageContent.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/th.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json
This PR resolves the issue where the endpoint's resource allocation values are not displayed when modifying the model service, and the first allocatable preset is automatically selected.
The logic was changed as follows:
- case 1: `allowCustomResourceAllocation = false`
- Hide resource group select and preset select. and display current value like below: 
- If the user click the "Change" button, the preset select component is shown with automatic selection of preset
- case 2: `allowCustomResourceAllocation = true`
- When modifying, the `allocationPreset` field is set to custom.
=> fix: modification of "model service's resource"

react/src/pages/EndpointListPage.tsx, src/lib/backend.ai-client-esm.ts
Added support for endpoint lifecycle stage filtering based on server version compatibility.
- Introduced a new feature flag 'endpoint-lifecycle-stage-filter' in the backend client for version 24.03.10 and above.
- Modified the EndpointListPage to conditionally render the lifecycle stage filter Radio.Group based on server support.
- Adjusted the API request to include the lifecycle stage filter only when supported by the server.
1. Ensure you're using a backend server version 24.03.10 or higher.
2. Navigate to the Endpoint List Page.
3. Verify that the lifecycle stage filter (Active/Destroyed) is visible.
4. Test the filter by selecting different options and confirm that the endpoint list updates accordingly.
5. Check that the API requests include the lifecycle stage filter parameter.
This …
=> fix: compatibility for lifecycle filter of Endpoint

react/src/helper/index.test.tsx, react/src/helper/index.tsx
Enhanced unit parsing functionality and added comprehensive tests for the `parseUnit` function.
- Updated the regular expression in `parseUnit` function to handle more edge cases, including numbers with leading decimal points.
- Added extensive unit tests for the `parseUnit` function to cover various scenarios.
- Included an additional test case for `iSizeToSize` function to handle zero input.
1. Run the updated test suite for the `parseUnit` function.
2. Verify that all new test cases pass, including:
- Parsing numbers with different units (px, em, %)
- Parsing numbers without units
- Handling invalid inputs
- Edge cases like '0', '0px', and '.5em'
3. Check that the `iSizeToSize` function correctly handles zero input.
This change improves the robustness of the `parseUnit` function, …
=> test: add more edge cases of `iSizeToSize` and `parseUnit`

react/src/pages/EndpointDetailPage.tsx, react/src/pages/EndpointListPage.tsx
An update that prevents modifications to an endpoint in `destroyed` and `destroying` state.
- Updated status checks to include both 'destroying' and 'destroyed' states
- Disabled certain buttons and actions when an endpoint is in 'destroying' or 'destroyed' state
[Additionally]
- Changed "LLM Playground" tooltip to "LLM Chat Test" in EndpointDetailPage
1. Navigate to the Endpoint List and Detail pages
2. Verify that buttons are properly disabled for endpoints in 'destroying' or 'destroyed' states
3. Check that the tooltip for the LLM chat test button now reads "LLM Chat Test"
4. Attempt to perform actions on endpoints in various states to ensure correct behavior
This change improves the user experience by:
1. Providing more accurate UI feedback for endpoint statuses
2. Preventing actions …
=> fix: disable edit button based on endpoint status

react/src/components/InputNumberWithSlider.tsx, react/src/components/ResourceAllocationFormItems.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/th.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json
Normally, users cannot set the value above the maximum limit because it automatically changes when the user focuses out of the input (blur event). However, it can be set programmatically above the maximum limit. For example, on the model service modification page, the existing model service can have a value above the maximum limit.
This PR added maximum value validation for CPU and memory allocation in the resource allocation form.
- Added a new rule to validate the maximum CPU value based on resource limits.
- Implemented a validator for memory allocation to ensure it doesn't exceed the maximum limit.
- Added a new translation key "MaxValueNotification" across all language files to support the new validation messages.
1. Open model service modification page.
2. Change [the initialValue …
=> feat: add max validation rule for CPU and memory in Form.Item.

react/src/components/ResourceAllocationFormItems.tsx
Fixed form field value retrieval for accelerator type in ResourceAllocationFormItems component.
Updated the `ensureValidAcceleratorType` function(#2628) to correctly retrieve the accelerator type from the form. The previous implementation was incorrectly nested, potentially leading to undefined values. The new implementation directly accesses the 'resource.acceleratorType' field.
Please ref to the #2628 's "How to test" section
This change ensures that the correct accelerator type is always retrieved from the form, preventing potential bugs or unexpected behavior when validating or updating the accelerator type. It improves the reliability of the resource allocation process and enhances the overall user experience when configuring resources.
=> fix: remove duplicated `form.getFieldValue` in `ensureValidAcceleratorType`

config.toml.sample, e2e/config-test.toml, e2e/config.test.ts, e2e/test-util.ts, react/src/components/ImageEnvironmentSelectFormItems.tsx, react/src/hooks/index.tsx, src/components/backend-ai-login.ts
Added option to show all environment images, regardless of installation status.
- Introduced a new configuration option `showNonInstalledImages` in `config.toml.sample`
- Updated `ImageEnvironmentSelectFormItems` component to use the new configuration
- Added `showNonInstalledImages` to the `BackendAIConfig` type
- Implemented the new configuration in the `BackendAILogin` component
=> add: convert showing all environment images including uninstalled ones by config

react/src/components/VFolderTable.tsx, react/src/hooks/backendai.tsx, react/src/pages/SessionLauncherPage.tsx
Modified `_.merge()` calls to include an empty object as the first argument.
This PR fixed a bug where the user could not turn on the "Use automatic OpenMP optimization" option after turning it off in the Neo Session Launcher.
Updated three instances of `_.merge()` function calls in different files:
1. In `VFolderTable.tsx`, added an empty object as the first argument to `mergedVFolderPermissions`.
2. In `backendai.tsx`, added an empty object as the first argument when merging `deviceMetadata` and `resourceSlots`.
3. In `SessionLauncherPage.tsx`, added an empty object as the first argument when merging `INITIAL_FORM_VALUES` and `formValuesFromQueryParams`.
The addition of an empty object as the first argument in `_.merge()` calls ensures that the original objects are not modified during …
=> fix: object merging with mutation in VFolderTable, hooks, and SessionLauncherPage

src/components/backend-ai-folder-explorer.ts
Updated the error color for mwc-textfield in the folder explorer component.
|before|after|
|---|---|
|![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/lSyr8xXz1wdXALkJKzVx/02c9ccb9-38d7-4fa7-91b4-a2c80f9417dd.png)|![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/lSyr8xXz1wdXALkJKzVx/32f67160-3461-4ce0-b41c-b67da9954a80.png)|
1. Navigate to the folder explorer component in the UI.
2. Trigger an error state in any textfield within the component.
3. Verify that the error color matches the `--token-colorError` defined in the theme.
This change ensures consistency in error color representation across the application by using the predefined `--token-colorError` variable. It improves the visual coherence of the UI and maintains a uniform look for …
=> fix: use antd color token for invalid mwc-textfield theme

react/src/components/ImportFromHuggingFaceModal.tsx, react/src/components/VFolderSelect.tsx, react/src/pages/VFolderListPage.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/th.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json
Add a new feature to import from Hugging Face in the VFolderListPage.
1. Modified `config.toml.sample` for indentation fix.
2. Added `ImportFromHuggingFaceModal` component to `react/src/components`.
3. Integrated `ImportFromHuggingFaceModal` in `VFolderListPage`.
4. Added new buttons and toggle functionality to `VFolderListPage.tsx`.
5. Updated language JSON files to include new translations for the Hugging Face import feature.
1. [Remove this line ](https://github.com/lablup/backend.ai-webui/pull/2514/files#diff-65e44191bce624d5e51a52298306cdece45d544cfb5ac1cc5fa4a202ddde6693R122)
2. Navigate to the data page. And click the model or model-store tab.
3. You can check the added modal by clicking an 'Import From Hugging Face' button.
---
=> Add an 'Import from hugging face' modal

config.toml.sample, react/src/hooks/index.tsx, react/src/pages/VFolderListPage.tsx, src/components/backend-ai-login.ts
This PR introduces a new feature that allows users to import models from Hugging Face. The changes include:
- Added a new configuration option `enableImportFromHuggingFace` in `config.toml.sample`
- Updated the `BackendAIConfig` type to include the new configuration option
- Modified the `VFolderListPage` component to conditionally render the "Import from Hugging Face" button based on the new configuration
- Updated the `BackendAILogin` component to handle the new configuration option and pass it to the global client configuration
**Checklist:**
=> feat: add `enableImportFromHuggingFace` option

react/src/components/ImportFromHuggingFaceModal.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/th.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json
**Changes:**
This PR enhances the `ImportFromHuggingFaceModal` component with improved URL validation and model information display. Key changes include:
1. Added URL validation for Hugging Face model URLs.
2. Implemented a check button to validate and fetch model information.
3. Added display of model name and author information.
4. Integrated suspense-based loading for fetching model data.
5. Updated translations for new UI elements and error messages.
**Rationale:**
These changes improve the user experience when importing models from Hugging Face by providing immediate feedback on URL validity and displaying key model information. The suspense-based loading ensures a smooth user interface while fetching content.
**Effects:**
Users will now see immediate validation of Hugging Face URLs …
=> feat: fetch the Hugging Face info using a URL

react/src/components/ImportFromHuggingFaceModal.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/th.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json
**Changes:**
This PR updates the ImportFromHuggingFaceModal component and related translations to enhance the user experience when importing models from Hugging Face. Key changes include:
1. Added new form fields for "Model store folder name" and "Service name".
2. Implemented a README.md preview card with Markdown support.
3. Added validation to ensure only LLM models (text-generation pipeline) are supported.
4. Updated translations for new strings across multiple languages.
**Rationale:**
These changes provide users with more control over the import process and better information about the model being imported. The README preview allows users to review model details before importing, while the additional form fields enable customization of the import location and service name. …
=> feat: Improve form item and switch to README preview on validation check

react/src/components/EndpointSelect.tsx
**Changes:**
This PR enhances the `EndpointSelect` component by adding support for filtering endpoints based on their lifecycle stage. The main changes include:
1. Importing the `useSuspendedBackendaiClient` hook.
2. Adding a `filter` parameter to the `EndpointSelectQuery`.
3. Implementing a conditional filter based on the client's support for the 'endpoint-lifecycle-stage-filter' feature.
**Rationale:**
The addition of the lifecycle stage filter allows for more precise endpoint selection, showing only endpoints in the "created" stage when supported by the client. This improves the user experience by presenting a more relevant list of endpoints.
**Effects:**
- Users will see a filtered list of endpoints in the "created" stage when using a client that supports this feature.
- Developers …
=> fix: display only active endpoints in EndpointSelect

react/src/components/ImportFromHuggingFaceModal.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/th.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json
Import or import and start a new service from HuggingFace and show the result with Modal.
- import only
- import & start service
- common
- Only for (super)admin, the current project is not 'model-store'.
- After clicking import & start service
- After clicking import with 'import only' option
=> feat: import from HuggingFace and show result with modal

e2e/session.test.ts, react/src/components/DynamicUnitInputNumberWithSlider.tsx, react/src/components/ResourceAllocationFormItems.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/th.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json
Added resource allocation warning for insufficient resources and implemented end-to-end test for resource policy modification.
- Added a new warning message for insufficient resource allocation in the session launcher
- Implemented logic to check if minimum resource values exceed maximum values
- Added an end-to-end test for modifying resource policy as a superadmin
- Updated the DynamicUnitInputNumberWithSlider component to handle cases where minimum values exceed maximum values
- Added translations for the new warning message across multiple languages
1. Log in as a superadmin and navigate to the resource policy page
2. Modify the resource limits (CPU, memory) to zero
3. Go to the session start page and check for the warning message in the resource allocation section
4. Run the new …
=> add: warning when maximum resources to allocate is not enough to the minimum required resources in selected image

react/src/components/ImageEnvironmentSelectFormItems.tsx, react/src/components/ImageList.tsx, react/src/components/lablupTalkativotUI/CopyButton.tsx
This PR enhances the user experience by adding copy functionality for image names in multiple components:
1. In `ImageEnvironmentSelectFormItems.tsx`:
- Added a copyable text for the environment/version label, allowing users to easily copy the full image name.
2. In `ImageList.tsx`:
- Introduced a new copy button in the image list, enabling users to copy the full image name with a single click.
3. Updated `CopyButton.tsx`:
- Added a `defaultIcon` prop to allow customization of the default icon displayed before copying.
These changes make it more convenient for users to copy and use image names across the application.
|Environments|Session Laucner|
|---|---|
|![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/lSyr8xXz1wdXALkJKzVx/8359f664-56bf-49ce-9562-f81a05f3452c.pn …
=> feat: add copy button for full image name in session launcher and environments page

src/components/backend-ai-resource-panel.ts, src/components/backend-ai-summary-view.ts, src/components/lablup-activity-panel.ts
**Changes:**
- Implemented `scrollableY="true"` attribute for activity panels in `BackendAIResourcePanel` and `BackendAISummary`
- Enhanced `lablup-activity-panel` to improve scrolling functionality:
- Added a `content` class to the inner div
- Adjusted height calculations to account for header space
- Implemented separate overflow settings for content area
**Checklist:**
=> fix: add scroll to the lablup-activity-panel

.cspell.json, e2e/vfolder.test.ts, src/components/backend-ai-summary-view.ts
This PR is about considers the state of the vfolder for vfolder invitations.
> This PR must be merged after the corresponding PR on the core side is merged. https://github.com/lablup/backend.ai/pull/2780
- The basic logic of the webui is the same. However, I added logic to refresh the invitation on error. 
- Added playwrite test code to test vfolder invitations. **All tests are performed against the Backend.AI core and webui initial installations**.
1. Navigate to the Core PR branch and apply the changes.
2. Run Playwrite test code, or test it yourself. 
(if you're testing it yourself. It needs 2 browser)
1. Create a vfolder and invite other users to join.
2. Login as the invited user and verify that the invitation appears on the summary page.
3. Open the browser that sent the invite and …
=> fix: Consider folder state for vfolder invitations

src/components/backend-ai-session-list.ts
[teams](https://teams.microsoft.com/l/message/19:86f7b329bde541d28d51542b4089bf95@thread.skype/1726712184037?tenantId=13c6a44d-9b52-4b9e-aa34-0513ee7131f2&groupId=483daa8a-29ee-4085-9f71-e93d7f112730&parentMessageId=1726102778706&teamName=project&channelName=KTCloud%20AI%20Serving%20(Public%2C%20South%20Cheongju)&createdTime=1726712184037)
This PR improves the display of GPU usage information in the session list component. It separates the display logic for CUDA and ROCm GPUs, providing more accurate and specific information for each GPU type.
**Changes:**
1. Added a new conditional block to display CUDA GPU memory usage.
2. Updated the existing ROCm GPU memory usage display.
3. Fixed a condition check for ROCm GPU slot parsing.
These changes allow for more precise reporting of GPU memory …
=> fix: separate CUDA FGPU slots from ROCM GPU slots

react/src/hooks/hooksUsingRelay.tsx
[Teams](https://teams.microsoft.com/l/message/19:b8327ceb372045beb1d0c6e28ca281da@thread.skype/1727081884563?tenantId=13c6a44d-9b52-4b9e-aa34-0513ee7131f2&groupId=483daa8a-29ee-4085-9f71-e93d7f112730&parentMessageId=1726212159210&teamName=project&channelName=KTCloud%20NPU&createdTime=1727081884563)
In Backend.AI core, when the value of max_concurrent_session is 0, it is treated as unlimited. I also changed the webui to treat a value of 0 as infinite. 
If the value of max_concurrent_session is 0, the webui passes a value of 100,000 to the session form item in the neo session launcher. (Maximum you can set in the control panel)
The `sessionSliderLimitAndRemaining` used by neo session laucner takes the minimum of the value of max_concurrent_session and 3, so if max_concurrent_session is 0, …
=> fix: session launcher validation logic when max_concurrent_sessions is set to 0 (unlimited)

react/src/components/FormItemWithUnlimited.tsx, react/src/components/KeypairResourcePolicyList.tsx, react/src/components/KeypairResourcePolicySettingModal.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/th.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json
follows #2357 
Enhanced the KeypairResourcePolicySettingModal component with dynamic resource slot rendering and improved form validation.
- Added dynamic rendering of resource slots based on available slots
- Implemented memory size validation (limit to 300 PiB)
- Improved layout consistency for form items
- Added step size of 0.1 for resource slots with '.shares' in their name
- Updated the totalResourceSlots calculation to handle all memory-related slots
- Remove the max value of `InputNumber` because the core doesn't set the max value.
1. Open the KeypairResourcePolicySettingModal
2. Verify that all available resource slots are displayed dynamically
3. Try entering a memory size larger than 300 PiB and check for validation error
4. Test the step size of 0.1 for resource slots with …
=> refactor: `KeypairResourcePolicySettingModal` update to support policy settings for all available accelerators.

react/src/components/ContainerRegistryList.tsx, react/src/components/KeypairResourcePolicyList.tsx, react/src/components/ResourcePresetList.tsx, react/src/components/ResourcePresetSettingModal.tsx, react/src/pages/EnvironmentPage.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/th.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json
> [!Note]
> Unlike other components, the `requiredMark="optional"` is not included to form. Because it contains too many optional inputs.
> <img width="300" alt="image" src="https://github.com/user-attachments/assets/12f4c0cf-3bbc-4b4b-bacb-94e2612d83b5">
resolves https://github.com/lablup/backend.ai-webui/issues/2651
Implemented a new ResourcePresetList, ResourcePresetSettingModal component and updated the EnvironmentPage to use it.
- Added a new ResourcePresetList component to manage resource presets
- Created a ResourcePresetSettingModal component for creating and editing resource presets
- Updated the EnvironmentPage to use the new ResourcePresetList component
- Adjusted padding and styling in ContainerRegistryList and KeypairResourcePolicyList
- Added new translations for resource …
=> refactor: resource preset page

react/src/components/ServiceLauncherPageContent.tsx
[teams](https://teams.microsoft.com/l/message/19:3c0acc0825024daeb2211f55c4e7f4aa@thread.skype/1727418901786?tenantId=13c6a44d-9b52-4b9e-aa34-0513ee7131f2&groupId=74ae2c4d-ec4d-4fdf-b2c2-f5041d1e8631&parentMessageId=1727418901786&teamName=devops&channelName=Backend.AI%20Talks&createdTime=1727418901786)
This PR introduces a new query to fetch the user's resource policy and applies the `max_session_count_per_model_session` limit to the service launcher page. The changes include:
- Added two new queries: `ServiceLauncherPageContent_UserInfoQuery` and `ServiceLauncherPageContent_UserResourcePolicyQuery`
- Utilized `useLazyLoadQuery` to fetch user information and resource policy
- Applied the `max_session_count_per_model_session` from the user's resource policy to the session count input field …
=> fix: Fixed the maximum desired number of sessions value in the Model Launcher modal to follow `max_session_count_per_model_session`

react/src/components/DynamicUnitInputNumberWithSlider.stories.tsx, react/src/components/DynamicUnitInputNumberWithSlider.tsx
**Changes:**
This PR fixes and enhances the `DynamicUnitInputNumberWithSlider` component by improving its value handling:
1. Update Input behavior (fix bug and improve UX):
- set the controllable value always.
1. Updated slider behavior:
- Set value to 0 and disable slider and hide tooltip when min value exceeds max value
- Added `filterOutInvalidMarks` function to remove marks that fall outside the valid range(min~ max).
1. Removed dependency on external `isMinOversMaxValue` function from `ResourceAllocationFormItems`
Addtionally this PR adds new stories:  
- "Greater min than max" to demonstrate behavior when min value exceeds max value
- "Extra marks" to show custom marks on the slider
- "Extra marks with greater min than max" combining both scenarios
**Rationale:**
These changes …
=> fix: value handling of DynamicUnitInputNumberWithSlider

react/src/components/VFolderLazyView.tsx
**Changes:**
This PR modifies the `VFolderLazyView` component to use the current location's pathname when navigating to a folder. Specifically:
- Imports the `useLocation` hook from `react-router-dom`
- Adds `const location = useLocation();` to get the current location
- Updates the `onClick` handler of the `Typography.Link` component to use `location.pathname` instead of the hardcoded '/data' path
**Rationale:**
This change allows the component to maintain the current route context when navigating to a folder, improving navigation consistency across different pages or sections of the application.
**Effects:**
Users will experience more predictable navigation behavior when interacting with folders, as the component will preserve the current route context instead of always redirecting to …
=> feat: change redirect path of `VfolderLazyView` to current page

e2e/session-launcher.test.ts, react/src/components/EnvVarFormList.test.tsx, react/src/components/EnvVarFormList.tsx, react/src/components/VFolderTableFormItem.tsx, react/src/pages/SessionLauncherPage.tsx
Added functionality to empty sensitive environment variables and updated form value synchronization.
- Introduced `sensitivePatterns` array with regular expressions to identify sensitive environment variables.
- Added `isSensitiveEnv` function to check if an environment variable is sensitive.
- Implemented `emptySensitiveEnv` function to clear values of sensitive environment variables.
- Updated `VFolderTableFormValues` interface to include `autoMountedFolderNames`.
- Modified form value synchronization in `SessionLauncherPage` to omit specific fields and empty sensitive environment variables.
- Unit test and E2E test for this change.
1. Navigate to the Session Launcher page.
2. Add environment variables with sensitive names (e.g., PASSWORD, SECRET_KEY).
3. Verify that sensitive …
=> feat: add sensitive env var clearing and e2e tests for session launcher

react/src/components/ImageEnvironmentSelectFormItems.tsx, react/src/components/ResourceAllocationFormItems.test.ts
Updated image identification and selection logic in ImageEnvironmentSelectFormItems component.
Images can have the same `digest`, but it's a rare case.
- Added 'id' field to the GraphQL query for images
- Changed image uniqueness check from 'digest' to 'id'
- Updated Select.Option key from 'image?.digest' to 'image?.id'
- Added 'id' property to Image type in ResourceAllocationFormItems test
=> fix: use `id` as a key of Image

react/src/components/ResourcePresetSettingModal.tsx
**Changes:**
This PR modifies the `ResourcePresetSettingModal` component by adding a `max` prop to the `DynamicUnitInputNumber` component. The `max` prop is set to "7.999p", which likely represents a maximum value of 7.999 petabytes. (BigInt)
**Rationale:**
Adding a maximum value to the input helps prevent users from entering unreasonably large resource allocations, improving the overall user experience and reducing the risk of configuration errors.
**Effects:**
- Users will be limited to entering resource values up to 7.999 petabytes in the affected input field.
- This change enhances input validation and provides clearer boundaries for resource allocation.
**Checklist:**
=> fix: set max shared memory to 7.999PiB in ResourcePresetSettingModal

react/src/pages/EndpointListPage.tsx
Added advanced filtering capabilities to the Endpoint List Page.
- Added support for filtering endpoints based on name, service endpoint, and owner (for admin/superadmin roles).
- Implemented query parameter support for filters using `useQueryParam`.
- Updated the layout to accommodate the new filter component.
- Added loading state for filter operations.
1. Navigate to the Endpoint List Page.
2. Verify that the new filter component is visible next to the lifecycle stage filter.
3. Test filtering by endpoint name, service endpoint, and owner (if you have admin/superadmin privileges).
4. Confirm that the filter persists in the URL and works correctly when the page is refreshed.
5. Check that the loading indicator appears when applying filters.
This change enhances the user experience by …
=> feat: add BAIPropertyFilter to Endpoint list

react/src/components/lablupTalkativotUI/ChatUIModal.tsx, react/src/components/lablupTalkativotUI/EndpointLLMChatCard.tsx, react/src/components/lablupTalkativotUI/LLMPlaygroundPage.tsx
**Changes:**
This PR enhances the ChatUIModal, EndpointLLMChatCard, and LLMPlaygroundPage components:
1. Added a refresh button to the "Cannot Find Model" alert in ChatUIModal and EndpointLLMChatCard.
2. Implemented the `destroyOnClose` prop for the Modal component in ChatUIModal. After this change, it refetches models when the modal is opened.
3. `useUpdatableState hook` in EndpointLLMChatCard for managing fetch key.
4. Improved layout and styling of LLMPlaygroundPage, particularly for the card skeleton.
**Rationale:**
These changes improve user experience by providing a way to refresh model data and enhance the overall UI responsiveness and appearance.
**Effects:**
- Users can now easily refresh model data when it's not found.
- The chat modal will reset its state when closed, ensuring …
=> feat: refetch endpoint's models

react/src/components/ImageList.tsx
**Changes:**
This PR enhances the image filtering functionality in the ImageList component:
1. Adds a `fullName` property to the image data object, populated with the result of `getImageFullName(image)`.
2. Extends the filtering logic to include a `fullNameMatch` check, allowing users to search for images based on their full names.
**Rationale:**
Including the full name in the search criteria provides users with more flexibility when filtering images, improving the overall user experience and making it easier to find specific images.
**Effects:**
- Users can now search for images using their full names, in addition to existing criteria.
- Developers working on the ImageList component should be aware of the new `fullName` property and its inclusion in the filtering logic.
**Checklist:**
=> feat: search image with full name in Environment page

react/src/components/ServiceLauncherPageContent.tsx
**Changes:**
This PR modifies the navigation behavior after updating an endpoint in the Service Launcher page. Instead of redirecting to the general '/serving' page, it now navigates to the specific endpoint details page using the endpoint's ID.
**Rationale:**
This change improves the user experience by directly taking users to the relevant endpoint details after updating, rather than to a general serving page. This allows for immediate access to the newly updated endpoint's information.
**Effects:**
Users will now be automatically redirected to the specific endpoint details page after updating an endpoint, providing a more seamless and intuitive workflow.
1. Create a new model service
2. Update
3. See detail page.
**Test list:**
**Checklist:**
=> feat: move to detail page after modifying model service

e2e/test-util.ts, e2e/user.test.ts
This PR adds end-to-end tests for user management functionality, covering the following scenarios:
1. create a new user
-> In webui, You can't permanently delete a user. So if you create a user and delete it, you can't create a new user with the same name. In this case, you can just active/inactive that user.
-> In that case, `AfterEach` in `Create user` test checks to verify if this is the case, and if so, displays that information in the test console.
2. delete the created user
-> When a user account is in the `Inactive` state, the user cannot log in.
-> The official docs of playwrite says to use `toThrow` or `toThrowError` when expecting a function to fail, but it didn't work, so I didn't use them when writing logout logic from delete user
3. modify user
-> Restore the deleted User …
=> test: e2e test for user page

react/src/pages/EndpointDetailPage.tsx
**Changes:**
- Enable the LLM chat button only if the endpoint status is `HEALTHY`.
- On the endpoint detail page, check whether the LLM chat button is enabled or disabled based on the status.
=> feat: disable LLM Chat button based on endpoint status

react/src/components/EndpointSelect.tsx
**Changes:**
The current EndpointList only fetches up to 100 endpoints via gql, and if you have more than 100 endpoints, it is not possible to search the entire data.
This PR enhances the `EndpointSelect` component to allow searching over the entire data using gql filters:
1. Introduced `useState` and `useTransition` hooks for managing search state and transitions.
2. Added a search filter to the GraphQL query when the backend supports 'endpoint-lifecycle-stage-filter'.
3. Implemented `onSearch` handler for the Select component to update the search string.
4. Added loading indicator during search transitions.
**How to test**
1. move to LLM Playground page.
2. Verify that endpoint select requests a new gql based on search string
**Rationale:**
These changes improve the user experience by …
=> feat: name-based query search feature on `EndpointSelect`

react/src/components/FolderCreateModal.tsx, react/src/pages/VFolderListPage.tsx
|before|after|
|---|---|
|![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/lSyr8xXz1wdXALkJKzVx/55ecbe42-f539-416a-8b63-7daf6132d564.png)|![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/lSyr8xXz1wdXALkJKzVx/9a71c8cc-fe1b-4be0-bcb5-bbae71317983.png)|
The new modal provides a interface for creating storage folders with react component. 
1. Move to `Data & Storage` page
2. Create a vfolder with new modal
3. Ensure that the new modal covers all of the functionality of the regacy modal. (e.g. validation logic, conditional options such as clonable, project select, etc..) 
**Key changes:**
- Created a new `FolderCreateModal` component with form fields for folder name, host, usage mode, type, permission, and cloneable option.
- …
=> refactor: folder creation modal

react/src/components/UserResourcePolicySelector.tsx, react/src/components/UserSettingModal.tsx
This PR resolves #2727 issue.
**Changes:**
- The user creation modal is written as a Lit Element, so I applied it to the edit modal first. 
- When migrating the user creation modal to react component, I thought that we need a user resource policy selector, so I wrote it as a separate component. 
- The `user_resource_policy` query doesn't provide filtering options yet, so I didn't add any filtering logic, but used antd's built-in search.
- Verify that the existing user's resource policy is properly applied as the default value. 
- In the user information edit modal, verify that the user's resoure policy is modified correctly.
|before|after|
|---|---|
|![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/lSyr8xXz1wdXALkJKzVx/e0c21f2d-a56b-4fd8-ab23-36048 …
=> feat: user resource policy allocation in user setting modal

react/src/components/ImageEnvironmentSelectFormItems.tsx
**Changes:**
This PR adds a space between the "Environments" and "Version" labels in the ImageEnvironmentSelectFormItems component. The change ensures proper spacing in the UI, improving readability.
**Checklist:**
=> misc: add a space between Environments and Version

react/src/components/EndpointSelect.tsx
follows #2743 
**Changes:**
- Updated `useControllableValue` hook in `EndpointSelect` component to explicitly type it with `string`
- Changed `@skip` directive to `@skipOnClient` in GraphQL query for the `endpoint` field
**Rationale:**
- The explicit typing of `useControllableValue<string>` improves type safety and clarity in the codebase
- Switching from `@skip` to `@skipOnClient` directive likely aligns with updated GraphQL schema or client-side optimization strategies
**Effects:**
- These changes should not directly affect users
- Developers will benefit from improved type checking and potentially more efficient GraphQL query execution
- Avoid runtime errors when endpoint is empty.
1. Remove all services
2. Enable `enableLLMPlayground` from config.toml
3. Visit LLM …
=> fix: replace `skip` with `skipOnClient` to avoid runtime errors

react/data/schema.graphql, react/src/components/ContainerRegistryEditorModalBefore2409.tsx, react/src/components/ContainerRegistryListBefore2409.tsx, react/src/components/lablupTalkativotUI/LLMChatCard.tsx, react/src/pages/EnvironmentPage.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/th.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json
- related PR: https://github.com/lablup/backend.ai/pull/1917, https://github.com/lablup/backend.ai/pull/2888
**TR;DR**
New GraphQL queries and mutations have been added related to the Registry since 24.09. Internally, the management from etcd has been changed to DB table. Therefore, version management is as follows:
- 24.09.0 and above: Use `ContainerRegistryList.tsx`, `ContainerRegistryEditorModal.tsx`
- 23.09.2 and above but below 24.09.0: Use `ContainerRegistryListBefore2409.tsx`, `ContainerRegistryEditorModalBefore2409.tsx`
- Below 23.09.2: Use `backend-ai-registry-list.ts`
**What's changed**
- `ContainerRegistryList.tsx` and `ContainerRegistryEditorModal.tsx` have been renamed to `ContainerRegistryListBefore2409.tsx`, `ContainerRegistryEditorModalBefore2409.tsx`.
- From 24.09.0, …
=> feat: fetch container registries with new nodes query

react/src/components/ContainerRegistryList.tsx
**Changes:**
This PR enhances the ContainerRegistryList component by adding a column visibility feature. Users can now customize which columns are displayed in the registry list table.
- Introduced a new TableColumnsSettingModal component for managing column visibility
- Added a settings button to toggle the column visibility modal
- Implemented local storage state to persist user's column visibility preferences
- Refactored the table columns definition for better maintainability
- Updated the Table component to use the filtered columns based on user preferences
**Rationale:**
This change improves the user experience by allowing customization of the registry list view. Users can now focus on the information most relevant to them, reducing clutter and improving efficiency.
**Impact:**
- …
=> feat: add `TableColumnSettingModal` to `ContainerRegistryList`

react/src/components/DynamicStepInputNumber.tsx, react/src/components/DynamicUnitInputNumberWithSlider.tsx, react/src/components/VFolderTable.tsx, react/src/hooks/useEventNotStable.tsx
This pull request includes several changes to improve type safety and optimize the performance of React components by using `useCallback` and ensuring proper type handling in hooks. The most important changes include modifications to `DynamicInputNumber`, `DynamicUnitInputNumberWithSlider`, and `VFolderTable` components, as well as updates to the `useEventNotStable` hook.
* [`react/src/components/DynamicStepInputNumber.tsx`](diffhunk://#diff-b3d890e46cddb08acfce125b27ff3da0ca9db076ab3ebcd35fadace06e7c8d92L32-R32): Updated the `updateKey` call to use `value.toString()` to ensure the value is a string.
* [`react/src/components/DynamicUnitInputNumberWithSlider.tsx`](diffhunk://#diff-26552acf4047ca1f6af64dbcf17ecdce04c84a7f669f055db97e13afe873a6e7L54-R54): Updated the `updateKey` call to use …
=> refactor: useEventNotStable type

react/src/App.tsx, react/src/components/SessionOwnerSetterCard.tsx, react/src/components/SessionTemplateModal.tsx, react/src/components/VFolderTable.tsx, react/src/components/VFolderTableFormItem.tsx, react/src/hooks/backendai.tsx, react/src/hooks/useBAISetting.tsx, react/src/pages/SessionLauncherPage.tsx, react/src/react-app-env.d.ts, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/th.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json
This pull request introduces several changes to the `react` project to enhance the session management features and improve form handling. The most important changes include adding a new `SessionTemplateModal` component, and enhancing the `SessionLauncherPage` with session history functionality.
* **`SessionTemplateModal` Component**: Added a new modal component to display recent session history, allowing users to apply previous session settings easily. (`react/src/components/SessionTemplateModal.tsx`)
* **Session History Handling**: Introduced a new hook `useRecentSessionHistory` to manage recent session history, including functions to push, clear, and remove session history entries. (`react/src/hooks/backendai.tsx`)
* **`SessionLauncherPage`**: Enhanced to include session history …
=> feat: recent session history

react/src/components/FolderCreateModal.tsx, react/src/components/ProjectSelect.tsx, react/src/components/ProjectSelectForAdminPage.tsx, react/src/components/StorageHostSettingsPanel.tsx
**TR;DR:**
Added a new component 'ProjectSelectForAdminPage' to display all projects in the project quota setting page. It extends `ProjectSelect` and uses `disableDefaultFilter` props as a default.
1. Endpoint: `http://10.82.230.49:8090`, Location: `/storage-settings/local:myceph`
2. Login with superadmin.
3. Click the 'For project' tab.
4. The project select shows all projects of selected domain. But top header project select is `ProjectSelect` that doesn't use `disableDefaultFilter`. So, it only shows accessible projects such as default and model-test.
**Checklist for reviewers:**
Check `ProjectSelectForAdminPage` displays all projects that include specific domain. You can check in `storage-settings/local:myceph` page.
**Changes:**
- Renamed `ProjectSelector` component …
=> feat: display all projects in project quota setting page.

src/components/backend-ai-session-list.ts
**Changes:**
- Added a new "Copy" button next to the session name in the session list
- The new button allows users to easily copy the session name to the clipboard
- Updated CSS to apply the same icon size styling to both rename and copy icons
**Rationale:**
This change enhances user experience by providing a quick and convenient way to copy session names, which can be useful for referencing or sharing session information.
**Effects:**
- Users can now copy session names with a single click, improving efficiency
- The UI remains consistent with the existing design, maintaining visual harmony
**Screenshots:**
**Checklist:**
=> feat: add session name copy button

react/src/components/FolderCreateModal.tsx, react/src/components/StorageSelect.tsx
**Changes:**
- Modified `FolderCreateModal.tsx`:
- Changed `autoSelectType` from "default" to "usage" in the `StorageSelect` component
- Added `showSearch` prop to the `StorageSelect` component
- Updated `StorageSelect.tsx`:
- Changed `optionLabelProp` to conditionally use 'label' when `showUsageStatus` is true, otherwise use 'value'
**Rationale:**
These changes improve the user experience when selecting storage options. The "usage" auto-select type prioritizes storage based on usage, while the added search functionality allows users to quickly find specific storage options. The conditional `optionLabelProp` ensures that the correct label is displayed when usage status is shown.
**Impact:**
Users will now have a more intuitive and efficient storage selection process, with the ability to …
=> fix: set autoSelectType to `usage` in FolderCreateModal

react/src/components/SessionTemplateModal.tsx, react/src/hooks/backendai.tsx, react/src/hooks/useRecentSessionHistory.tsx, react/src/pages/SessionLauncherPage.tsx
**Changes:**
This PR refactors the `useRecentSessionHistory` hook by moving it from `hooks/backendai.tsx` to its own file `hooks/useRecentSessionHistory.tsx`. The functionality remains the same, but it's now in a separate, dedicated file for better organization and maintainability.
Additionally, this PR resolves the [Jest test failure](https://github.com/lablup/backend.ai-webui/runs/31819326674) related to importing a file.
**Updates:**
1. `SessionTemplateModal.tsx`: Updated the import path for `useRecentSessionHistory`.
2. `hooks/backendai.tsx`: Removed the `useRecentSessionHistory` hook and its related imports.
3. `hooks/useRecentSessionHistory.tsx`: Created this new file to house the `useRecentSessionHistory` hook.
4. `SessionLauncherPage.tsx`: Updated the import path for …
=> refactor: move useRecentSessionHistory to a separate file

react/src/components/lablupTalkativotUI/ChatUIModal.tsx, react/src/components/lablupTalkativotUI/LLMChatCard.tsx
**Changes:**
Hide "Compare with Other Models" menu item" in LLM playground:
- Added `showCompareMenuItem` prop to `LLMChatCard` component
- Implemented conditional rendering of "Compare with Other Models" menu item based on `showCompareMenuItem` prop
- Utilized `filterEmptyItem` helper function to remove empty items from the menu
**Rationale:**
This change allows for more flexible control over the visibility of the "Compare with Other Models" menu item in the LLM Chat interface. By making it conditional, we can show or hide this option based on the context or user permissions.
**Effects:**
- Developers can now control the visibility of the comparison feature by passing the `showCompareMenuItem` prop
- Users may or may not see the "Compare with Other Models" option depending on how the …
=> fix: hide "compare with other models" in LLM Playground

react/src/components/ContainerRegistryEditorModalBefore2409.tsx, react/src/components/ContainerRegistryListBefore2409.tsx
**Changes:**
- Since we are using a switch with a string[] type input, I use a custom validator to validate it. 
- Modify tag in list to output correctly by specifying the data type used in from item.
As of Core 24.09.0rc1, 
- Modify the query in `ContainerRegistryList.tsx` to @since(version: "24.09.0rc1"). 
- In `EnvironmentPage.tsx`, modify isManagerVersionCompatibleWith('24.09.0") to "24.09.0rc1". 
- Go to the registry tab and verify the behavior. 
=> fix: Fix for container registry form entry validation rules in version earlier 24.09.0

react/src/components/FolderCreateModal.tsx, react/src/components/VFolderTable.tsx
This PR enhances the folder creation functionality and improves the VFolderTable component:
1. Updated `FolderCreateModal`:
- Modified `onRequestClose` to accept an optional `FolderCreationResponse` parameter
- Added `FolderCreationResponse` interface to define the structure of the created folder data
- Updated `mutationToCreateFolder` to use the `FolderCreationResponse` type
- Modified the `onSuccess` callback to pass the created folder data to `onRequestClose`
2. Enhanced `VFolderTable`:
- Added a "Create Folder" button with a plus icon
- Implemented a modal for creating new folders
- Updated the table to refresh and select the newly created folder after creation
- Added tooltips for the refresh and create folder buttons
- Set the default sort order for the "Created" column to …
=> feat: create folder in the vfolder form item

react/src/components/BAILink.tsx, react/src/components/FolderExplorerOpener.tsx, react/src/components/VFolderTable.tsx
**Changes:**
- Added a new `BAILink` component for consistent link styling
- Enhanced `FolderExplorerOpener` with a `generateFolderPath` function
- Updated `VFolderTable` to use `BAILink` for folder names, making them clickable
- Improved folder name display in `VFolderTable` with better alignment and hover effects
**Rationale:**
These changes improve the user experience by making folder navigation more intuitive and consistent. The new `BAILink` component ensures uniform styling for links across the application, while the `generateFolderPath` function allows for dynamic link generation based on the current URL.
**Effects:**
- Users can now click on folder names in the `VFolderTable` to open them directly
- Folder links have a consistent hover effect, improving visual feedback
- The …
=> feat: open vFolder in vFolder form item

react/src/components/BAILink.tsx, react/src/components/ServiceLauncherPageContent.tsx
**Changes:**
This PR modifies the `ServiceLauncherPageContent` component to use the nullish coalescing operator (`??`) instead of the logical OR operator (`||`) when setting the `desiredRoutingCount` value. This ensures that a value of `0` for `endpoint?.desired_session_count` is respected rather than defaulting to `1`.
**Rationale:**
The previous implementation using `||` would treat `0` as a falsy value, causing it to default to `1`. By using `??`, we now correctly handle cases where `desired_session_count` is explicitly set to `0`, while still defaulting to `1` when the value is `null` or `undefined`.
**Impact:**
This change allows users to set a `desired_session_count` of `0` for endpoints, which may be necessary for certain service configurations or management scenarios.
=> fix: 0 desired routing count in endpoint edit page

e2e/test-util.ts, e2e/vfolder.test.ts
**Changes:**
- Fixed folder creation modal to pass selectable arguments as props. 
- Minimized exceptions by specifying types for selectable arguments. 
- Used `.toBeVisible()` function for vfolder test scenarios to improve accuracy. 
- When logging out of the page, there was a situation where logging out occurred once more after login, so we minimized the logout by using a new page.
- Run the `vfolder.test.ts` test using the vscode playwright extension to verify that there are no errors. 
- Verify that running the same test multiple times produces the same results.
=> test: refactor test code due to changes in the folder creation modal

react/src/components/ResourceAllocationFormItems.tsx, react/src/components/ServiceLauncherPageContent.tsx, react/src/pages/SessionLauncherPage.tsx
This PR control the resource group value of the launcher using initial values, and update the global current resource group through the launcher when creating, so that the resource group of the resource monitor becomes the resource group just used.
resolve https://github.com/lablup/backend.ai-webui/issues/2770
- Replacing ResourceGroupSelectForCurrentProject with ResourceGroupSelect component
- Adding resource group state management to maintain selection consistency
- Setting initial form values with the current global resource group
- Updating the global resource group state when creating new sessions or services.
=> fix: handle current resource group using initial values in launchers

react/src/components/ContainerRegistryEditorModal.tsx
related PR: https://github.com/lablup/backend.ai-control-panel/pull/892
**Changes:**
This PR modifies the password handling logic in the `ContainerRegistryEditorModal` component. The condition for setting the password has been updated to include cases where a new container registry is being created (`!containerRegistry`). This ensures that the password is properly set for both new and existing registries.
**Rationale:**
The previous implementation only considered the `isChangedPassword` flag, which could lead to issues when creating a new container registry. By including the `!containerRegistry` condition, we ensure that the password is always set correctly for new registries, even if the `isChangedPassword` flag is not explicitly set.
**Impact:**
This change improves the reliability of …
=> hotfix: container registry password caanot be set when creating

react/src/components/lablupTalkativotUI/LLMChatCard.tsx
This PR is for the conditional divider render that is missing from the https://github.com/lablup/backend.ai-webui/pull/2762 PR.
|before|after|
|---|---|
|![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/lSyr8xXz1wdXALkJKzVx/e43dc73e-8a82-4809-88cc-ed40fa5189d5.png)|![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/lSyr8xXz1wdXALkJKzVx/cc530c3f-fd0b-4637-a569-5195b3d3645a.png)|
=> fix: hide divider in LLMChatCard

src/components/backend-ai-session-list.ts
**Changes:**
This PR adds support for displaying Gaudi 2 utilization in the session list. It introduces a new section that shows the Gaudi 2 utilization percentage and a progress bar, similar to existing resource utilization displays.
**Details:**
- Adds a conditional rendering block for Gaudi 2 slot information
- Displays Gaudi 2 utilization percentage
- Includes a progress bar to visually represent Gaudi 2 utilization
**Rationale:**
This addition allows users to monitor Gaudi 2 resource usage directly in the session list, providing better visibility and management of Gaudi 2 accelerators.
=> fix: display Gaudi 2 util in session list

e2e/config.test.ts, e2e/session-launcher.test.ts, e2e/test-util.ts
**Changes:**
This PR updates several end-to-end tests to improve reliability and reduce flakiness:
1. In `config.test.ts`, removed an unnecessary click action on the environment selector.
2. In `session-launcher.test.ts`, increased the timeout for session tests to 60 seconds.
3. In `test-util.ts`:
- Added a 15-second timeout to the "App close" button click.
- Updated the session deletion verification to use a more specific locator with a 15-second timeout.
**Rationale:**
These changes address potential timing issues in the tests, allowing for slower operations or network delays. The removal of the unnecessary click in the config test simplifies the test flow.
=> e2e: set-timout-to-session-e2e

react/src/components/BAITable.tsx
Fixed a potential null reference error in BAITable's ResizableTitle component by adding an optional chaining operator to the `onResize` callback. This prevents runtime errors when the callback is undefined.
[Teams](https://teams.microsoft.com/l/message/19:14c484402d874dafb15806d093b95a82@thread.skype/1730194784997?tenantId=13c6a44d-9b52-4b9e-aa34-0513ee7131f2&groupId=74ae2c4d-ec4d-4fdf-b2c2-f5041d1e8631&parentMessageId=1730194784997&teamName=devops&channelName=Frontend&createdTime=1730194784997)
**Checklist:**
=> fix: handle Undefined onResize in BAITable component

react/src/components/ComputeSessionList.tsx, react/src/components/ComputeSessionNodeItems/ContainerLogModalWithLazyQueryLoader.tsx, src/components/backend-ai-session-list.ts, src/lib/backend.ai-client-esm.ts
**Changes:**
With this PR, user can open a NEO session log modal in session list
The new implementation uses a lazy-loaded query to fetch session logs and displays them in a modern container log modal.
**Key Updates:**
- Introduces `ContainerLogModalWithLazyQueryLoader` component for handling session logs
- Adds event listener for `bai-open-session-log` to bridge legacy and React components
- Implements suspense boundary with skeleton loading state
- Replaces direct API calls with GraphQL queries for log fetching
**Review Requirements:**
- Open the log modal by clicking session's log button in session list.
=> feat: use NEO session log modal in session list

.cspell.json, react/data/schema.graphql, react/src/components/DoubleTag.tsx, react/src/components/ImageList.tsx, react/src/components/ImageTags.tsx, react/src/hooks/index.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/th.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json, resources/image_metadata.json, src/lib/backend.ai-client-esm.ts
related PR: https://github.com/lablup/backend.ai/pull/2939
This PR adds support for extended image information in the ImageList component and related translations. It introduces new fields and modifies the display of image details when the backend supports the 'extended-image-info' feature.
**Checklist:**
1. Updated `ImageListQuery` to include new fields: `namespace`, `base_image_name`, `tags`, and `version`.
2. Modified the ImageList component to conditionally render columns based on the `supportExtendedImageInfo` flag.
3. Added new translations for "Base image name" and "Tags" in multiple languages.
4. Updated the backend client to support the 'extended-image-info' feature for manager version 24.09.1 and above.
- Users will see more detailed image information when using a compatible …
=> feat: new image parsing on Environment page

react/src/components/ImageEnvironmentSelectFormItems.tsx, react/src/components/ResourceAllocationFormItems.test.ts, react/src/helper/index.tsx, react/src/hooks/useBackendAIImageMetaData.test.tsx, react/src/pages/MyEnvironmentPage.tsx, src/lib/backend.ai-client-esm.ts
This PR introduces support for the extended image info feature, which affects how image namespaces are handled and displayed throughout the application.
**Changes:**
- Added a `supportExtendedImageInfo` flag based on the backend client's capabilities
- Updated image queries to use `namespace` instead of `name` when extended image info is supported
- Modified image full name generation to prioritize `namespace` over `name`
- Adjusted environment selection logic to use `namespace` when available
- Updated table columns in MyEnvironmentPage to display and sort by `namespace` when supported
**Rationale:**
These changes allow the application to work with both the old and new image information structures, providing a smooth transition as the backend evolves.
**Effects:**
- Users will see more …
=> feat: replace name with namespace

react/src/components/ImageList.tsx, src/lib/backend.ai-client-esm.ts
**Changes:**
This PR enhances the ImageList component in the following ways:
1. Adds a new TableColumnsSettingModal component for customizing visible columns.
2. Implements column visibility persistence using local storage.
3. Introduces a settings button to open the column customization modal.
4. Improves the digest column rendering with ellipsis and tooltip for better readability.
> endpoint: 10.100.64.15
1. Checkout core branch to `topic/10-22-feature_add_info_field_to_gql_image_schema`
2. Visit Environments page.
3. Check the setting icon at the bottom of the table.
**Rationale:**
These changes provide users with more control over the information displayed in the image list, improving the overall user experience and allowing for a more personalized view of the data. …
=> feat: add table column setting to Environments page

react/src/components/AliasedImageDoubleTags.tsx
**Changes:**
Created a new reusable component `AliasedImageDoubleTags` to display image tags with aliased names and highlighting capabilities. The component supports customized tag styling and search term highlighting.
**Rationale:**
Extracts duplicated tag rendering logic from ImageList into a dedicated component for better maintainability and reusability. The component handles tag aliasing and visual highlighting of search terms consistently.
**Minimum required manager version:** 24.09.1
> endpoint: 10.100.64.15
1. Checkout core branch to `topic/10-22-feature_add_info_field_to_gql_image_schema`
2. Visit Environments - Images pages.
3. Check Tags column. (The Environments page uses same code with `AliasedImageDoubleTags` and it will be replaced after the image list query …
=> feat: add `AliasedImageDoubleTags`

react/src/components/CustomizedImageList.tsx, react/src/helper/index.tsx, react/src/pages/MyEnvironmentPage.tsx
I just separated MyEnvironmentPage into two components, moving the Card component to `MyEnvironmentPage`. Thus, you don't need to check the detailed logic of CustomizedImageList. To see the improved codes for CustomizedImageList, please refer https://github.com/lablup/backend.ai-webui/pull/2795.
---
**Changes:**
Refactored the customized image list functionality by:
- Extracting image list logic from MyEnvironmentPage into a new CustomizedImageList component
- Simplified MyEnvironmentPage to use tabs and the new component
- Added proper type definitions and GraphQL query/mutation handling
- Implemented sorting, filtering, and column customization features
- Added copy functionality for image names
- Included delete confirmation dialogs with proper error handling
**Checklist:**
- Column …
=> refactor: `MyEnvironmentPage` into two components

react/src/components/CustomizedImageList.tsx
**Changes:**
Adds search functionality and enhanced display features to the customized image list, including:
- New search bar with real-time filtering
- Refresh button to reload image data
- Copy button for full image paths
- Text highlighting for search matches
- New columns for base image name, version, and tags when extended image info is supported
- Improved table loading states using transitions
**Minimum required manager version:** 24.09.1
> endpoint: 10.100.64.15
1. Checkout core branch to `topic/10-22-feature_add_info_field_to_gql_image_schema`
2. Visit My Environments page.
**What to check:**
**Requirements to check during review:**
- Search functionality filters across all relevant fields
- Text highlighting properly emphasizes search terms
- Copy button …
=> refactor: new image parsing on `CustomizedImageList`

react/src/components/ImageList.tsx
**Changes:**
Updates image filtering logic to support extended image information in version 24.09.1 and later:
- Adds support for filtering by tags, version, and digest
- Modifies namespace filtering to use direct image namespace when available
- Removes installed status filtering
- Maintains backward compatibility for pre-24.09.1 filtering capabilities
**Checklist:**
- Filter images using new tag key/value pairs
- Filter by image version
- Filter by digest
- Verify namespace filtering works with both old and new image information
- Confirm backward compatibility for pre-24.09.1 filtering
=> refactor: improve image filter of `ImageList`

react/src/components/EnvVarFormList.tsx, react/src/components/ImageEnvironmentSelectFormItems.tsx, react/src/components/ImageList.tsx, react/src/components/ResourceAllocationFormItems.test.ts, react/src/hooks/useBackendAIImageMetaData.test.tsx, react/src/pages/SessionLauncherPage.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/th.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json
**Changes:**
This PR enhances the image selection UI to support extended image information in the session launcher, providing more detailed and structured image metadata display.
Key updates:
- Adds support for displaying base image name, version, architecture and tags in a more organized format
- Introduces tag aliasing functionality to show more user-friendly tag names
- Updates the image selection interface to show customized image tags with distinct styling
- Adds translations for "Tags" across all supported languages
**Minimum required manager version:** 24.09.1
**Review Requirements:**
1. Verify extended image info display works when backend supports 'extended-image-info' feature
2. Check tag aliasing correctly translates technical tags to user-friendly names
3. Confirm customized …
=> refactor: session launcher image parsing

react/src/helper/index.test.tsx
resolves https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2787/feat-replace-name-with-namespace#comment-PRRC_kwDOCRTcws5s0Ev6 
**Changes:**
Added unit tests for the `getImageFullName` helper function to verify image name construction under different scenarios:
- When only namespace is provided
- When only name is provided
- When both namespace and name are provided
The tests ensure the function correctly formats the full image name using the registry, namespace/name, tag, and architecture in the format: `registry/<namespace or name>:tag@architecture`
run `pnpm run test:react`
**Checklist:**
=> test: add `getImageFullName` tests

react/data/schema.graphql, react/src/components/AliasedImageDoubleTags.tsx, react/src/components/CustomizedImageList.tsx, react/src/components/ImageEnvironmentSelectFormItems.tsx, react/src/components/ImageList.tsx, src/lib/backend.ai-client-esm.ts
Updates version references from 24.09.1 to 24.12.0 for extended image information features
This PR updates version references for extended image information features (namespace, base_image_name, tags, version) from 24.09.1 to 24.12.0 across GraphQL schema and React components. This change ensures proper version compatibility checks and deprecation notices.
**Checklist:**
- Verify extended image information features work correctly with manager version 24.12.0
- Confirm deprecation notices display properly for the `name` field
- Validate version compatibility checks in backend client
The changes affect:
- GraphQL schema deprecation notices and version tags
- React component queries and version checks
- Backend client version compatibility detection
=> fix: change `extended-image-info` version to 24.12.0

.github/workflows/add-to-project.yml
Remove the automation workflow that adds issues/PRs to the Frontend daily board because it is now handled by the workflow feature of GitHub Projects.
=> ci: remove job to add to Frontend daily board

react/src/components/CustomizedImageList.tsx, react/src/components/ImageList.tsx
Refactored image list column definitions to use conditional expressions with filterEmptyItem
This PR simplifies the column definitions in CustomizedImageList and ImageList components by:
- Replacing spread operator and conditional arrays with boolean expressions
- Using filterEmptyItem to remove falsy column definitions
- Maintaining the same functionality while reducing code complexity
**Checklist:**
The changes make the code more maintainable by:
1. Eliminating nested conditional arrays
2. Making column visibility logic more explicit
3. Keeping column definitions flat and easier to read
The functionality remains identical for users, with no changes to the UI or behavior.
=> refactor: Use `filterEmptyItem` for table columns to improve readability.

src/components/backend-ai-session-list.ts
Added memory usage monitoring capabilities for various accelerator types in the session list view. The following accelerators now display memory usage metrics with progress bars:
- TPU memory usage
- IPU memory usage  
- ATOM memory usage
- ATOM+ memory usage and utilization
- Gaudi 2 memory usage
- Warboy memory usage
- RNGD memory usage
- LPU memory usage
Each accelerator type shows:
- Current/maximum memory usage in GiB
- Visual progress bar indicating memory utilization ratio
- Proper formatting of memory values without trailing zeros
**Checklist:**
=> fix: show memory usage for each device in session list

react/src/components/UserInfoModal.tsx, react/src/components/UserSettingModal.tsx, src/components/backend-ai-credential-view.ts
> This PR is the bottom of the stack so that it can be merged into main first.This is why this PR also including the part that will be fixed in #2757 PR.
**Changes:**
- I modified the `UserSettingModal.tsx` component because the input for the `modify_user` query and the `create_user` query are not very different.
- If you don't pass a userEmail value in the web component, the response data for the user query will be null. I took advantage of this and branched the modify and create logic.
- (minor) Modified UserInfoModal to show resource policy and description.
1. move to `User Credential & Polices` page
2. Verify that the modal looks correctly different on create/modify.
3. Verify that user creation is successful.
4. Verify that the non-required value is mapped and …
=> feat: migrate create user modal into react component

react/src/components/CustomizedImageList.tsx
**Changes:**
Improves error handling when deleting customized images by:
- Adding specific error checks for `forget_image_by_id` and `untag_image_from_registry` operations
- Displaying individual error messages from the error array with 2.5s duration
- Only showing success message and refreshing the environment when all operations complete successfully
**Checklist:**
**Test Cases:**
1. Delete an image with `forget_image_by_id` failure
2. Delete an image with `untag_image_from_registry` failure
3. Delete an image with multiple GraphQL errors
4. Delete an image successfully
=> refactor: improve error handling of `CustomizedImageList`

react/src/pages/SessionLauncherPage.tsx
Internationalize notification edit button text in session launcher
Changes the hardcoded Korean text "수정" to use the internationalized string key `t('button.Edit')` for the edit button text in session notifications.
**Checklist:**
=> fix: missed i18n

react/src/components/ComputeSessionNodeItems/ContainerLogModal.tsx, react/src/hooks/useMemoWithPrevious.test.tsx, react/src/hooks/useMemoWithPrevious.tsx
Resolves #2819 
**Changes:**
Introduces a new `useMemoWithPrevious` hook to manage previous and current values with reset capability, replacing the manual `useRef` implementation in ContainerLogModal. This hook provides a more robust way to track state changes while maintaining previous values.
**Implementation Details:**
- Created new `useMemoWithPrevious` hook that returns both current and previous values along with a reset function
- Updated ContainerLogModal to use the new hook for tracking log line numbers
- Replaced manual `previousLastLineNumber` ref management with the new hook's `resetPrevious` functionality
- Improved state management when switching kernel IDs or changing log sizes
**Testing Requirements:**
- Verify log highlighting works correctly when switching between …
=> feat: `useMemoWithPrevious` React hook

resources/image_metadata.json
Adds additional tag pattern replacements for image metadata
This PR extends the tag replacement patterns in `image_metadata.json` to support more standardized formatting of:
- Python versions (py35 → Python 3.5)
- ROCm GPU versions (rocm5 → GPU:ROCm5) 
- Ubuntu versions (ubuntu20.04 → Ubuntu 20.04)
- Anaconda versions (anaconda3.7 → Anaconda 3.7)
- Julia versions (ji1.6 → Julia 1.6)
- TPU versions (tpuv3 → TPU:TPUv3)
- Alpine Linux versions (alpine3 → Alpine Linux 3)
**Checklist:**
Example transformations:
```
py37 → Python 3.7
rocm5 → GPU:ROCm5
ubuntu20.04 → Ubuntu 20.04
ji1.6 → Julia 1.6
tpuv3 → TPU:TPUv3
alpine3 → Alpine Linux 3
```
=> refactor: add more tagReplace patterns

react/src/components/BAITable.tsx
Resolves #2830
Prevents column sorting when resizing columns in BAITable
This PR fixes an issue where users could accidentally trigger column sorting while resizing table columns. It adds a debounced resize state check that temporarily disables click events during and shortly after column resizing operations.
**Implementation details:**
- Added `isResizing` state to track when a column is being resized
- Implemented a 100ms debounced version of the resize state
- Modified click handler to prevent column sorting when resize is in progress
- Preserved original click behavior when not resizing
=> fix: resizing column action causes order change in BAITable

react/src/components/ComputeSessionNodeItems/ContainerLogModal.tsx
Resolves #2833
**Changes:**
Enhances the container log modal dropdown by adding node IDs alongside cluster roles. The first 5 characters of each node's row_id are now displayed in a monospace font next to the cluster role, making it easier to identify specific nodes.
**Visual Impact:**
The dropdown now shows entries in the format: `cluster_role (12345)` where the ID portion is styled with a monospace font and secondary color.
=> feat: display kernel node id and idx in Kernel select component

react/src/components/AliasedImageDoubleTags.tsx, react/src/components/CustomizedImageList.tsx, react/src/components/ImageEnvironmentSelectFormItems.tsx, react/src/components/ImageList.tsx, react/src/components/ImageTags.tsx, react/src/helper/index.tsx, react/src/hooks/index.tsx
**Changes:**
Refactored image handling similar to #2785 and #2795 for versions before 24.12. Before 24.12, most data parsing is handled on the frontend.
Key changes:
- Consolidated separate tag components (BaseImageTags, ConstraintTags, LangTags) into a single ImageTags component
- Simplified image metadata extraction by using string operations instead of complex parsing
- Removed redundant language column and consolidated information into Tags column
- Added new getTags utility function to consistently parse and format image tag information
- Updated image search functionality to search through tag keys and values
**Impact:**
- Cleaner, more consistent display of image metadata in the UI
- More maintainable code structure for handling image tags
- Improved search capabilities across …
=> refactor: parsing image data for versions before 24.12

react/src/components/ImageEnvironmentSelectFormItems.tsx, react/src/pages/SessionLauncherPage.tsx
**Changes:**
Refactored image handling similar to #2800 for versions before 24.12. Before 24.12, most data parsing is handled on the frontend.
- Unified the display format of image information across components
- Added base version and image tags display
- Replaced custom tag display with standardized ImageTags component
- Removed conditional rendering based on extended image info support
**Rationale:**
The changes provide a more uniform and informative way to display image metadata, making it easier for users to understand the characteristics of selected container images.
**What to check:**
Data parsing is the same as 24.12.
**Effects:**
Users will see:
- Consistent image information display format
- Clearer representation of image base versions
- Standardized tag display across the …
=> refactor: parsing image data in session launcher for before 24.12

react/src/components/BAITable.tsx, react/src/components/CustomizedImageList.tsx, react/src/components/ImageList.tsx
Adds resizable columns and consistent sorting behavior to image list tables
This PR enhances the user experience of image list tables by:
- Making columns resizable in both CustomizedImageList and ImageList components
- Adding consistent sort directions (descend -> ascend -> descend) for sortable columns
- Removing sorter tooltips for cleaner UI
- Setting fixed initial width for image name columns based on screen size
- Converting standard antd Tables to BAITable components for consistency
**Screenshots:**
**Checklist:**
To verify:
1. Check that columns can be resized by dragging their borders
2. Verify sort behavior cycles through: descending -> ascending -> descending
3. Confirm image name columns have appropriate initial widths
4. Ensure sorting works without tooltips appearing
=> feat: make image lists resizable

react/src/hooks/index.test.tsx, react/src/hooks/index.tsx
=> test: add image util functions test

src/components/backend-ai-edu-applauncher.ts, src/components/backend-ai-session-list.ts, src/components/backend-ai-session-view.ts, src/lib/backend.ai-client-esm.ts
**Changes:**
Adds conditional support for the 'PREPARED' session status based on manager version compatibility (24.12.0+). The status is now only included in session listings and filters when supported by the backend.
**Testing:**
Verify that the 'PREPARED' session status only appears in the UI when using Backend.AI manager version 24.12.0 or higher.
=> hotfix: session list fetch failure due to missing version condition for `PREPARED`

react/src/components/AgentDetailModal.tsx, react/src/components/AgentList.tsx, react/src/components/AvailableResourcesCard.tsx, react/src/components/DynamicUnitInputNumber.tsx, react/src/components/DynamicUnitInputNumberWithSlider.tsx, react/src/components/KeypairResourcePolicySettingModal.tsx, react/src/components/ResourceAllocationFormItems.tsx, react/src/components/ResourceNumber.tsx, react/src/components/ResourcePresetList.tsx, react/src/components/ResourcePresetSettingModal.tsx, react/src/components/ServiceLauncherPageContent.tsx, react/src/helper/index.test.tsx, react/src/helper/index.tsx, react/src/hooks/useResourceLimitAndRemaining.tsx, react/src/pages/SessionLauncherPage.tsx
Refactors binary and decimal size unit conversion functions
This PR renames `iSizeToSize` to `convertBinarySizeUnit` and adds a new `convertDecimalSizeUnit` function to clearly distinguish between binary (1024-based) and decimal (1000-based) size unit conversions. The changes improve code readability and maintainability by:
- Renaming `iSizeToSize` to the more descriptive `convertBinarySizeUnit`
- Adding `convertDecimalSizeUnit` for 1000-based conversions
- Introducing a shared internal `convertSizeUnit` function
- Adding comprehensive unit tests for both conversion methods
- Adding support for automatic unit selection with 'auto' parameter
- Adding proper TypeScript exports for size unit types
**Checklist:**
=> refactor: size unit convert functions

src/components/backend-ai-app-launcher.ts, src/components/backend-ai-import-view.ts, src/components/backend-ai-session-list.ts
resolves https://github.com/lablup/backend.ai-webui/issues/2843
**Changes:**
Improves clipboard functionality across browsers by:
- Adding optional chaining operators to clipboard API calls for better error handling
- Introducing a new `copyText()` method in session list for cross-browser text copying
- Implementing fallback copy mechanism for browsers without clipboard API support
**Rationale:**
The clipboard operations needed to be more robust across different browsers and handle cases where the clipboard API might be unavailable or restricted.
**Effects:**
- More reliable text copying functionality in session management
- Better error handling for clipboard operations
- Support for browsers without native clipboard API
**Checklist:**
**Testing Requirements:**
- Verify clipboard …
=> fix: improve clipboard handling with optional chaining

react/src/App.tsx, react/src/components/MainLayout/WebUISider.tsx, react/src/components/WebUILink.tsx, react/src/components/WebUINavigate.tsx
Resolves #2198
Introduces `WebUILink` and `WebUINavigate` components to handle navigation events consistently across the application. These components dispatch custom events for routing in Web component world when navigation occurs, ensuring proper synchronization between React routing and external navigation handlers.
The routing configuration has been restructured to use nested routes, particularly for the session and serving sections, improving route organization and maintainability.
=> feat: WebUILink and WebUINavigate component

react/src/App.tsx, react/src/components/WebUINavigate.tsx, react/src/pages/SessionLauncherPage.tsx
Resovles #2857
**Changes:**
- Preserves query parameters when redirecting from root to `/job` path
- Simplifies WebUINavigate component by extracting query parameters directly from the URL
- Adds "See Detail" notification with navigation link after session creation
**Impact:**
- Users will maintain their URL parameters when being redirected from the root path
- Session creation now provides a direct link to view session details via notification
- Improves navigation flow between different sections of the application
**Testing Steps:**
1. Create a new session
2. Confirm "See Details" notification appears with correct session link
3. Click "See Details" in session creation notification.
4. Confirm a session detail panel is opened
=> feat: user can open a session detail panel in notifications

react/src/components/MainLayout/MainLayout.tsx, react/src/components/WebUIBreadcrumb.tsx
Resolves #2841
Adds a breadcrumb navigation component to the WebUI interface, providing users with clear path indication and navigation capabilities. The breadcrumb appears below the header and displays the current location hierarchy based on the route structure.
Key features:
- Displays current navigation path with clickable links
- Integrates with existing routing system
- Supports internationalization (i18n) for labels
- Maintains consistent styling with Ant Design theme tokens
- Preserves navigation history for better user orientation
To review:
1. Verify breadcrumb appears correctly on all pages
2. Check navigation links work as expected
3. Confirm proper i18n label rendering
4. Validate styling consistency with design system
=> feat: Global breadcrumb

react/src/components/BAISider.tsx, react/src/components/MainLayout/MainLayout.tsx, react/src/components/MainLayout/WebUISider.tsx, react/src/components/SiderToggleButton.tsx, react/src/hooks/useKeyboardShortcut.ts, react/src/hooks/usePrimaryColors.ts, src/components/backend-ai-webui-styles.ts, src/components/lablup-activity-panel.ts
**Changes:**
- Added keyboard shortcut '[' to toggle sidebar collapse state
- Introduced a collapsible button on the sidebar that appears on hover
- Moved sidebar footer content into a more structured layout
- Added `useKeyboardShortcut` hook to handle keyboard shortcuts when no input is focused
- Refactored BAISider component to use forwardRef and improve layout structure
- Standardized sidebar width constants (COLLAPSED_SIDER_WIDTH = 74, SIDER_WIDTH = 240)
- Removed bottomText prop from BAISider in favor of direct content rendering
- Added hover detection for showing/hiding the collapse toggle button
**Testing Requirements:**
1. Verify the '[' keyboard shortcut toggles sidebar when no input is focused
2. Check that the collapse button appears on sidebar hover
3. Confirm sidebar footer …
=> feat: NEO sider's toggle button and refactoring

e2e/agent.test.ts, e2e/config.test.ts, e2e/environment.test.ts, e2e/login.test.ts, e2e/session-launcher.test.ts, e2e/test-util.ts, react/src/components/ProjectSelect.tsx, react/src/components/ResourceAllocationFormItems.tsx, react/src/components/WebUIBreadcrumb.tsx, react/src/pages/SessionLauncherPage.tsx
- In component:
- Added Suspense wrapper around AgentSelect component (related to https://github.com/lablup/backend.ai-webui/pull/2599)
- Added copy button functionality for environment image names in session launcher
- Updated breadcrumb selectors in e2e tests to use `data-testid` attribute
- Fixed resource limit column name casing in environment tests
- In test code:
- Added clipboard permission handling for copying image strings in config tests
- Increased session creation timeout from 15s to 30s
**Rationale:**
- Improves test reliability by using more stable selectors
- Enhances user experience by adding copy functionality for image names
- Prevents timeout issues during session creation in slower environments
- Implements proper loading state handling for agent selection
**Testing:** …
=> e2e: fix broken tests due to NEO mainlayout, Agent select and Image parsing

react/src/components/ImageEnvironmentSelectFormItems.tsx
follows #2860 
Use the `name` value only of `image_metadata.json`. It resolves unexpected parsing problems.
> endpoint: https://cloud.backend.ai/
1. Create a new session.
2. Click 'Environments & Resource allocation'.
3. Select Environments.
4. See error.
Before
After
=> fix: invalid environment name parsing

react/src/components/AgentDetailModal.tsx, react/src/components/BAIProgressWithLabel.tsx
Fix `Right operand of ?? is unreachable because the left operand is never nullish.` error by using `||` operator.
=> fix: use `||` operator instead of unreachable `??`

src/components/backend-ai-folder-explorer.ts
This PR resolves an issue where the SFTP session is created as an interactive session rather than an upload session due to the missing session `type` argument.
=> fix: Add the missing session `type` argument to the SFTP session creation API

react/src/index.tsx
Suppress Relay GraphQL Field Warning Messages in Development
This change filters out frequent Relay warning messages in the browser console during development. These warnings occur due to GraphQL query directives used for manager version compatibility and do not indicate actual issues.
The warnings specifically relate to "RelayResponseNormalizer: Payload did not contain a value for field" messages, which are expected behavior but can clutter the development console.
**Checklist:**
- Before: Console shows repeated Relay field warnings
- After: These specific warnings are suppressed while preserving other console messages
=> chore: suppress Relay warning messages in development mode

react/src/components/ResourceAllocationFormItems.tsx, react/src/pages/SessionLauncherPage.tsx
This PR resolves [#2837](https://github.com/lablup/backend.ai-webui/issues/2837)
**Changes:**
Makes agent selection in resource allocation form configurable via a new `enableAgentSelect` prop, defaulting to false. The agent selection field will only display when both `enableAgentSelect` is true and `baiClient._config.hideAgents` is false.
**Implementation:**
- Added `enableAgentSelect` prop to ResourceAllocationFormItems component
- Set `enableAgentSelect` to true in SessionLauncherPage to maintain existing behavior
- Agent selection field visibility now requires both configuration flags to be properly set
**Testing Steps:**
> Prerequisites: 
> - Create model type vfolder
> - Create model-definition.yaml file and upload it to the vfolder you just created in step 1, according to the link …
=> add:  option to show/hide agent select option by launcher

react/src/components/AgentDetailModal.tsx
closes https://github.com/lablup/backend.ai-webui/issues/2890
**Changes:**
Updates network statistics display in the Agent Detail Modal to use decimal units (B) instead of binary units (iB) for TX/RX values, making the display more consistent with common network traffic representations.
**Checklist:**
**Testing:**
Verify that network traffic values (TX/RX) in the Agent Detail Modal are now displayed with 'B' (bytes) instead of 'iB' (binary bytes) suffix.
=> fix: Convert network live stats to decimal size units.

react/src/components/ProjectSelect.tsx, react/src/components/StorageHostSettingsPanel.tsx
closes https://github.com/lablup/backend.ai-webui/issues/2891
Adds `popupMatchSelectWidth={false}` to ProjectSelect component to allow the dropdown width to adjust based on content rather than matching the width of the select input.
**Checklist:**
=> style: set `popupMatchSelectWidth` to false of `ProjectSelect`

react/src/components/LoginSessionExtendButton.tsx
The PR resolves [backend.ai#3180](https://github.com/lablup/backend.ai/issues/3180) changes the condition for detecting an expired session from checking if seconds are exactly 0 to checking if the total duration in seconds is less than or equal to 0. This fixes an edge case where the session could appear valid even when expired.
**Checklist:**
> Prerequisites
> [Webserver related setup]
> 1. Set `enable_extend_login_session` to True in the `service` section of the `webserver.conf` file.
> 2. Set `login_session_extension_sec` to 3600 (one hour) in the `session` section of the `webserver.conf` file.
> 3. Restart the webserver process.
>
> [WebUI related setup]
> 1. Set `enableExtendLoginSession` to true in the `general` section of the `config.toml` file.
1. Login with any active user …
=> fix: compare time is expired by using `asSeconds()` instead of `seconds()`

react/src/components/ResourceAllocationFormItems.tsx
[Teams](https://teams.microsoft.com/l/message/19:14c484402d874dafb15806d093b95a82@thread.skype/1733106308378?tenantId=13c6a44d-9b52-4b9e-aa34-0513ee7131f2&groupId=74ae2c4d-ec4d-4fdf-b2c2-f5041d1e8631&parentMessageId=1733106308378&teamName=devops&channelName=Frontend&createdTime=1733106308378)
Currently, the `Accelerator` form in `ResourceAllocationFormItems.tsx` sets disable based on the accelerator resource limit of the selected image.
However, there are cases where the selected resource group does not support accelerators, so we need to add whether the resource group has selectable accelerators to the disabled determination.
**Changes:**
- Added a condition to the disabled determination condition for AI Accelerator for if there are no selectable accelerators in the resource group …
=> fix: disabled accelerator select when no GPUs are allowed

react/src/components/ContainerRegistryEditorModal.tsx
Fixes #2904.
Minium required manager version: 24.09
=> fix: Add missing container registry types

react/src/components/BAIIntervalView.tsx, react/src/components/LoginSessionExtendButton.tsx, react/src/hooks/useIntervalValue.tsx
**Changes:**
This PR resolves [backend.ai#3180](https://github.com/lablup/backend.ai/issues/3180)
Added a 5-second timeout delay before reloading the page when the login session expires in the LoginSessionExtendButton component. This ensures the page reload is properly applied after session expiration. Also added a disabled state to prevent button interaction during expiration.
**Rationale:**
The immediate page reload was causing issues with proper application of the reload. The timeout ensures the system has enough time to process the session expiration before triggering the reload action. The disabled state prevents users from attempting to extend an already expired session.
**Impact:**
Users will experience a 5-second delay between their session expiring and the page reloading, …
=> fix: add 5s delay when session expiration datetime is over

react/__test__/matchMedia.mock.js, react/src/components/ResourceAllocationFormItems.test.ts, react/src/components/ResourceAllocationFormItems.tsx, react/src/components/ResourceGroupSelect.tsx, react/src/hooks/useResourceLimitAndRemaining.test.ts, react/src/hooks/useResourceLimitAndRemaining.tsx
Resolves #2911
When a user changes the resource group, the related data is not updated as expected. This issue occurs in the following scenario:
1. The user navigates to the session launcher or service launcher.
2. The user changes the resource group
3. The expected behavior is that all related data and configurations should update to reflect the new resource group such as accelerator types.
4. However, the data remains unchanged, leading to inconsistencies.
**Changes:**
- Replaced global resource group state with form-level resource group state in ResourceAllocationFormItems
- Added transition handling for resource group selection changes to prevent UI jitters
- Added validation to ensure selected resource group exists before checking presets
- Improved auto-selection behavior for …
=> fix:  Resource group change does not update related data in form

react/src/RelayEnvironment.ts, react/src/components/BAIErrorBoundary.tsx, react/src/components/LoginSessionExtendButton.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/th.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json
Resolves #2918
**Changes:**
Improves login session expiration handling by:
- Adding dedicated error messages and UI for expired login sessions
- Implementing proper error propagation for 401/authorization errors
- Centralizing login session state management using Jotai
- Adding translations for session expiration messages across all supported languages
**Impact:**
- Users now see a clear "Session Expired" message instead of a generic error
- Provides a direct "Login" button when sessions expire
- More graceful handling of authorization failures
- Consistent experience across all languages
**Testing Requirements:**
1. Verify session expiration message appears when token expires
2. Confirm authorization errors show proper UI
3. Check translations display correctly in different languages
4. …
=> feat: Add error view for expired login session

react/src/components/WebUILink.tsx
Resolves #2905
**Changes:**
Adds meta/ctrl key detection to WebUILink component to prevent triggering navigation event for `backend-ai-app` web component navigation. 
**Impact:**
Users can now use standard keyboard shortcuts (cmd/ctrl + click) to open links in new tabs, matching expected browser behavior.
=> fix: allow cmd/ctrl click to open link in new tab

react/src/components/ContainerRegistryEditorModal.tsx
Resolves #2901
Removes hardcoded Docker Hub project restrictions, allowing users to specify custom projects for Docker Hub registries instead of defaulting to 'library'
=> fix: enable and remove auto-setting for project name field

resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/th.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json
This PR resolves #2921 by updating the "Download Backend.AI Web UI App" text across all language files to reference "Desktop App" instead, making the terminology more generic and user-friendly.
**Changes:**
- Replaces "Backend.AI Web UI App" with "Desktop App" (or equivalent translation) in:
- German: "Laden Sie die Desktop-App herunter"
- Greek: "Κατεβάστε την εφαρμογή Desktop"
- English: "Download Desktop App"
- Spanish: "Descargar la aplicación de escritorio"
- Finnish: "Lataa työpöytäsovellus"
- French: "Télécharger l'application de bureau"
- And 13 other language files
**Checklist:**
=> misc: replace title of desktop app download to be more comprehensive

react/src/components/BAIPropertyFilter.tsx
Resolves #2939
**Changes:**
Updates the filter combination logic in BAIPropertyFilter to:
- Return `undefined` instead of empty string when merging empty filter values
- Change operator types from 'and'/'or' to '&'/'|' to match backend expectations 
- Standardize filter combination to use '&' operator consistently
=> fix: use combine operator `& and `|`

react/src/components/ComputeSessionList.tsx, react/src/components/ComputeSessionNodeItems/ContainerLogModal.tsx, react/src/components/ComputeSessionNodeItems/ContainerLogModalWithLazyQueryLoader.tsx, react/src/components/SessionDetailAndContainerLogOpenerLegacy.tsx
Resolves #2944
**Changes:**
- Refactored session log modal opening mechanism to use React transitions for smoother loading states
- Added proper cleanup of selected kernel when container log modal closes
- Improved modal state management by moving logic to a dedicated component
**Rationale:**
The changes improve the user experience when opening session logs by:
- Preventing UI jank during loading with transition states
- Ensuring cleaner state management between modal opens/closes
**Effects:**
Users will experience:
- Smoother transitions when opening session logs
- More consistent behavior when closing and reopening logs
- Better handling of loading states with visual feedback
=> refactor: Session log modal transition handling

package.json, pnpm-lock.yaml
fix: Resolve node module macos-alias installation on non-macOS platforms
- Add `optionalDependencies` for node module `macos-alias` in package.json
- Prevent npm build failures on Linux platform & non-macOS platforms
closes #2941
Reference:
* npm Doc: package.json's optionalDependencies section
https://docs.npmjs.com/cli/v10/configuring-npm/package-json#optionaldependencies
* what's the difference of optionalDependencies and peerDependenciesMeta's optional? https://stackoverflow.com/questions/74916906/whats-the-difference-of-optionaldependencies-and-peerdependenciesmetas-optiona
=> fix: Resolve node module macos-alias installation on non-macOS platforms

react/src/components/SessionDetailContent.tsx
resolves https://github.com/lablup/backend.ai-webui/issues/2955 
**Changes:**
Enhances the session detail view by wrapping the resource allocation section and displaying the scaling group inside a Tag component for better visual hierarchy and consistency.
**Impact:**
Users will see a clearer, more visually distinct scaling group indicator in the session details, with improved wrapping behavior for resource allocation information.
**Before:**
**After:**
**Checklist:**
=> style: Add flex-wrap and tag resource group text for improved readability.

src/components/backend-ai-resource-group-list.ts
Related PR: [control-panel#930](https://github.com/lablup/backend.ai-control-panel/pull/930)
**Changes:**
Currently, validation rules are not applied in Backend.AI Core, but plan to add them to the scope of domain and project in the future. Therefore, I added validation rules (allow dot and unicode) to match the rules on the core side.
**Invalid strings:**
- contains special characters 
- consisting of leading, trailing, or only spaces, or more than one space between characters.
- empty string
- Move to resources page and click resource group tab
- Create a new resource group and verify that the validation rule works correctly.
=> fix: enhance resource group name validation logic for spaces and special characters

react/src/components/ResourceAllocationFormItems.tsx, react/src/pages/SessionLauncherPage.tsx
Resolves #2958
**Changes:**
To fix the inconsistency bug, refactored resource allocation preset handling in session launcher to improve reliability and maintainability:
1. Typo: renamed initial allocation preset from 'auto-preset' to 'auto-select'
2. Wrapped resource field update functions with useEventNotStable to prevent invoke useEffect unnecessary.
3. Consolidated preset selection logic into a single useEffect hook that handles:
- Initial form setup when resourceSlots are loaded
- Automatic preset selection based on available resources
- Validation of accelerator type
4. Added separate useEffect for handling minimum-required preset updates when image changes
These changes make the resource allocation behavior more predictable and easier to maintain while fixing potential race …
=> fix: auto-update login inconsistency in ResourceAllocationFormItems

react/src/components/AgentList.tsx, react/src/components/AgentSummaryList.tsx, react/src/components/ContainerRegistryList.tsx, react/src/components/CustomizedImageList.tsx, react/src/components/ErrorLogList.tsx, react/src/components/ImageList.tsx, react/src/components/KeypairResourcePolicyList.tsx, react/src/components/ProjectResourcePolicyList.tsx, react/src/components/TableColumnsSettingModal.tsx, react/src/components/UserResourcePolicyList.tsx, react/src/hooks/useBAISetting.tsx, react/src/hooks/useHiddenColumnKeysSetting.tsx, react/src/pages/EndpointListPage.tsx
resolves https://github.com/lablup/backend.ai-webui/issues/2809
**Changes:**
Refactored table column visibility management across multiple list components to use centralized user settings storage instead of individual localStorage entries. This change:
- Replaces `useLocalStorageState` with `useBAISettingUserState` for storing hidden column preferences
- Updates column visibility logic to use a hidden columns approach rather than displayed columns
- Standardizes column setting modal behavior across components using `useToggle`
- Implements consistent column visibility state management pattern across:
- AgentList
- AgentSummaryList
- ContainerRegistryList
- CustomizedImageList
- ErrorLogList
- ImageList
- KeypairResourcePolicyList
- ProjectResourcePolicyList
- UserResourcePolicyList
- …
=> fix: switch to managing hiddenColumnKeys in TableColumnsSettingModal

react/data/schema.graphql, react/src/components/BAICodeEditor.tsx, react/src/components/ContainerRegistryEditorModal.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/th.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json
related Core PR: [#3208](https://github.com/lablup/backend.ai/pull/3208)
24.09~24.09.2 : Using `container_registry_nodes` but does not support extra fields.
24.09.3 ~ : support extra field
**Changes:**
Extra field and argument are supported from version 24.09.3 onwards. 
Because the arguments for each mutation are not provided as input types, you must create a separate mutation if you want to exclude a specific argument.
- Added `extra` field to container registry nodes to support additional JSON metadata
- Added JSON editor UI component for managing extra information in container registry editor
- Added validation for proper JSON formatting with error messages
- Made `value` and `onChange` props optional in BAICodeEditor component
- Added translations for JSON format validation messages …
=> feat: support for extra field in registry type

react/src/hooks/useBackendAIImageMetaData.test.tsx, resources/image_metadata.json
**Changes:**
Updated all instances of "Nvidia" to "NVIDIA" in GPU Cloud references across image metadata and test files to maintain consistent branding with NVIDIA's official capitalization.
> The correct way of writing NVIDIA is in all uppercase letters.
**Rationale:**
Ensures proper brand name representation and consistency with NVIDIA's corporate identity guidelines.
Ref
- https://http.download.nvidia.com/image_kit/LG_NVCorpBadge.pdf
**Checklist:**
=> chore: update NVIDIA references in image metadata

react/src/components/lablupTalkativotUI/ChatUIModal.tsx, react/src/components/lablupTalkativotUI/LLMChatCard.tsx, react/src/pages/EndpointDetailPage.tsx
resolves #2865 
**Changes:**
Adds automatic token population in the chat UI modal by passing the most recently created endpoint token to the chat interface.
**Details:**
- Extends `ChatUIModal` to accept endpoint token fragment data
- Adds logic to find the newest token from the endpoint token list
- Automatically populates the token field in the chat interface with the most recent token
- Enhances user experience by removing manual token entry requirement
1. Click the LLM Chat Test from the serving page.
2. If it is not a public vllm model, you can get the custom modal.
3. If there are tokens, the most recently created and valid token will be set as the placeholder.
4. If there is no valid token, the placeholder is empty.
**Checklist:**
**Review Requirements:**
1. Verify …
=> feat: Set the initial value of the chat modal to the recently created token

react/src/components/UserSettingModal.tsx
closes https://github.com/lablup/backend.ai-webui/issues/2964
Updates the user settings modification logic to use `_.isNil` instead of `_.isEmpty` when filtering properties, ensuring that `sudo_session_enable` is changed properly.
**Checklist:**
=> hotfix: `sudo_session_enable` setting doesn't work

react/src/components/ComputeSessionNodeItems/SessionActionButtons.tsx, react/src/components/ComputeSessionNodeItems/SessionStatusTag.tsx, react/src/components/SessionList.tsx, react/src/components/SessionListColums/SessionInfoCell.tsx, react/src/pages/SessionListPage.tsx, src/components/backend-ai-edu-applauncher.ts, src/components/backend-ai-session-list.ts, src/components/backend-ai-session-view.ts, src/lib/backend.ai-client-es6.js, src/lib/backend.ai-client-esm.ts, src/lib/backend.ai-client-node.js, src/lib/backend.ai-client-node.ts
After https://github.com/lablup/backend.ai/pull/3114, Added `CREATING` session status to represent container creation phase, and redefined `PREPARING` status to specifically indicate pre-container preparation phases.
=> feat: Add `CREATING` session status

react/src/components/UserCredentialList.tsx, src/components/backend-ai-summary-view.ts
Updates the credential page navigation and improves the invitation panel UI:
1. Changes credential page navigation parameters from `?action=add` and `?action=manage` to `?tab=credentials`
2. Enhances invitation panel layout:
- Adds proper spacing between buttons using `gap: 8px`
- Makes panel narrow with `scrollableY="true"`
- Improves vertical layout with justified flex wrap
- Adds consistent 10px padding and gap spacing
These changes provide better navigation consistency and a more polished invitation interface.
**Checklist:**
=> fix: resetting the navigate route and modifying the CSS in summary page

react/data/schema.graphql, react/src/components/ProjectResourcePolicyList.tsx, react/src/components/ProjectResourcePolicySettingModal.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/th.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json, src/lib/backend.ai-client-esm.ts
Related PR: [Core #2857](https://github.com/lablup/backend.ai/pull/2857)
Fixes an issue where the addition of the `max_network_count` field to the Project resource policy prevented the creation of a new project resource policy due to the undefinedType input of that field.
**Changes:**
- Since core version "24.12.0", `max_network_count` field was added to the proeject resource policy.
=> fix: set `Max Network Count` field to project resource policy

react/src/components/BAIProgressWithLabel.tsx, react/src/components/SessionDetailContent.tsx, react/src/components/SessionUsageMonitor.tsx
**Changes:**
- Displays the resources allocated to the session. Currently, the compute session node does not include a live stat field, which shows the live stat information of the main kernel associated with the session.
- Since each device has different usage, I've shown the usage below the progress bar to bring consistency to the design.
- Access the Detail page of the endpoint that is currently in service. 
- Verify that resource usage looks normal.
|normal|small screen|
|---|---|
|![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/lSyr8xXz1wdXALkJKzVx/b491c912-330f-4467-b995-b0d05aded2ea.png)|![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/lSyr8xXz1wdXALkJKzVx/c1bb67ea-d3c5-4b79-8ee1-18fb9e052906.png)|
**Checklist:** (if …
=> [FR-52] feat: Session usage monitor in react

react/src/components/lablupTalkativotUI/ChatMessage.tsx, react/src/components/lablupTalkativotUI/LLMChatCard.tsx
> [!NOTE]  
> Many LLM models send token info as a NaN; So calculate usages on a front part.
Adds real-time performance metrics to the chat interface including:
- Token generation speed (tokens/second)
- Total tokens generated
The metrics are displayed in a tag at the bottom of the chat window, providing users visibility into the chat performance.
**Checklist:**
- Messages are generated
- Files are uploaded
- Chat session continues over time
=> [FR-22] feature: provide token-related information

react/package.json, react/pnpm-lock.yaml, react/src/components/lablupTalkativotUI/LLMChatCard.tsx, react/src/hooks/useTokenizer.ts
**Changes:**
Implements accurate token counting for LLM chat using the `gpt-tokenizer` library instead of character length calculations. This provides more precise token measurements for GPT model interactions.
**Details:**
- Added `gpt-tokenizer` package dependency
- Created new `useTokenizer` hook for async token counting
- Updated token calculations in LLMChatCard to use proper tokenization
- Separated token counting for input, chat messages, and assistant responses
- Improved tokens per second calculation accuracy
**Impact:**
Users will see more accurate token counts and token/second metrics in the chat interface, which better reflects actual GPT model token usage.
=> [FR-316] feat: introduce `useTokenCount` using `gpt-tokenizer`

react/src/helper/index.tsx, react/src/pages/SessionLauncherPage.tsx
**Changes:**
- Adds default empty string parameter to `preserveDotStartCase` function to prevent undefined errors
- Initialize the query string via setQuery on reset. currentTabKey will change, so it will be moved to the first step.
- use form.resetFields() method to initialize the form value to the Initial value. If the form value changes, `syncFormToURLWithDebounce` is executed by the provider and the initialization value is saved as a query string.
**Checklist:**
=> [FR-7] fix: neo session launcher reset function behavior

react/src/components/AgentSummaryList.tsx, react/src/hooks/useCurrentProject.tsx
Refactors SFTP scaling group data fetching in agent summary list because original code is for only superadmin. To allow all users access to the agent summary page, a different API should be used.
This PR moves the SFTP scaling group data fetching logic from the AgentSummaryList component to the useCurrentProject hook. Instead of making a direct API call within the component, it now uses the pre-fetched data from the project context, improving code organization and reducing redundant API calls.
The change simplifies the AgentSummaryList component by removing the direct backend client dependency and API call logic, while maintaining the same filtering functionality for SFTP upload agents.
**Checklist:**
- Verify that SFTP agents are still properly filtered from the agent summary list
- …
=> [FR-341] fix: Page Error on Accessing Agent Summary with a Regular User Account

react/src/components/FolderCreateModal.tsx, react/src/components/StorageStatusPanel.tsx, react/src/pages/VFolderListPage.tsx
Apply rules based on the `current user role` and `list_allowed_types` to the vfolder type selector in `FolderCreateModal`. 
**Changes:**
- Only `super admin` or `admin` can create project type vfolder. 
- vfolder type in folder create modal is based on `list_allowed_types` comes from server
- Show `max_vfolder_count` in `Project Resource Policy` if user role is only `Super Admin` or `Admin`.
=> [FR-240] fix: show vfolder types in folder create modal based on user permission

.gitignore, e2e/envs/.env.playwright.sample, e2e/screenshot.test.ts, e2e/test-util.ts, package.json, playwright.config.ts, pnpm-lock.yaml
resolves https://lablup.atlassian.net/browse/FR-344
Added screenshot testing functionality to capture UI states across all routes. The tests take screenshots in four variations for each route:
- Normal view
- Dark mode
- Without sidebar
- Dark mode without sidebar
Added configuration option `test.screenshotPath` to specify custom screenshot save location, defaulting to `e2e/screenshots` directory.
Upgraded Playwright test framework from v1.46.1 to v1.49.1 for improved testing capabilities.
=> [FR-344] feat: auto screenshot with Playwrite

react/src/components/ComputeSessionNodeItems/ContainerLogModal.tsx
resolves https://lablup.atlassian.net/browse/FR-356
**Changes:**
Disabled clickable links (`enableLinks`) in container log viewer to prevent logs from disappearing.
**How to check:**
1. login with demo-admin@lablup.com in dogbowl
2. search `test2-4fadc1ba-d370-4f9b-a682-ca15b5963c2a` logs in terminated session.
3. compare 161 line.
4. check all contents appear.
**Checklist:**
=> [FR-356] fix: remove `enableLinks` to prevent logs from disappearing in the container log

.github/PULL_REQUEST_TEMPLATE.md
This PR adds a reminder to explicitly link the GitHub issue and the corresponding Jira issue.
=> chore: Update PR template to remind mentioning both GitHub/Jira issues

.cspell.json, react/src/components/ServiceLauncherPageContent.tsx, react/src/components/ServiceValidationView.tsx, react/src/pages/EndpointDetailPage.tsx, react/src/pages/EndpointListPage.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/th.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, src/lib/backend.ai-client-esm.ts
Since Backend.AI Core version 24.12.0, the desired_session_count field has been replaced with `replicas`. 
**Changes:**
- Added `replicas` field to service creation and update interfaces
- Deprecated `desired_session_count` field for manager version >= 24.12.0
- Updated GraphQL queries to handle both `desired_session_count` and `replicas` fields
- Added version-based field selection using `@deprecatedSince` and `@since` directives
- Added `replicas` feature flag check in client capabilities
- Check whether `desired_session_count` or `replicas` is used when creating or modifying a service, depending on the manager version. (From 24.12.0 onwards, replicas is used.) 
- Check whether desired_session_count is displayed correctly on the Service page and Detail page.
=> feat(FR-17): update `desired_session_count` field name to `replicas`

react/src/components/ComputeSessionNodeItems/EditableSessionName.tsx, react/src/components/SessionDetailContent.tsx, react/src/components/SessionDetailDrawer.tsx, react/src/components/SessionNameFormItem.tsx, react/src/hooks/backendai.tsx, src/components/backend-ai-login.ts, src/lib/backend.ai-client-esm.ts
resolves #3035 (FR-244)
Enhances session name editing functionality with improved validation and user experience:
- Adds form-based editing interface with validation rules for session names
- Implements escape key to cancel editing
- Shows visual feedback during editing with a down-left corner icon
- Maintains consistent validation rules between initial creation and editing
- Enables editing session names directly in the session detail drawer
- Restricts editing to session owners and non-preparing states
- Prevents accidental drawer closure with keyboard shortcuts while editing
**Checklist:**
=> feat(FR-244): session renaming in the session detail panel

react/src/components/ModelCardModal.tsx, react/src/components/ModelCloneModal.tsx, src/components/backend-ai-data-view.ts, src/components/backend-ai-folder-explorer.ts, src/components/backend-ai-storage-list.ts, src/components/backend-ai-summary-view.ts, src/lib/backend.ai-client-esm.ts, src/lib/pep440.test.ts
resolves https://github.com/lablup/backend.ai-webui/issues/3039 (FR-372)
related PR: https://github.com/lablup/backend.ai/pull/3451
Adds support for vfolder ID-based operations in the backend client and updates related components to handle both name-based and ID-based folder operations. This change enables more reliable folder management by using unique IDs instead of potentially ambiguous folder names.
**Changes:**
- Introduces `vfolder-id-based` feature flag for manager versions 25.1.0, 24.09.5, and 24.03.11
- Updates folder operations (clone, rename, share, info) to use folder IDs when supported
- Modifies file operations within folders to use the appropriate identifier
- Updates UI components to handle both ID and name-based operations seamlessly
**How to check:**
1. checkout core …
=> feat(FR-372): support id based object resolution

react/src/components/ImageInstallModal.tsx, react/src/components/ServiceLauncherPageContent.tsx, react/src/components/ServiceValidationView.tsx, react/src/pages/EndpointDetailPage.tsx
resolves #3043 (FR-384) #3044 (FR-382)
Introduces a new `namespace` field for image objects while deprecating the existing `name` field. This change affects how image names are constructed throughout the application, particularly in the image installation modal, service launcher, and endpoint detail pages.
The image name construction now prioritizes the `namespace` field, falling back to `name` when namespace is not available: `registry/namespace:tag` or `registry/name:tag`.
**Checklist:**
=> fix(FR-382, FR-384): Handle deprecated image name fields in service launcher and image download

react/src/components/ComputeSessionNodeItems/ContainerCommitModal.tsx, react/src/components/ContainerRegistryList.tsx, react/src/components/ContainerRegistryListBefore2409.tsx, react/src/components/MaintenanceSettingList.tsx, react/src/components/ModelCloneModal.tsx, react/src/hooks/useBAINotification.tsx, react/src/pages/SessionLauncherPage.tsx
resolves #3060, [(FR-352)](https://lablup.atlassian.net/browse/FR-352)
I added functionality to handle `task's status` based on the notification in `useNotification`. Since the existing approach was not changed, no additional modifications are needed.
**changes**
* update `useBAINotification` to handle task's status
* refactor `MaintenanceSetttingList` component (I have confirmed that it is working properly.)
=> feature(FR-352): update-useBAINotification

react/src/components/ImageList.tsx, react/src/components/ManageAppsModal.tsx, react/src/components/ManageImageResourceLimitModal.tsx
resolves #3063 (FR-423)
Updates image fragment handling in ManageAppsModal and ManageImageResourceLimitModal to support the new namespace field introduced in version 24.12.0, while maintaining backwards compatibility with the deprecated name field.
**Checklist:**
- Verify image management works with both old and new image naming formats
- Confirm resource limits and app management functions correctly with namespaced images
=> fxi(FR-423): Unkown image error in Image list's control modal

react/src/components/SessionDetailContent.tsx
resolves #3051 (FR-249)
>https://github.com/lablup/backend.ai/pull/3461 PR must be merged first.
This PR makes folder explorer available in the Session Detail Panel.
In versions prior to Backend.AI Core 24.12.0, the vfolder_nodes field is not provided. Therefore, you must use the `mounts` field of the `compute_session_node` query.
Mounts field does not provide vfolder name. So we need to use `vfolder_mounts` field in legacy `compute_session` query.  vfolder_mounts' provide the name of the vfolder in the same order as the `mounts' field in `compute_session_node'.
**Feature:**
- allow to open folder explorer in session detail panel
- checkout Core branch to [lablup/backend.ai#3461](https://github.com/lablup/backend.ai/pull/3461)
- open session detail panel. you can open …
=> feat(FR-247, FR-249): open folder explorer from session detail panel using vfolder_mounts

react/src/App.tsx, react/src/components/MainLayout/WebUISider.tsx, react/src/hooks/useBAISetting.tsx, react/src/pages/UserSettingsPage.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/th.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json
Resolves #3094 (FR-459)
Adds an experimental NEO session list feature that can be toggled in user settings. When enabled, users are redirected to a new `/session` path instead of the legacy `/job` path for viewing compute sessions. The new view includes a loading skeleton while the session list loads.
To test:
1. Enable the "NEO Session List" option under User Settings > Experimental Features
2. Navigate to Sessions from the sidebar
3. Verify redirection to new `/session` path with loading skeleton
4. Verify legacy `/job` path still works when feature is disabled
=> feat(FR-459): User setting for experimental NEO session list

react/src/components/FolderCreateModal.tsx, src/components/backend-ai-data-view.ts, src/components/backend-ai-storage-list.ts
resolves #3031 (FR-368)
Adds a new `backend-ai-folder-created` event to refresh the folder list immediately after folder creation in the React modal component. This ensures the storage list view stays synchronized when folders are created through the new React-based creation modal.
**Checklist:**
1. Create a new folder
2. Check the folder list is updated immediately.
Check the folder list is updated immediately.
=> feat(FR-368): Update folder list Immediately after creating a new folder.

react/src/components/ComputeSessionNodeItems/SessionIdleChecks.tsx, react/src/components/ComputeSessionNodeItems/SessionReservation.tsx, react/src/components/IdleCheckDescriptionModal.tsx, react/src/components/SessionDetailContent.tsx, react/src/pages/SessionListPage.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/th.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json, src/components/backend-ai-session-list.ts, src/lib/backend.ai-client-esm.ts
resolves #3062 (FR-250)
>The issues below will be addressed as separate issues. 
> - Utilization checks should add heterogeneity support, currently only checks for cuda and ipu devices.
> - Utilization checks should return the device key as the key of the device metadata.
> - The session end time calculated by the idle checker is returned as remaining (sec) and calculated on the client side, which may cause an error from the actual calculated value.
**Changes:**
- Provide idle check information in the session details panel. 
- Fixed `SessionDetailContent` to use fetchKey of `SessionDetailDrawer` as controllableState for refetch session data via session status.
- Sends an interval network request to update the information in the idle checker.
- Displays an alert at the top of the drawer …
=> feat(FR-250): show session idle checker in session detail panel

react/src/components/SessionDetailAndContainerLogOpenerLegacy.tsx, react/src/components/SessionDetailContent.tsx, react/src/pages/EndpointDetailPage.tsx, src/components/backend-ai-session-list.ts, src/lib/backend.ai-client-esm.ts
resolves #3091 (FR-458)
Adds version compatibility to the session detail panel. 
**Feature:**
- session detail panel is available in version after 24.09 and later (after additional versions of session-node)
- folder explorer in session detail panel is available in version after 25.1.1, and after 24.09.6. Not available in version 24.12.xx
- You can use the folder explorer opener by clicking the session list name or by clicking the session id on the endpoint detail page.
- Verify that the session detail panel is not available in versions prior to 24.09.
- Verify that the folder explorer in session detail panel is not available in versions prior to 25.1.1, and prior to 24.09.6.
=> fix(FR-458): set session detail panel version compatibility

react/src/components/BAITable.tsx, react/src/components/SessionNodes.tsx
resolves #3103 (FR-465)
Introduces a new `neoStyle` prop to BAITable component, replacing the previous `tableComponentToken`. This change provides a more focused styling approach for table headers, particularly in light mode where headers now have a specific background color (#E3E3E3). The styling is applied through a combination of CSS classes and theme configuration.
The changes can be verified by:
1. Checking table header appearance in both light and dark modes
2. Confirming the header background color (#E3E3E3) in light mode when `neoStyle` is enabled
3. Verifying that existing table functionality remains intact
=> feat(FR-465): Add prop to enable NEO style in BAITable

react/src/pages/EndpointDetailPage.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/th.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json, resources/theme.json
resolves #2974 (FR-473)
Added internationalization support for auto-scaling rule table headers in the endpoint detail page. The following columns are now translated across all supported languages:
- Metric Name
- Metric Source
- Min/Max Replicas
- Last Triggered
- Created At
**Checklist:**
=> misc(FR-473): missing i18n update and remove table token value

react/src/App.tsx, react/src/pages/EndpointDetailPage.tsx, react/src/pages/ServiceLauncherPage.tsx
resolves #3110 (FR-470)
To fix unexpected infinite rendering:
Updates the GraphQL fragment in EndpointDetailPage to include ServiceLauncherPageContentFragment and modifies the fetch policy in ServiceLauncherPage from 'network-only' to 'store-and-network' to improve data caching behavior.
=> fix(FR-470): Unable to access service update page

react/src/components/ServiceLauncherPageContent.tsx
resolves #3114 (FR-472)
Adds `allocationPreset` parameter with default value of 'auto-select' to the service launcher configuration, enabling automatic resource allocation for new service instances.
=> fix(FR-472): empty resource preset in service launcher

e2e/maintenance.test.ts, e2e/test-util-antd.ts, react/src/components/MaintenanceSettingList.tsx
resolves #3041, [(FR-393)](https://lablup.atlassian.net/browse/FR-393)
**changes**
* Added test cases for `Rescan Images` and `Recalculate Usage` on the `maintenance` page.
* Added functions in `test-util-antd.ts` to retrieve notification text.
* Added `1-minute` timeout to rescan image test (1min)
**Checklist:**
=> feature(FR-393): add e2e test for maintenance page

react/src/pages/EndpointDetailPage.tsx
resolves #3115 (FR-480)
Added version compatibility check for auto-scaling rules in the endpoint detail page. The auto-scaling rules section will only be displayed when the manager version is 25.1.0 or higher.
=> fix(FR-480): Backward version compatibility for Endpoint Autoscaling Rules

react/src/components/ComputeSessionNodeItems/ConnectedKernelList.tsx, react/src/components/ComputeSessionNodeItems/ContainerLogModal.tsx
resolves #3138 (FR-503)
Added a container log viewer button to the connected kernel list. Users can now directly view container logs for each kernel by clicking the log icon next to the kernel ID, which opens a modal displaying the container logs.
=> feat(FR-503): open kernel log modal in Kernel list

react/src/components/ComputeSessionNodeItems/ConnectedKernelList.tsx, react/src/components/UnmountModalAfterClose.tsx
resolves #3137 (FR-502)
Introduces a new `UnmountModalAfterClose` component that properly unmounts modal components after they close, preventing unnecessary re-renders and memory leaks. The component is implemented in the `ConnectedKernelList` to manage the `ContainerLogModal`.
The new component:
- Tracks modal open/close state internally
- Preserves original `afterClose` callbacks
- Only renders the modal when needed
- Handles cleanup after modal animations complete
=> feat(FR-502): introduce UnmountModalAfterClose

react/src/components/BAIJSONViewerModal.tsx, react/src/components/InferenceSessionErrorModal.tsx, react/src/components/ServiceLauncherPageContent.tsx, react/src/pages/EndpointDetailPage.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/th.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json
resolves #3179 (FR-532)
Improves error handling and visualization in the model service UI by:
1. Adding a new JSON viewer modal component for displaying error details
2. Replacing question mark icons with exclamation icons for error indicators
3. Adding error data visualization for both session and route errors
4. Adding translations for JSON format errors and route errors across all languages
=> feat(FR-532): display error_data of model service's route

react/src/components/BAIPropertyFilter.tsx, react/src/components/SessionUsageMonitor.tsx, react/src/pages/ComputeSessionListPage.tsx
resolves #3175 (FR-528)
Improves UI layout and responsiveness:
- Removes unnecessary flex styling in BAIPropertyFilter
- Caps session utilization bar width to 140px in SessionUsageMonitor
- Makes compute session list filters wrap properly on smaller screens
=> fix(FR-528): session list filter UI in small screen

react/src/components/BAIFetchKeyButton.tsx, react/src/components/BAITable.tsx, react/src/hooks/useDeferredQueryParams.tsx, react/src/pages/ComputeSessionListPage.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/th.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json
resolves #3174 (FR-567)
Adds auto-refresh functionality to the compute session list page with a dedicated refresh button that shows loading state and supports automatic updates every 15 seconds. The table now displays a loading state with reduced opacity during updates and shows the total number of items.
Key changes:
- New `BAIFetchKeyButton` component for manual/automatic data refresh
- Enhanced table loading states with smooth opacity transitions
- Added "Last Updated" translations across all languages
- Improved badge visibility for running sessions
- Fixed state updates in `useDeferredQueryParams` hook
=> feat(FR-527): introduce BAIFetchKeyButton

react/src/pages/ComputeSessionListPage.tsx
resolves #3080 (FR-448)
Adds individual session count badges for each session type (interactive, inference, batch, system) in the compute session list page. Previously, only the total count of running sessions was displayed. Now, each tab shows the count of active sessions for its specific type.
=> feat(FR-448): Type counts in NEO session list tabs

src/components/backend-ai-session-list.ts
resolves #3101 (FR-464)
This pull request includes changes to the `SessionList` component to improve type safety and optimize the rendering of mounted folders.
Type safety improvements:
* [`react/src/components/SessionList.tsx`](diffhunk://#diff-ede34ab99a0537aad79dc2a521bba1562b78a3337e681653981e693ac11bcb85L202-R202): Modified the `render` function to explicitly type the `value` parameter as an array of strings.
Rendering optimization:
* [`react/src/components/SessionList.tsx`](diffhunk://#diff-ede34ab99a0537aad79dc2a521bba1562b78a3337e681653981e693ac11bcb85L212-R212): Changed the `title` property in the `tooltip` to use `_.uniq` to ensure that only unique mounted folders are displayed.
Refs
- lablup/backend.ai#3593
=> fix(FR-464): Ensure unique values in compute session mount list

react/src/components/SessionDetailContent.tsx
resolves #3142 (FR-506)
Fixes an issue where the design was inconsistent because the width of the description was not specified.
=> fix(FR-506): Set the width of the description in the session detail panel to maximum

react/src/components/lablupTalkativotUI/EndpointLLMChatCard.tsx, react/src/components/lablupTalkativotUI/LLMChatCard.tsx, react/src/helper/index.tsx
resolves https://github.com/lablup/backend.ai-webui/issues/2861 ([FR-255](https://lablup.atlassian.net/browse/FR-255?atlOrigin=eyJpIjoiODA5YzI1OGQ2OWJhNGM5NThmMWFmNWU3NWVhY2QwZjYiLCJwIjoiaiJ9))
Adds file attachment synchronization support to the LLM chat interface, enabling consistent file handling across multiple chat instances. When files are attached in one chat window, they are now properly synchronized across all active chat sessions.
**Changes:**
- Introduces `synchronizedAttachmentState` atom for managing shared file attachments
- Adds file attachment handling in `EndpointLLMChatCard`
- Implements `createDataTransferFiles` utility function for consistent file processing
- Updates attachment state management in `LLMChatCard`
**Checklist:**
- Test file attachments in synchronized …
=> feat(FR-255): synchronize the file input in the LLM Playground.

react/src/components/AgentList.tsx
resolves #3196 (FR-547)
Fixed memory utilization display in agent list by multiplying the ratio by 100 to show correct percentage values in the progress bar.
**Checklist:**
=> fix(FR-547): fix calculate logic for agent list memory usage progress percent

react/src/components/FolderCreateModal.tsx
resolves #3198 (FR-552)
User cannot reopen vfolder creation modal after closing in session launcher.  To fix added Suspense boundary with Skeleton loading state to the StorageSelect component in the folder creation modal. This also improves the user experience by showing a loading indicator while the storage selection component is being loaded.
=> fix(FR-552): can not reopen vfolder createion modal in session launcher

react/src/components/AutoScalingRuleEditorModal.tsx, react/src/pages/EndpointDetailPage.tsx
resolves #3204 (FR-561)
Added percentage symbol (%) display for kernel-based auto-scaling rule thresholds in both the rule editor modal and endpoint detail page. This provides clearer indication when threshold values represent percentages for kernel metrics.
In Form
In List
**Checklist:**
=> feat(FR-561): add percentage suffix for kernel metric threshold

react/src/pages/EndpointDetailPage.tsx, resources/i18n/en.json
resolves #1234 (FR-568)
Update "Cool Down Seconds" translation to "CoolDown Seconds" to align with standard industry terminology.
**Checklist:**
=> fix(FR-568): remove whitespace and update CoolDown text in autoscaling UI

resources/image_metadata.json
resolves #3213 (FR-569)
Added Rebellions NPU support by introducing two new image templates:
- `rbln-ubuntu`: Basic Ubuntu-based image for Rebellions NPU
- `rbln-triton`: Triton Inference Server image optimized for Rebellions NPU deployment
=> feature(FR-569): add Rebellions image metadata

react/src/components/AgentList.tsx, react/src/components/AgentSummaryList.tsx, react/src/components/BAICard.tsx, react/src/components/BAIRadioGroup.tsx, react/src/components/BAITable.tsx, react/src/components/BAITabs.tsx, react/src/components/ComputeSessionNodeItems/SessionStatusTag.tsx, react/src/components/EndpointList.tsx, react/src/components/SessionLauncherPreview.tsx, react/src/components/SessionOwnerSetterCard.tsx, react/src/components/SummaryPageItems/SummaryItemInvitation.tsx, react/src/components/UserCredentialList.tsx, react/src/components/UserNodeList.tsx, react/src/pages/ComputeSessionListPage.tsx, react/src/pages/EndpointDetailPage.tsx, react/src/pages/ImportAndRunPage.tsx, react/src/pages/ServingPage.tsx, react/src/pages/UserCredentialsPage.tsx
resolves #3182 (FR-534)
resolves #3182 (FR-534)
Introduces new UI components and enhances existing ones to improve visual consistency and user experience:
- Added BAIRadioGroup component with custom styling for radio buttons
- Added BAITabs component with customized tab styling and borders
- Enhanced BAICard with divider control and styling options
- Updated SessionStatusTag with improved tooltip and border radius
- Refactored EndpointList from a page to a reusable component
- Enhanced table headers with tooltips instead of multi-line text
- Applied consistent spacing and styling across components
- Updated serving page layout and padding
=> feat(FR-534): introduce NEO style Tabs and RadioGroup

react/src/components/EndpointList.tsx, react/src/pages/EndpointDetailPage.tsx
resolves #3183 (FR-535)
Refactors endpoint status checking by introducing a new function `isEndpointInDestroyingCategory` that accepts an endpoint object instead of individual parameters. This improves code readability and reduces repetitive parameter passing throughout the codebase.
The function consolidates the logic for determining if an endpoint is in a destroying state by checking both the replica count and status in a single location.
=> refactor(FR-535): Endpoint destroying category

react/src/components/MainLayout/WebUISider.tsx
Reorders the navigation menu items in the WebUI sidebar to place the Chat option before Import & Run, providing a more intuitive menu flow for users.
**Checklist:**
=> hotfix: Move Chat menu under Serving menu

index.html, react/src/components/DefaultProviders.tsx
resolves #3098 (FR-462)
related with https://github.com/lablup/backend.ai/pull/3585
refer https://lit.dev/docs/api/ReactiveElement/#ReactiveElement.styles
Added CSP nonce support to the AntD ConfigProvider to enable Content Security Policy compatibility in the React application. This allows the application to properly handle style injection when CSP is enabled. The webserver will replace the `'{{nonce}}'` string with proper nonce value.
**Checklist:**
=> feat(FR-462): Add CSP nonce string that will be injected by webserver.

e2e/agent.test.ts, e2e/config.test.ts, e2e/login.test.ts, e2e/test-util.ts, e2e/user.test.ts, e2e/vfolder.test.ts
resolves #3233 ([FR-582](https://lablup.atlassian.net/browse/FR-582))
Updates E2E tests to match recent UI changes:
- Replaces "E-mail" with "Email" in login and user forms
- Updates agent list test to use more reliable selectors
- Removes LLM playground test as the feature is now handled differently
- Updates session creation test to use new app dialog close button
- Modifies folder sharing tests to match updated email field labels
**Checklist:**
- Login with updated email field label
- Create and manage users with new form labels
- Share folders using updated email input
- Navigate agent list with new selectors
- Create session with new app dialog close flow
[FR-582]: https://lablup.atlassian.net/browse/FR-582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHVi …
=> fix(FR-582): Resolve E2E Test Failures Due to i18n and Component Updates

src/components/backend-ai-resource-panel.ts
resolves https://github.com/lablup/backend.ai-webui/issues/3220 (FR-578)
Fix the mismatch key in the CUDA FGPU progress bar.
**Checklist:**
=> fix(FR-578): fix resource panel i18n key error.

src/components/backend-ai-app-launcher.ts
resolves #3218 (FR-576).
simplify informing "Host info" by get rid of unnecessary hyperlinks which confuses users whether it tend to click or not.
| After | Before|
| ![Screenshot 2025-02-26 at 3.38.01 PM.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/Dgoz5XqHffJdivyccymr/db9dee27-7eec-46a0-8538-eb706d33b220.png) | ![Screenshot 2025-02-26 at 2.49.04 PM.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/Dgoz5XqHffJdivyccymr/bc637646-339a-4e92-9177-20715b66e213.png) |
How to test:
1. Create a session.
2. Click app dialog.
3. Click SSH / SFTP icon inside the app dialog.
4. See the changes.
- [] Test case(s) to demonstrate the difference of before/after
=> fix(FR-576): remove hyperlink in sftp/ftp link on app launcher dialog

react/src/App.tsx, react/src/components/EndpointList.tsx, react/src/hooks/reactPaginationQueryOptions.tsx, react/src/hooks/useDeferredQueryParams.tsx, react/src/pages/ComputeSessionListPage.tsx, react/src/pages/ServingPage.tsx
resolves #3250 (FR-593)
Refactors the Serving page and Endpoint list components to improve performance and maintainability:
- Extracts endpoint list into a reusable component with Relay fragment
- Adds loading states and suspense boundaries with skeleton placeholders
- Implements deferred query params to prevent UI jank during filtering/pagination
- Optimizes pagination state management with memoization
- Adds proper type safety for endpoint data structures
- Improves filter and lifecycle stage handling
- Implements proper loading states during data fetches
- Navigate to Serving page
- Test filtering, pagination, and lifecycle stage toggles
- Verify loading states and transitions
- Filter endpoints by name/url/owner
- Toggle between Active/Destroyed views
- Paginate …
=> refactor(FR-593): Endpoint list loading state management

react/src/hooks/reactPaginationQueryOptions.tsx, react/src/hooks/useDeferredQueryParams.tsx, react/src/pages/ComputeSessionListPage.tsx, react/src/pages/ServingPage.tsx
resolves #3210 (FR-567)
Adds URL search parameter persistence for pagination state in ComputeSession and Serving pages. When users navigate between different tabs or return to these pages, their pagination settings (page size and current page) are now preserved through the URL.
Key changes:
- Added `useBAIPaginationOptionStateOnSearchParam` to store pagination state in URL
- Fixed query parameter sharing in `useDeferredQueryParams` to properly merge states
- Updated ComputeSession page to maintain pagination state across tab switches
- Changed default lifecycle stage filter in Serving page from 'created&destroying' to 'active'
=> feat(FR-567): preserve pagination/filter/order data in session/endpoint page

src/components/backend-ai-session-list.ts
resolves FR-605
Removes inference metrics display (request count and last response time) from the session type column in the session list view. The session type badge remains unchanged.
=> feature(FR-604): remove deprecated inference request metrics

react/src/components/ActionItemContent.tsx, react/src/components/BAIBoard.tsx, react/src/components/MainLayout/WebUISider.tsx, react/src/components/ThemeAdminProvider.tsx, react/src/components/ThemeSecondaryProvider.tsx, react/src/hooks/useBAISetting.tsx, react/src/pages/StartPage.tsx, resources/theme.json, src/backend-ai-app.ts, src/components/backend-ai-webui.ts
**Changes:**
- Refactored the Start Page layout and components to improve maintainability and user experience
- Added theme providers (ThemeAdminProvider and ThemeSecondaryProvider) for consistent styling
- Updated BAIBoard component with proper TypeScript types and improved class handling
- Simplified ActionItemContent by removing unnecessary scroll detection
- Renamed settings key from `summary_items` to `start_board_items` for better clarity
- Added colorSuccess token to theme configuration
- Removed unused startFromExample component
**Rationale:**
The changes improve code organization and type safety while providing better theming support for different UI components. The Start Page layout has been simplified to focus on core functionality and maintain consistent styling across …
=> refactor(FR-587): Start page components

react/src/components/BAINotificationItem.tsx, react/src/components/FolderCreateModal.tsx, react/src/hooks/useBAINotification.tsx
Resolves #3269(FR-603)
Adds folder creation notification with navigation link
Enhances the folder creation notification system. When a folder is created, users now receive a notification with a direct link to navigate to the newly created folder. The notification includes a folder icon and displays success message with the folder name.
=> feat(FR-603): Add folder creation notification with an open button

react/src/components/BAIProgress.tsx, react/src/components/QuotaPerStorageVolumePanelCard.tsx, resources/theme.json
resolves #3151 (FR-513)
Adds a new quota per storage volume panel card to display project and user storage quotas. The panel shows usage percentages and storage limits for both project and user quotas when a storage volume is selected. The card includes:
- Progress bars showing usage percentages
- Storage usage in GB for both project and user quotas
- Support for volumes with quota capability
- Empty state for volumes without quota support
- Integration with existing storage volume selection
checkout #3232
**Checklist:**
=> feat(FR-513): NEO quota per storage volume card

react/src/components/BAIModal.css, react/src/components/BAIModal.tsx, react/src/components/BAISelect.tsx, react/src/components/LegacyFolderExplorer.tsx, react/src/hooks/index.tsx, src/components/backend-ai-folder-explorer.ts
resolves #3257 (FR-598)
add permission setting to folder explorer.
replace delete, create, upload buttons.
use fragment to VFolderNameTitle instead of query.
=> feat(FR-598): Add permission setting button to the folder explorer

react/src/components/MaintenanceSettingList.tsx, react/src/components/SettingList.tsx, react/src/pages/UserSettingsPage.tsx
Adds group headers to the SettingList component to improve item organization
The SettingList component now displays group titles with dividers above their respective setting items, making it easier to identify which group each setting belongs to. This improves visual organization and helps users better understand the structure of their settings.
Key changes:
- Added a GroupSettingItems component to handle the display of group titles and their items
- Introduced sticky headers with dividers to separate groups
- Updated the tab system to properly show group counts and filtered items
- Fixed type definitions for SettingGroup to better represent the data structure
=> refactor(FR-608): Settinglist component style

react/data/schema.graphql, react/src/App.tsx, react/src/components/SessionDetailContent.tsx, src/lib/backend.ai-client-esm.ts
resolves #3051 (FR-249)
>https://github.com/lablup/backend.ai/pull/2987 PR must be merged first.
This PR makes folder explorer available in the Session Detail Panel.
In versions after to Backend.AI Core 24.12.0, the vfolder_nodes field is provided.
**Feature:**
- allow to open folder explorer in session detail panel
- checkout Core branch to https://github.com/lablup/backend.ai/pull/2987
- open session detail panel. you can open session detail panel via using query string (?sessionDetail=<sessionID>)
- click the folder icon in session detail panel
- Verify that folder opener works for the vfolder you clicked on (name, contents, etc. match)
=> feat(FR-249): open folder explorer from session detail panel using vfolder_nodes

react/src/pages/SessionLauncherPage.tsx
resolves #3276 (FR-607)
Modifies the HPC optimization toggle behavior in the session launcher to:
- Clear optimization environment variables when auto-optimization is enabled
- Set default values (OMP_NUM_THREADS=1, OPENBLAS_NUM_THREADS=1) when auto-optimization is disabled
- Remove default environment variables from initial form state
=> fix(FR-607): hpc optimization option are 1 even auto switch is on

react/src/pages/StartPage.tsx
Resolves #3298 (FR-618)
The BAIBoard displayed a broken UI in the Electron environment. To fix this, the draggable BAIBoard component has been replaced with a fixed grid layout on the StartPage. The new layout uses Ant Design's Row and Col components to create a responsive grid system that adapts to different screen sizes:
- Small screens: 1 card per row
- Medium screens: 2 cards per row
- Large screens: 4 cards per row
Each action item is now displayed in a fixed-height Card component, maintaining consistent spacing and alignment across the page.
=> hotfix(FR-618): use Grid component instead of BAIBoard to fix broken layout in Electron

react/src/pages/ComputeSessionListPage.tsx, react/src/pages/VFolderNodeListPage.tsx
resolves #3299 (FR-619)
Sets default sorting order to '-created_at' for both compute sessions and VFolder node lists, ensuring consistent display of newest items first. Additionally improves loading state presentation in VFolder storage status cards by fixing style formatting.
=> hotfix(FR-619): set default order to '-created_at' for

src/components/lablup-activity-panel.ts
resolves #3310(FR-626)
**chagens**
* using `border-radius` instead of `overflow: hidden`
before
after
=> bugifx(FR-626): Card component's css bug

.github/workflows/package.yml, react/src/components/DomainSelector.test.tsx
resolves #3291 (FR-612)
Increases Node.js memory allocation limit to resolve heap out of memory errors during static resource bundling. Additionally removes unnecessary `act` wrapper in DomainSelector tests as the operations are already wrapped in async functions.
Fixes the following error during GitHub Actions build:
```
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
```
=> fix(FR-612): Increase max-old-space-size to 4096 of package.yml

config.toml.sample, react/src/components/SessionDetailContent.tsx, react/src/hooks/index.tsx, src/components/backend-ai-login.ts
resolves #3214 (FR-571)
Always show kernel list in session detail panel by removing the conditional flag `showKernelList`. This change ensures users can consistently view and manage kernels within their sessions without requiring additional configuration.
**Checklist:**
=> fix(FR-571): remove `showKernelList` configuration

react/src/components/ModelCardModal.tsx, react/src/components/ModelCloneModal.tsx
Resolve #3308 (FR-625)
Fixed model store clone functionality by updating the vfolder ID reference from `id` to `row_id` in the clone mutation. Removed deprecated vfolder info handling since it's no longer needed with the current API structure.
The changes ensure proper folder cloning when users select and clone items from the model store.
=> fix(FR-625): 404 error when using clone feature in model store

react/src/components/InviteFolderSettingModal.tsx, react/src/components/LegacyFolderExplorer.tsx, src/components/backend-ai-storage-list.ts
resolves #3330 (FR-620)
Adds a new event listener to refresh the folder list when folder permissions are modified in the legacy folder explorer. This ensures the storage list view stays synchronized with permission changes made through the UI.
**Checklist:**
=> fix(FR-620): folder permission refresh folder list after updating folder permission in FolderExplorer

react/src/components/VFolderLazyView.tsx, react/src/pages/EndpointDetailPage.tsx
**Changes:**
Adds null-safety checks for UUID handling in virtual folder components and endpoint model storage display. The endpoint model storage tab now only renders when an endpoint model exists, preventing potential rendering issues with undefined values.
- Connect to the bogbowl endpoint.
- Access the 19ce39ca-ada3-4f63-8b83-19fc2eb3d69a model service detail page and verify that the replaceAll error does not occur.
**Checklist:**
=> fix(FR-585): apply conditional rendering by using ternary operator on VFolderLazyView

react/data/schema.graphql, react/src/components/ResourcePresetSettingModal.tsx
resolves #3319 (FR-630)
Starting from this PR, resource preset updates will be made using the `id` instead of `name`, following the core `version 25.4.0`
**changes**
* there are two type of modify commit, `ResourcePresetSettingModalModifyByIdMutation` and `ResourcePresetSettingModalModifyByNameMutation`.
=> fix(FR-630): Support modifying resource preset using id

react/src/pages/StartPage.tsx
resolves #3333 (FR-653)
This pr comment out the StartFromURL card on the start page and then check if the layout is not broken afterward.
**changes**
* comment out the startFromURL card on the startpage
=> chore(FR-653): comment out StartFromURL card from startpage

resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/th.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json, src/components/backend-ai-app-launcher.ts
resolves https://github.com/lablup/backend.ai-webui/issues/3218 ([FR-576](https://lablup.atlassian.net/browse/FR-576))
This PR adds a new dialog for TCP-based applications that displays connection information (host and port) when a TCP connection is established. The dialog shows the application name, host, and port information to help users connect to TCP-based services.
The implementation includes:
- Added a new "TCPConnection" string to all language translation files
- Created a new TCP dialog component with connection information display
- Enhanced the app launcher to detect TCP connections and show the appropriate dialog
- Added logic to extract host and port information from redirect URLs
1. Log in in dogbowl
2. Create a session with …
=> feat(FR-576): Add TCP connection guidance dialog

react/src/components/ComputeSessionNodeItems/ConnectedKernelList.tsx
resolves #3337 (FR-656)
This PR modify the icon-related design on the session page.
**changes**
* modify the spacing between the copyable icon and the log icon.
before
after
* display '-' if container ID is not available.
before
after
=> chore(FR-656) Modify the icon-related design on the session page

react/src/components/ResourceAllocationFormItems.tsx, react/src/components/ResourcePresetSelect.tsx
resolves https://github.com/lablup/backend.ai-webui/issues/3376 ([FR-678](https://lablup.atlassian.net/browse/FR-678))
follows #3349 
This PR changes the `ResourcePresetSelect` component to accept a specific resource group name instead of a boolean flag. This allows for more precise control over which resource presets are displayed based on the provided resource group rather than relying on the current resource group from the global context.
Changes:
- Renamed prop `perResourceGroup` to `resourceGroup` in `ResourcePresetSelect`
- Updated the component to filter presets based on the explicitly provided resource group name
- Updated the usage in `ResourceAllocationFormItems` to pass the current resource group name
**Checklist:**
[FR-678]: …
=> feat(FR-678): Add resourceGroup Prop to Enhance ResourcePresetSelect Composability

react/src/components/SettingList.tsx
resolves #3378 (FR-679)
this PR adds optional `description` attribute to `SettingGroup` as `ReactNode`
**changes**
* add optional `description` attribute to `SettingGroup` component
It is supposed to display the description following the image.
=> feat(FR-679): Add optional description attribute to SettingGroup

react/src/hooks/useSuspendedFilteredAppTemplate.ts, src/components/backend-ai-app-launcher.ts
This PR changes the default category for custom applications from '0.Default' to '99.Custom' in the app launcher component. This change ensures that custom applications from Backend.AI agent are properly categorized and displayed at the end of the application list rather than at the beginning.
The PR also fixes the category name extraction logic by using a split method to properly extract the category name after the dot notation.
Before
After
**Checklist:**
=> feat(FR-663): Set default category if app is not included app template.

react/src/components/ResourcePresetList.tsx
resolves https://github.com/lablup/backend.ai-webui/issues/3395 (FR-695)
This PR updates the sorting functionality in the ResourcePresetList component:
1. Replaces the generic `sorter: true` with a proper locale-aware string comparison function for the "Name" column
2. Removes the unnecessary sorting capability from the "Shared Memory" column
These changes ensure that resource preset names are sorted correctly according to the user's locale.
**Checklist:**
=> fix(FR-695): match resource preset sorting

react/src/App.tsx, react/src/hooks/useBAISetting.tsx, react/src/pages/UserSettingsPage.tsx
resolves https://github.com/lablup/backend.ai-webui/issues/3148 ([FR-647](https://lablup.atlassian.net/browse/FR-647))
This PR removes the experimental flag for the Neo Data Page, making it the default view for all users. The changes include:
1. Removing the `experimental_neo_data_page` setting from the user settings interface
2. Updating the Data page route to always render the `VFolderNodeListPage` component
3. Removing the `experimental_neo_data_page` property from the UserSettings interface
**Checklist:**
[FR-647]: https://lablup.atlassian.net/browse/FR-647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FR-647): set NEO vfolder as a default.

react/src/components/FolderCreateModal.tsx, react/src/pages/VFolderNodeListPage.tsx
This PR adds a new `usageMode` prop to the `FolderCreateModal` component, allowing the caller to specify whether the folder being created is for general use or specifically for models. When the modal is opened from the VFolder list page with the `mode=model` query parameter, it will now automatically set the folder's usage mode to 'model'.
1. create a folder
2. select model tab 
3. check usage mode is model
**Checklist:**
=> feat(FR-563): Set model usage mode when selected tab is model.

react/src/pages/VFolderNodeListPage.tsx
resolves https://github.com/lablup/backend.ai-webui/issues/3364 (FR-670)
This PR modifies the VFolder node list filtering to exclude nodes with "DELETE_COMPLETE" status from the main list view, while also removing them from the deletion status filter. **This ensures that completely deleted folders are not displayed to users**, improving the clarity of the interface. For deleting folders from DB, admin should use control panel.
=> feat(FR-670): hide `DELETE_COMPLETE` folders

config.toml.sample, react/src/components/FolderCreateModal.tsx, react/src/hooks/index.tsx, react/src/pages/VFolderListPage.tsx, react/src/pages/VFolderNodeListPage.tsx, src/components/backend-ai-login.ts
resolves (FR-404)
related PR: https://github.com/lablup/backend.ai/pull/3503
Adds a configuration flag `enableModelFolders` to control the visibility of model folder features in the UI. When disabled, this removes the "Model" option from folder creation and hides the Models tab in the folder list view.
**Checklist:**
- Model radio option should be hidden in folder creation dialog when disabled
- Models tab should not appear in folder list when disabled
- Features should be visible when enabled (default true)
=> feat(FR-404): show or hide model folder related info

react/src/components/MainLayout/MainLayout.tsx, react/src/components/NoResourceGroupBanner.tsx, react/src/hooks/useCurrentProject.tsx, react/src/index.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/th.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json, src/components/backend-ai-resource-broker.ts
This PR introduces showing warning notification when current selected project doesn't contains resource group, such as `model-store`.
Backend.AI applied new type of project(group), so called "model-store", which doesn't contain any resource group, but to only contains and manages each model card(metadata of model itself). The problem is that, When a user with superadmin role, who has an access to see those project(group) in WebUI, changes the current project to `model-store`, things gets in trouble, since our logic is based on one rule, "Every project(group) has resource group, and resource group mostly has certain amount of resource(if not then it will display zero)."
To avoid those confusions, we decided to show warning notification on every pages "No resource group assigned in this …
=> add(FR-638): NoResourceGroupBanner to show warning when no resource group is assigned

react/src/components/Chat/ChatCard.tsx, react/src/components/Chat/ChatMessage.tsx
resolves #3398 (FR-690)
This PR improves the performance of the Chat UI by:
1. Replacing `useThrottle` with React's native `useDeferredValue` in ChatMessage component for better rendering performance of message content and reasoning
2. Adding experimental throttling (100ms) to the chat fetch request to reduce unnecessary network calls during rapid state changes
To reproduce browser freezing:
1. create two chat windows on the Chat page, set "Sync" input  in both chat
2.  Send a question that will generate a lot of markdown (e.g. "Let me know the JavaScript sort function"). 
3. While waiting for a response, quickly type in the chat message input.
=> fix(FR-690): browser freezing during user inputs chat message

pnpm-lock.yaml, react/package.json, react/src/components/Chat/ChatMessage.tsx, react/src/components/VFolderNodeIdenticon.tsx, react/src/components/VFolderNodes.tsx, react/src/pages/VFolderNodeListPage.tsx
This PR adds avatar icons to folders in the VFolderNodes component by integrating the DiceBear avatar generation library. Each folder now displays a unique avatar based on its ID and name, enhancing visual identification of folders in the UI.
The implementation:
- Adds `@dicebear/core` and `@dicebear/collection` packages to dependencies
- Uses the "shapes" avatar style from DiceBear to generate consistent, unique avatars
- Displays avatars alongside folder names in a flex container with proper spacing
**Checklist:**
=> feat(FR-595): add identicon to name

react/src/App.tsx, react/src/components/AnnouncementAlert.tsx, react/src/pages/StartPage.tsx
Resolves #3411 (FR-716)
This PR moves the `AnnouncementAlert` component from the Summary page to the Start page. The changes:
1. Remove the `AnnouncementAlert` component from the Summary page route in `App.tsx`
2. Add the `AnnouncementAlert` component to the Start page
3. Wrap the Start page content in a `Flex` component with column direction to properly display the alert
=> feat: move the announcement component to the start page

react/src/components/MainLayout/MainLayout.tsx, react/src/components/MainLayout/WebUISider.tsx, src/components/backend-ai-page.ts, src/components/backend-ai-webui.ts
Resolves #3418 (FR-726)
This PR resolve the bug related plugin's menu item. When users click the plugin menu item, it should be move to the plugin page.
Additionally, this PR enhances the plugin page system by adding two new optional properties:
1. `icon`: Allows specifying custom icons for plugin menu items
2. `group`: Enables grouping of plugin menu items
The changes include:
- Adding the new properties to the `PluginPage` type definition
- Updating the `MenuItem` type to support the new properties
- Implementing an icon mapping system with support for `link` and `externalLink` icons
- Adding the properties to the `BackendAIPage` component
- Ensuring the properties are passed through from plugin pages to the menu system
These additions provide more flexibility for plugin developers to …
=> hotfix(FR-726): plugin menu item doesn't work

react/src/components/AgentList.tsx, react/src/components/AgentSummaryList.tsx, react/src/components/ComputeSessionNodeItems/ConnectedKernelList.tsx, react/src/components/InviteFolderSettingModal.tsx, react/src/components/MyKeypairInfoModal.tsx, react/src/components/VFolderNodes.tsx, src/components/backend-ai-folder-explorer.ts, src/components/backend-ai-registry-list.ts, src/components/backend-ai-resource-group-list.ts, src/components/backend-ai-session-list.ts, src/components/backend-ai-storage-list.ts, src/components/backend-ai-storage-proxy-list.ts
resolves #3330 (FR-616)
this PR removed unnecessary # column from table
**changes**
* remove from `/data`, `/agent`, `/job`, `/agent-summary`, `/sessionDetail`, `myKeyPairInfoModal`, `InvteFolderSettingModal`, `vfolder-explorer` and experimental `/data`
* delete unused functions and variables
* The `backend-ai-resource-preset-list` and `backend-ai-scaling-group-list` files also use the # column, but these components are no longer in use. Therefore, these files are being deleted in a different PR #3352, so I will exclude them from this PR.
=> chore(FR-616): Remove unnecessary # column from table and unused codes

react/src/pages/VFolderNodeListPage.tsx
Resolves #3404 (FR-706)
This PR enhances the user experience in the VFolderNodeListPage by preserving the pagination state when switching between the "created" and "deleted" folder tabs. Previously, the pagination would reset to page 1 when switching tabs, causing users to lose their position in the list. Additionally, the pagination state is now maintained even after refreshing the browser.
Now, the pagination state is stored separately for each tab and restored when switching back to a previously visited tab.
**Changes:**
- Switched from `useBAIPaginationOptionState` to `useBAIPaginationOptionStateOnSearchParam` to better handle pagination state
- Modified the `queryMapRef` to store both query parameters and pagination state for each tab
- Updated the tab switching logic to restore the …
=> feat(FR-706): preserving pagination and filter state of VFolder list

react/src/App.tsx, react/src/components/AvailableResourcesCard.tsx, react/src/components/MainLayout/WebUISider.tsx, react/src/components/MySessionCard.tsx, react/src/components/RecentlyCreatedSessionCard.tsx, react/src/pages/DashboardPage.tsx, src/components/backend-ai-webui.ts
resolves [FR-326](https://lablup.atlassian.net/browse/FR-326)
This PR adds a new Dashboard page to replace the Summary page in the WebUI. The changes include:
- Created a new `DashboardPage` component with cards for:
- My Sessions
- Available Resources
- Recently Created Sessions
- Added the Dashboard page to the router configuration
- Updated the sidebar navigation to link to the Dashboard instead of Summary
- Commented out the Summary page code for potential future removal
**Checklist:**
[FR-326]: https://lablup.atlassian.net/browse/FR-326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FR-326): dashboard layout

react/src/components/AvailableResourcesCard.tsx, react/src/components/BAIFetchKeyButton.tsx, react/src/components/MySessionCard.tsx, react/src/components/QuotaPerStorageVolumePanelCard.tsx, react/src/components/RecentlyCreatedSessionCard.tsx, react/src/components/ResourceGroupSelectForCurrentProject.tsx, react/src/components/SessionNodes.tsx, react/src/components/StorageSelect.tsx, react/src/hooks/useResourceLimitAndRemaining.tsx, react/src/pages/DashboardPage.tsx
Resolves #3426 (FR-732)
This PR enhances the dashboard components with a unified refresh mechanism and improves UI consistency:
- Implements a centralized refresh approach for dashboard cards using a shared fetch key
- Refactors `BAIFetchKeyButton` to properly extend button props
- Improves resource group and storage selection UI with borderless variants
- Standardizes refresh button behavior across all dashboard cards
- Adds automatic 15-second refresh interval for dashboard components
- Renames `isSorterDisabled` prop to more intuitive `disableSorter` in SessionNodes
- Fixes resource limit and remaining hook to properly handle fetch key changes
=> feat(FR-732): Unified dashboard refetch mechanism and UI improvements

e2e/config.test.ts, e2e/login.test.ts
Resolves #3444 (FR-752)
This PR updates E2E tests to reflect recent UI changes:
1. Improves the test description for `showNonInstalledImages` to better describe its functionality
2. Updates element selectors to be more precise:
- Uses `exact: true` for the Environments text selector
- Replaces the icon selector with a more reliable button selector for "Start Session"
3. Updates login test to reflect that users are now redirected to the `/start` page instead of `/summary` after login
**Checklist:**
=> fix(FR-752): e2e for showNonInstalledImages and login

react/src/components/ComputeSessionNodeItems/SessionSlotCell.tsx, react/src/hooks/backendai.tsx
Resolves #3437 (FR-750)
This PR improves the display of resource slots in the SessionSlotCell component:
1. Replaces `deviceMetadata` with `mergedResourceSlots` from the `useResourceSlotsDetails` hook
2. Enhances memory display with fixed decimal precision (3 digits)
3. Filters out accelerators with zero or invalid values
4. Uses `display_unit` from resource slots data instead of `human_readable_name`
5. Modifies the `useResourceSlotsDetails` hook to:
- Accept empty resource group name to fetch all resource slots
- Handle URL parameter construction more robustly
- Return an empty object instead of undefined when manager version is incompatible
Before 1: New accelerator type and 0 accelerator type
After 1: New accelerator type and 0 accelerator type
Before 2: 
After 2:
=> fix(FR-750): improve resource slot display in SessionSlotCell component

react/src/components/ComputeSessionNodeItems/SessionActionButtons.tsx
This PR resolves #3433 (FR-733)
This PR modifies the session termination button to be enabled for all active sessions, not just those in the "RUNNING" state. This change allows users to terminate sessions that are in other active states, such as "PREPARING" or "RESTARTING".
1. Login with user/admin.
2. Go to session page.
3. Create a session with random name.
4. Click the session name
5. Detail page showed up.
6. Change the status of the session just created in step 3.
> NOTE: For now, testing in Core server in local, scheduler changes the status of session too fast, therefore It status should be changed manually using manager.
```
$ ./backend.ai mgr dbshell 
$ UPDATE sessions SET status='CREATING' WHERE name='<created-session-name>'
```
7. Check status whether terminate session button is …
=> fix(FR-733): use isActive function for session termination button disable condition

e2e/test-util.ts, react/src/components/BAIPropertyFilter.tsx, react/src/components/FolderCreateModal.tsx, react/src/pages/VFolderNodeListPage.tsx
resolves https://github.com/lablup/backend.ai-webui/issues/3450 (FR-759)
>[!NOTE]
> This PR only handles creation.
This PR updates the folder creation test in `e2e/test-util.ts` to work with the new UI components. The changes include:
1. Removing the 'wd' (Delete) permission option as it's no longer supported
2. Updating the folder creation workflow to use the "Create Folder" button
3. Adding data-testid attributes to radio buttons in FolderCreateModal for better test targeting
4. Updating the folder verification process to work with the new UI components
**Checklist:**
=> e2e(FR-759): fix create test code

e2e/test-util.ts, e2e/vfolder.test.ts
resolves https://github.com/lablup/backend.ai-webui/issues/3450 (FR-759)
This PR adds a new utility function `restoreVFolderAndVerify` to support restoring virtual folders from the trash. It also adds a comprehensive test case that verifies the complete lifecycle of a virtual folder: creation, moving to trash, restoration, and permanent deletion.
The new test ensures users can successfully restore folders from the trash before permanently deleting them, providing better test coverage for the virtual folder management workflow.
**Checklist:**
=> e2e(FR-759): add vfolder restore test code

e2e/test-util.ts, e2e/vfolder.test.ts
resolves https://github.com/lablup/backend.ai-webui/issues/3450 (FR-759)
This PR refactors the vfolder sharing tests to improve readability and maintainability. It adds two new utility functions:
1. `shareVFolderAndVerify` - Handles the process of sharing a folder with another user
2. `acceptAllInvitationAndVerifySpecificFolder` - Accepts all pending invitations and verifies a specific folder is accessible
The PR simplifies the existing vfolder sharing tests by replacing repetitive code with these utility functions, making the tests more concise and focused on the actual test scenarios rather than implementation details.
=> e2e(FR-759): fix test code for vFolder invitation test cases

react/src/components/FolderLink.tsx, react/src/components/SessionDetailContent.tsx
resolves #3406 (FR-703)
this PR resolves layout bug in mounted folder section on session detail modal
**changes**
* add `FolderLink` component using `BAILink`
* remove `flex` style from session status item
|before|after|
|-------|-----|
| ![스크린샷 2025-03-25 오후 4.22.14.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/xbCemO1RqqcSjEXCRK3p/909fc9d6-6f03-4d3d-a80f-c59ce1a4602a.png) |![스크린샷 2025-03-27 오후 1.27.19.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/xbCemO1RqqcSjEXCRK3p/88ff37e2-5699-4e93-ae23-3b853bb812b3.png) |
=> fix(FR-703): Add word-break to mounted folders on session detail modal

react/src/components/SessionOwnerSetterCard.tsx, react/src/components/VFolderTable.tsx, react/src/components/VFolderTableFormItem.tsx, react/src/pages/SessionLauncherPage.tsx
resolves #3017 (FR-242)
> The ability to create a session by setting a Session Owner is not currently available. https://lablup.atlassian.net/browse/BA-414
> In this PR, I'm aiming to show the right vfolder list for the set session owner.
In the `VFolderTable` used by the session launcher, we are fetching the vfolder list via the REST API. Since the API provides the ability to filter the data based on owner email, use it to show the vfolder list based on the delegated owner email assigned by the session launcher.
**feature:**
- If owner is set in the session launcher, it will show a list of vfolders for that user.
- If a previously selected vfolder exists, all selections will be reset when the owner related settings are changed.
=> fix(FR-242): show vfolder list based on delegated user

react/src/components/FolderCreateModal.tsx
resolves #3475 (FR-801)
Reset button can hide cloneable toggle button
**changes**
* Change `setFieldsValue` to `resetFields` in the reset button
=> fix(FR-801): update reset button to hide cloneable toggle

react/src/components/Chat/ChatInput.tsx
resolves #3419 (FR-727)
This PR resolves dark mode bug in the `ChatSender` component.
**changes**
* remove the `background` style to enable dark mode
* remove unnecessary `border-radius` style
|before|after|
|------|-----|
| ![Microsoft Teams 2025-03-27 23.33.42.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/xbCemO1RqqcSjEXCRK3p/d506a714-3d49-4b49-991a-95b737a8edcb.png)| ![CleanShot 2025-03-28 at 00.46.08@2x.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/xbCemO1RqqcSjEXCRK3p/a052b02a-fa2a-46ba-907c-186b2be920dc.png) |
=> fix(FR-727): Modify ChatSender's style to follow Antd's design system

react/src/components/AgentSelect.tsx
Resolves #3454 (FR-764)
This PR enhances the AgentSelect component by adding search functionality that allows users to filter agents by ID. The implementation:
- Adds a search box to the agent selection dropdown
- Implements search filtering using the `ilike` operator to match agent IDs
- Uses React's `useTransition` hook to handle search state updates without blocking the UI
- Increases the default page size from 20 to 50 agents
- Disables the default filtering option in favor of the custom search implementation
=> fix(FR-764): increase agent select page size and add search functionality

react/src/components/VFolderNodes.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/th.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json
Resolves #3476 ([FR-802](https://lablup.atlassian.net/browse/FR-802))
This PR prevents users from moving project folders to trash by disabling the "Move to Trash" button for group-owned folders when the current user has a 'user' role. The button is visually disabled and shows a tooltip explaining that users cannot delete project folders.
- project folder with 'user' role
- general folder
**Checklist:**
[FR-802]: https://lablup.atlassian.net/browse/FR-802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> hotfix(FR-802): Disable Delete Button for Users with 'User' Role

react/src/App.tsx, react/src/pages/StartPage.tsx, resources/theme.json
Resolves #3482 (FR-816)
This PR adds support for the XXL breakpoint in the responsive design system. It includes:
1. Added `screenXLMax`, `screenXXLMin`, and `screenXXL` values to both light and dark themes in `theme.json`
2. Added `xxl={4}` column sizing to the card layout in StartPage, allowing for better use of screen space on larger displays
3. Removed the `AnnouncementAlert` component from the summary page
These changes improve the UI layout on larger screens by allowing more cards to be displayed in a row when sufficient screen space is available.
=> style(FR-816): Improve Start page grid size for XXL screen

react/data/schema.graphql, react/src/components/DynamicUnitInputNumberWithSlider.tsx, react/src/components/ResourceAllocationFormItems.tsx, react/src/hooks/useResourceLimitAndRemaining.tsx
Resolves #3463 (FR-777)
To conduct the test, you must use the environment at https://github.com/lablup/backend.ai/pull/4108. There is a test server for this PR, and related details can be found at the following [link](https://teams.microsoft.com/l/message/19:acd1be4236b94664b814f4d4e5c84da6@thread.skype/1744025901127?tenantId=13c6a44d-9b52-4b9e-aa34-0513ee7131f2&groupId=74ae2c4d-ec4d-4fdf-b2c2-f5041d1e8631&parentMessageId=1744011801142&teamName=devops&channelName=JIRA%20Issue%20Notification&createdTime=1744025901127).
This PR adds several new GraphQL types and queries:
1. (Key change) **Enhanced resource limit calculation to consider scaling group resource limits**
2. Update schema for `resource_slot_limit` field to the ScalingGroup type to expose resource limits
3. Fixed number …
=> feat(FR-777): use resource limit of resource group

react/data/schema.graphql, react/src/hooks/useResourceLimitAndRemaining.tsx
This PR renames the GraphQL field `resource_slot_limit` to `resource_allocation_limit_for_sessions` in the ScalingGroup type to better reflect its purpose.
=> fix(FR-777): Update  `resource_slot_limit` to `resource_allocation_limit_for_sessions`

react/src/components/ErrorLogList.tsx
Resolves #3486 ([FR-823](https://lablup.atlassian.net/browse/FR-823))
This PR modifies the `ErrorLogList` component to conditionally set the vertical scroll height. When there are no error logs to display (filtered log data with `isError` is empty), the vertical scroll height is set to `undefined` instead of a fixed calculation. This prevents unnecessary scrollbars from appearing when there's no error data to scroll through.
**Checklist:**
[FR-823]: https://lablup.atlassian.net/browse/FR-823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(FR-823): log message scroll bar is too wide when logs are empty.

react/src/components/SessionDetailContent.tsx
Resolves #3493 (FR-821)
This PR modifies the display of agent IDs in the session detail view. Instead of showing potentially duplicate agent IDs, it now displays a unique, comma-separated list of agent IDs by using Lodash's `uniq` function and joining the results.
dogbowl `/session?order=-created_at&type=all&statusCategory=finished&current=1&sessionDetail=6ff414fb-1a2a-4c25-ae09-654a516bda16`
[FR-821]: https://lablup.atlassian.net/browse/FR-821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(FR-821): display unique agent IDs with comma separation

react/src/components/ResourcePresetList.tsx, react/src/components/ResourcePresetSettingModal.tsx
Resolves #3485 ([FR-819](https://lablup.atlassian.net/browse/FR-819))
This PR adds the `stringMode` prop to the InputNumber component in the ResourcePresetSettingModal. This change ensures that decimal values are properly handled when users input resource allocation values, particularly for fields with fractional values.
**Changes:**
- Added `stringMode={true}` to the InputNumber component to preserve decimal precision in resource preset settings
**Checklist:**
[FR-819]: https://lablup.atlassian.net/browse/FR-819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(FR-819): Fix share unit of resource preset.

react/src/components/MainLayout/MainLayout.tsx, react/src/components/MainLayout/WebUISider.tsx
resolves https://github.com/lablup/backend.ai-webui/issues/3340, https://github.com/lablup/backend.ai-webui/issues/3496 ([FR-820](https://lablup.atlassian.net/browse/FR-820))
This PR removes the redundant `onCollapse` handler from the MainLayout component. The handler was setting the `sideCollapsed` state, which is already being handled by the existing `onBreakpoint` function.
- wide screen
- middle screen
- narrow screen
**Checklist:**
[FR-820]: https://lablup.atlassian.net/browse/FR-820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(FR-820): compact sidebar doesn't work when refreshing.

react/src/pages/VFolderNodeListPage.tsx
Resolves #3507 ([FR-842](https://lablup.atlassian.net/browse/FR-842))
This PR passes the props to the root Flex component in VFolderNodeListPage and adds the fetchKey prop to the StorageStatusPanelCard component to ensure proper data fetching and refresh behavior.
**Checklist:**
[FR-842]: https://lablup.atlassian.net/browse/FR-842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(FR-842): storage status mismatch with virtual nodes total count.

react/src/components/VFolderNodes.tsx
Resolves #3508 ([FR-843](https://lablup.atlassian.net/browse/FR-843))
This PR modifies the owner check in the VFolderNodes component to only display the owner checkmark for group-owned folders when the user has an admin role. Previously, the checkmark would appear for any user if the folder belonged to the current project group.
**Checklist:**
[FR-843]: https://lablup.atlassian.net/browse/FR-843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(FR-843): Users with a user role are incorrectly identified as the owner of the project folder.

resources/i18n/ko.json
Resolves #3518 ([FR-850](https://lablup.atlassian.net/browse/FR-850))
Fixed a typo in the Korean translation by removing an invisible control character (backspace) in the "CreateFolderAndUploadFiles" string.
**Checklist:**
[FR-850]: https://lablup.atlassian.net/browse/FR-850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(FR-850): typo error - folder creation and file upload

react/src/components/SessionMetricGraph.tsx, react/src/pages/StatisticsPage.tsx
=> feat(FR-833): Improve metric label formatting in user session history page

react/src/components/EditableVFolderName.tsx, react/src/components/VFolderNodes.tsx
Resolves #3504 ([FR-839](https://lablup.atlassian.net/browse/FR-839))
This PR adds a permission check to prevent users from editing virtual folder names when they don't have the 'update_attribute' permission. It also ensures the edit mode is properly exited when an error occurs during editing.
Changes:
- Added permissions to the GraphQL query in VFolderNodes
- Added a permission check to only allow editing folder names when the user has 'update_attribute' permission
- Fixed a bug where the edit mode wasn't properly exited when an error occurred during name editing
[FR-839]: https://lablup.atlassian.net/browse/FR-839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(FR-839):Handle rename functionality when update_attribute is absent

react/src/components/LegacyFolderExplorer.tsx
resolves #3531 (FR-861)
**changes**
* modified to call the _fetchVFolder function of backend-ai-folder-explorer to update the changes when the mount permission change is successful.
=> fix(FR-861): fix bug where changing mount permission would not sync with Lit component

src/components/backend-ai-folder-explorer.ts
resolves #NNN (FR-558)
In this PR, make the file sizes that appear in folder explorer human-readable.
**changes** 
* make the file sizes that appear in folder explorer human-readable in the `backend-ai-folder-exporer`
=> feat(FR-558): display human readable file size on folder explorer

react/src/components/VFolderTable.tsx
resolves #3537 (FR-869)
**changes**
* fix showing the type of a folder in the session launcher to look the same as it does on the data page
* I'm not getting a value for `group_name`, so I've removed the part that shows it. Please let me know if you need this in your review.
|before|after|
|-----|------|
|![12eb0504-2009-4ba3-ba91-6cf06a9e364c.jpg](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/xbCemO1RqqcSjEXCRK3p/90cf0e22-239d-48c2-a61e-ab2b0b49addc.jpg) | ![CleanShot 2025-04-19 at 21.12.18@2x.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/xbCemO1RqqcSjEXCRK3p/93f5bf78-ea26-4b21-a2a6-8f7099bbfd5c.png)|
=> fix(FR-869): fix session launcher to display appropriate type for folders

react/src/components/AliasedImageDoubleTags.tsx, react/src/components/ImageEnvironmentSelectFormItems.tsx, react/src/components/ImageList.tsx, react/src/components/ImageTags.tsx, react/src/components/SessionLauncherPreview.tsx
Resolves #3543 ([FR-871](https://lablup.atlassian.net/browse/FR-871))
This PR modifies the tag display logic across multiple components to ensure customized tags are properly displayed. The key changes include:
1. Added a condition to show tags when `isCustomized` is true, regardless of the alias equality check
2. Updated `ImageTags` component to properly pass props to the React.Fragment
These changes ensure that customized tags are consistently displayed in the UI, fixing an issue where they might be filtered out incorrectly.
- My Environment
- Session launcher
- Images
**Checklist:**
[FR-871]: https://lablup.atlassian.net/browse/FR-871?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FR-871): improve visibility of committed container names

react/src/components/FolderExplorer.tsx
Follow-up to #1896 and resolves #3541 (FR-870)
This pull request suggests to use raw number comparison instead of `date` comparison for file size in folder explorer.
=> fix(FR-870): invalid sorter for file size in folder explorer

react/src/components/LegacyFolderExplorer.tsx, react/src/components/ModelCloneModal.tsx, src/lib/backend.ai-client-esm.ts
Resolves #3534 ([FR-867](https://lablup.atlassian.net/browse/FR-867))
This PR removes the 'wd' (write-delete) permission option from folder permissions throughout the application:
1. Updates `LegacyFolderExplorer.tsx` to handle 'wd' permission by converting it to 'rw' in the UI
2. Removes the 'Delete' permission option from the ModelCloneModal dropdown
3. Updates documentation in backend.ai-client-esm.ts to reflect that only 'ro' and 'rw' permissions are valid options
1. update folder permission to 'wd' in DB.
```
update vfolders set permission='wd' where name='<vfolder name>';
```
2. check vfolder explorer
**Checklist:**
[FR-867]: https://lablup.atlassian.net/browse/FR-867?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(FR-867): incorrect permission value display for 'wd' permission

src/components/backend-ai-folder-explorer.ts
resolves #NNN (FR-559)
**Changes**
* Change to show localized create date using `toLocaleString('en-US'`)
=> feat(FR-559): display localized create date on the folder explorer

react/src/pages/StartPage.tsx
Resolves #3561 ([FR-887](https://lablup.atlassian.net/browse/FR-887))
This PR modifies the StartPage component to conditionally render the model service section based on the `enableModelFolders` configuration flag from the BAI client. When this flag is disabled, the model service section will not be displayed in the UI.
**Checklist:**
[FR-887]: https://lablup.atlassian.net/browse/FR-887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FR-887): hide model service card on start page if enableModelFolders is false

react/src/components/AgentSummaryList.tsx
Resolves #3564 ([FR-889](https://lablup.atlassian.net/browse/FR-889))
Added Resource Group column to the Agent Summary List table. The new column displays the scaling group information for each agent, and supports sorting functionality.
[FR-889]: https://lablup.atlassian.net/browse/FR-889?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FR-889): Add resource group column to agent summary

react/src/components/Chat/AIAgentSelect.tsx, react/src/components/Chat/ChatCard.tsx, react/src/components/Chat/ChatHeader.tsx, react/src/components/Chat/ChatModel.tsx, react/src/components/Chat/Conversation.tsx, react/src/components/Chat/EndpointSelect.tsx, react/src/pages/ChatPage.tsx
Resolves #3574 (FR-896)
- Refactored `AIAgentSelect` to use the `useAIAgent` hook directly instead of requiring agents to be passed as props
- Simplified `ChatCard` component by removing redundant state management and using controlled components
- Added `onUpdateChat` callback to `ChatCard` to propagate changes to parent components
- Improved `ChatHeader` component by making it more declarative with explicit callbacks
- Enhanced `Conversation` component to properly update chat state using the new callback pattern
-Fetch default endpoint selection in `ChatPage` to improve initial user experience
- Removed unnecessary state variables and transitions for better performance
- Fixed prop types and interfaces across components for better type safety
=> refactor(FR-896): chat card state managment and naming convention

react/src/components/ContainerRegistryList.tsx
resolves #3577 (FR-901)
**changes**
* change `message.info` to `message.success`.
=> chore(FR-901): change info icon to success icon on the message

react/src/components/ResourcePresetList.tsx
resolves #3575 (FR-899)
**changes**
* add `message.success` when deleting is completed.
=> fix(FR-899): fix to display success message when deleting a resource preset

react/src/components/BAITable.tsx, react/src/components/EndpointList.tsx, react/src/components/ImageList.tsx, react/src/components/InviteFolderSettingModal.tsx, react/src/components/ResourcePresetList.tsx, react/src/components/SessionNodes.tsx, react/src/components/UserNodeList.tsx, react/src/components/VFolderNodes.tsx, react/src/components/VFolderTable.tsx, react/src/pages/ComputeSessionListPage.tsx, react/src/pages/EndpointDetailPage.tsx, react/src/pages/ServingPage.tsx, react/src/pages/VFolderNodeListPage.tsx
Resolves #3587 (FR-883)
This PR fixes inconsistent sorting behavior in table components that caused NEO session and NEO folder lists to appear differently when first loaded compared to when navigating between pages.
The key changes include:
- Added `orderString` prop to `BAITable` component to control sort direction based on URL parameters
- Modified table components to use this prop for consistent sorting
- Removed hardcoded `sortDirections` and `defaultSortOrder` properties that were causing inconsistencies
- Updated `ComputeSessionListPage`, `ServingPage`, and `VFolderNodeListPage` to properly handle default sorting
- Ensured sort indicators are correctly displayed based on the current sort order
These changes ensure that tables maintain consistent sorting behavior throughout the …
=> fix(FR-883): Implement consistent sorting behavior across table components

react/src/components/AutoScalingRuleEditorModal.tsx, react/src/components/ContainerRegistryEditorModal.tsx, react/src/components/ContainerRegistryEditorModalBefore2409.tsx, react/src/components/ContainerRegistryList.tsx, react/src/components/ContainerRegistryListBefore2409.tsx, react/src/components/CustomizedImageList.tsx, react/src/components/KeypairResourcePolicyList.tsx, react/src/components/KeypairResourcePolicySettingModal.tsx, react/src/components/ManageAppsModal.tsx, react/src/components/ManageImageResourceLimitModal.tsx, react/src/components/ProjectResourcePolicyList.tsx, react/src/components/ResourcePresetSettingModal.tsx, react/src/components/ServiceLauncherPageContent.tsx, react/src/components/UserResourcePolicyList.tsx, react/src/components/UserSettingModal.tsx, react/src/pages/EndpointDetailPage.tsx
resolves #3520 (FR-851)
Remove the duration value set to custom for `message` in that PR to use the value set to global. And when I modified the `duration` option of the message in the `DefaultProvider`, I made sure that the value was reflected.
=> refactor(FR-851): remove custom duration for message

src/components/backend-ai-import-view.ts
resolves #3572 (FR-895)
In that PR, change the `resource statistics panel` on the `Import & Run` page to be scrollable.
=> fix(FR-895): change resource statistics panel on the Import & Run page to be scrollable

react/src/components/ServiceLauncherPageContent.tsx, react/src/components/VFolderSelect.tsx
resolves #3207 ([FR-564](https://lablup.atlassian.net/jira/software/projects/FR/boards/21?assignee=712020:52c9a410-dfd2-4acd-97a6-8c6112ec8a34&selectedIssue=FR-564))
This PR enhances the `VFolderSelect` component by adding two new features:
1. Folder exploration - allows users to navigate to the selected folder
2. Folder creation - enables users to create new folders directly from the select component
The component now accepts two new props:
- `allowFolderExplorer`: Enables folder navigation links
- `allowCreateFolder`: Adds a button to create new folders
These features are implemented in the Service Launcher page to improve the user experience when working with folders.
- Go to serving page
- Create a new service and check the `model storage to mount' field to create a …
=> feat(FR-564): Allow create folder and explorer for vfolder select

react/src/components/ImageInstallModal.tsx
fix separator between image name & tag
On the environment page, fix seperator between image name & tag. originally use `:` seperator between image name and tag
incorrect: `correct: cr.backend.ai/stable/r-base/3.6`
correct: `cr.backend.ai/stable/r-base:3.6`
resolves #3610 
resolves #NNN (FR-MMM)
=> Fix: change separator between image name & tag

react/src/components/ComputeSessionNodeItems/TerminateSessionModal.tsx
resolves #3596 (FR-921)
This PR updates the `TerminateSessionModal` component to use the session's access key directly from the session object instead of using the global access key from the BAI client configuration. This change ensures that the correct access key is used when terminating a session, particularly in cases where the session might have been created with a different access key than the one currently configured.
**Checklist:**
=> fix(FR-921): Fix incorrect access key when terminating another user's session

react/src/pages/ComputeSessionListPage.tsx
Resolves #3603 (FR-941)
The allocated resources card falls back to a skeleton every time it auto refetches, which decreases usability. This PR changes it so that only the refresh button shows a loading state during auto refetching.
=> fix(FR-941): prevent suspense fallback when Allocated resource card is auto-refreshing

react/src/components/ResourceAllocationFormItems.tsx
Resolves #3595 (FR-920)
This PR modifies the behavior of resource allocation preset selection in the ResourceAllocationFormItems component:
1. When a preset becomes unavailable in the current resource group:
- If custom resource allocation is allowed, it now defaults to 'minimum-required' instead of 'custom'
- If custom resource allocation is not allowed, it sets the value to null
2. Added dependency on `baiClient._config.allowCustomResourceAllocation` to the useEffect to ensure proper re-rendering when this configuration changes
3. Changed the form validation to make it work in preview step:
- Removed the `required` prop from Form.Item
- Added explicit validation rules to maintain the required behavior
=> feat(FR-920): set `minimum-required` resources when no available preset

react/src/components/VFolderNodes.tsx, react/src/pages/VFolderNodeListPage.tsx
https://lablup.atlassian.net/browse/FR-915
Resolves #3588 (FR-915)
This PR enhances the folder selection behavior when restoring or deleting folders. When a folder is moved to trash or restored, the updated folder ID is now passed to the `onRequestChange` callback, allowing the parent component to update its selected folder list accordingly. This can resolve the selectedFolder mismatch when deleting or restoring single folder after multi-check.
The main changes:
- Updated the `onRequestChange` callback signature to accept an optional folder ID parameter
- Modified the restore and delete mutation success handlers to pass the folder ID to the callback
- Added logic in `VFolderNodeListPage` to remove the updated folder from the selected folder list
This prevents issues where deleted/restored …
=> fix(FR-915): fix error when deleting or restoring single folder after multi-check

react/src/components/MySessionCard.tsx, react/src/components/RecentlyCreatedSessionCard.tsx, react/src/pages/DashboardPage.tsx
https://lablup.atlassian.net/browse/FR-978
Resolves #3643 (FR-978)
Updated the `projectId` parameter in the `DashboardPageQuery` GraphQL query to be non-nullable by changing its type from `UUID` to `UUID!`. This ensures that the query will always require a project ID to be provided, preventing potential null reference issues.
**Checklist:**
=> fix(FR-978): Comprehensive backward compatibility check (24.09.x) before 25.8.0 release

react/src/components/MainLayout/WebUISider.tsx, react/src/components/TermsOfServiceModal.tsx
resolves #3512 [(FR-844)](https://lablup.atlassian.net/browse/FR-844)
Migrate the Terms of Service to a React modal in that PR. This modal is only active in parts that are written in React.
**changes** 
* add `TermsOfServiceModal.tsx`
* The modal has a width of `80%` and I'm not sure if that value is appropriate.
You can enable the modal by clicking on Terms of Service at the bottom of the side menu.
=> refactor(FR-844): migrate Terms of Service modal to react component

react/src/components/MainLayout/WebUISider.tsx, react/src/components/PrivacyPolicyModal.tsx
resolves #NNN (FR-992)
Migrate the `Privacy Policy` modal from that PR to a React component in NEO Style. This modal is only visible in React.
**changes**
* add `PrivacyPolicyModal`
* If the language is anything other than Korean, it will be displayed in English.
You can view this modal by clicking the `privacy policy` button at the bottom of the side menu.
=> refactor(FR-992): migrate Privacy Policy modal to NEO Style react component

src/components/backend-ai-app-launcher.ts
resolves #3660 (FR-994)
The app launcher running in the session detail panel is using the `backend-ai-app-launcher`. The `backend-ai-app-launcher` validates the tcp-based app spawn eligibility when the app launcher dialog is displayed on the screen. However, this process is missing when opening the app launcher in the session detail panel.
**Bug report:**
When refreshing after creating a new session but before the APP DIALOG was displayed, the port information was not displayed in the INFORMATION MODAL when executing SSH/SFTP through the SESSION DETAIL PANEL.
- Connect to a test server with SSH/SFTP enabled (e.g. dogbowl).
- Create a new session and refresh the browser before opening the app launcher dialog
- Open the `session detail panel` and run ssh/sftp 
- Verify that …
=> fix(FR-994): Validate that TCP APPs are allowed when open app laucnher on session detail panel

react/src/components/WEBUIHelpButton.tsx
https://lablup.atlassian.net/browse/FR-997
Resolves #3666 (FR-997)
This PR adds a mapping for the "service" page to the "model_serving/model_serving.html" help document, allowing users to access the appropriate help documentation when using the service page.
**Checklist:**
=> feat(FR-997): Linking the correct documentation page for a model service start/update

react/src/components/Chat/ChatMessageContent.tsx, react/src/components/Chat/SyntaxHighight.tsx
resolves #3613 (FR-951)
This PR adds `whiteSpace: 'pre-wrap'` styling to code elements in both `ChatMessageContent.tsx` and `SyntaxHighight.tsx` to ensure that code blocks properly wrap text instead of overflowing their containers.
=> fix(FR-951): Add white-space pre-wrap to code blocks

react/src/components/BAISelect.tsx, react/src/components/Chat/EndpointSelect.tsx, react/src/components/TotalFooter.tsx, react/src/hooks/usePaginatedQuery.ts
Resolves #3669 (FR-1002)
This PR enhances the BAISelect component with infinite scrolling capabilities and improves the EndpointSelect component to leverage these new features.
- Added infinite scrolling support to BAISelect with `endReached` callback
- Implemented scroll position tracking to detect when users reach the bottom of the dropdown
- Added footer support to display loading state and total item count
- Created a new `TotalFooter` component to show loading state and item counts
- Implemented `useLazyPaginatedQuery` hook for efficient data pagination
- Enhanced EndpointSelect to use the new pagination features
- Added optimistic UI updates for better user experience
- Improved search functionality with deferred value handling
**Checklist:**
=> feat(FR-1002): Infinite scrolling of EndpointSelect

react/src/components/ComputeSessionNodeItems/SessionSlotCell.tsx, react/src/components/SessionNodes.tsx, react/src/components/SessionUsageMonitor.tsx, react/src/hooks/useSessionNodeLiveStat.tsx
This PR enhances the session resource monitoring by adding visual indicators that show resource usage directly in the session slot cells. It adds colored status badges that change based on usage percentage thresholds (warning at 50%, critical at 80%).
Key changes:
- Added usage badges to CPU, memory, and accelerator resource displays
- Implemented tooltips showing detailed usage information (current/capacity)
- Moved session usage monitoring logic from a separate component into the slot cells
- Added a new `useSessionLiveStat` hook to handle resource statistics
- Enhanced `BAISelect` component with optional title support in dropdown
The badge changes based on the percentage value:
- At 0%, it displays as a gray circle with only a border.
- For values below 50%, it appears as a filled gray …
=> feat(FR-976): Session live stat badge

react/src/components/AgentList.tsx, react/src/components/BAICard.tsx, react/src/components/BAITable.tsx, react/src/components/SessionNodes.tsx, react/src/components/SessionTemplateModal.tsx, react/src/components/StorageProxyList.tsx, react/src/components/UserCredentialList.tsx, react/src/components/VFolderNodes.tsx, react/src/pages/ComputeSessionListPage.tsx, react/src/pages/ResourcesPage.tsx, react/src/pages/ServingPage.tsx, react/src/pages/VFolderNodeListPage.tsx
Resolves #3625 (FR-966)
Refactored the BAITable component to provide better pagination control and flexibility. The main changes include:
- Separated pagination from the Table component to allow for custom content next to pagination
- Added support for extra content in the pagination area through a new `extraContent` property
- Improved the sorting mechanism by replacing `orderString` with `order` and `onChangeOrder` props
- Fixed TypeScript types for better type safety and developer experience
- Updated all component implementations to use the new API pattern
- Apply `BAITable` with `extraContent` prop to AgentList
These changes make the BAITable component more versatile while maintaining its existing functionality.
=> feat(FR-966): Custom view beside of BAITable's pagination

react/src/components/AgentList.tsx, react/src/components/ResourceGroupList.tsx, react/src/components/StorageProxyList.tsx, react/src/pages/ResourcesPage.tsx
resolves #3462 (FR-967)
> The controls and generate functions are worked on separate stacks.
This PR updates the Resource Page UI by:
1. Replacing standard Ant Design Table with BAITable component in AgentList and StorageProxyList
2. Adding a new ResourceGroupList component using BAITable instead of the web component
3. Improving layout consistency across all resource list components
4. Fixing table styling with proper padding and spacing
5. Moving control buttons to the right side of tables with fixed positioning
6. Standardizing pagination display format across tables
=> refactor(FR-967): migrate list components in resources page to Neo Style

react/src/components/FolderExplorerActions.tsx, react/src/components/LegacyFolderExplorer.tsx
This PR improves the FolderExplorerActions component by:
1. Adding proper TypeScript typing for the FolderExplorerElement interface
2. Replacing LegacyRef with RefObject for better type safety
3. Removing unnecessary @ts-ignore comments
4. Fixing the "Create" button functionality to call openMkdirDialog() instead of openCreateFileDialog()
**Checklist:**
=> fix(FR-1007): Allow to create a new folder in folder explorer 

react/src/components/Chat/EndpointSelect.tsx, src/backend-ai-app.ts
Resolves #3679 (FR-1008)
This PR fixes TypeScript errors in the EndpointSelect component by simplifying the type definition for EndpointSelectProps. It also removes an unused import for the resource group list component.
**Changes:**
- Simplified the EndpointSelectProps interface to extend from SelectProps directly
- Removed a @ts-ignore comment that is no longer needed
- Removed the 'resource' case and its associated import in backend-ai-app.ts
**Checklist:**
=> fix(FR-1008): Simplify EndpointSelectProps type and remove unused resource import

react/src/components/ComputeSessionNodeItems/EditableSessionName.tsx, react/src/components/SessionNameFormItem.tsx
resolves #3695 (FR-1020)
This PR refactors the session rename functionality to use the REST API instead of GraphQL mutation. The implementation now:
1. Uses `useTanMutation` with the REST API endpoint `/session/${session.name}/rename`
2. Adds validation to check for existing session names before attempting to rename
3. Improves the optimistic UI updates during rename operations
4. Adds proper transition states for better user experience
**Checklist:**
=> fix(FR-1020): Change session name update method to use REST API

react/src/components/SharedFolderPermissionInfoModal.tsx
resolves #3689 [(FR-1016)](https://lablup.atlassian.net/browse/FR-1016)
Change the `leave` API to use `vfolderId` instead of `vfolderName` in the `leave` API to leave an invited folder. 
=> feat(FR-1016): change using folderId instead of folderName when leaving a shared folder

react/src/components/AgentSummaryList.tsx
Resolves #3566 ([FR-890](https://lablup.atlassian.net/browse/FR-890))
This PR updates the pagination total count in the AgentSummaryList component to use the length of the filtered agent summary list instead of the total count from the agent summary list. This ensures that the pagination accurately reflects the number of items currently being displayed after filtering.
**Checklist:**
[FR-890]: https://lablup.atlassian.net/browse/FR-890?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(FR-890): Fix pagination count issue in agent summary table

react/src/components/Flex.tsx
https://lablup.atlassian.net/browse/FR-971
Resolves #3628 (FR-971)
This PR adds a new 'ms' size option to the `GapSize` type in the Flex component and changes the token reference from 'padding' to 'size' when converting string gap sizes to their numeric values.
**Checklist:**
=> feat: add 'ms' gap size to Flex component

react/src/index.tsx
resolves #3698 (FR-1021)
> This is only an issue with EDGE BROWSER. If you are using a MAC environment, please [INSTALL EDGE BROWSER ](https://www.microsoft.com/ko-kr/edge/mac?form=MA13UX&cs=2282084340) for MAC.
Ant Design's Tooltip renders its children as DOM nodes outside of the parent component's DOM hierarchy. If a React Component is used inside a Lit Element, the portal will not behave properly and will be trapped inside the shadow DOM, causing layout deformations due to the tooltip.
Modify the portal to work properly by setting a ConfigProvider on the `CopyableCodeText.tsx` component.
- Run WebUI with edge browser, and run vscode in a running session.
- Run the browser inspector, and modify the text inside the SSH password tag to make the button wrap. …
=> fix(FR-1021): Set Tooltip popup container to document.body via ConfigProvider to fix layout shift

electron-app/package.json, index.html, manifest.json, package.json, react/package.json, version.json
This PR updates the package version from 25.5.0-alpha.0 to 25.9.0-alpha.0 across all configuration files. The build number has also been updated from 6552 to 6700, and the build date is now set to 250522.130550 with revision c51fa09e7.
=> chore: Bump version to 25.9.0-alpha.0

package.json
This PR resolves #3712 (FR-1035) by removing the `test:react` script from the package.json file, which was previously used to run tests in the React subdirectory.
**Checklist:**
=> misc(FR-1035): remove unused pnpm command for test using jest framework

react/src/components/VFolderNodeDescription.tsx, react/src/components/VFolderNodes.tsx, src/lib/backend.ai-client-esm.ts
Resolves #3548 ([FR-877](https://lablup.atlassian.net/browse/FR-877))
This PR enables project admins to change the permission of group folders. Previously, only the owner of a folder could change its permission. Now, project admins can also change the permission of folders that belong to their project.
The changes include:
- Adding the `group` field to the GraphQL query for both legacy and new vfolder APIs
- Using the current project context to determine if the user is an admin of the project
- Allowing permission changes when the folder belongs to the current project and the user is an admin
- Using `baiClient.is_admin` instead of `userRole === 'admin'` for consistency
1. make a new project folder with admin user.
2. click the folder name to change the project mount permission. …
=> fix(FR-877): Enable project folder mount permissions editing for admins

react/src/components/MainLayout/MainLayout.tsx, react/src/components/TOTPActivateModal.tsx, react/src/components/TOTPActivateModalWithToken.tsx, react/src/index.tsx, src/components/backend-ai-login.ts, src/lib/backend.ai-client-esm.ts
Resolves #3614 (FR-952)
This PR implements a TOTP registration flow for users who are required to set up two-factor authentication before they can log in. The implementation includes:
- Added a new React component `TOTPActivateModalWithToken` that handles TOTP registration before login
- Refactored `TOTPActivateModal` to extract the form into a reusable component
- Added backend client methods for anonymous TOTP initialization and verification
- Updated the login component to detect when TOTP registration is required and show the registration modal
The flow now properly handles the case where the server returns "TOTP key registration required" during login attempts, allowing users to set up 2FA without being logged in first.
You can use a [test …
=> feat(FR-952): TOTP registration before login

react/src/hooks/useDeferredQueryParams.tsx, react/src/pages/ComputeSessionListPage.tsx, react/src/pages/ServingPage.tsx, react/src/pages/VFolderNodeListPage.tsx
Resolves #3742 (FR-1058)
This PR updates the `useDeferredQueryParams` hook to properly handle default values for query parameters. Previously, default values were only applied when explicitly setting parameters, but not when reading from the global state. This caused issues with pagination and sorting on various list pages.
Changes:
- Modified `useDeferredQueryParams` to apply default values when reading from global state
- Updated default order parameter to `-created_at` in ComputeSessionListPage, ServingPage, and VFolderNodeListPage
- Removed redundant fallback logic for order parameters in these pages
=> fix(FR-1058): handling default value in useDeferredQueryParams

.eslintrc.json, packages/backendai-ui/.gitignore, packages/backendai-ui/.storybook/main.ts, packages/backendai-ui/.storybook/preview.ts, packages/backendai-ui/package.json, packages/backendai-ui/src/components/Flex.stories.tsx, packages/backendai-ui/src/components/Flex.tsx, packages/backendai-ui/src/index.ts, pnpm-lock.yaml, react/src/pages/StartPage.tsx
resolves #3618 [(FR-955)](https://lablup.atlassian.net/browse/FR-955)
In this PR, move custom `Flex` component in react project to `backend.ai-ui` project
**changes**
* add `Flex` component to `backend.ai-ui` project
* set up `storybook`
* add stories about `Flex` component
**how to test**
1. Please go to `packages/backendai-ui` and run `pnpm build`.
2. Run `pnpm install` in the root.
3. Run `pnpm build:d` and `pnpm server:d`.
4. Import `Flex` from `backend.ai-ui` on Webui.
5. If you want to see it with storybook, please run `pnpm run storybook` in `packages/backendai-ui`
=> feat(FR-955): move Flex component to backend.ai-ui project

react/src/components/AgentDetailModal.tsx, react/src/components/AgentList.tsx, react/src/components/AgentSummaryList.tsx, react/src/components/AllocationHistoryStatistics.tsx, react/src/components/AvailableResourcesCard.tsx, react/src/components/ComputeSessionNodeItems/SessionSlotCell.tsx, react/src/components/DynamicUnitInputNumber.tsx, react/src/components/DynamicUnitInputNumberWithSlider.tsx, react/src/components/KeypairResourcePolicySettingModal.tsx, react/src/components/NumberWithUnit.tsx, react/src/components/QuotaPerStorageVolumePanelCard.tsx, react/src/components/ResourceAllocationFormItems.tsx, react/src/components/ResourceNumber.tsx, react/src/components/ResourcePresetList.tsx, react/src/components/ResourcePresetSettingModal.tsx, react/src/components/ServiceLauncherPageContent.tsx, react/src/components/SessionMetricGraph.tsx, react/src/components/SessionUsageMonitor.tsx, react/src/components/VFolderNodeDescription.tsx, react/src/helper/big-number.test.ts, react/src/helper/big-number.ts, react/src/helper/index.test.tsx, react/src/helper/index.tsx, react/src/hooks/useResourceLimitAndRemaining.tsx, react/src/pages/SessionLauncherPage.tsx
Resolves #3741 (FR-1057)
This PR refactors how size units are displayed across the UI by introducing more consistent formatting methods. It replaces the previous conversion functions (`convertBinarySizeUnit` and `convertDecimalSizeUnit`) with improved versions (`convertToBinaryUnit` and `convertToDecimalUnit`) that provide better formatted output.
The changes improve readability by:
1. Standardizing the display of binary units (KiB, MiB, GiB) and decimal units (KB, MB, GB)
2. Adding `displayValue` and `displayUnit` properties to conversion results
3. Simplifying unit parsing and conversion logic
4. Making the API more consistent across all components
Refactoring of Function Responsibilities:
- `convertUnitValue`: Converts the unit of a value expressed with a lowercase unit. The existing …
=> refactor(FR-1057): Refactor size unit formatting in UI components

react/src/App.tsx, react/src/components/FolderInvitationResponseModal.tsx, react/src/components/FolderInvitationResponseModalOpener.tsx, react/src/hooks/backendai.tsx, react/src/hooks/useVFolderInvitations.tsx, react/src/pages/StartPage.tsx, react/src/pages/VFolderNodeListPage.tsx
Resolves #3714 ([FR-739](https://lablup.atlassian.net/browse/FR-739))
This PR refactors the folder invitation system to use a global modal that can be accessed from anywhere in the application.
Key changes:
- Created a new `useVFolderInvitations` hook with Jotai state management for better performance and global state access
- Added `FolderInvitationResponseModalOpener` component that can be triggered via URL query parameters
- Moved invitation data model to a dedicated hook for better code organization
- Added notification for pending folder invitations on the StartPage
- Improved rendering performance with memoization of invitation items
- Fixed key prop warning in the invitation list
**Checklist:**
[FR-739]: https://lablup.atlassian.net/browse/FR-739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmND …
=> feat(FR-739): add FolderInvitationResponseModal and related hooks for managing folder invitations

e2e/login.test.ts
Resolves #3768 (FR-1079)
This PR adds two new E2E tests to verify proper error handling during login:
1. Tests the error message when attempting to login with a non-existent email
2. Tests the error message when attempting to login with an incorrect password
Both tests verify that the appropriate error notification is displayed to the user when login credentials are invalid.
=> e2e(FR-1079): Add login failure cases due to email and password

react/src/components/Chat/EndpointSelect.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/th.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json
This PR resolves https://github.com/lablup/backend.ai-webui/issues/3746 (FR-1065) by
adding an info button next to the selected endpoint label in the endpoint select dropdown. When clicked, it will navigate to the endpoint details page (implementation pending).
**Changes:**
- Added an info button with `InfoCircleOutlined` icon to the endpoint select component
- Implemented custom label rendering to display the info button alongside the endpoint name
- Applied styling to match the UI design using theme tokens
###Screenshot(s):
[Screen Recording 2025-06-10 at 7.05.02 PM.mov <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/api/v1/graphite/video/thumbnail/Dgoz5XqHffJdivyccymr/60786a6a-cc6c-425b-87a6-3b68400a3fec.mov" …
=> feature(FR-1065): add: custom label on EndpointSelect component

react/src/components/ServiceLauncherPageContent.tsx, react/src/components/SessionDetailContent.tsx, react/src/pages/SessionLauncherPage.tsx, src/components/backend-ai-app-launcher.ts, src/components/backend-ai-folder-explorer.ts, src/components/backend-ai-import-view.ts, src/components/backend-ai-splash.ts, src/lib/backend.ai-client-esm.ts, src/types/backend-ai-console.d.ts
Resolves #3751 ([FR-1070](https://lablup.atlassian.net/browse/FR-1070))
This PR refactors the session creation API to handle the parsing and check logic in react component.
1. Restructures `SessionConfig` into `SessionResources` with a nested `config` object
2. Renames fields to match backend API conventions:
- `startsAt` → `starts_at`
- `env` → `environ`
- Moves resource specifications into appropriate nested objects
3. Removes console.log statement in SessionDetailContent
4. Simplifies the client's `createIfNotExists` method by removing redundant parameter transformations
5. Fixes a typo in ServiceLauncherPageContent ("temporally" → "temporarily")
**Checklist:**
[FR-1070]: https://lablup.atlassian.net/browse/FR-1070?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2 …
=> feat(FR-1070): Include new accelerator information in session creation payload

react/src/components/DynamicUnitInputNumber.tsx, react/src/components/SessionUsageMonitor.tsx, react/src/hooks/useSessionNodeLiveStat.tsx
This PR removes unnecessary `console.log` statements from multiple components and fixes the CPU utilization calculation in the `SessionUsageMonitor` component. The CPU utilization is now properly calculated by dividing the CPU percentage by the number of allocated CPUs.
e.g.) If you are using 1 core in a 4-core allocation session, the progress bar should only be 25% filled.
Additionally, the PR updates the session live stat hook to use the main kernel node instead of the first kernel node, ensuring more accurate resource usage reporting for multi-node sessions.
=> fix(FR-949): incorrect CPU usage disaply in session usage monitor

react/src/components/Chat/ChatHistory.ts, react/src/pages/ChatPage.tsx
This PR addresses two issues:
1. Fixes the chat history merging logic to properly preserve existing data when updating history. Now it retrieves the existing data from the cache before merging with new data.
2. Renames a parameter in the `onClearMessage` callback from `chat` to `chatData` to better reflect its purpose and maintain consistency with other parameter names.
=> fix(FR-1097): Fix missing chat messages

react/src/components/ResourcePresetSelect.tsx
This PR changes the condition for filtering resource presets by replacing a null check with `_.isEmpty()`. This ensures that resource presets with empty scaling group names are properly included in the filtered results, fixing an issue where some valid presets might not appear in the selection.
Before this PR, Resource preset select can not display any presets with Manager v24.09.x.
This PR is related to https://github.com/lablup/backend.ai-webui/pull/3349 PR
=> fix(FR-1104): Improve backward compatibility in ResourcePresetSelect

react/src/components/FolderInvitationResponseModal.tsx, react/src/hooks/useVFolderInvitations.tsx
Resolves #3800 ([FR-1101](https://lablup.atlassian.net/browse/FR-1101))
This PR enhances the folder invitation system to support both new and old manager API versions:
- Adds compatibility with manager versions before 25.6.0 by supporting both `inviter_user_email` and legacy `inviter` fields
- Uses `useSuspendedBackendaiClient` to check manager version compatibility
- Conditionally displays the appropriate inviter information based on the manager version
- Updates the `InvitationItem` interface to make email fields optional and include legacy fields
**Checklist:**
[FR-1101]: https://lablup.atlassian.net/browse/FR-1101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(FR-1101): Missing Sender Information in User Invitation Email

react/src/components/ResourceAllocationFormItems.tsx, react/src/components/ResourcePresetSelect.tsx, react/src/components/ResourcePresetSettingModal.tsx
Resolves #3808 (FR-1106)
This PR fixes a bug where the automatic shared memory (shmem) setting was incorrectly overriding resource preset conf
igurations. When a resource preset with a specific shmem value was selected, the automatic shmem rule would always set it to 1GB when memory >= 4GB, ignoring the preset's configured value.
When users selected a resource preset that included a specific shared memory configuration:
1. **Expected behavior**: The preset's shmem value should be used
2. **Actual behavior**: The automatic shmem rule would override the preset value with 1GB when memory >= 4GB
In `ResourceAllocationFormItems.tsx`:
- Line 538: `enabledAutomaticShmem` was always set to `true` when selecting any preset
- Lines 398-399: The preset's shmem value was correctly applied to the form …
=> fix(FR-1106): prevent automatic shmem override when resource preset has specific shmem configuration

react/src/components/UserSessionsMetrics.tsx
This PR improves the user sessions metrics display by:
1. Implementing a responsive grid layout using Ant Design's Row and Col components to display metrics in a two-column format on larger screens
2. Enhancing metric sorting logic to group related metrics together:
- Prioritizing CPU utilization and memory metrics
- Grouping accelerator metrics by type (e.g., GPU)
- Sorting accelerator metrics to show utilization before memory metrics
3. Excluding 'cpu_used' metric from display
The new layout provides a more organized view of metrics, making better use of screen space while maintaining readability on both desktop and mobile devices.
=> feat(FR-1105): Improve session metrics layout and remove CPU used metric

react/src/components/SessionMetricGraph.tsx
This PR enhances the `getMetricTitle` function in the SessionMetricGraph component to better handle different types of metrics. It adds special handling for 'cuda', 'rocm', and 'io' metrics to display them in uppercase, and improves the resource slot key lookup by searching for partial matches instead of exact matches.
- Connect to endpoints that support devices like CUDA or ROCm or etc.
- Access the STATISTICS page and verify that the device name is capitalized on the card in USER SESSION HISTORY.
=> fix(FR-957): Display device name in upper case on prometheus metrics

react/src/components/Chat/ChatHeader.tsx
This PR resolves #3827 (FR-1110) by changing the placement property of the Popover component in ChatHeader.tsx from "bottom" to "bottomLeft" to better align the popover with its trigger element. 
(Please refer to antd component description: https://ant.design/components/tooltip#common-api)
|-------|-------|
| ![Screenshot 2025-06-20 at 4.39.11 PM.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/Dgoz5XqHffJdivyccymr/7c2ab094-f7ac-45a6-a72c-ccee19998f81.png) |  ![Screenshot 2025-06-20 at 4.39.22 PM.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/Dgoz5XqHffJdivyccymr/066e5d03-be0d-4b6f-9fd9-2812eed34c3e.png) | 
**Checklist:**
=> hotfix(FR-1110): place tooltip of chat parameter to left side to avoid overflow

react/src/components/VFolderTableFormItem.tsx
This PR resolves #3825 (FR-1112) by removing an unnecessary `useEffect` hook that was resetting form values (`mounts`, `vfoldersAliasMap`, and `autoMountedFolderNames`) whenever the `tableProps.ownerEmail` changed. This initialization is likely handled elsewhere in the application flow.
> Prerequisite:
> - Backend.AI Core version from 24.09~
> - two users(one is admin, and the other is userA)
> - at least one or more user-owned automount folder. (starts with `.`(dot))
1. Login with user account
2. Go to Data page
3. Create a `general` usage-mode user type folder, a name starts with `.`(dot).
4. Go to Session page.
5. Click `Start` button.
6. Go to `Data & Storage` section.
7. See automount folder just created in step 2 displayed properly.
8. Go to preview section and create session.
9. …
=> fix(FR-1112): remove unnecessary form reset effect in VFolderTableFormItem

react/src/components/AllowedVfolderHostsWithPermission.tsx, react/src/components/KeypairResourcePolicyInfoModal.tsx
This PR resolves #3838 (FR-1124) the import paths for Relay GraphQL generated files in two components:
1. `AllowedVfolderHostsWithPermission.tsx`: 
- Moves generated type imports from local `./__generated__` to `../`
- Updates Relay imports to use direct `react-relay` instead of `babel-plugin-relay/macro`
2. `KeypairResourcePolicyInfoModal.tsx`:
- Moves generated type imports from local `./__generated__` to `../`
- Updates Relay imports to use direct `react-relay` instead of `babel-plugin-relay/macro`
=> misc(FR-1124): fix import error by correcting right path and library

react/src/components/Chat/ChatCard.tsx, react/src/pages/ChatPage.tsx
resolves #3844 (FR-1126)
Resolves the issue of not being able to access the CHAT page if the service endpoint already has a port.
This PR refactors URL handling in two components:
1. In `ChatCard.tsx`, simplifies the `createModelsURL` function by:
- Removing unnecessary port extraction and handling
- Using the `origin` property directly which already includes the port information
- Streamlining the URL construction process
2. In `ChatPage.tsx`, removes unnecessary fragment wrapper around the `PureChatPage` component
These changes make the code more concise while maintaining the same functionality.
**Checklist:**
=> fix(FR-1126): Duplicated port number in generating URL

react/src/components/DynamicUnitInputNumber.tsx, react/src/components/DynamicUnitInputNumberWithSlider.stories.tsx, react/src/components/ResourceAllocationFormItems.tsx
resoves #3862 (FR-1155)
This PR adds `stringMode` to `DynamicUnitInputNumber` component to ensure proper handling of string values. It also fixes memory validation in `ResourceAllocationFormItems` by providing fallback values (`'0g'`) when comparing memory values, preventing potential errors when dealing with empty or undefined values.
=> fix(FR-1155): Set DynamicUnitInputNumber to stringMode

react/src/components/BAITable.tsx
resolves #3873 [(FR-1170)](https://lablup.atlassian.net/browse/FR-1170)
Fixed BAITable pagination by checking if pagination prop exists before accessing it. Previously, the component was trying to access pagination properties directly from tableProps, which could cause errors if pagination was not provided. Now it safely checks if tableProps.pagination exists before using it with useControllableValue.
=> fix(FR-1170): make BAITable to controll correct pagination values

pnpm-lock.yaml, react/package.json, react/src/components/ServiceValidationView.tsx, react/src/helper/index.tsx, react/src/hooks/useBAINotification.tsx
Resolves #3740 ([FR-1056](https://lablup.atlassian.net/browse/FR-1056))
Currently, when accessing an endpoint on a remote server, the authentication cookie is not included in the request, making background task tracking impossible due to permissions issues.
By default, when you declare an SSE handler, you can declare a BaseType that will be common to all handlers.
```
const SSEEventHandlers: SSEEventHandlerTypes<BackgroundTaskEvent> = { ... } 
```
If you need a different type for a particular handler, you can override it by declaring the handler that requires type overriding next to the BaseType.
```
const SSEEventHandlers: SSEEventHandlerTypes<BackgroundTaskEvent, { onFailed: {message: {error: string}}}>
```
This PR fixes this by sending requests with the session ID in the request header …
=> fix(FR-1056): Use fetch-event-source for authenticated SSE requests

react/src/components/BAIConfirmModalWithInput.tsx
resolves #3884 (FR-1186)
This PR fixes an issue with the `okButtonProps` in the `BAIConfirmModalWithInput` component. Previously, the component was overriding any `okButtonProps` passed through the `props` object. Now, it properly spreads the existing `okButtonProps` before applying the required `disabled` and `danger` properties.
This change ensures that custom button properties (like `loading`, `className`, etc.) can be passed to the OK button while still maintaining the required confirmation behavior.
**Checklist:**
=> fix(FR-1186): update okButtonProps to include disabled and danger in BAIConfirmModalWithInput component

react/src/components/ImageEnvironmentSelectFormItems.tsx
resolves #3896 (FR-1197)
In the "Environments & Resource allocation" step of the session page, the validation message for the Environments select item has been updated. Previously, the validation relied on the default behavior provided by antd, but now a custom message has been specified in the rules to display a more appropriate text. The updated messages are confi
rmed to appear correctly in both Korean, English and other languages.
<br><br><br>
=> chore(FR-1197): modify validation message in environments select

electron-app/package.json, index.html, manifest.json, package.json, react/package.json, version.json
Resolves #3881 ([FR-1181](https://lablup.atlassian.net/browse/FR-1181))
Updates the package version from 25.9.0-alpha.0 to 25.12.0-alpha.0 across all configuration files. Also updates the build number from 6700 to 6785 and updates the build date and revision in version.json.
[FR-1181]: https://lablup.atlassian.net/browse/FR-1181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(FR-1181):update mai branch version to v25.2.0-alpha.0

react/src/components/SessionOwnerSetterCard.tsx, react/src/components/TOTPActivateModal.tsx, react/src/components/TableColumnsSettingModal.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/th.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json, src/components/backend-ai-page.ts
resolves #3893 (FR-1195)
The logic in TableColumnsSettingModal has been updated to require at least one checkbox to be selected. Previously, selecting zero checkboxes caused the table to appear empty. Now, when attempting to confirm with zero selections, a validation message is displayed.
<br><br>
=> chore(FR-1195): modify column setting logic

react/src/pages/UserSettingsPage.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/th.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json
resolves #3877 [(FR-1178)](https://lablup.atlassian.net/browse/FR-1178)
Clarified Chinese language options in the user settings page by:
- Renamed "Chinese" to "SimplifiedChinese" (简体中文)
- Renamed "Chinese (Simplified)" to "TraditionalChinese" (繁體中文)
- Updated all language translation files to reflect these changes
This change provides clearer distinction between the two Chinese language options available in the system.
=> fix(FR-1178): correct the labels for Simplified and Traditional Chinese in the language selection

react/src/components/AgentList.tsx, react/src/components/StorageHostResourcePanel.tsx, react/src/components/StorageProxyList.tsx, react/src/helper/index.tsx
resolves #3885 (FR-1190)
This PR enhances how resource metrics are displayed throughout the UI by:
1. Adding proper spacing around division symbols (`/`) in resource usage displays
2. Using dynamic base units for memory and storage metrics instead of hardcoded units
3. Replacing the deprecated `bytesToGB` function with more flexible conversion utilities:
- `convertToDecimalUnit` for decimal-based conversions (storage)
- `convertToBinaryUnit` for binary-based conversions (memory)
- `convertUnitValue` for determining appropriate display units
4. remove `humanReadableDecimalSize` function.
These changes make resource metrics more readable and ensure consistent formatting across the application.
=> style(FR-1190): enhance the ux for resource display on the agent page

react/src/components/SessionMetricGraph.tsx, react/src/components/UserSessionsMetrics.tsx
resolves #3918 ([FR-1219](https://lablup.atlassian.net/jira/software/projects/FR/boards/21?assignee=712020%3A52c9a410-dfd2-4acd-97a6-8c6112ec8a34&selectedIssue=FR-1219))
This PR adds a `key` prop to the `SessionMetricGraph` component to ensure proper re-rendering when metrics are resized in the dashboard. When a user resizes a metric graph, the component now regenerates with a unique key based on the item ID and timestamp, forcing a complete re-render of the graph with the new dimensions.
The changes include:
- Added a required `key` prop to the `SessionMetricGraph` component interface
- Implemented special handling for resized items in the board's `onItemsChange` event
- Regenerated graph content with fresh keys when resizing occurs
How to test:
- Move to `User Session History` page. 
- …
=> fix(FR-1219): Support responsive session metric graph

react/src/components/ActionItemContent.tsx, react/src/hooks/useBAISetting.tsx, react/src/pages/StartPage.tsx
resolves #3866 (FR-1161)
This PR enhances the Start Page by:
1. Replacing the static card grid with a movable BAIBoard component, allowing users to rearrange start page items
2. Implementing persistent layout storage in user settings via `start_page_board_items`
3. Improving the ActionItemContent component's layout and styling:
- Fixed overflow handling with proper flex structure
- Enhanced text alignment and spacing
- Improved divider styling
- Better responsiveness for different content types
The changes provide a more customizable and visually consistent start page experience.
=> feat(FR-1161): Apply BAIBoard component to Start Page

react/src/components/FolderInvitationResponseModal.tsx
resolves #3962 (FR-1250)
Improved error handling in the `FolderInvitationResponseModal` component by adding specific error messaging when a folder already exists (status code 409). Now when users attempt to accept an invitation for a folder that already exists in their account, they will see a clear error message instead of a generic failure notification.
=> fix(FR-1250): add error handler for 409 error to acceptoin invitaion

react/src/components/FolderInvitationResponseModal.tsx, react/src/components/FolderInvitationResponseModalOpener.tsx
Resolves #3959 ([FR-1251](https://lablup.atlassian.net/browse/FR-1251))
This PR improves the folder invitation handling by automatically refreshing invitation data when the invitation modal is opened. The implementation:
1. Modifies `useVFolderInvitationsValue` hook to accept an optional `shouldRefresh` parameter
2. Adds a new effect that triggers invitation data refresh when `shouldRefresh` becomes true
3. Removes the unused `fetchKey` prop from `FolderInvitationResponseModal`
4. Updates the modal to pass its `open` state to the hook to trigger refreshes
These changes ensure that users always see the most up-to-date invitation data when opening the invitation modal.
**Checklist:**
[FR-1251]: https://lablup.atlassian.net/browse/FR-1251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5 …
=> fix(FR-1251): folder invitation response modal doesn't show latest data.

react/src/hooks/useBAINotification.tsx
This PR adds `desktopNotification` to the dependency array of the `useCallback` hook in `useSetBAINotification`. This ensures that the callback is properly updated when the `desktopNotification` value changes, fixing a potential bug where desktop notifications might not reflect the current state of the `desktopNotification` setting.
=> fix(FR-1254): Add desktop notification localstorage setting to callback dependency array

react/src/pages/ComputeSessionListPage.tsx, react/src/pages/VFolderNodeListPage.tsx
https://lablup.atlassian.net/browse/FR-1257
Resolves #3970 (FR-1257)
This PR enhances the layout of the Compute Session List Page by:
- Making cards stretch to fill their container height
- Using flexbox display for columns to ensure proper alignment
- Setting consistent `minHeight` instead of fixed `height` for better responsiveness
- Applying width of 100% to cards to ensure they fill their containers
- Ensuring the ActionItemContent component stretches to full height
These changes improve the visual consistency of the page, especially in different screen sizes.
Before
After
**Checklist:**
=> style(FR-1257): broken UI of create session panel

data/merged_schema.graphql, data/schema.graphql, react/src/components/CustomizedImageList.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/th.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json, src/lib/backend.ai-client-esm.ts
resolves #3968 [(FR-1252)](https://lablup.atlassian.net/browse/FR-1252)
This PR updates the GraphQL schema and image management functionality with several improvements:
1. Updates the version annotations for user utilization metrics from 25.5.0 to 25.6.0
2. Fixes a typo in `MetircResultValue` to `MetricResultValue`
3. Adds new service configuration queries and mutations in version 25.8.0:
- `available_service`, `available_services`
- `service_config`, `service_configs`
- `modify_service_config`
4. Enhances image management:
- Adds `installed` boolean field to `ImageNode` in version 25.11.0
- Adds `clear_image_custom_resource_limit` mutation in version 25.6.0
- Updates `purge_image_by_id` to support registry removal option in version 25.10.0
5. Refactors the image deletion process in …
=> fix(FR-1252): Separate untag and forget queries

react/src/components/ResourceNumber.tsx
Resolves #3860 ([FR-1153](https://lablup.atlassian.net/browse/FR-1153))
|  Before  | After    |
|---------|--------|
| ![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/XqC2uNFuj0wg8I60sMUh/4d1155f1-c416-47ed-b2db-447e512a1328.png)               |     ![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/XqC2uNFuj0wg8I60sMUh/a7edac83-0906-4d36-84de-713de081304b.png)        |
This PR replaces the deprecated Material Web Component icons with Lucide icons for CPU and memory resources. Specifically:
- Removes the `MWCIconWrap` component that was using the deprecated `mwc-icon` element
- Imports `CpuIcon` and `MemoryStickIcon` from Lucide React
- Updates the resource type icons to use these Lucide components instead of the MWC icons
[FR-1153]: …
=> chore(FR-1153): replace CPU and MEM icons in React

react/src/pages/ComputeSessionListPage.tsx, react/src/pages/SessionLauncherPage.tsx
Resolves #3981 ([FR-1263](https://lablup.atlassian.net/browse/FR-1263))
Added automatic refresh of the compute session list when sessions are created or pending.
- Added monitoring of session creation notifications in the ComputeSessionListPage
- Implemented two effects to refresh the session list:
1. A timeout-based refresh when pending sessions are detected but not yet visible in the list
2. An immediate refresh when session creation notifications are resolved
- Added session name to the GraphQL query to properly track sessions
- Exported the SESSION_LAUNCHER_NOTI_PREFIX constant for consistent notification key management
1. Create a new compute session from the Session Launcher page
2. After creation, it will be navigated to the Compute Session List page
3. Verify that pending sessions …
=> feat(FR-1263): show pending sessions in the session list immediately aftercreation

src/components/backend-ai-login.ts
resolves #3990 (FR-1274)
~This PR fixes sign up modal bug so that the signup modal opens correctly regardless of the endpoint value.~
This bug occurrs because the `api_endpoint` value is updated only when the login button was pressed. So, This PR fixes sign up modal bug so that `api_endpoint` updates when focus is out.
=> fix(FR-1274): add @change option to api_endpoint to update value immediately

react/src/helper/graphql-transformer.test.ts, react/src/helper/graphql-transformer.ts
Resolves #4002 (FR-1295)
This PR enhances the GraphQL transformer to properly handle fragments after field filtering. The implementation now:
1. Uses a multi-pass approach to correctly identify and preserve necessary fragments
2. Removes truly unused fragments after transformation
3. Properly handles `@since` directives while maintaining fragment references
The changes split the transformation process into three distinct passes:
- First pass: Remove fields with client directives and clean up directives
- Second pass: Collect fragment spreads from the transformed AST
- Third pass: Remove unused fragment definitions
This prevents the "Fragment is never used" error while ensuring we don't keep unnecessary fragments in the final query.
=> fix(FR-1295): Preserve necessary GraphQL fragments after client directive filtering

pnpm-lock.yaml, react/package.json, react/src/components/BAIPanelItem.tsx, react/src/components/BAIProgress.tsx, react/src/components/StorageStatusPanelCard.tsx, react/src/hooks/usePrimaryColors.ts
Resolves #4014 ([FR-1298](https://lablup.atlassian.net/browse/FR-1298))
The `headerBg` token from the Layout theme configuration is currently being misused across React components as a general-purpose accent color, when it should only be used for the actual header background. This creates an inconsistent design system where header-specific styling tokens are inappropriately used for other UI elements.
- **Added @ant-design/colors package** for proper color palette generation
- **Extended usePrimaryColors hook** to provide `primary1` through `primary10` color palette using `generate()` function
- **Replaced headerBg misuse** in multiple React components:
- `BAIProgress.tsx`: Progress bar colors and percentage text
- `StorageStatusPanelCard.tsx`: Invited folder count text color  
- …
=> refactor(FR-1298): replace headerBg token misuse with proper primary color palette

.claude/commands/create-pr-stack-for-stage.md
Resolves #4026 ([FR-1304](https://lablup.atlassian.net/browse/FR-1304))
This PR enhances the Claude Code PR creation workflow to automatically assign newly created Jira issues to the currently active sprint in the FR project, improving workflow efficiency.
- ✅ Enhanced `/create-pr-stack-for-stage` command documentation
- ✅ Added Atlassian MCP integration instructions for automatic sprint assignment
- ✅ Specified correct sprint field format (`customfield_10020` with numeric ID)
- ✅ Added JQL query examples for finding active sprints
- ✅ Included step-by-step MCP command usage for user and sprint assignment
- Integrates `mcp__Atlassian__searchJiraIssuesUsingJql` for active sprint detection
- Uses `mcp__Atlassian__editJiraIssue` for automatic issue assignment
- Maintains backward …
=> feat(FR-1304): enhance PR workflow to auto-assign issues to active sprints

react/src/components/SessionMetricGraph.tsx
Resolves #4020 ([FR-1301](https://lablup.atlassian.net/browse/FR-1301))
The SessionMetricGraph component is causing a React warning: "`key` is not a prop. Trying to access it will result in `undefined` being returned."
The component incorrectly defines `key` as a regular prop in its interface and tries to access it. In React, `key` is a reserved prop used internally for reconciliation and cannot be accessed as a regular prop within components.
Remove the improper usage of the `key` prop:
- Remove `key` from the component's props interface
- Remove `key` parameter from function destructuring
- Remove redundant `key` usage in JSX elements
- **react/src/components/SessionMetricGraph.tsx**: Removed `key: string` from `PrometheusMetricGraphProps` interface, removed `key` parameter from …
=> fix(FR-1301): remove improper key prop usage in SessionMetricGraph component

packages/backend.ai-ui/src/components/index.ts, packages/backend.ai-ui/src/components/unsafe/UNSAFELazyUserEmailView.tsx, packages/backend.ai-ui/src/components/unsafe/index.ts, packages/backend.ai-ui/src/helper/index.ts, packages/backend.ai-ui/src/hooks/index.ts, packages/backend.ai-ui/src/index.ts, react/src/components/ComputeSessionNodeItems/AppLauncherModal.tsx, react/src/components/ComputeSessionNodeItems/SessionActionButtons.tsx, react/src/components/ComputeSessionNodeItems/SessionIdleChecks.tsx, react/src/components/DeleteVFolderModal.tsx, react/src/components/EditableVFolderName.tsx, react/src/components/LegacyFolderExplorer.tsx, react/src/components/RecentlyCreatedSession.tsx, react/src/components/RestoreVFolderModal.tsx, react/src/components/SessionDetailContent.tsx, react/src/components/VFolderNodeDescription.tsx, react/src/components/VFolderNodes.tsx, react/src/helper/index.tsx, react/src/hooks/useVirtualFolderNodePath.ts
This PR adds a new component `UNSAFELazyUserEmailView` that safely fetches and displays user email addresses. It also:
- Adds utility functions `toGlobalId` and `toLocalId` for GraphQL ID conversion
- Creates a new `useMemoizedJSONParse` hook for efficient JSON parsing
- Refactors session components to use the new email view component
- Removes legacy session fragments that are no longer needed
- FYI, `service_ports` of ComputeSessionNode is available since v24.09.0
- Updates the SessionIdleChecks component to use lazy loading
-  FYI, `idle_checks` of ComputeSessionNode is available since v24.12.0
The changes improve code organization and provide a safer way to display user emails in the UI.
**Checklist:**
=> refactor(FR-1287): remove `service_port` in legacy session fragment

react/src/components/ComputeSessionNodeItems/SessionIdleChecks.tsx, react/src/components/ImageTags.tsx, react/src/components/LegacyFolderExplorer.tsx, react/src/components/SessionDetailContent.tsx
This PR refactors the ImageTags component and adds a new component for fetching session image information via GraphQL.
Key changes:
- Added `UNSAFELazySessionImageTag` component that lazily loads session image data
- Made several ImageTags subcomponents non-exported as they're only used internally
- Refactored SessionDetailContent to use the new image tag components
- Updated variable name in LegacyFolderExplorer from `vfolderUUID` to `vfolderGlobal` for clarity
- Removed redundant components like `BaseVersionTags`, `LangTags`, and `ConstraintTags`
- Reorganized SessionKernelTags to be a memoized component
=> refactor(FR-1287): remove image infomation in legacy session fragment

react/src/components/LegacyFolderExplorer.tsx, react/src/components/SessionDetailContent.tsx, react/src/components/VFolderNodeDescription.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/th.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json
This PR improves error handling in the LegacyFolderExplorer component by adding proper null checks for the vfolder_node and displaying an error message when a folder is not found or access is denied. It also removes unnecessary folder access checks in the SessionDetailContent component that were causing issues.
Key changes:
- Added conditional rendering in LegacyFolderExplorer to handle cases where vfolder_node is null
- Added an error message when folder is not found or access is denied
- Removed unnecessary folder invitation checks in SessionDetailContent
- Updated VFolderNodeDescription to properly type its props
- Added translations for the new error message in all supported languages
=> feat(FR-1287): Show "No Access" in Explorer, not disable Session Detail

react/src/components/LegacyFolderExplorer.tsx, react/src/components/MountedVFolderLinks.tsx, react/src/components/SessionDetailContent.tsx, react/src/components/SessionDetailDrawer.tsx, react/src/components/SessionNodes.tsx, react/src/pages/ComputeSessionListPage.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/th.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, src/components/backend-ai-folder-explorer.ts, src/lib/backend.ai-client-esm.ts
This PR enhances the folder explorer and session detail drawer with several improvements:
1. Added permissions field to folder explorer GraphQL query to prepare for permission-based access control
2. Created a new `MountedVFolderLinks` component to handle folder mounting display in sessions
3. Improved session detail drawer performance by:
- Passing session fragment data via location state to avoid redundant fetches
- Adding timestamp to determine when to refresh cached data
4. Added error handling for folders with no permissions
5. Added translations for "No permissions to access this folder" message in all supported languages
The changes optimize data fetching patterns and improve the user experience when viewing session details and folder contents.
=> feat(FR-1287): Optimize session detail navigation with state caching and GraphQL fragment improvements

react/src/components/Chat/ChatMessageContent.tsx
Resolves #4041 ([FR-1313](https://lablup.atlassian.net/browse/FR-1313))
Fix a rendering bug in ChatMessageContent component where inline code was not properly displayed and was causing content below it to be hidden or overlapped.
- Inline code snippets were not rendering correctly in chat messages
- Code content was being wrapped in unnecessary Flex containers
- Content below inline code was being hidden or overlapped
- Poor visual distinction between inline code and code blocks
- Remove unnecessary Flex wrapper for inline code
- Apply proper styling for single-line inline code (background, border, padding)  
- Add overflow handling for code blocks with `renderPre` callback
- Improve visual distinction between inline and block code
- Added `renderPre` callback with overflow auto styling
- …
=> feat(FR-1313): improve inline code rendering and styling in ChatMessageContent

react/src/components/Chat/ChatCard.tsx
Resolves #4052 ([FR-1320](https://lablup.atlassian.net/browse/FR-1320))
Fixes Chat system prompt compatibility issue with vision models by preventing empty system prompt from being sent in API requests.
- Modified react/src/components/Chat/ChatCard.tsx to use undefined instead of empty string for system prompt when no agent is selected
- This ensures the system field is omitted from the API request payload entirely when empty
When no agent is selected in the Chat feature, an empty string was being sent as the system prompt parameter, causing compatibility issues with certain AI models like Llama 3 Vision which throw errors when receiving empty system prompts.
[FR-1320]: https://lablup.atlassian.net/browse/FR-1320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHV …
=> fix(FR-1320): prevent sending empty system prompt in Chat API requests

.cspell.json, packages/backend.ai-ui/src/components/BAICard.stories.tsx
Resolves #4053 ([FR-1321](https://lablup.atlassian.net/browse/FR-1321))
This PR adds a comprehensive Storybook file for the BAICard component, showcasing various configurations and usage patterns. The stories demonstrate different card states including:
- Default card appearance
- Status variants (default, success, warning, error)
- Cards with extra content and buttons
- Tab integration
- Size variations
- Loading states
- Hoverable and borderless options
- Custom styling capabilities
Additionally, adds "hoverable" to the cspell dictionary to prevent spell check errors.
`pnpm run storybook` in /packages/backend.ai-ui
**Checklist:**
[FR-1321]: https://lablup.atlassian.net/browse/FR-1321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FR-1321): add comprehensive Storybook stories for BAICard component

packages/backend.ai-ui/package.json, packages/backend.ai-ui/setupTests.ts, packages/backend.ai-ui/src/components/BAIFlex.test.tsx, packages/backend.ai-ui/src/components/__snapshots__/BAIFlex.test.tsx.snap, pnpm-lock.yaml, react/tsconfig.json
Resolves #4069 ([FR-1331](https://lablup.atlassian.net/browse/FR-1331))
This PR sets up Jest testing environment to support testing of React components in the backend.ai-ui package, specifically for the BAIFlex component.
The backend.ai-ui package needs proper testing infrastructure to ensure component reliability and maintainability. This includes setting up Jest with proper DOM testing capabilities and implementing comprehensive tests for the BAIFlex component.
* Configure Jest testing environment with jsdom support in package.json
* Add setupTests.ts file with jest-dom extensions
* Implement comprehensive unit tests for BAIFlex component with various scenarios:
- Default render
- Custom props (direction, wrap, justify, align, gap, style)
- Children components
* Move and update test …
=> feat(FR-1331): setup Jest testing environment for BAIFlex component

src/components/backend-ai-dialog.ts
https://lablup.atlassian.net/browse/FR-1218
Resolves #3916 (FR-1218)
This PR adds a fallback variable `--header-background-color` to the dialog header styling, ensuring proper background color rendering when the primary token variables are not available.
**Checklist:**
=> feat(FR-1218): Add a css custom variable for backend-ai-dialog title.

pnpm-lock.yaml, react/craco.config.js, react/package.json
Resolves #4024 ([FR-1303](https://lablup.atlassian.net/browse/FR-1303))
This PR fixes development environment warnings by updating the outdated caniuse-lite dependency and resolving webpack dev server deprecation warnings.
- ✅ Updated `caniuse-lite` to version `1.0.30001731` in react/package.json to eliminate "7 months old" browser data warning
- ✅ Modified `craco.config.js` to replace deprecated `onBeforeSetupMiddleware` and `onAfterSetupMiddleware` with the new `setupMiddlewares` option
- ✅ Updated pnpm-lock.yaml to reflect the latest caniuse-lite version across all dependencies
- Eliminates console noise during development
- Ensures compatibility with future webpack-dev-server versions
- Maintains all existing development functionality
[FR-1303]: …
=> fix(FR-1303): update caniuse-lite and resolve webpack dev server deprecation warnings

react/src/pages/ComputeSessionListPage.tsx
This PR replaces the usage of `useUpdatableState` with the more specific `useFetchKey` hook in the ComputeSessionListPage component. The change simplifies the code by using a dedicated hook for managing fetch key state.
=> fix(FR-1351): replace useUpdatableState with useFetchKey in ComputeSessionListPage

react/src/components/Chat/ChatCard.tsx
Moved the try block to wrap the entire function body in the `useModels` query function. This ensures that any errors occurring during the function execution, including those from conditional checks and URL creation, are properly caught and handled by the error handling mechanism.
=> fix(FR-1352): catch baseURL check errors in useModels

react/src/components/FolderCreateModal.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/th.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json
Resolves #4098 ([FR-1346](https://lablup.atlassian.net/browse/FR-1346))
- Add help text for user type when creating model folders in non-exclusive projects
- Update conditional logic to always show appropriate help text based on folder type and project context
- Add new i18n key `CreateModelFolderOnlyInExclusiveProject` for user type model folders
- Fix missing descriptive text issue in FolderCreateModal
When creating folders in the FolderCreateModal, descriptive text was missing for user type folders, particularly when dealing with model store scenarios. Users should see helpful guidance text even when the folder type is "user", but it wasn't appearing.
- **Fixed conditional logic**: Updated the help text display logic to show appropriate messages for both `user` and `project` folder …
=> fix(FR-1346): show descriptive text for model store folder creation

packages/backend.ai-ui/src/helper/index.ts, react/src/components/BaseResourceItem.tsx, react/src/components/MyResource.tsx, react/src/components/MyResourceWithinResourceGroup.tsx
Resolves #4101 ([FR-1348](https://lablup.atlassian.net/browse/FR-1348))
- Fix incorrect RAM unit display in My/Total Resource panels
- Move RAM binary unit conversion from data processing to display layer in `BaseResourceItem`
- Remove duplicate binary conversion in `MyResourceWithinResourceGroup` component
- Ensure consistent RAM unit display (MB, GB, etc.) across resource monitoring components
There was an issue with incorrect RAM unit display in the My/Total Resource panels within resource groups. RAM values were being converted to binary units (MB, GB, etc.) at the wrong layer, which caused inconsistent or incorrect unit displays in the resource monitoring UI.
- **Moved conversion logic:** Relocated RAM binary unit conversion from the data processing layer to the display layer in …
=> fix(FR-1348): correct RAM unit display in resource monitoring

react/src/components/ServiceLauncherPageContent.tsx, react/src/components/VFolderTable.tsx, react/src/components/VFolderTableFormItem.tsx, react/src/pages/SessionLauncherPage.tsx
Resolves #4121 ([FR-1358](https://lablup.atlassian.net/browse/FR-1358))
Fixed a structural issue in the VFolderTable component that caused auto-mounted folder lists to be incorrectly filtered by the display rowFilter, resulting in empty arrays being passed to parent components via the onChangeAutoMountedFolders callback.
- **Permission-based filtering**: Separated into , , and 
- **Auto-mount folder extraction**: Now only depends on permission-filtered folders, not display filters
- **Display filtering**: Isolated to  with both external rowFilter and search keywords
- Renamed  prop to  to clarify its purpose as a display-only filter
- Updated prop destructuring to maintain backward compatibility
-  →  (clearer purpose)
-  →  (more concise)
This fix ensures that auto-mounted folders …
=> refactor(FR-1358): separate filtering concerns in VFolderTable to fix auto-mount detection

react/src/components/BaseResourceItem.tsx
Resolves #4123 ([FR-1359](https://lablup.atlassian.net/browse/FR-1359))
This PR adds a conditional check to only render the accelerator section when there are visible accelerators. Previously, the section would always render even when empty, creating unnecessary visual space.
Before
After
**Checklist:**
[FR-1359]: https://lablup.atlassian.net/browse/FR-1359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(FR-1359): hide empty accelerator resource section in BaseResourceItem

e2e/.eslintrc.json, e2e/utils/classes/FolderCreationModal.ts, e2e/utils/test-util.ts, e2e/vfolder.test.ts
resolves #4086 [(FR-1337)](https://lablup.atlassian.net/browse/FR-1337) (FR-1338)
This PR adds an ESLint configuration file for the e2e test directory and updates the folder creation tests to support Auto Mount folders. It also fixes several UI label references in the test utilities to match the actual UI text.
Changes include:
- Added new `.eslintrc.json` configuration for e2e tests
- Updated label references in `FolderCreationModal.ts` from "Model" to "Models" and "Read Only" to "Read only"
- Added a new method `getAutoMountUsageModeRadio()` to support Auto Mount folder testing
- Fixed folder name references in trash verification functions to use the actual folder name
- Added a test case for Auto Mount vFolder creation
- Added logic to handle cleanup of Auto Mount folders …
=> e2e(FR-1337): refactor brokend e2e test of vfolder and add auto mount vfolder test case

e2e/session.test.ts, e2e/utils/classes/StartPage.ts
resolves #4088 (FR-1337) (FR-1341)
This PR introduces a new `StartPage` class that implements the Page Object Model pattern for E2E tests. The class encapsulates the functionality of the Start page, providing methods to navigate to the page and interact with its various card elements.
The implementation:
- Creates a new `StartPage` class with methods to access different cards (Interactive Session, Batch Session, etc.)
- Refactors existing session tests to use this new class
- Improves test readability by abstracting page interaction details
**Checklist:**
=> e2e(FR-1337): refactor broken e2e test of session and create a class for start page

packages/backend.ai-ui/src/components/BAIUnmountAfterClose.tsx, packages/backend.ai-ui/src/components/index.ts, react/src/components/ComputeSessionNodeItems/ConnectedKernelList.tsx, react/src/components/FolderInvitationResponseModalOpener.tsx, react/src/components/RecentlyCreatedSession.tsx, react/src/components/SessionDetailAndContainerLogOpenerLegacy.tsx, react/src/pages/EndpointDetailPage.tsx
Resolves #4094 ([FR-1343](https://lablup.atlassian.net/browse/FR-1343))
This PR refactors the `UnmountAfterClose` component to improve its organization and reusability within the codebase. The component has been moved from the React-specific directory to the shared backend.ai-ui package and renamed to follow the BAI naming convention.
- **Moved** `UnmountAfterClose` component from `react/src/components/` to `packages/backend.ai-ui/src/components/`
- **Renamed** component from `UnmountAfterClose` to `BAIUnmountAfterClose`
- **Enhanced** component interface to be more generic and work with both Modal and Drawer components
- **Added** proper type guards for safe handling of Modal and Drawer props
- **Updated** all import statements throughout the codebase to use the new component location …
=> feat(FR-1343): BAIUnmountAfterClose in BUI

react/src/components/StorageStatusPanelCard.tsx
Resolves #4131 ([FR-1363](https://lablup.atlassian.net/browse/FR-1363))
Update the StorageStatusPanelCard component to use the newly introduced BAIRowWrapWithDividers component instead of the traditional Ant Design Row/Col layout. This change improves the visual consistency and provides better responsive behavior with automatic dividers between items.
|  Before  | After    |
|---------|--------|
|     ![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/XqC2uNFuj0wg8I60sMUh/84989ee0-7ab9-4f2d-8f74-cc7687f9bc0b.png)          |    ![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/XqC2uNFuj0wg8I60sMUh/cf72f225-9165-42f3-9516-303d16126d1d.png) |
- Replaced Ant Design Row/Col layout with BAIRowWrapWithDividers component
- Configured proper spacing …
=> refactor(FR-1363): migrate StorageStatusPanelCard to BAIRowWrapWithDividers

react/src/helper/index.tsx
resolves #4133 [(FR-1364)](https://lablup.atlassian.net/browse/FR-1364)
remove `throw error` on `onerror` in `fetchEventSource` to `fetchEventSource` can retry automatically.
**how to test**
1. go to maintenance page
2. click `Rescan Images`
=> fix(FR-1364): remove thorw error on onerror in eventSource to retry automatically

.claude/commands/create-pr-stack-for-stage.md, .claude/commands/fill-out-i18n.md, backend.ai-webui.code-workspace
Resolves #4078 ([FR-1335](https://lablup.atlassian.net/browse/FR-1335))
Implements a new Claude Code slash command `/fill-out-i18n` to automate the internationalization workflow for [Backend.AI](http://Backend.AI) WebUI, with improved Jira integration documentation.
- Detects new Korean/English i18n keys from git changes
- Reviews and improves text quality with interactive suggestions
- Generates translations for 20+ languages using Claude AI
- Updates locale files atomically with jq optimization
- Added `.claude/commands/fill-out-i18n.md` with comprehensive command documentation
- Supports stage/commit/branch analysis modes
- Includes quality review for Korean/English text improvements
- Optimized for performance with zero-overhead design
- **NEW**: Improved …
=> feat(FR-1335): add automated i18n translation Claude Code slash command

react/src/components/AgentSummaryList.tsx, react/src/components/ResourceGroupSelectForCurrentProject.tsx, react/src/hooks/useCurrentProject.tsx, react/src/hooks/useResourceLimitAndRemaining.tsx
Resolves [FR-1384](https://lablup.atlassian.net/browse/FR-1384)
When either `scalingGroup.list` or `vfolder.list_hosts` API calls fail, the entire Promise.all chain throws an error, preventing the UI from displaying any available data and potentially causing the entire page to crash.
- Replace `Promise.all` with `Promise.allSettled` to handle failures gracefully
- Return `undefined` for failed API calls while preserving successful data
- Update dependent components to handle undefined values appropriately
- Rename variables for clarity (`allSftpScalingGroups` → `sftpScalingGroups`, `resourceGroups` → `nonSftpScalingGroups`)
This change improves the resilience of the UI when backend services are partially unavailable, allowing users to continue working with available resources rather than …
=> fix(FR-1384): handle backend API failures gracefully with Promise.allSettled

react/src/components/ComputeSessionNodeItems/ConnectedKernelList.tsx
resolves #4185 (FR-1406)
Removed the explicit `pagination={false}` prop from the Table component in ConnectedKernelList, as it's redundant when pagination is already disabled by default.
=> fix(FR-1406):fix to enalbe pagination for ConnectedKernelList compnent

react/src/pages/ServingPage.tsx
Resolves ([FR-1403](https://lablup.atlassian.net/browse/FR-1403))
This PR improves the lifecycle stage filter logic for active serving instances in the ServingPage component.
- Updated lifecycle stage filter from specific inclusion logic (`lifecycle_stage == "created" | lifecycle_stage == "destroying"`) to exclusion logic (`lifecycle_stage != "destroyed"`)
- This provides better coverage of all non-destroyed lifecycle stages when filtering for "active" serving instances
- Users will see a more comprehensive view of active serving instances
- Improves accuracy of filtering serving instances by their lifecycle stage
- Better alignment with the intended behavior of showing all active (non-destroyed) services
**Checklist:**
[FR-1403]: …
=> fix(FR-1403): improve lifecycle stage filter logic for active serving instances

.claude/commands/create-jira-issue.md, .claude/commands/create-pr-stack-for-stage.md, .claude/commands/enhance-component-docs.md, .claude/commands/fill-out-i18n.md, .claude/commands/improve-release-note.md, .claude/commands/update-storybook-autodoc.md
Adds YAML frontmatter to all Claude command files to improve command discoverability and functionality:
- Added `description` fields to provide clear purpose for each command
- Specified `argument-hint` for commands that accept arguments
- Set `model: claude-sonnet-4-20250514` for all commands
- Fixed a formatting issue in create-jira-issue.md where quotes were incorrectly surrounding $ARGUMENTS
**Checklist:**
=> chore: add YAML frontmatter to Claude command files

react/src/components/ServiceLauncherPageContent.tsx
Resolves #4153 ([FR-1378](https://lablup.atlassian.net/browse/FR-1378))
Improves error handling logic in the service update flow to properly display server error messages when endpoint modification fails.
- Removed unused legacy mutation function `legacyMutationToUpdateService`
- Simplified conditional logic by removing `baiClient.supports('modify-endpoint')` check
- Streamlined error handling to ensure server error messages are properly displayed
- Consolidated success/error message flow for better user experience
**Type:** Bug Fix
**Component:** Service Launcher
[FR-1378]: https://lablup.atlassian.net/browse/FR-1378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(FR-1378): improve error handling logic in service update flow

react/src/components/ServiceLauncherPageContent.tsx
Resolves #4233 ([FR-1435](https://lablup.atlassian.net/browse/FR-1435))
This PR modifies the vfolder selection filter in the service launcher to exclude group-owned vfolders. Now, only model vfolders that are ready and not owned by a group will be available for selection when launching a service.
**Checklist:**
[FR-1435]: https://lablup.atlassian.net/browse/FR-1435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FR-1435): exclude project type folder from folder selector of service creation page.

react/src/components/ResourceAllocationFormItems.tsx
Resolves #4194 ([FR-1414](https://lablup.atlassian.net/browse/FR-1414))  
This PR modifies the resource allocation form to properly handle the `allowCustomResourceAllocation` configuration setting. Instead of hiding the entire card when custom allocation is disabled, it now:
1. Always shows the resource allocation card
2. Hides specific form items (CPU, mem, cluster size) when custom allocation is disabled
3. Only sets the allocation preset to 'custom' when custom allocation is allowed
This approach provides better UX by maintaining consistent layout while respecting configuration settings.
[FR-1414]: https://lablup.atlassian.net/browse/FR-1414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FR-1414): allow shmem adjustment when allowCustomResourceAllocation is disabled

react/src/components/InviteFolderSettingModal.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/th.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json
Resolves #4169 ([FR-1386](https://lablup.atlassian.net/browse/FR-1386))
Updates the folder sharing modal title from "Modify Permissions" to "Share Folder" for improved clarity and better user understanding.
- Changed modal title in `InviteFolderSettingModal.tsx` from "Modify Permissions" to "Share Folder"
- Removed unused "ModifyPermissions" translation key from all 21 language files
- Improves user experience by using more descriptive and accurate modal title
[FR-1386]: https://lablup.atlassian.net/browse/FR-1386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> style(FR-1386): change invite folder modal title from 'Modify Permissions' to 'Share Folder'

Makefile, packages/backend.ai-ui/vite.config.ts
Resolves [FR-1434](https://lablup.atlassian.net/browse/FR-1434)
This PR addresses two important improvements to the project's Makefile:
1. **Security Enhancement in Clean Target**:
- Fixed the `clean` target to use explicit paths instead of `cd` commands
- Prevents risk of deleting unintended directories if paths don't exist or fail
- Makes the clean process safer and more predictable
2. **Cross-Platform Compatibility**:
- Replaced `uuidgen` dependency with `openssl rand` for random ID generation
- Ensures build process works reliably in minimal Linux environments
- Maintains backward compatibility while improving portability
These changes improve the robustness and security of the build process without breaking existing functionality.
**Checklist:**
[FR-1434]: …
=> fix(FR-1434): improve Makefile security and cross-platform compatibility

packages/backend.ai-ui/src/components/BAIGraphQLPropertyFilter.stories.tsx, packages/backend.ai-ui/src/components/BAIGraphQLPropertyFilter.tsx, packages/backend.ai-ui/src/components/index.ts
Resolves #4143 ([FR-1370](https://lablup.atlassian.net/browse/FR-1370))
This PR introduces a new `BAIGraphQLPropertyFilter` component that provides an advanced filtering interface for GraphQL-based [Backend.AI](http://Backend.AI) applications. The component allows users to construct complex filter conditions that can be directly used in GraphQL queries.
Key features:
- Support for various GraphQL filter types (String, Number, Boolean, Enum)
- Flexible combination modes (AND/OR) for multiple filter conditions
- Rich set of operators (eq, ne, contains, startsWith, endsWith, gt, gte, lt, lte, in, notIn)
- Type-safe filtering with automatic operator suggestions based on property types
- Bidirectional conversion between UI conditions and GraphQL filter objects
- Validation rules and …
=> feat(FR-1370): Property filter component for GraphQL v2 filter type

electron-app/package.json, index.html, manifest.json, package.json, react/package.json, version.json
Updates the package version from 25.12.0-alpha.0 to 25.14.0-alpha.0 across all configuration files. Also updates the build number from 6785 to 6927 and revision hash in version.json.
=> chore: Update alpha version index to 25.14.0-alpha.0

packages/backend.ai-ui/package.json, packages/backend.ai-ui/src/components/fragments/BAISessionAgentIds.tsx, packages/backend.ai-ui/src/locale/de.json, packages/backend.ai-ui/src/locale/el.json, packages/backend.ai-ui/src/locale/en.json, packages/backend.ai-ui/src/locale/es.json, packages/backend.ai-ui/src/locale/fi.json, packages/backend.ai-ui/src/locale/fr.json, packages/backend.ai-ui/src/locale/id.json, packages/backend.ai-ui/src/locale/it.json, packages/backend.ai-ui/src/locale/ja.json, packages/backend.ai-ui/src/locale/ko.json, packages/backend.ai-ui/src/locale/mn.json, packages/backend.ai-ui/src/locale/ms.json, packages/backend.ai-ui/src/locale/pl.json, packages/backend.ai-ui/src/locale/pt-BR.json, packages/backend.ai-ui/src/locale/pt.json, packages/backend.ai-ui/src/locale/ru.json, packages/backend.ai-ui/src/locale/th.json, packages/backend.ai-ui/src/locale/tr.json, packages/backend.ai-ui/src/locale/vi.json, packages/backend.ai-ui/src/locale/zh-CN.json, packages/backend.ai-ui/src/locale/zh-TW.json, pnpm-lock.yaml, react/src/components/ComputeSessionNodeItems/SessionSlotCell.tsx, react/src/components/SessionDetailContent.tsx, react/src/components/SessionNodes.tsx
Resolves #4218 ([FR-1425](https://lablup.atlassian.net/browse/FR-1425))
This PR adds a new `BAISessionAgentIds` component to improve the display of agent IDs in session details. The component:
- Shows a limited number of agent IDs inline (default: 3)
- Displays remaining IDs in a popover when clicked
- Includes a "Copy All" button for easy copying of all agent IDs
- Handles empty states gracefully
The component is integrated in both the session detail view and session nodes table, replacing the previous simple string display.
**Checklist:**
[FR-1425]: https://lablup.atlassian.net/browse/FR-1425?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FR-1425): implement BAISessionAgentIds component to improve agent display

react/src/components/ComputeSessionNodeItems/SessionReservation.tsx, react/src/components/SessionNodes.tsx
Resolves #4237 ([FR-1437](https://lablup.atlassian.net/browse/FR-1437))
Enhanced session display capabilities with owner information and improved date formatting for better user experience and administrative visibility.
- **SessionReservation.tsx**: Enhanced date display with Typography.Text components and added tooltips for better UX
- **SessionNodes.tsx**: Added owner email column display for superadmin users when [Backend.AI](http://Backend.AI) manager version 25.13.0+ is available
- Improved UI consistency with proper Typography components for session dates
- Date tooltips provide better context when viewing elapsed time
- Owner email visibility for superadmin users to better manage session ownership
- Conditional rendering based on user role and manager version compatibility
- …
=> feat(FR-1437): enhance session display with owner information and improved date formatting

react/src/components/MyResourceWithinResourceGroup.tsx, react/src/components/PendingSessionNodeList.tsx, react/src/components/SharedResourceGroupSelectForCurrentProject.tsx, react/src/components/TotalResourceWithinResourceGroup.tsx, react/src/index.tsx
Resolves #4247 ([FR-1445](https://lablup.atlassian.net/browse/FR-1445))
This PR renames `ResourceGroupSelectForCurrentProject` to `SharedResourceGroupSelectForCurrentProject` and adds a new `onChangeInTransition` prop to handle changes during transition state. The component now properly handles loading states and optimistic updates when changing resource groups.
In `PendingSessionNodeList`, the component now uses the global resource group state instead of maintaining its own local state, improving consistency across the application.
[FR-1445]: https://lablup.atlassian.net/browse/FR-1445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor(FR-1445): rename ResourceGroupSelectForCurrentProject to SharedResourceGroupSelectForCurrentProject and add onChangeInTransition

react/src/components/AgentList.tsx, react/src/components/AgentSummaryList.tsx, react/src/components/ContainerRegistryList.tsx, react/src/components/PendingSessionNodeList.tsx, react/src/components/StorageProxyList.tsx, react/src/components/UserCredentialList.tsx, react/src/components/UserNodeList.tsx, react/src/hooks/reactPaginationQueryOptions.tsx, react/src/pages/ComputeSessionListPage.tsx, react/src/pages/ServingPage.tsx, react/src/pages/VFolderNodeListPage.tsx
Resolves #4225 ([FR-1431](https://lablup.atlassian.net/browse/FR-1431))
This PR implements URL-based state persistence for pagination, filtering, and sorting across multiple list components. When users refresh the page, their current view state (including filters, sorting, and pagination) is now preserved.
`useDeferredQueryParams`​ had known bugs. To resolve this issue, we migrated to the stable hooks provided by the `use-query-params`​ library (`useQueryParams`​).
However, the  hooks have a limitation when used with  `useTransition`​, state changes don't occur within the transition, causing UI inconsistencies. To address this, we are following the same pattern used in other list page components throughout the codebase.
- **State Management**: Replaced  with  and  for persistent state …
=> fix(FR-1431): URL-based state persistence for pagination and filters

packages/backend.ai-ui/src/components/Table/index.ts, packages/backend.ai-ui/src/components/index.ts, react/package.json, react/src/components/MyResource.tsx, react/src/components/MyResourceWithinResourceGroup.tsx, react/src/components/TotalResourceWithinResourceGroup.tsx, react/src/hooks/useBAISetting.tsx
resolves #4262 (FR-1451)
This PR exports additional types and utility functions from the backend.ai-ui package to make them properly accessible to consuming applications:
1. Exports `BAITableColumnOverrideRecord` type from Table component
2. Exports utility functions `processMemoryValue` and `convertToNumber` from ResourceStatistics
3. Adds ESLint rule to prevent importing from internal paths (enforcing imports from the main entry point)
4. Updates import statements in components to use the proper exported paths:
- MyResource
- MyResourceWithinResourceGroup
- TotalResourceWithinResourceGroup
- useBAISetting
**Checklist:**
=> feat(FR-1451): add lint rule to restrict imports from backend.ai-ui

packages/backend.ai-ui/package.json, packages/backend.ai-ui/src/locale/.prettierrc, packages/backend.ai-ui/src/locale/de.json, packages/backend.ai-ui/src/locale/el.json, packages/backend.ai-ui/src/locale/en.json, packages/backend.ai-ui/src/locale/es.json, packages/backend.ai-ui/src/locale/fi.json, packages/backend.ai-ui/src/locale/fr.json, packages/backend.ai-ui/src/locale/id.json, packages/backend.ai-ui/src/locale/it.json, packages/backend.ai-ui/src/locale/ja.json, packages/backend.ai-ui/src/locale/ko.json, packages/backend.ai-ui/src/locale/mn.json, packages/backend.ai-ui/src/locale/ms.json, packages/backend.ai-ui/src/locale/pl.json, packages/backend.ai-ui/src/locale/pt-BR.json, packages/backend.ai-ui/src/locale/pt.json, packages/backend.ai-ui/src/locale/ru.json, packages/backend.ai-ui/src/locale/th.json, packages/backend.ai-ui/src/locale/tr.json, packages/backend.ai-ui/src/locale/vi.json, packages/backend.ai-ui/src/locale/zh-CN.json, packages/backend.ai-ui/src/locale/zh-TW.json, pnpm-lock.yaml
resolves #4254 (FR-1447)
This PR adds JSON sorting capabilities to the locale files in the backend.ai-ui package. It includes:
1. Added two Prettier plugins as dev dependencies:
- `@trivago/prettier-plugin-sort-imports` for sorting imports
- `prettier-plugin-sort-json` for sorting JSON keys
2. Created a `.prettierrc` configuration file in the locale directory to enable JSON sorting with:
```json
{
"plugins": ["prettier-plugin-sort-json"],
"jsonRecursiveSort": true
}
```
3. Applied sorting to all locale JSON files (de.json, el.json, en.json, etc.), organizing translation keys alphabetically for better maintainability and easier comparison between language files.
The sorted JSON files maintain the same content but with a consistent ordering pattern, making it easier to locate and manage …
=> feat(FR-1447): add JSON sort plugin to prettier in the BUI project

packages/backend.ai-ui/src/components/ResourceStatistics.tsx, packages/backend.ai-ui/src/locale/de.json, packages/backend.ai-ui/src/locale/el.json, packages/backend.ai-ui/src/locale/en.json, packages/backend.ai-ui/src/locale/es.json, packages/backend.ai-ui/src/locale/fi.json, packages/backend.ai-ui/src/locale/fr.json, packages/backend.ai-ui/src/locale/id.json, packages/backend.ai-ui/src/locale/it.json, packages/backend.ai-ui/src/locale/ja.json, packages/backend.ai-ui/src/locale/ko.json, packages/backend.ai-ui/src/locale/mn.json, packages/backend.ai-ui/src/locale/ms.json, packages/backend.ai-ui/src/locale/pl.json, packages/backend.ai-ui/src/locale/pt-BR.json, packages/backend.ai-ui/src/locale/pt.json, packages/backend.ai-ui/src/locale/ru.json, packages/backend.ai-ui/src/locale/th.json, packages/backend.ai-ui/src/locale/tr.json, packages/backend.ai-ui/src/locale/vi.json, packages/backend.ai-ui/src/locale/zh-CN.json, packages/backend.ai-ui/src/locale/zh-TW.json, react/src/components/MyResourceWithinResourceGroup.tsx, react/src/components/ResourceAllocationFormItems.test.ts, react/src/components/ResourceAllocationFormItems.tsx, react/src/hooks/useResourceLimitAndRemaining.tsx
This PR addresses issues with resource allocation validation and type safety in the React components:
1. Added null coalescing operators (`?? 0`) in `MyResourceWithinResourceGroup.tsx` to handle potentially undefined values when accessing resource usage data
2. Updated `RemainingSlots` type to make `cpu` and `mem` properties optional, and allow `undefined` values in the accelerators map
3. Fixed a potential null reference in `ResourceAllocationFormItems.tsx` by adding a fallback value when `remaining.mem` is undefined
4. Removed unnecessary lodash import in the test file
5. Modified the resource limit calculation logic to return `undefined` instead of `Number.MAX_SAFE_INTEGER` when no valid limits are found
These changes improve type safety and prevent potential runtime errors when …
=> fix(FR-1455): correct the incorrect values shown on the dashboard

react/src/pages/SessionLauncherPage.tsx
Resolves [FR-1479](https://lablup.atlassian.net/browse/FR-1479)
Fix a bug where shmem (shared memory) values are being automatically adjusted during session creation API request, regardless of the `enabledAutomaticShmem` setting.
- Remove forced automatic shmem adjustment logic from SessionLauncherPage
- Remove unused `compareNumberWithUnits` import
- Ensure shmem values are passed as configured by the user
The ResourceAllocationFormItems component properly handles automatic shmem adjustment through the `enabledAutomaticShmem` flag. However, SessionLauncherPage was applying automatic adjustment unconditionally during the API request, overriding the user's preference and causing unexpected behavior.
[FR-1479]: https://lablup.atlassian.net/browse/FR-1479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY …
=> fix(FR-1479): remove forced automatic shmem adjustment during session creation

react/src/components/PrivacyPolicyModal.tsx
Resolves #4292 ([FR-1483](https://lablup.atlassian.net/browse/FR-1483))
This PR fixes a bug in the `PrivacyPolicyModal` component where the query key was incorrectly set to `'termsOfService'` instead of `'privacyPolicy'`. This ensures that the privacy policy content is properly cached and retrieved with the correct key.
**Checklist:**
[FR-1483]: https://lablup.atlassian.net/browse/FR-1483?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(FR-1483): correct queryKey from 'termsOfService' to 'privacyPolicy'

react/src/components/ComputeSessionNodeItems/SessionSlotCell.tsx, react/src/components/SessionDetailContent.tsx, react/src/components/SessionUsageMonitor.tsx, react/src/hooks/useSessionNodeLiveStat.tsx, resources/i18n/ko.json
Resolves #4216 ([FR-1424](https://lablup.atlassian.net/browse/FR-1424))
This PR enhances the session resource usage monitoring by:
1. Fixing memory usage calculation to use occupied slots instead of capacity
2. Implementing aggregated live stats across all kernel nodes instead of just the main node
3. Improving UI layout for session details with better word breaks
4. Refining Korean translations for agent-related terms
The changes ensure that resource usage percentages are calculated correctly by comparing current usage against the allocated resources rather than total capacity, providing more accurate monitoring information.
**Checklist:**
[FR-1424]: https://lablup.atlassian.net/browse/FR-1424?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FR-1424): update to calculate liveStat and capacity per session

react/src/components/ImageNodeSimpleTag.tsx
Resolves #4296 ([FR-1487](https://lablup.atlassian.net/browse/FR-1487))
Refactor the ImageNodeSimpleTag component to use BAIFlex layout container for better visual organization and consistent spacing.
- Replace fragment wrapper with BAIFlex container for better layout control
- Add consistent spacing between image metadata elements (icon, base image name, version, architecture)  
- Improve divider positioning with proper margin control
- Enhance tag spacing by removing default margins
- Maintain existing functionality while improving visual presentation
[FR-1487]: https://lablup.atlassian.net/browse/FR-1487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> style(FR-1487): improve layout and spacing for ImageNodeSimpleTag component

packages/backend.ai-ui/src/components/BAIStatistic.tsx
Resolves #4281 ([FR-1474](https://lablup.atlassian.net/browse/FR-1474))
This PR fixes the progress calculation in the BAIStatistic component by adding a check for `total === Infinity`. When the total value is Infinity, the progress will now correctly return 0 instead of attempting to calculate a progress value.
**Checklist:**
[FR-1474]: https://lablup.atlassian.net/browse/FR-1474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(FR-1474): handle infinity values in resource progress calculation

react/src/components/ImageEnvironmentSelectFormItems.tsx, react/src/components/SessionFormItems/ResourceAllocationFormItems.test.ts, react/src/components/SessionFormItems/ResourceAllocationFormItems.tsx, react/src/helper/index.test.tsx, react/src/hooks/useBackendAIImageMetaData.test.tsx
Resolves #2781 ([FR-55](https://lablup.atlassian.net/browse/FR-55))
This PR enhances accelerator selection by using the `supported_accelerators` field from images instead of relying on accelerator limits. The implementation:
1. Adds `supported_accelerators` to the GraphQL query in ImageEnvironmentSelectFormItems
2. Replaces the previous accelerator filtering logic with a new approach that:
- Checks if an accelerator type is supported by the image using the `supported_accelerators` field
- Supports wildcard matching with '*' or empty string to indicate all accelerators are supported
- Allows prefix matching for accelerator types
- Maintains backward compatibility with manual image input
This change improves the user experience by showing only relevant accelerator options based on what the …
=> feat(FR-55): support ai.backend.accelerators image label's * value

data/schema.graphql, packages/backend.ai-ui/src/components/provider/BAIClientProvider/index.ts, packages/backend.ai-ui/src/components/provider/BAIClientProvider/types.ts, packages/backend.ai-ui/src/hooks/index.ts, packages/backend.ai-ui/src/hooks/useViewer.ts, react/src/hooks/backendai.test.tsx, react/src/hooks/backendai.tsx
Resolves #4279 ([FR-1472](https://lablup.atlassian.net/browse/FR-1472))
Implements GraphQL `viewer` query functionality to handle current user information and determine user roles.
- Added `Viewer` type to GraphQL schema with user information fields
- Created `useViewer` hook for accessing current user data via GraphQL
- Enhanced BAI Client Provider with viewer-related hooks and type definitions  
- Integrated viewer functionality into React hooks system
This implementation is based on the backend changes from https://github.com/lablup/backend.ai/pull/5728, which introduces the Viewer functionality for retrieving authenticated user information.
[FR-1472]: https://lablup.atlassian.net/browse/FR-1472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
=> feat(FR-1472): implement GraphQL viewer query for current user information

src/components/backend-ai-import-view.ts
Resolves #4276 ([FR-1469](https://lablup.atlassian.net/browse/FR-1469))
This PR fixes the URL host comparison logic in the import view to support GitHub-like domains such as `codeland.github.com`. The current implementation uses exact string matching (`=== 'github.com'`) which fails to recognize GitHub-like domains that contain `github.com` as part of their hostname.
- Modified GitHub host detection from exact matching to inclusive checking using `.endWith('github.com')`
- Applied the change to all 3 occurrences in `src/components/backend-ai-import-view.ts` (lines 451, 464, 487)
- This allows importing repositories from domains like `codeland.github.com` while maintaining backward compatibility
- **Before**: Only exact `github.com` domains were recognized for GitHub import flow
- …
=> fix(FR-1469): use inclusive checking for GitHub host detection

packages/backend.ai-ui/src/components/Table/BAITable.tsx, packages/backend.ai-ui/src/components/baiClient/FileExplorer/BAIFileExplorer.tsx, packages/backend.ai-ui/src/components/baiClient/FileExplorer/DragAndDrop.tsx, packages/backend.ai-ui/src/components/baiClient/FileExplorer/ExplorerActionControls.tsx, packages/backend.ai-ui/src/components/baiClient/FileExplorer/hooks.ts, packages/backend.ai-ui/src/locale/de.json, packages/backend.ai-ui/src/locale/el.json, packages/backend.ai-ui/src/locale/en.json, packages/backend.ai-ui/src/locale/es.json, packages/backend.ai-ui/src/locale/fi.json, packages/backend.ai-ui/src/locale/fr.json, packages/backend.ai-ui/src/locale/id.json, packages/backend.ai-ui/src/locale/it.json, packages/backend.ai-ui/src/locale/ja.json, packages/backend.ai-ui/src/locale/ko.json, packages/backend.ai-ui/src/locale/mn.json, packages/backend.ai-ui/src/locale/ms.json, packages/backend.ai-ui/src/locale/pl.json, packages/backend.ai-ui/src/locale/pt-BR.json, packages/backend.ai-ui/src/locale/pt.json, packages/backend.ai-ui/src/locale/ru.json, packages/backend.ai-ui/src/locale/th.json, packages/backend.ai-ui/src/locale/tr.json, packages/backend.ai-ui/src/locale/vi.json, packages/backend.ai-ui/src/locale/zh-CN.json, packages/backend.ai-ui/src/locale/zh-TW.json, react/src/components/FolderExplorer.tsx, react/src/components/FolderExplorerHeader.tsx
resolves #4077 ([FR-1334](https://lablup.atlassian.net/browse/FR-1334))
This PR adds drag and drop file upload functionality to the file explorer. Users can now drag files directly into the file explorer area to upload them, providing a more intuitive and convenient way to manage files.
Key changes:
- Created a new `DragAndDrop` component that appears when files are dragged over the file explorer
- Extracted file upload logic into a reusable hook `useUploadVFolderFiles` to avoid code duplication
- Added event listeners to detect drag and drop events at the document level
- Added translations for the drag and drop feature in all supported languages
- Simplified the file upload process in the `ActionItems` component by using the new hook
**Checklist:**
[FR-1334]: …
=> feat(FR-1334): implement drag-and-drop file upload functionality

src/components/backend-ai-session-list.ts
This PR adds a null check using the optional chaining operator (`?.`) when mapping over `tmpSessionStatus.scheduler.failed_predicates` to prevent potential errors if `failed_predicates` is undefined.
**Checklist:**
=> fix: can't access property "map", `failed_predicates` is undefined

packages/backend.ai-ui/src/components/fragments/BAIImportArtifactModal.tsx, packages/backend.ai-ui/src/locale/ko.json, packages/backend.ai-ui/src/locale/ms.json, packages/backend.ai-ui/src/locale/pl.json, packages/backend.ai-ui/src/locale/pt-BR.json, packages/backend.ai-ui/src/locale/pt.json, packages/backend.ai-ui/src/locale/ru.json, packages/backend.ai-ui/src/locale/th.json, packages/backend.ai-ui/src/locale/tr.json, packages/backend.ai-ui/src/locale/zh-CN.json, packages/backend.ai-ui/src/locale/zh-TW.json, react/src/pages/ReservoirArtifactDetailPage.tsx, react/src/pages/ReservoirPage.tsx
=> feat(FR-1495): implement progress bar with bai notifiacation

packages/backend.ai-ui/src/components/fragments/BAIImportArtifactModal.tsx, react/src/pages/ReservoirArtifactDetailPage.tsx
=> feat(FR-1496): update pulling artifact edge after import revisions

react/src/components/FolderExplorer.tsx, src/components/backend-ai-folder-explorer.ts, src/types/backend-ai-console.d.ts
Resolves #4330 ([FR-1511](https://lablup.atlassian.net/browse/FR-1511))
This PR fixes two critical issues in the FolderExplorer modal:
1. Non-functional filebrowser and SFTP server creation buttons
2. Incompatibility with ID-based managers due to vfolder name-based mounting
- Added hidden `backend-ai-folder-explorer` component to FolderExplorer React component to restore button functionality
- Implemented mount-by-id support in `backend-ai-folder-explorer.ts` for both filebrowser and SFTP server creation
- Added `mount_ids` field to SessionResources type definition
The fix checks for backend support of `mount-by-id` capability and uses:
- `mount_ids` array with vfolder IDs when supported
- Falls back to `mounts` array with vfolder names for backward compatibility
This ensures …
=> fix(FR-1511): fix FolderExplorer modal buttons and implement mount-by-id support

react/src/components/SessionFormItems/ResourceAllocationFormItems.tsx
resolves #4338 (FR-1517)
This PR fixes an issue in the `ResourceAllocationFormItems` component where it was not properly handling undefined values for `acceleratorSlotsInRG` and `currentImage`. The changes add null/undefined checks to prevent potential runtime errors.
Key changes:
- Added a guard clause in the `supportedAcceleratorTypesInRGByImage` useMemo to return undefined when required dependencies are missing
- Updated conditional checks to use optional chaining (`?.length`) when accessing properties of potentially undefined objects
**Checklist:**
=> fix(FR-1517): fix to ensure the gpu accelerator value is loaded correctly

react/src/components/BAIComputeSessionNodeNotificationItem.tsx, react/src/components/BAINodeNotificationItem.tsx
Resolves #4306 ([FR-1494](https://lablup.atlassian.net/browse/FR-1494))
Refactored session notification component to improve UX for session creation and app launch. Created a dedicated `BAIComputeSessionNodeNotificationItem` component to handle compute session notifications with better state management and auto-refresh capabilities.
- Created new `BAIComputeSessionNodeNotificationItem.tsx` component with:
- Auto-refresh interval based on session status
- Automatic cleanup when session terminates
- Improved status tracking and UI feedback
- Refactored `BAINodeNotificationItem.tsx` to use the new dedicated component
- Fixed ESLint warnings and improved code organization
Per FR-1494, this improves the user experience for session creation and app launch by providing better real-time feedback …
=> feat(FR-1494): refactor session notification with dedicated component for improved UX

index.html, react/craco.config.js, src/backend-ai-app.ts
Resolves #4294 ([FR-1486](https://lablup.atlassian.net/browse/FR-1486))
- Fixed plugin import path in `backend-ai-app.ts` to conditionally use the correct path based on environment
- Added dynamic NODE_ENV injection for development environment in `index.html`
- Removed hardcoded `process.env` from `index.html` and moved it to be injected during development
- Implemented template content replacement in `craco.config.js` to inject development environment variables
- Run the application in development mode and verify plugins load correctly
- Build the application and verify plugins load correctly in production mode
- Check console for any plugin loading errors in both environments
This change ensures plugins are loaded from the correct path in both development and production environments, …
=> fix(FR-1486): correct plugin import path from relative to parent directory

react/src/components/Chat/EndpointSelect.tsx, react/src/pages/ChatPage.tsx, src/lib/backend.ai-client-esm.ts
Resolves #4341 ([FR-1519](https://lablup.atlassian.net/browse/FR-1519))
This PR expands the `LifecycleStage` type to include new states: 'pending', 'scaling', and 'ready', while marking 'created' as deprecated. The default lifecycle stage filter now includes both 'ready' and 'created' states to ensure backward compatibility while adopting the new 'ready' state.
The filter in ChatPage has also been updated to match endpoints with either 'ready' or 'created' lifecycle stages.
**Checklist:**
[FR-1519]: https://lablup.atlassian.net/browse/FR-1519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(FR-1519): Endpoint lifecycle state change from created to ready not reflected

react/src/components/ComputeSessionNodeItems/SFTPConnectionInfoModal.tsx
This PR updates the import of `BAIModal` in `SFTPConnectionInfoModal.tsx` to use the component from `backend.ai-ui` package instead of the local component. It also imports `BAIModalProps` from the same package.
=> fix: BAIModal import in SFTPConnectionInfoModal to use backend.ai-ui package

pnpm-workspace.yaml
This PR adds a `minimumReleaseAge` setting of 1440 minutes (24 hours) to the pnpm-workspace.yaml file. This setting helps ensure we only use package versions that have been available for at least 24 hours, reducing the risk of using packages that might be quickly yanked due to issues.
=> feat(FR-1503):Adopt pnpm minimumReleaseAge for security

react/src/components/BAINotificationButton.tsx
Resolves #4377 ([FR-1539](https://lablup.atlassian.net/browse/FR-1539))
This PR adds keyboard shortcut functionality and tooltip to the notification button to improve accessibility and user experience.
- Added keyboard shortcut (']' key) to toggle notification drawer open/close
- Integrated useKeyboardShortcut hook with skipShortcutOnMetaKey option to avoid conflicts
- Added tooltip displaying "Notifications ]" to inform users about the available shortcut
- Tooltip positioned on the left side of the button for better visibility
- Improved accessibility through keyboard navigation
- Better user experience with clear visual hints about available shortcuts
- Enhanced productivity for power users who prefer keyboard shortcuts
[FR-1539]: …
=> feat(FR-1539): add keyboard shortcut and tooltip to notification button

react/src/hooks/useIntervalValue.test.tsx
This PR adds comprehensive test coverage for the `useInterval` and `useIntervalValue` hooks. The tests verify:
- Proper execution of callbacks at specified intervals
- Pausing functionality when a window loses focus (`pauseOnWindowBlur` parameter)
- Resuming execution when a window regains focus
- Proper handling of null delay values
The PR also includes a minor CSS class update in the DomainSelector snapshot test.
run `pnpm run test` in the react directory.
**Checklist:**
=> feat(FR-1530): add `useIntervalValue` test code and fix broken test code snapshot

packages/backend.ai-ui/package.json, packages/backend.ai-ui/src/components/baiClient/FileExplorer/hooks.ts, pnpm-lock.yaml
Resolves #4382 ([FR-1540](https://lablup.atlassian.net/browse/FR-1540))
This PR removes the problematic `use-query-params` and unused `react-router-dom` dependencies from the FileExplorer component that were causing the folder explorer to be unusable.
- **Removed dependencies**: `use-query-params` and `react-router-dom` from `packages/backend.ai-ui/package.json`
- **Removed URL query parameter synchronization**: Cleaned up the FileExplorer hooks to remove the query param sync logic (`useQueryParam`, `setCurrentPathParam`)
- **Updated lockfile**: `pnpm-lock.yaml` reflects the dependency removal
The `use-query-params` package dependency was blocking the folder explorer functionality. Since the `backend.ai-ui` project currently doesn't use this package and plans to implement this …
=> fix(FR-1540): remove use-query-params dependency from FileExplorer
