src/components/backend-ai-resource-monitor.ts, src/components/lablup-slider.ts
Now user can write down with enter key inside expansion slots.
User can switch expansion slots by mouse-click instead of pressing enter key.
=> refs #311 : modify - disable switching wl-expansions by enter key

main.electron-packager.js
* Force Update Screen crashes the app and wsproxy connection, so replace
it with Refresh App.
* Zoom menu items were not working.
=> Update main.electron-packager.js for Mac menu items

src/components/backend-ai-environment-list.ts
=> refs #382 : bugfix - rearrange images list after sorting

src/components/backend-ai-resource-monitor.ts, src/plastics/mwc/mwc-multi-select-base.ts
=> Bugfix/404 Folders to mount label overlaps selected folders text

src/components/backend-ai-resource-monitor.ts
=> refs #411 : add - text indicator for gauges

src/components/backend-ai-data-view.ts, src/components/backend-ai-storage-list.ts
=> refs #413 : bugfix - change regexp to allow dot on folder

src/components/backend-ai-environment-list.ts, src/lib/backend.ai-client-node.ts
This pull-request resolves #406.
I just added `domain` and `group` information in creating a kernel for downloading.
=> Add domain and group information for image downloading

src/components/backend-ai-environment-list.ts
=> Fix GPU/fGPU heterogeneous environment installation on both 19.09 /20.03 (#428)

src/components/backend-ai-session-list.ts, src/components/backend-ai-usersettings-view.ts
* Only for >= 20.03. Logging for terminated sessions is not supported <= 19.09.
=> feat: enable log button for terminated sessions

src/components/backend-ai-splash.ts
=> feat: add license mark support for perpetual / subscription (#438)

src/components/backend-ai-resource-monitor.ts
=> fix : asynchronous resource template refresh (#445)

package-lock.json, package.json, src/wsproxy/lib/backend.ai-ws-appproxy.js, src/wsproxy/lib/bindStream.js, src/wsproxy/lib/console-appproxy.js, src/wsproxy/lib/logger.js, src/wsproxy/local_proxy.js, src/wsproxy/manager.js
There was no logging in local wsproxy. Currently, logging to console screen is enabled.
=> feat: enable logging for local wsproxy

src/components/backend-ai-storage-list.ts
This pull request resolves #453 by exposing delete icon for directories as well.
=> feat: delete directory button in vfolder file explorer

src/components/backend-ai-storage-list.ts
=> feat: Queue support to upload files

resources/i18n/en.json, resources/i18n/ko.json, src/components/backend-ai-settings-view.ts, src/lib/backend.ai-client-node.ts
=> feat: GUI option to change image pull behavior

src/components/backend-ai-summary-view.ts, src/components/lablup-activity-panel.ts
=> feat: Change invitation panel after decision is made

src/components/backend-ai-console.ts, src/components/backend-ai-credential-view.ts, src/components/backend-ai-login.ts, src/components/backend-ai-resource-monitor.ts, src/lib/backend.ai-client-node.ts
=> feat: spring clean - remove 19.03 support

src/components/backend-ai-console-styles.ts, src/components/backend-ai-console.ts
=> feat: Adopt finer group select element on UI (#475)

src/components/backend-ai-console.ts, src/components/backend-ai-settings-store.ts
=> feat: Keep last used group on console 

resources/i18n/en.json, resources/i18n/ko.json, src/components/backend-ai-console.ts, src/components/backend-ai-release-check.ts, src/components/backend-ai-settings-store.ts, src/components/backend-ai-summary-view.ts, src/components/backend-ai-usersettings-general-list.ts
=> feat: automatic release check

resources/i18n/en.json, resources/i18n/ko.json, src/components/backend-ai-session-list.ts
This pull-request resolves #502.
=> feat: add refresh button for session logs

resources/i18n/en.json, resources/i18n/ko.json, resources/icons/LICENSE.md, resources/storage_metadata.json, src/components/backend-ai-data-view.ts
* This PR resolves #509 
* Common storage type description support when choosing storage
This part: info icon to show information.
=> feat: common storage type description support when choosing storage (#509)

src/components/backend-ai-resource-monitor.ts
=> fix: reset query interval on resource group changes (#513)

src/components/backend-ai-resource-monitor.ts, src/components/backend-ai-resource-policy-list.ts
=> bugfix: set resource policy unlimited (#516)

src/components/backend-ai-resource-monitor.ts
=> fix: GPU resource preset properly updated when environment changes

src/components/backend-ai-console.ts, src/components/backend-ai-help-button.ts
=> feat: online help button on site (#524)

src/components/backend-ai-console-styles.ts, src/components/backend-ai-console.ts
=> feat: show hover menu description on mini sidebar UI (#528)

src/components/backend-ai-console.ts
=> fix: display admin pop-overs only if user is admin

resources/i18n/en.json, resources/i18n/ko.json, src/components/backend-ai-console-styles.ts, src/components/backend-ai-console.ts, src/components/backend-ai-general-styles.ts, src/components/backend-ai-information-view.ts, src/components/backend-ai-session-list.ts, src/components/backend-ai-sidepanel-notification.ts, src/components/backend-ai-sidepanel-task.ts, src/components/lablup-notification.ts
=> fest: notification stack ui on sidepanel

resources/i18n/en.json, resources/i18n/ko.json, src/components/backend-ai-storage-list.ts
Added kick option for shared virtual folder.
This PR should be merged after https://github.com/lablup/backend.ai-manager/pull/288 is merged in manager.
=> feat: add kick out option for shared virtual folder

src/components/backend-ai-change-forgot-password-view.ts, src/components/backend-ai-dialog.ts, src/components/backend-ai-login.ts
=> feat: change session store method (#567)

config.toml.sample, src/components/backend-ai-console-styles.ts, src/components/backend-ai-console.ts
=> feat: add blocklist feature for sidebar menus (#562)

resources/i18n/en.json, resources/i18n/ko.json, src/components/backend-ai-dialog.ts, src/components/backend-ai-resource-monitor.ts
=> feat: Open notification when no virtual folder is attached on console (#583)

resources/i18n/en.json, resources/i18n/ko.json, src/components/backend-ai-app-launcher.ts, src/components/backend-ai-change-forgot-password-view.ts, src/components/backend-ai-console-styles.ts, src/components/backend-ai-console.ts, src/components/backend-ai-credential-list.ts, src/components/backend-ai-credential-view.ts, src/components/backend-ai-data-view.ts, src/components/backend-ai-dialog.ts, src/components/backend-ai-email-verification-view.ts, src/components/backend-ai-environment-list.ts, src/components/backend-ai-environment-view.ts, src/components/backend-ai-general-styles.ts, src/components/backend-ai-login.ts, src/components/backend-ai-registry-list.ts, src/components/backend-ai-resource-monitor.ts, src/components/backend-ai-resource-policy-list.ts, src/components/backend-ai-resource-preset-list.ts, src/components/backend-ai-scaling-group-list.ts, src/components/backend-ai-session-list.ts, src/components/backend-ai-signup.ts, src/components/backend-ai-splash.ts, src/components/backend-ai-storage-list.ts, src/components/backend-ai-user-list.ts, src/components/backend-ai-usersettings-general-list.ts, src/components/backend-ai-usersettings-view.ts, src/components/lablup-terms-of-service.ts
=> feat: migrate legacy dialogs to backend.ai dialog for unified look and feel (#584)

src/components/backend-ai-email-verification-view.ts
=> fix: consider 201 status to be always successful

src/components/backend-ai-agent-list.ts
=> Feature/fraction info for fgpus #289

src/components/backend-ai-resource-broker.ts
This PR resolves #640 in alternative way.
=> fix: change scaling group lookup routine to be robust (Alternative) (#640)

src/components/backend-ai-registry-list.ts
This PR resolves #652.
(notice: password is optional, therefore password with dots appears only if its input is not empty.)
Related: OP#683.
=> fix: Hide registry password

resources/i18n/en.json, resources/i18n/ko.json, src/components/backend-ai-storage-list.ts
This PR resolves #653 and should be merged after https://github.com/lablup/backend.ai-manager/pull/308.
Related: OP#686.
=> fix: more detailed message when vfolder invitation duplicated

src/components/backend-ai-session-launcher.ts
=> fix: undefined reference to a property in checking if mounted vfolders

resources/i18n/en.json, resources/i18n/ko.json, src/components/backend-ai-resource-preset-list.ts
=> fix: resource preset validation

src/components/backend-ai-environment-list.ts
=> fix: Incorrect image downloaded after filtered by keywords

src/components/backend-ai-session-launcher.ts
=> fix: layout overlap in Start new session dialog

src/components/backend-ai-error-log-list.ts, src/components/backend-ai-resource-broker.ts, src/components/backend-ai-session-launcher.ts, src/components/backend-ai-tasker.ts, src/components/lablup-notification.ts
This PR resolves https://github.com/lablup/backend.ai-console/issues/691 and https://github.com/lablup/backend.ai-console/issues/689.
=> fix: display error message when kernel creation failed

resources/i18n/en.json, resources/i18n/ko.json, src/components/backend-ai-console.ts
-  Change 'About' to 'About Backend.AI' #694 
- backend-ai-console.ts
- ko.json
- en.json
=> Change 'About' to 'About Backend.AI'

src/components/backend-ai-session-list.ts
=> fix: use io calculator to io data, not time calculator (#685)

index.html, main.js, src/components/backend-ai-app-launcher.ts, src/components/backend-ai-console.ts, version.json
=> fix: refer 'open to public' while it is possible (#720)

src/components/backend-ai-environment-list.ts, src/components/backend-ai-import-view.ts
After this PR, image downloading cannot be blocked by the undefined function call.
=> fix: new image cannot be downloaded

src/components/backend-ai-splash.ts
backend.ai master branch is not changed to 'main'. :)
Thanks.
=> Fix backend.ai LICENSE path

src/components/backend-ai-maintenance-view.ts
=> fix: Image rescan/Recalculate usage button throws an error. 

resources/i18n/en.json, resources/i18n/ko.json, src/components/backend-ai-agent-view.ts, src/components/backend-ai-scaling-group-list.ts
=> fix: resource group deletion reflected to table

config.toml.sample, src/components/backend-ai-app-launcher.ts, src/components/backend-ai-login.ts
This PR resolves https://github.com/lablup/backend.ai-console/issues/752.
Internal ticket: OP#838.
=> feat: add option to enable/disable open port to public checkbox

src/components/backend-ai-console.ts, src/components/backend-ai-login.ts
=> feat: add check routine for manager availablity (#762)

src/components/backend-ai-change-forgot-password-view.ts, src/components/backend-ai-console-styles.ts, src/components/backend-ai-console.ts, src/components/backend-ai-email-verification-view.ts, src/components/backend-ai-environment-list.ts, src/components/lablup-terms-of-service.ts
=> fix: change password verify email page shows properly

index.html, resources/i18n/en.json, resources/i18n/ko.json, src/components/backend-ai-agent-list.ts, src/components/backend-ai-credential-list.ts, src/components/backend-ai-dialog.ts, src/components/backend-ai-environment-list.ts, src/components/backend-ai-error-log-list.ts, src/components/backend-ai-login.ts, src/components/backend-ai-page.ts, src/components/backend-ai-resource-preset-list.ts, src/components/backend-ai-session-list.ts, src/components/backend-ai-signup.ts, src/components/backend-ai-storage-list.ts, src/components/backend-ai-user-list.ts, src/components/lablup-progress-bar.ts, version.json
=> feature: GPU/ASIC usage gauge per node

configs/debug.toml, configs/default.toml, configs/main.toml, resources/i18n/en.json, resources/i18n/ko.json, src/components/backend-ai-login.ts
This PR resolves #783 (client solution)
=> feat: add login block feature (#783)

config.toml.sample, src/components/backend-ai-login.ts, src/components/backend-ai-session-launcher.ts
This PR resolves https://github.com/lablup/backend.ai-console/issues/788.
=> feat: max cores, max CUDA devices, and max shared mem can be configurable now

src/components/backend-ai-storage-list.ts
=> fix: allow write permission for admin user in the group type of vfolder

resources/i18n/en.json, resources/i18n/ko.json, src/components/backend-ai-credential-list.ts, src/components/backend-ai-credential-view.ts
=> fix: allow keypair creation for users only

src/components/backend-ai-user-list.ts
=> fix: enable updating user detail

src/components/backend-ai-session-launcher.ts, src/components/lablup-slider.ts
=> fix: enable gpu resource value changing

src/components/backend-ai-storage-list.ts
=> fix: disable file uploading by drag and drop operation with notification

src/components/backend-ai-usage-list.ts
=> feat: hide per week option when user account created less than a week.

src/components/backend-ai-storage-list.ts
=> fix: auto-wrap for control panel in data & storage vfolder list and in the vfolder explorer dialog

resources/i18n/en.json, resources/i18n/ko.json, src/components/backend-ai-session-list.ts
=> fix: remove warning message in session list export csv

src/components/backend-ai-storage-list.ts
=> fix: hide rename operation if the user is not the owner of Vfolder

resources/i18n/en.json, resources/i18n/ko.json, src/components/backend-ai-credential-view.ts, src/components/backend-ai-user-list.ts
=> feat: re-implement inactive user list (#826)

src/components/backend-ai-resource-monitor.ts
=> fix: resource group to match with resource statistics gauge

README.md, configs/debug.toml, configs/default.toml, configs/main.toml, resources/i18n/en.json, resources/i18n/ko.json, src/components/backend-ai-login.ts, src/components/backend-ai-storage-list.ts
=> feat: add option to change upload file size. (#830)

src/components/backend-ai-console.ts, src/components/backend-ai-usersettings-general-list.ts
=> fix: incorrect i18n resource for the default language

src/components/backend-ai-user-list.ts
=> fix: show description of each user

src/components/backend-ai-storage-list.ts
=> feat: initialize vfolder invitation dialog to original layout 

src/components/backend-ai-console.ts, src/components/backend-ai-user-list.ts
=> feat: apply update immediately in header text when current user information has been changed

src/plastics/chart-js.ts
=> fix: responsive layout for each chart in statistics page

resources/i18n/en.json, resources/i18n/ko.json, src/components/backend-ai-app-launcher.ts, src/components/backend-ai-change-forgot-password-view.ts, src/components/backend-ai-console.ts, src/components/backend-ai-credential-list.ts, src/components/backend-ai-credential-view.ts, src/components/backend-ai-data-view.ts, src/components/backend-ai-email-verification-view.ts, src/components/backend-ai-environment-list.ts, src/components/backend-ai-indicator-pool.ts, src/components/backend-ai-login.ts, src/components/backend-ai-maintenance-view.ts, src/components/backend-ai-painkiller.ts, src/components/backend-ai-resource-preset-list.ts, src/components/backend-ai-scaling-group-list.ts, src/components/backend-ai-session-launcher.ts, src/components/backend-ai-session-view.ts, src/components/backend-ai-signup.ts, src/components/backend-ai-storage-list.ts, src/components/backend-ai-user-list.ts, src/components/backend-ai-usersettings-general-list.ts, src/components/backend-ai-usersettings-view.ts
After merging this PR, every notification will be translated to current language settings.
Also, there was a minor bug exporting csv menu in the users page (Admin Only), and It will be fixed via this PR.
=> fix: update inputfield pattern and support translation in every notification

src/components/backend-ai-usersettings-general-list.ts
After merging this PR, auto-logout feature panel in usersettings will be rearranged automatically by screen width.
=> fix: put auto-logout panel into the group

resources/i18n/en.json, resources/i18n/ko.json, src/components/backend-ai-page.ts, src/components/backend-ai-registry-list.ts
=> feat: support harbor v2 (#856)

resources/i18n/en.json, resources/i18n/ko.json, src/components/backend-ai-storage-list.ts
=> feat: show warning when reupload same file in vfolder

resources/i18n/en.json, resources/i18n/ko.json, src/components/backend-ai-console.ts, src/components/backend-ai-resource-policy-list.ts, src/components/backend-ai-session-launcher.ts, src/components/lablup-slider.ts
After merging this PR,
There will be no mwc based console error occurred, and also session launcher button will be translated automatically with current language.
=> fix: adjust slider min max and support KO/EN translation in session launcher button

resources/i18n/en.json, resources/i18n/ko.json, src/components/backend-ai-data-view.ts, src/components/backend-ai-resource-policy-list.ts, src/components/backend-ai-storage-list.ts, src/plastics/chart-js.ts
This PR resolves #858.
**In detail:**
- add new panel with doughnut chart and numeric information for current storage status(e.g. created, invited, capacity)
- add new column for whether for each vfolder has owned by the user or not.
=> feat: show detailed vfolder info

README.md, src/components/backend-ai-console.ts
=> feat: general option for auto logout (#865)

.gitignore, .gitmodules, src/components/backend-ai-data-view.ts, src/components/backend-ai-error-log-list.ts, src/components/backend-ai-session-launcher.ts, src/components/backend-ai-storage-list.ts
This PR will allow '-' character in Vfolder creation and renaming.
=> fix: vfolder name validation pattern update

resources/app_template.json, resources/i18n/en.json, resources/i18n/ko.json, src/components/backend-ai-app-launcher.ts, src/components/backend-ai-environment-list.ts, src/components/backend-ai-resource-broker.ts, src/components/backend-ai-session-list.ts
This PR resolves #872 
feat: add icon on session list
fix: update metadata
=> feat: add app category feature (#872)

src/components/backend-ai-storage-list.ts
=> fix: use type property to determine whether an entry is a directory or not

src/components/backend-ai-console-styles.ts, src/components/backend-ai-console.ts
=> fix: missing help / user setting button on mini sidebar mode (#878)

src/components/backend-ai-session-launcher.ts, src/components/lablup-slider.ts
=> fix: max value of shared memory changes depending on current value of memory.

src/components/backend-ai-storage-list.ts
=> fix: inspect file's mode in legacy API to distinguish file and directory

src/components/backend-ai-environment-list.ts, src/components/backend-ai-help-button.ts
This PR will fix the broken links for documentation in each menu in Backend.AI GUI Console.
=> fix: update documentation link

src/components/backend-ai-storage-proxy-list.ts
This PR provides determinate progress bar UI for percentage of [FlashBlade](https://www.purestorage.com/products/file-and-object/flashblade.html) volume.
=> feat: add progress bar for flashblade volume

src/components/backend-ai-storage-list.ts
=> feat: Add filter and sorting by each name of Vfolder

src/components/backend-ai-session-launcher.ts
=> fix: Set floating-point of shared memory in resource preset into 2 digits.

src/components/backend-ai-webui-styles.ts
=> feat: drag feature to loading screen (#925)

src/components/backend-ai-session-launcher.ts
=> fix: prevent "Infinity" max value to be converted as NaN in discrete GPU mode

src/components/backend-ai-environment-list.ts, src/components/backend-ai-session-launcher.ts
=> fix: support legacy R images / add pre-test routines for list casting

src/components/backend-ai-app-launcher.ts, src/components/backend-ai-login.ts, src/components/backend-ai-session-list.ts, src/lib/backend.ai-client-node.ts, src/wsproxy/lib/bindStream.js, src/wsproxy/manager.js
This PR resolves bugs of #680, by adding app proxy garbage collector / port collector.
=> fix: better port garbage collection for websocket proxy

src/components/backend-ai-data-view.ts, src/components/backend-ai-edu-applauncher.ts, src/components/backend-ai-storage-list.ts
**⚠️  FYI: Since there's been a high chance of request blocking issues during cloning large-size virtual folder, cloning feature will be disabled for the time being.**
This PR disables the feature about cloning the virtual folder.
=> fix: temporary disable clone feature

src/components/backend-ai-credential-view.ts, src/components/backend-ai-resource-policy-list.ts
=> fix: replace wl-textfield to mwc-textfield and update validation logics on input field

src/components/lablup-codemirror.ts
show all contents of shell script.
this closes #983
=> bugfix: show the all contents of shell script

package-lock.json, src/components/backend-ai-data-view.ts, src/components/backend-ai-page.ts, src/components/backend-ai-storage-list.ts, src/components/backend-ai-summary-view.ts, src/lib/backend.ai-client-node.ts
This PR resolves #990 
* feat:  rewrite base class' attributeChangedCallback monitoring 
* add: introduces atomic call check to folder refresh routine
=> fix: rewrite base class' attributeChangedCallback monitoring (#990)

src/components/backend-ai-login.ts, src/components/backend-ai-storage-list.ts
=> fix: unify height of login panel

configs/main.toml
Increase the maximum shared memory in desktop app (1GB -> 8GB)
=> feat: increase the maximum shared memory in desktop app

index.html, src/components/backend-ai-credential-view.ts, src/components/backend-ai-data-view.ts, src/components/backend-ai-environment-list.ts, src/components/backend-ai-error-log-list.ts, src/components/backend-ai-general-styles.ts, src/components/backend-ai-registry-list.ts, src/components/backend-ai-resource-policy-list.ts, src/components/backend-ai-scaling-group-list.ts, src/components/backend-ai-session-list.ts, src/components/backend-ai-session-view.ts, src/components/backend-ai-storage-list.ts, src/components/backend-ai-usersettings-general-list.ts, src/components/lablup-notification.ts
Change Noto font to Ubuntu or general font
- `--input-font-family: var(--general-font-family);`
- `--label-font-family: 'Ubuntu', 'Quicksand', Roboto;`
=> feat: change font family

resources/i18n/en.json, resources/i18n/ko.json, src/components/backend-ai-data-view.ts
Replace "Groups" in the dialog that you add folders with "Project"
=> feat: rename from group to project

src/components/backend-ai-login.ts
fix login form cloud icon element style
before fix
after fix
this pr close #1011
=> fix: login icon style

src/components/backend-ai-session-launcher-legacy.ts, src/components/backend-ai-session-launcher.ts
=> bugfix: duplicate declaration error

src/components/backend-ai-session-launcher.ts, src/components/lablup-progress-bar.ts
=> feature: Add Progress bar transition speed css variable

src/components/backend-ai-session-launcher-legacy.ts, src/components/backend-ai-session-launcher.ts
~~This PR fixes timing mismatch between resource refreshing and launch button enabling.~~
This PR also resolves resource gauge bug ( #1066 )
=> fix: add resource gauge bugs  (#1066, #1067)

src/components/backend-ai-user-list.ts
This PR resolves GraphQL generated error by deleting `password` field in user-list request.
=> update: remove 'password' field from getting user list request

src/components/backend-ai-data-view.ts, src/components/backend-ai-storage-list.ts
=> feat: correct permission label name

src/components/backend-ai-session-list.ts, src/components/backend-ai-session-view.ts
=> fix: inconsistent button layout and shadow

resources/i18n/ko.json
- fix the wrong translation of mounted folder (from 마운트한 폴더 to 마운트된 폴더)
=> fix: wrong translation of mounted folder

Dockerfile
This PR resolves [contribution #76](https://github.com/lablup/contribution-academy-2021/discussions/76)
=> bugfix: cannot build docker-compose

index.html, resources/i18n/en.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ru.json, src/components/backend-ai-session-launcher.ts, version.json
=> add: manually turn on / off automatic OpenMP optimization (#1119)

src/components/backend-ai-edu-applauncher.ts
- Fix error caused by empty endpoint when connecting manager.
- Fix timeout error when creating session using a template by adding timeout parameter.
Related: [control-panel#120](https://github.com/lablup/backend.ai-control-panel/pull/120), [manager#480](https://github.com/lablup/backend.ai-manager/pull/480)
=> fix: safe fallback of API endpoint for education app launcher handler

src/components/backend-ai-storage-list.ts
This PR resolves #1164 and also shows different msg according to the number of files to delete.
=> fix: refactor vaadin-grid template elements to renderer function

src/components/backend-ai-session-launcher.ts
=> fix: change event listener to check mount folder selection properly

src/components/backend-ai-login.ts, src/components/backend-ai-session-launcher.ts
=> fix: split the visibility of signup button and change password button

src/components/backend-ai-settings-view.ts
- this PR follows https://github.com/lablup/backend.ai-webui/pull/1120
=> feat: add max range of mtu

src/components/backend-ai-session-launcher.ts
Resolve:  lablup/backend.ai-webui #1074 
- display session information in last page of session launcher
**test image**
=> feat: add image name in session launcher

src/components/backend-ai-storage-list.ts
=> bugfix: wrong folder id path

src/components/backend-ai-storage-list.ts
=> fix: wrong path of shared to email

src/components/backend-ai-registry-list.ts
Resolve Issue #1204 
The add registry dialog will remove the existing values in the fields after a successful addition.
=> fix: add registry field values not being removed

resources/i18n/en.json, resources/i18n/ko.json, src/components/backend-ai-usersettings-general-list.ts, src/components/lablup-codemirror.ts
=> feat: display bootstrap script button in user settings page

config.toml.sample, src/components/backend-ai-common-utils.ts, src/components/backend-ai-credential-list.ts, src/components/backend-ai-login.ts, src/components/backend-ai-session-launcher.ts, src/components/backend-ai-session-list.ts, src/components/backend-ai-user-list.ts, src/components/backend-ai-webui.ts
This PR provides a new feature, which is string masking in order to fulfill privacy policy.
It masks not only the current login user but also the information of other users, which was only visible to those users who have `admin` or `super-admin` roles as well.
This resolves #1251.
=> Feature: masking user info

resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt.json, resources/i18n/pt_BR.json, resources/i18n/ru.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh_CN.json, resources/i18n/zh_TW.json, src/components/backend-ai-import-view.ts
check github default branch using github api
fix https://github.com/lablup/backend.ai-webui/issues/1224
=> check github default branch using api

src/components/backend-ai-session-launcher.ts
=> Make the gpu slider active when there is a gpu available.

resources/i18n/en.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ru.json, src/components/backend-ai-session-list.ts
=> Failing to update a compute session's name will set the value of edit element to `undefined`

resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt.json, resources/i18n/pt_BR.json, resources/i18n/ru.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh_CN.json, resources/i18n/zh_TW.json, src/components/backend-ai-import-view.ts
Support to import Gitlab repository.
add default repository input box (ex. main, master, core, etc) for import Gitlab repository
add gitlab exception messages, change exception message notification location.
add i18n messages for Gitlab messages
https://github.com/lablup/backend.ai-webui/issues/1267
=> Support to import Gitlab repository

src/components/backend-ai-credential-view.ts, src/components/backend-ai-resource-policy-list.ts
Add margins to policy dialog to distinguish fields
Adjusted some element CSS margins.
close https://github.com/lablup/backend.ai-webui/issues/1111
=> Add margins to policy dialog to distinguish fields

src/components/backend-ai-storage-list.ts
Enhance design of folder-explorer-dialog
1. move the buttons(file browser, file upload, new directory) on the top right to the top center.
2. add margin-left for arrow image.
https://github.com/lablup/backend.ai-webui/issues/1109
=> Enhance design of folder-explorer-dialog

src/components/backend-ai-session-launcher.ts
this fixes #1271 
[Screenshot]
=> feat: show vfolder host when creating a session

src/components/backend-ai-login.ts
This reverts https://github.com/lablup/backend.ai-webui/commit/137d8ef462957c7255c19e9c174737398338f391.
=> fix: remove broken logic to launch a login dialog always upon browser refresh

resources/i18n/en.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ru.json, src/components/backend-ai-webui.ts
For better user experience, added the password change place.
this PR follows up #1295
=> feat: add password change place message

src/components/backend-ai-session-list.ts, src/components/backend-ai-session-view.ts
=> Reduce requests to fetch the session list

src/components/backend-ai-resource-group-list.ts
This PR fixes the logic error on validating scheduler options in creating resource group.
=> fix: logic error on validating scheduler options in creating resource group

src/components/backend-ai-change-forgot-password-view.ts, src/components/backend-ai-edu-applauncher.ts, src/components/backend-ai-email-verification-view.ts, src/components/backend-ai-signup.ts
The client esm file is not imported, so if you go to the change password link via email, a blank page appears.
=> hotfix: import client-esm to fix backend-ai client ReferenceError

src/components/backend-ai-app-launcher.ts, src/components/backend-ai-environment-list.ts, src/components/backend-ai-session-launcher.ts, src/components/backend-ai-session-list.ts, src/components/backend-ai-storage-list.ts
- fix: value disappears when moving the slider to modify the image resource limit
- fix: lint errors
this resolves #1131
=> fix: make gpu required image available to download

src/components/backend-ai-credential-view.ts, src/components/backend-ai-resource-policy-list.ts
- refactor: rename some variables for matching naming convention
- this resolves #1336
=> fix: prevents resource policy updates with incorrect values

config.toml.sample, resources/i18n/en.json, resources/i18n/ko.json, src/components/backend-ai-login.ts, src/lib/backend.ai-client-esm.ts
- Expose SSO Login buttons by referencing `general.singleSignOnVendors` parameter.
- https://github.com/lablup/backend.ai/pull/652
=> feature: support SSO login (SAML 2.0)

src/components/backend-ai-registry-list.ts
=> fix: save button was not working due to the wrong function call

src/components/backend-ai-error-log-list.ts
=> style: remove `flex-grow="0"` from paramaters column in log page

src/components/backend-ai-registry-list.ts
=> fix: do not allow blank username / password

resources/i18n/en.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ru.json, src/components/backend-ai-session-list.ts
this PR resolves https://github.com/lablup/backend.ai/issues/641
=> feature: display message when session's status is `no-available-instances`

src/components/backend-ai-import-view.ts
#1387
To solve this problem, I created a variable called `importButtonDisabled`.
Checking length of textfield's input value through `@change` property and it can handle `importButtonDisabled` value properly.
The button dynamically changes the property called `disabled` according to the variable.
=> fix: add validation check and enable button only valid status in import and run page

src/components/backend-ai-environment-list.ts
=> hotfix: don't show the Environments Images list

src/components/backend-ai-agent-list.ts, src/components/backend-ai-credential-list.ts, src/components/backend-ai-environment-list.ts, src/components/backend-ai-error-log-list.ts, src/components/backend-ai-list-status.ts, src/components/backend-ai-registry-list.ts, src/components/backend-ai-resource-policy-list.ts, src/components/backend-ai-resource-preset-list.ts, src/components/backend-ai-scaling-group-list.ts, src/components/backend-ai-session-list.ts, src/components/backend-ai-storage-list.ts, src/components/backend-ai-storage-proxy-list.ts, src/components/backend-ai-user-list.ts, src/components/backend-ai-usersettings-view.ts
- fix: blocking cannot read properties of null (list_status)
- refactor: use camelcase to properties that are related to `backend-ai-list-status`
[Minor changes]
- fix: lint errors (`backend-ai-environment-list` indentations)
- fix: typo error for `cudaUtilCapacity`
=> bugfix: list status unrecognized

src/components/backend-ai-agent-list.ts, src/components/backend-ai-credential-list.ts, src/components/backend-ai-environment-list.ts, src/components/backend-ai-error-log-list.ts, src/components/backend-ai-list-status.ts, src/components/backend-ai-registry-list.ts, src/components/backend-ai-resource-policy-list.ts, src/components/backend-ai-resource-preset-list.ts, src/components/backend-ai-scaling-group-list.ts, src/components/backend-ai-session-list.ts, src/components/backend-ai-storage-list.ts, src/components/backend-ai-storage-proxy-list.ts, src/components/backend-ai-user-list.ts
=> refactor: use type alias for `listCondition`

resources/i18n/en.json, resources/i18n/id.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ru.json, src/components/backend-ai-session-launcher.ts
resolve #1367
I added project name.
I made it simply to match styles around it.
Please let me know if I need to change in style or to add additional information.
=> feature: add extra information in the last page of session launcher

src/components/backend-ai-agent-summary-list.ts, src/components/backend-ai-agent-summary-view.ts
=> fix: rename `BackendAIAgent` to `BackendAIAgentSummaryList` and add detail typings

src/components/backend-ai-session-launcher.ts
remove animation of buttons that do not trigger other events
related issue: https://github.com/lablup/backend.ai-webui/issues/1335
before
https://user-images.githubusercontent.com/29423339/188257954-9cab2d1a-4888-4754-b0f1-a17d57b66d8f.mov
after
https://user-images.githubusercontent.com/29423339/188257941-56ed909f-839d-4e4a-a7d0-4027a2128ac2.mov
=> fix: remove animation of buttons that do not trigger other events

src/plastics/chart-js.ts
=> fix: add type-check before initializing chart

src/components/backend-ai-session-launcher.ts
This PR resolves #1464
[Before]
[After]
=> style: total allocation pane is too big

src/components/backend-ai-storage-list.ts
Removes Hover events from the Data & Storage tab
related issue: #1335 
<br/>
before
https://user-images.githubusercontent.com/72901045/189806675-388ea730-2d45-4adb-bd48-c5d881cdd4d3.mov
after
https://user-images.githubusercontent.com/72901045/189806929-01f8d4b2-578e-4633-8ad6-d79247ff47c6.mov
=> fix: remove animations from which events do not occur

README.md
add Electron app debugging content on README.md
=> add Electron app debugging content on README

resources/i18n/en.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ru.json, src/components/backend-ai-session-launcher.ts
resolves #1471 
- Click the **`Reset` button** with input any value -> show confirm dialog -> delete all of the values and rows. but the first row will not be removed.
- Click the **close button** with input any value -> show confirm dialog -> delete all values and rows except for the pre-saved environ values. (the first row will not be removed too.)
- Click the reset button without input value -> delete all values and rows except the first row.
[Screenshots]
- Default 
- When clicking the `Reset` button or close button with input.
=> style: change `modify-env-dialog` style

src/components/backend-ai-storage-list.ts
=> feature: unify folder view icon and directory list into one column

src/components/backend-ai-scaling-group-list.ts
This PR resolves leftovers of #1128
=> update: remove template from vaadin table for resource group

src/components/backend-ai-app-launcher.ts
=> fix: typo error

src/components/backend-ai-project-switcher.ts, src/components/backend-ai-session-launcher.ts, src/components/backend-ai-user-dropdown-menu.ts, src/components/backend-ai-webui.ts
This PR refactors top bar items in WebUI app shell to make app shell lighter / modular.
Also, it includes
- Tab focus move between session launcher resource sliders.
- Disable slider reset after changing cluster mode.
=> feature: modular top-bar items

src/components/backend-ai-chart.ts, src/components/backend-ai-webui.ts
resolves #1499 
[Screenshots]
- **Before**  
- **After**
=> fix: modify y-axis value setting callback function to have only unique integer values.

src/components/backend-ai-storage-list.ts
=> fix: can't upload to vfolder after canceling upload

src/components/backend-ai-data-view.ts
=> fix: make available to select project in creating the project data folder

src/components/backend-ai-credential-view.ts, src/components/backend-ai-summary-view.ts
- Open dialog, add credential when path from action=add
- #1394
=> Open dialog and add credential with URL option

resources/i18n/en.json, resources/i18n/ko.json, src/components/backend-ai-credential-list.ts
Resolves #1493
* translate title in new-keypair-dialog in kor
* translate userID in new-keypair-dialog in kor
* translate words related `Rate Limit` in new-keypair-dialog in kor
=> chore(backend-ai-dialog): translate new-keypair-dialog in kor

config.toml.sample, resources/i18n/en.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ru.json, src/components/backend-ai-app-launcher.ts, src/components/backend-ai-login.ts, src/components/backend-ai-summary-view.ts, src/components/backend-ai-webui-styles.ts, src/components/backend-ai-webui.ts
- this resolves #1486 
- Add `appDownloadUrl` option to config.
- Add a button that links to `<appDownloadUrl>/v<webui version>/backend.ai-desktop-<webui-version>-<OS>-<architecture>.<extension>`
related PR: https://github.com/lablup/backend.ai/pull/861
=> feat: add download link button for webui desktop

resources/i18n/en.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ru.json, src/components/backend-ai-common-utils.ts, src/components/backend-ai-session-list.ts
=> feat: add log download button on session log dialog

src/components/backend-ai-credential-view.ts, src/components/backend-ai-resource-policy-list.ts, src/lib/backend.ai-client-esm.ts
This reverts commit 5bd9208ec0df6ca8094d063c5efd0d8b715caba8.
=> Revert "Feature/update data handling part in receiving and updating keypair resource policy (#1517)"

src/components/backend-ai-credential-view.ts, src/components/backend-ai-resource-policy-list.ts, src/lib/backend.ai-client-esm.ts
This PR is restored branch of #1517.
=> feat: update data handling on keypair resource policy

src/lib/backend.ai-client-esm.ts
This PR implements lablup/backend.ai#890
=> add: header-based session login feature

resources/storage_metadata.json, src/components/backend-ai-data-view.ts, src/components/backend-ai-storage-list.ts, src/components/backend-ai-storage-proxy-list.ts
related PR: [backend.ai#744](https://github.com/lablup/backend.ai/pull/744)
=> feat: add IBM Spectrum Scale and WekaIO to quota support storage list

src/components/backend-ai-credential-list.ts
=> style: set font-weight for readability and align `lablup-shields` as center

src/components/backend-ai-storage-list.ts
The PR resolves https://github.com/lablup/giftbox/issues/25.
=> fix: call `toString` method in setting quota value

src/components/backend-ai-session-launcher.ts
=> feat/fix: initialize aliases after successfully creating a session and fix the error that mounts using another name

src/components/backend-ai-session-list.ts, src/components/backend-ai-storage-proxy-list.ts
Those small errors block compiling.
=> fix minor typo errors which block compile

index.html, manifest.json, package-lock.json, package.json, src/components/backend-ai-login.ts, src/components/backend-ai-painkiller.ts, src/components/backend-ai-usersettings-general-list.ts, src/components/backend-ai-webui.ts, src/components/lablup-notification.ts, version.json
This PR resolves #1509 and #1478 together.
=> update: check login status to show notification after logout

src/components/backend-ai-storage-list.ts, src/lib/backend.ai-client-esm.ts, src/lib/backend.ai-client-node.ts
=> update: change slash / colon escaping to apply whole string

src/components/backend-ai-data-view.ts
=> fix: temporally comment out unused folder usage mode

src/components/backend-ai-common-utils.ts, src/components/backend-ai-storage-list.ts
=> fix: refactor vfolder quota setting dialog

src/components/backend-ai-storage-list.ts
Since there's redundant conditional html rendering statement in storage-list component, I merged the three same conditional rendering parts into one, which could improve rendering time a bit.
=> fix: merge splitted conditional render html template on controls column

src/components/backend-ai-agent-list.ts, src/components/backend-ai-session-list.ts
Related: https://github.com/lablup/giftbox/issues/80, https://github.com/lablup/backend.ai-control-panel/pull/500
=> feat: display CUDA memory utilization in node and session pages

src/components/backend-ai-session-launcher.ts
resolves https://github.com/lablup/giftbox/issues/112
this PR follows #1549
=> bugfix: insert a dash in image Requirements (tag) in launching a compute session

resources/i18n/en.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ru.json, src/components/backend-ai-storage-list.ts
resolves https://github.com/lablup/giftbox/issues/74
related PR: https://github.com/lablup/backend.ai/pull/1018, https://github.com/lablup/backend.ai/pull/1017, https://github.com/lablup/backend.ai-control-panel/pull/505
=> feat: add status column and disable deleting folders

src/components/backend-ai-storage-list.ts
I don't think "yellow" is a good color for a normal status.
ready: yellow -> green
deleting: red -> yellow
=> misc: change data folder's status color

src/components/backend-ai-session-list.ts
resolves https://github.com/lablup/giftbox/issues/128
follows https://github.com/lablup/backend.ai-webui/pull/1580
=> fix: incorrect display of GPU memory utilization

src/components/backend-ai-agent-summary-view.ts, src/components/backend-ai-agent-view.ts, src/components/backend-ai-app-launcher.ts, src/components/backend-ai-credential-view.ts, src/components/backend-ai-data-view.ts, src/components/backend-ai-email-verification-view.ts, src/components/backend-ai-environment-view.ts, src/components/backend-ai-error-log-view.ts, src/components/backend-ai-error-view.ts, src/components/backend-ai-import-view.ts, src/components/backend-ai-information-view.ts, src/components/backend-ai-maintenance-view.ts, src/components/backend-ai-pipeline-view.ts, src/components/backend-ai-resource-monitor.ts, src/components/backend-ai-session-launcher.ts, src/components/backend-ai-session-list.ts, src/components/backend-ai-session-view.ts, src/components/backend-ai-settings-view.ts, src/components/backend-ai-summary-view.ts, src/components/backend-ai-usage-list.ts, src/components/backend-ai-user-dropdown-menu.ts, src/components/backend-ai-user-list.ts, src/components/backend-ai-usersettings-view.ts, src/components/lablup-activity-panel.ts, src/components/lablup-loading-spinner.ts, src/components/lablup-terms-of-service.ts
This PR increases the design injection points through custom.css, making the design override process easier.
=> add: more CSS injection point to custom.css

src/components/backend-ai-change-forgot-password-view.ts, src/components/backend-ai-common-utils.ts, src/components/backend-ai-credential-view.ts, src/components/backend-ai-signup.ts, src/components/backend-ai-user-dropdown-menu.ts, src/components/backend-ai-user-list.ts
=> fix: allow any special characters in password input

src/components/backend-ai-session-launcher.ts, src/plastics/lablup-shields/lablup-shields.ts
resolves https://github.com/lablup/giftbox/issues/205
**Before**
**After**
=> style: display all characters of session image tag

resources/i18n/en.json
2FA enabled -> 2FA Enabled to match the convention with other columns.
=> fix: minor capital letter issue

src/components/backend-ai-login.ts, src/components/backend-ai-user-dropdown-menu.ts, src/components/backend-ai-user-list.ts, src/lib/backend.ai-client-esm.ts
=> hotfix: 2FA item is not display after the initial login

src/components/backend-ai-login.ts
resolves https://github.com/lablup/giftbox/issues/231
=> hotfix: Remove the waiting text in the login dialog in typing OTP

resources/i18n/ko.json
=> update: change '강제종료' to '종료' for multiple session termination button text

config.toml.sample, src/components/backend-ai-dialog.ts, src/components/backend-ai-login.ts, src/components/backend-ai-user-dropdown-menu.ts, src/lib/backend.ai-client-esm.ts
Display this dialog on every page if `force2FA` is true and 2FA is not activated. 
resolves [Add an option to enforce users 2FA#261](https://github.com/lablup/giftbox/issues/261)
related PR: https://github.com/lablup/backend.ai/pull/1161
=> feat: add force 2fa option

src/components/backend-ai-storage-list.ts
- refactor: render permission info when only permission exists
=> feat: display usage_mode to folder-info-dialog

config.toml.sample, src/components/backend-ai-app-launcher.ts, src/components/backend-ai-login.ts
resolves #1634
related PR: https://github.com/lablup/backend.ai/pull/1178
=> feat: add `allowPreferredPort` to show/hide `Try preferred port`

src/components/backend-ai-help-button.ts
follow-up of #1638 
remove highlight after click help button
=> fix : remain highlight after click on help button

resources/i18n/en.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ru.json, src/components/backend-ai-credential-list.ts
=> feat: add confirm dialog for delete credentials

resources/i18n/en.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ru.json, src/components/backend-ai-user-list.ts
=> fix: change messege type of delete user

src/components/backend-ai-credential-list.ts
=> fix: resize column for resolve disappearing-icon

src/components/backend-ai-session-list.ts
Some string is missing because it is not properly parsing.
=> fix: escape status info detail message text.

src/components/backend-ai-session-list.ts
=> hotfix: remove inline styling applied in force terminate button

src/components/backend-ai-session-launcher.ts
=> fix: import `wl-textfield` to display env list to apply in session launcher

resources/i18n/en.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ru.json, src/components/backend-ai-login.ts
=> feat: add endpoint validation

src/components/backend-ai-session-list.ts
resolves https://github.com/lablup/giftbox/issues/249
display agent id even if the user is not admin if `hideAgent` is set to false.
=> feat: show agent id to session list if `hideAgent` is false

src/components/backend-ai-session-list.ts
resolves https://github.com/lablup/giftbox/issues/387
Before
After
=> hotfix: Disable the app icon if the user is not the owner of the session.

src/components/backend-ai-session-launcher.ts
This PR resolves #1723.
* before
* after
=> fix: enable npu resource slider when limited

src/lib/backend.ai-client-esm.ts
=> fix: set timeout value to 10sec on fetching `user_stats`

src/components/backend-ai-webui.ts
- just move logout inside preserve_login check block...
- resolves https://github.com/lablup/backend.ai-webui/issues/1751
=> fix: do not auto logout when preserve login true

react/src/components/ProjectResourcePolicySettingModal.tsx, react/src/components/StorageHostResourcePanel.tsx, react/src/components/StorageHostSettingsPanel.tsx, react/src/components/UserResourcePolicySettingModal.tsx
for fix the build errors. these codes will be used in the future, so I just annotate them.
=> fix: annotate unused codes

react/src/components/QuotaScopeCard.tsx, react/src/components/ResourcePolicyCard.tsx, resources/i18n/en.json, resources/i18n/ko.json
- Match button icon and styles
- Change the ID column name of the quota setting to "Quota Scope ID"
=> cosmetic changes of quota scope setting page

react/src/components/QuotaScopeCard.tsx, react/src/components/ResourcePolicyCard.tsx, react/src/components/StorageHostResourcePanel.tsx, resources/theme.json
|--------|------|
| <img width="1274" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/621215/44a45e71-e95e-479b-a4a2-4729195abbc6"> | <img width="1500" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/621215/fb3dd4da-fab2-451d-b32c-8cc365501d22"> |
=> compact ui version of storage quota setting

src/components/backend-ai-session-list.ts, src/components/backend-ai-session-view.ts
=> feat: merge running and others tab in the session list

react/src/components/QuotaScopeCard.tsx, react/src/components/QuotaSettingModal.tsx, react/src/components/StorageHostSettingsPanel.tsx, react/src/components/UserSelector.tsx
- remove resource policy panel 
- use email value as a the value of UserSelector's options
- sort users by email on UserSelecotr
- increase the limit of UserSelecotor query to 150
=> feat: Remove resource policy panel on Quota setting and bugfix

react/src/components/UserSelector.tsx
=> feat: add loading indicator on UserSelector

react/src/components/StorageStatusPanel.tsx
=> bugfix: prevent flicking of StorageStatusPanel using deferredFetchKey 

src/components/backend-ai-app-launcher.ts, src/components/backend-ai-common-utils.ts, src/components/backend-ai-credential-view.ts, src/components/backend-ai-data-view.ts, src/components/backend-ai-dialog.ts, src/components/backend-ai-environment-list.ts, src/components/backend-ai-login.ts, src/components/backend-ai-page.ts, src/components/backend-ai-resource-monitor.ts, src/components/backend-ai-session-launcher.ts, src/components/backend-ai-session-list.ts, src/components/backend-ai-storage-list.ts, src/components/backend-ai-user-dropdown-menu.ts, src/components/backend-ai-usersettings-general-list.ts, src/components/backend-ai-webui.ts, src/components/lablup-codemirror.ts, src/components/lablup-notification.ts, src/components/lablup-terms-of-service.ts, src/plastics/chart-js.ts, src/plastics/font/font-awesome.js, src/plastics/mwc/mwc-dialog.ts, src/plastics/mwc/mwc-drawer.ts
=> refactor: remove `any` from code typing

graphql.config.js, react/data/relay-directives.graphql
This PR has changes to fix VS Code graphql extension configuration.
=> fix: vscode graphql extention configuration

src/components/backend-ai-multi-select.ts, src/components/backend-ai-resource-group-list.ts
This PR resolves #1811 
|Before|Before(Problem)|
|------|-----------------|
|![before](https://github.com/lablup/backend.ai-webui/assets/81795729/690aa423-5d0f-4349-a354-0bc05e532c8f)|![before(problem)](https://github.com/lablup/backend.ai-webui/assets/81795729/1659cecc-03ff-4a31-81e7-e1d32c1372ee)|
|After|After(solved)|
|-----|-------------|
| ![after](https://github.com/lablup/backend.ai-webui/assets/81795729/e61edff6-ee7d-46a3-9c58-6924e310bc8e)| ![after(solved)](https://github.com/lablup/backend.ai-webui/assets/81795729/e91c324a-9a72-4eb3-91e3-8e57da2b79d3)|
=> fix: Solve to extract `backend-ai-multi-select` tag from scheduler options

resources/i18n/ko.json
Before | After
------ | ------
=> update: change '표시 할' to '표시할' for no-announcement text

src/components/backend-ai-app-launcher.ts, src/components/backend-ai-edu-applauncher.ts, src/components/backend-ai-session-list.ts
- feat: AppProxy connection via query param
- feat: App delete request with query param
- fix: remove debug console log
=> feat: authorize app by query param

src/components/backend-ai-statistics-view.ts
related: https://github.com/lablup/giftbox/issues/477
=> style: import custom.css to statistics-view

i18n.config.js, resources/i18n/en.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ru.json
=> fix: Add the React component to i18n scan target

react/src/helper/react-to-webcomponent.tsx, react/src/pages/ServingListPage.tsx, react/src/pages/SessionListPage.tsx, resources/custom.css, resources/theme.json
- feat: Add `link` to custom.css for React-based component
- refactor: Remove custom `<ConfigProvider/>`
- fix: Remove hard-coded color values in the antd component.
With this pull request, react based components(and antd components) can be customized by updating `custom.css` and `theme.json`, even in production builds.
- The `Tabs` component can be customized using `resources/theme.json`, which is an antd theme configuration file.
- The `Tabs` component can also be customized using `custom.css`.
```css
/* custom.css */
.ant-tabs {
background-color: #2A2C30;
}
```
=> hotfix: custom.css and theme.json for react component

src/components/backend-ai-app-launcher.ts, src/components/backend-ai-session-list.ts, src/components/lablup-expansion.ts
resolves #1754, #1755
- Default: opened
- Closed
=> feat: display pre open ports to the inside of lablup-expansion

react/src/components/Information.tsx, src/lib/backend.ai-client-esm.ts
This PR resolves #1812
|Result|
|------|
|<img width="519" alt="스크린샷 2023-08-10 13 37 43" src="https://github.com/lablup/backend.ai-webui/assets/81795729/5d7d06b1-81af-44c4-92b7-07c6d7ab0b73">|
=> fix:  Remove license errors in open-source project version

src/backend-ai-app.ts, src/components/backend-ai-edu-applauncher.ts, src/components/backend-ai-login.ts, src/components/backend-ai-webui.ts, src/lib/backend.ai-client-esm.ts
- feat: Pass token as body parameter in token login
- feat: launch app when session_id is given
=> feat: edu-applauncher opens app for a session

resources/custom.css, resources/theme.json
- style: modify `colorPrimary` of tabs
resolves #1863
=> style: set card tab background color to white

react/src/components/ManageAppsModal.tsx, react/src/index.tsx, src/components/backend-ai-environment-list.ts
=> refactor: Change manage apps dialog to react component

react/src/components/DoubleTag.tsx, react/src/components/ImageEnvironmentSelectFormItems.tsx, react/src/components/SessionListColums/SessionInfoCell.tsx, react/src/components/TextHighlighter.tsx, resources/theme.json
=> feat: react-based image environment select display tags with search highlight

react/craco.config.js, react/package.json
ref: https://create-react-app.dev/docs/proxying-api-requests-in-development/
=> fix: react dev server to proxy any unknown requests to web-dev-server

react/src/components/ServiceLauncherModal.tsx, resources/i18n/en.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ru.json
=> feature: show an error message when the service fails to start

resources/i18n/en.json, resources/i18n/ko.json, src/components/backend-ai-data-view.ts, src/components/backend-ai-storage-list.ts
=> feature: add tab for pipeline dedicated folder list

react/src/components/BAIModal.css, react/src/components/BAIModal.tsx, react/src/components/ManageAppsModal.tsx, react/src/components/ModelServiceSettingModal.tsx, react/src/components/ProjectResourcePolicySettingModal.tsx, react/src/components/QuotaSettingModal.tsx, react/src/components/ResourcePolicyCard.tsx, react/src/components/ServiceLauncherModal.tsx, react/src/components/ServingRouteErrorModal.tsx, react/src/components/TOTPActivateModal.tsx, react/src/components/UserInfoModal.tsx, react/src/components/UserResourcePolicySettingModal.tsx, react/src/components/UserSettingModal.tsx, react/src/fix_antd.css, react/src/pages/ServingListPage.tsx, resources/custom.css, resources/theme.json, src/components/backend-ai-general-styles.ts
- style: center modal component
resolves #1876 
|Before|After|
|------|-------|
|<img width="539" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/28584164/f274a3d4-67d4-4744-8475-ec491c70f8cb">|<img width="534" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/28584164/69f1c1eb-576e-441b-9352-fe631f4a72c5">|
=> style: apply custom header to Modal 

src/components/backend-ai-session-list.ts
resolves https://github.com/lablup/giftbox/issues/403
Before
After
=> style: reduce sftp icon size

src/components/backend-ai-app-launcher.ts
Fixes a bug where the app launcher does not appear after the session is created.
=> fix: add optional chaining to show app launcher

react/src/helper/index.test.tsx
The initial test code of iSizeToSize in https://github.com/lablup/backend.ai-webui/pull/1920 had errors. This PR fixes that.
=> fix: errors in test code for iSizeToSize

react/src/components/ImageEnvironmentSelectFormItems.tsx
=> feature: add showPrivate props to ImageEnvironmentSelectFormItems

src/components/backend-ai-registry-list.ts
=> style: widen control column to show rescan icon

src/components/backend-ai-app-launcher.ts
This PR resolves [giftbox#538](https://github.com/lablup/giftbox/issues/538).
| After  |  Before|
|-------|-------|
| <img width="388" alt="Screenshot 2023-10-24 at 10 13 15 AM" src="https://github.com/lablup/backend.ai-webui/assets/46954439/efe45581-607d-4f78-8d1f-09a8569b4991"> | <img width="388" alt="Screenshot 2023-10-24 at 10 19 30 AM" src="https://github.com/lablup/backend.ai-webui/assets/46954439/b6d64cf0-aea0-400a-a0ae-c656f5e4df5c"> |
=> add: disable hostkey checking option for sftp session

resources/i18n/de.json, resources/i18n/el.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json
This PR fills missing i18n resources via machine translation.
=> update: i18n resources

.github/PULL_REQUEST_TEMPLATE.md
This is the first version of PULL_REQUEST_TEMPLATE.md
=> update: PULL_REQUEST_TEMPLATE.md

react/data/schema.graphql, react/src/components/ProjectResourcePolicySettingModal.tsx, react/src/components/ResourcePolicyCard.tsx, react/src/components/StorageStatusPanel.tsx, react/src/components/UserResourcePolicySettingModal.tsx, src/components/backend-ai-credential-list.ts, src/components/backend-ai-credential-view.ts, src/components/backend-ai-resource-policy-list.ts, src/lib/backend.ai-client-esm.ts
=> fix: revert max_vfolder_count removing

react/src/components/UserSettingModal.tsx, src/components/backend-ai-credential-view.ts, src/components/backend-ai-environment-view.ts, src/components/backend-ai-resource-policy-list.ts, src/lib/backend.ai-client-esm.ts
=> bugfix: GraphQL variable type error

src/components/backend-ai-app-launcher.ts
=> docs: Update documentation link

.cspell.json, react/src/components/InputNumberWithSlider.tsx, react/src/components/ResourceAllocationFormItems.tsx, react/src/components/ServiceLauncherModal.tsx, react/src/components/SliderInputFormItem.tsx, react/src/hooks/hooksUsingRelay.tsx, react/src/pages/SessionLauncherPage.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json
ref [Task list ](https://github.com/lablup/backend.ai-webui/issues/2025)
- Cluster form items
- Cluster & total allocations
Please test cluster mode using Backend.AI server supports cluster mode such as `xxx.xx.64.15` test server(with cluster size 1 and 2).
=> feat: cluster mode in Neo Session launcher 

react/src/components/EnvVarFormList.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json
Ref https://github.com/lablup/backend.ai-webui/issues/2025
This PR has 
- fix: envvar variable name validation (do not allow duplicated name)
- update i18n
=> fix: variable name validation rule of `EnvVarFormList`

src/components/backend-ai-webui.ts
Ref https://teams.microsoft.com/l/message/19:3c0acc0825024daeb2211f55c4e7f4aa@thread.skype/1700901615410?tenantId=13c6a44d-9b52-4b9e-aa34-0513ee7131f2&groupId=74ae2c4d-ec4d-4fdf-b2c2-f5041d1e8631&parentMessageId=1700543148815&teamName=devops&channelName=Backend.AI%20Talks&createdTime=1700901615410
Fixed Invisible Data&Storage menu at sidebar
=> Fix:Invisible Data&Storage menu

react/src/components/UserProfileSettingModal.tsx
This PR resolves issue https://github.com/lablup/backend.ai-webui/issues/2033
User can't change blank user name.
=> fix: remove `unhandled promise rejection` in UserProfileSettingModal 

src/components/backend-ai-webui.ts
I delete wrong code that is merged when you merge other branch.
=> Fix: modify small tag to follow main branch

src/components/backend-ai-storage-list.ts
This PR resolves issue https://github.com/lablup/backend.ai-webui/issues/2077
=> Fix: Sharing vfolder dialog is not closed when user click outside of dialog

src/components/backend-ai-app-launcher.ts
This PR resolves [teams](https://teams.microsoft.com/l/message/19:56185f8ff32e4393bff26c11ce37a5d1@thread.tacv2/1702863084903?tenantId=13c6a44d-9b52-4b9e-aa34-0513ee7131f2&groupId=b1f3bcf4-facf-40d3-94ab-169abb4f0f52&parentMessageId=1702863084903&teamName=customers%20%26%20clients&channelName=NHNCloud-AICA&createdTime=1702863084903)
=> fix: Remove unnecessary spaces in sFTP upload session commands

package.json, react/package-lock.json, react/package.json
This PR makes the relay-compiler restart automatically when the schema file changes.
=> feat: run `relay:watch` with nodemon

react/src/components/ResourceAllocationFormItems.tsx, react/src/components/ServiceLauncherModal.tsx, react/src/hooks/index.ts, src/components/backend-ai-login.ts
This PR resolves #1967 by replacing resource allocation form items to ResourceAllocationFormItems component.
After applying this changes, users can...
| <img width="377" alt="Screenshot 2023-12-20 at 4 15 15 PM" src="https://github.com/lablup/backend.ai-webui/assets/46954439/788fee5f-ec4d-4730-a32f-bf5caa9ceab1"> | <img width="398" alt="Screenshot 2023-12-20 at 4 15 52 PM" src="https://github.com/lablup/backend.ai-webui/assets/46954439/e8f3c176-2383-43c3-a231-f51add30f6db"> |
=> feature: Set resource limitation in service launcher

react/src/components/UserDropdownMenu.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json, src/components/backend-ai-webui-styles.ts, src/components/backend-ai-webui.ts
This PR resolves https://github.com/lablup/backend.ai-webui/issues/2084
Before
After
=> fix:Add white-space style

react/src/components/UserDropdownMenu.tsx
=> fix:UserDropdownMenu userName's item overflow issue

react/src/components/SessionList.tsx, react/src/components/SessionListColums/SessionInfoCell.tsx
This PR resolves https://github.com/lablup/backend.ai-webui/issues/2128
=> fix: implement Neo Session column's content

react/src/components/SessionList.tsx, react/src/components/SessionListColums/SessionInfoCell.tsx
I mistakenly merged the PR, confusing it with another PR.
Reverts lablup/backend.ai-webui#2130
=> Revert "fix: implement Neo Session column's content"

src/components/backend-ai-data-view.ts
This PR resolves https://github.com/lablup/backend.ai-webui/issues/2141
=> fix: default select value is appeared correctly in add-folder-dialog

src/components/backend-ai-storage-list.ts
This PR resolves https://github.com/lablup/backend.ai-webui/issues/2142
=> fix: apply overflow style and modify option to mwc-list-item in modify-permission-dialog

react/src/components/SessionList.tsx, react/src/components/SessionListColums/SessionInfoCell.tsx
The original PR is #2130, but it was mistakenly merged by me. I'll create this PR again. Sorry for causing confusion.
Please review. @agatha197 
=> fix: implement Neo Session column's content (2)

react/src/components/ErrorLogList.tsx, react/src/components/TextHighlighter.tsx
Before this PR:
- There was a lag when the user typed quickly in the log search input.
- RegExp didn't work when the user typed text that needed to escapeRegExp, such as n.
This PR improves user search UX.
=> feature: improve log search performance and UX

src/components/backend-ai-session-list.ts
This PR resolves https://github.com/lablup/backend.ai-webui/issues/2148
Before
After
=> fix: improve session status info

react/package-lock.json, react/package.json, react/src/components/BatchSessionScheduledTimeSetting.tsx, src/components/backend-ai-storage-proxy-list.ts
- Install `@babel/plugin-proposal-private-property-in-object` to fix the below warning.
- add type to fix compile error
```
TS7006: Parameter 'date' implicitly has an 'any' type.
47 |             {...datePickerISOProps}
48 |             popupStyle={{ position: 'fixed' }}
> 49 |             disabledDate={(date) => {
|                            ^^^^
50 |               return date.isBefore(dayjs().startOf('minute'));
51 |             }}
52 |             disabled={!isChecked}
```
- `if (storage_volumes !== undefined && storage_volumes.length != 0) {` -> `if (storage_volumes !== undefined && storage_volumes.length **>** 0) {`
- fix antd version to 5.13.2
=> add: type for date

src/components/backend-ai-app-launcher.ts, src/components/backend-ai-session-list.ts
This PR 
- fixes a bug user can not delete a session in Electron app.
=> fix: optional chaining and  handle `_requestDestroySession`

react/src/components/MainLayout/WebUISider.tsx
=> fix:  FastTrack menu key to `pipeline`

react/src/components/MainLayout/MainLayout.tsx
This PR introduces the `theme-logo-url` CSS variable, which changes automatically based on dark/light mode.
=> feat: `theme-logo-url` css variable

src/components/backend-ai-app-launcher.ts, src/components/backend-ai-general-styles.ts, src/components/backend-ai-storage-list.ts
- remove background color in mwc-button
=> style: modify background color more naturally

Makefile
- add cli to remove build files in react folder.
=> feat: 'make clean' removes build files in the react folder

src/lib/backend.ai-client-esm.ts
follows https://github.com/lablup/backend.ai-webui/pull/2303
duplicated code with line number 689.
=> fix: `vfolder-trash-bin` is duplicated

src/components/backend-ai-summary-view.ts
|light|dark|
|---|---|
|<img width="211" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/51399982/7172faad-762c-4492-ad1e-f08f4d4e63e5">|<img width="205" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/51399982/25206892-25f2-4d2a-8bec-59b3ed603e70">|
=> feat: set color for text 'only'

react/src/components/ImageEnvironmentSelectFormItems.tsx, react/src/pages/SessionLauncherPage.tsx
=> fix: regression of applying default session environment

src/components/backend-ai-session-list.ts
- Remove container commit interaction button in `upload session`, In other columns, webui shows interaction button as normal.
=> fix: remove container commit interaction button in `upload session`

src/components/backend-ai-app-launcher.ts
=> feat: add `UserKnownHostsFile` to vs code app guide

src/components/backend-ai-webui.ts
resolve #2282 
After the #2121 PR is merged, many parts of `backend-ai-webui.ts` are no longer used. Let's clean up.
=> refactor: clean up backend-ai-webui.ts

react/src/components/ManageImageResourceLimitModal.tsx
=> hotfix: Rename Relay mutation type file name

react/data/schema.graphql, react/src/components/AllowedHostNamesSelect.tsx, react/src/components/DynamicUnitInputNumberWithUnlimitedFormItems.tsx, react/src/components/FormItemWithUnlimited.tsx, react/src/components/KeypairResourcePolicyList.tsx, react/src/components/KeypairResourcePolicySettingModal.tsx, react/src/hooks/backendai.tsx, react/src/hooks/index.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json
=> New keypair resource policy page

react/src/components/AgentDetailModal.tsx
Set footer to null and modify gutter of `AgentDetailModal`.
---
=> style: set footer to null and styling AgentDetailModal

resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json
=> fix: missing i18n for BAIPropertyFilter

src/components/backend-ai-session-list.ts
Input validation logic for user commit images was not performing properly. Should only allow `4+ English characters, numbers, hyphens and underscores`.
The pattern property of mwc-textfield was not working properly. So I used [Custom Validation](https://www.npmjs.com/package/@material/mwc-textfield/v/0.22.0-canary.59174b9f.0#Validation) instead. 
=> fix: Add user commit image input validation logic

react/src/components/MainLayout/WebUISider.tsx, resources/i18n/it.json
- Fix compiled error
- translation: backend.AI -> Backend.AI
=> fix: compiled and typo error

react/src/App.tsx, react/src/components/InferenceSessionErrorModal.tsx, react/src/pages/EndpointDetailPage.tsx, react/src/pages/EndpointListPage.tsx
This PR only changes the component names related to `Endpoint`.
=> refactor: rename page components related to the `Endpoint` type

react/package-lock.json
There is a missing update related to #2461.
=> fix: missing `react/pacakge-lock.json` update

react/src/components/MainLayout/WebUISider.tsx, react/src/helper/customThemeConfig.ts, resources/theme.json, resources/theme.schema.json
Add `size` and `sizeCollapsed` to `theme.json` for easy modification of the logo size.
---
=> Add size options to `theme.json`

.github/workflows/package.yml
=> ci: add permissions for uploading release assets

src/lib/backend.ai-client-node.ts
Changes the request timeout value from 5000ms to 15000ms to ensure longer requests have enough time to complete. Includes modifications in the Client class within backend.ai-client-node.ts.
---
=> feat: Adjust fetch timeout to 15s for improved UX

react/src/App.tsx, react/src/index.tsx, react/src/pages/VFolderListPage.tsx, src/components/backend-ai-data-view.ts, src/components/backend-ai-webui.ts
Introduced a new feature to preserve the selected tab on the `/data` page based on query parameters.
Replaced the mwc-tab with a React component on the `/data` page and removed several unused components and imports.
Fixed tab layout
| before | after |
| -- | -- |
|  ![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/XqC2uNFuj0wg8I60sMUh/4e005030-821c-4560-a04f-bf4985691231.png) |  ![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/XqC2uNFuj0wg8I60sMUh/12f2d5dd-6499-4b1a-b4f6-dfb85bd3d82b.png) | 
1. **App.tsx**: Added `VFolderListPage` component to the app's routing.
2. **index.tsx**: Removed `ModelStoreListPage` import and unused components like `StorageStatusPanel` and `StorageStatusPanelFallback`.
3. **VFolderListPage.tsx**: Created a new file …
=> feature: preserve selected tab in vfolder list page

resources/fonts/fonts.css
=> fix: Correct references to ubuntu mono bold fonts

react/src/App.tsx, react/src/hooks/useBAISetting.tsx, react/src/pages/InteractiveLoginPage.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json, src/components/backend-ai-webui.ts
This PR introduces a new interactive login page.
This feature can be used by [this PR](https://github.com/lablup/backend.ai-fasttrack/pull/840). Before that PR is merged, we can review and merge this PR into the WebUI.
A new react-based interactive login page has been added to allow users to log in using a Backend.AI account. The login page will present user info and service-related data, and provide options to use an external service or logout.
You can test this change by navigating to the newly added route `/interactive-login?name=Backend.AI+FastTrack&callback=http%3A%2F%2F127.0.0.1%3A3000%2Flogin`.
Make sure the following features work properly:
- Logout
- Redirect to WebUI login(`/login`) when the user is not logged in
- Redirect after the user clicks the login button on the …
=> feat: Interactive Login for SSO

react/src/components/ServiceLauncherPageContent.tsx, react/src/pages/EndpointDetailPage.tsx, react/src/pages/EndpointListPage.tsx
This PR loads saved environment variable of endpoint on update and routing detail for better usability.
By this feature, user can track what they input when executing a service.
=> add: existing environment when modifying endpoint or querying endpoint detail

resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json
Fixed incorrectly specified I18N KEY for ATOM+ devices. 
=> fix: resetting i18n key of atom plus device

src/components/backend-ai-session-list.ts
follows #2524 
This pull request updates the `BackendAISessionList` component to support retrieving logs specific to a selected kernel.
The `get_logs` method of `backendaiclient` has been modified to accept an additional parameter, `kernelId`. If a kernel is selected, logs for that specific kernel will be retrieved. If no kernel is selected, all logs will be retrieved as before. This change affects two places in the `backend-ai-session-list.ts` file where `get_logs` is called.
1. In the UI, select a specific kernel.
2. Trigger a log retrieval action.
3. Verify that the logs retrieved are specific to the selected kernel.
4. Unselect the kernel and trigger log retrieval again.
5. Verify that all logs are retrieved when no kernel is selected.
The motivation behind this change is to provide …
=> fix: 400 error occurs when refreshing container logs

react/src/components/DefaultProviders.tsx, react/src/index.tsx
=> fix: `index.css` for Lucide icon in Electron environment

react/src/components/ModelCloneModal.tsx
=> fix: all cloning folder errors are handled as existing name errors

react/src/components/ModelCardModal.tsx, react/src/pages/ModelStoreListPage.tsx
follows #2533 
Dynamically adjust the size and layout of the model card based on the data. If all data is available, display it in two wide columns.
1. Display in two columns if both description and README exist, and in one column if only one exists. Also, dynamically adjust the size of the modal.
2. Partially reverted the content of #2533 to display the description content in card format.
3. Do not display if description does not exist.
4. Add descriptions to the model store list cards and make it searchable.
1. Navigate to the component displaying the `ModelCardModal`.
2. Ensure the modal's width, description's column span, and README column span adjust dynamically as described.
3. Check description is displayed. The maximum row is 3 and not expandable.
4. The description is searchable. …
=> feat: Improve model card layout and add descriptions to the model store list

react/src/components/lablupTalkativotUI/ChatInput.tsx, react/src/components/lablupTalkativotUI/ChatMessage.tsx, react/src/components/lablupTalkativotUI/ChatUIModal.tsx, react/src/components/lablupTalkativotUI/LLMChatCard.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json
=> feat: Add feature to reset chat and set non-LLM models to custom

react/src/pages/SessionLauncherPage.tsx, src/components/backend-ai-resource-broker.ts, src/components/backend-ai-resource-panel.ts, src/components/backend-ai-session-list.ts, src/components/backend-ai-summary-view.ts
=> fix: too many interval network request

resources/templates/under_construction.html, resources/webui.css, src/components/backend-ai-app-launcher.ts, src/components/backend-ai-credential-list.ts, src/components/backend-ai-credential-view.ts, src/components/backend-ai-dialog.ts, src/components/backend-ai-environment-view.ts, src/components/backend-ai-sidepanel-notification.ts, src/components/backend-ai-sidepanel-task.ts, src/components/backend-ai-signup.ts, src/components/backend-ai-summary-view.ts, src/components/backend-ai-user-list.ts, src/components/backend-ai-webui-styles.ts, src/components/lablup-expansion.ts, src/lib/codemirror/base-style.css.js, src/pipeline/components/pipeline-job-list.ts, src/pipeline/components/pipeline-job-view.ts, src/pipeline/lib/pipeline-configuration-form.ts
Refactor border color definitions to use CSS variables instead of hard-coded values.
- Updated various HTML and CSS files to replace hard-coded border colors with CSS variables `--token-colorBorder` and `--token-colorLink` for better theming support.
- Files affected include HTML templates, CSS files, and multiple TypeScript component files.
1. Run the application and navigate through the UI components that previously had hard-coded border colors.
2. Verify that the borders now follow the appropriate theme based on CSS variables.
3. Ensure no visual regressions are present.
- Improve theming capabilities by centralizing border color definitions using CSS variables.
- Enhance maintainability and consistency of styling across the application.
Before
After
---
=> style: use token value for border colors

src/components/backend-ai-session-list.ts
Add functionality to select multiple sessions using a header checkbox in the BackendAI session list.
- Introduced a new property `_boundHeaderCheckboxRenderer` to bind the header checkbox renderer function.
- Added a new property `sessionAllChecked` to track the state of the header checkbox.
- Implemented `_toggleSelectAll` method to handle the select/deselect all functionality.
- Added `headerCheckboxRenderer` method to render the header checkbox.
1. Navigate to the session list in the BackendAI application.
2. Verify the presence of a header checkbox in the session list table.
3. Click the header checkbox to select all sessions; click again to deselect.
4. Ensure the multi-action buttons are appropriately displayed based on selection.
This change enhances the session management …
=> feat: add a checkbox to select all items in session list

react/src/components/ContainerRegistryEditorModal.tsx, react/src/components/ContainerRegistryList.tsx, react/src/components/KeypairResourcePolicyList.tsx, react/src/components/KeypairResourcePolicySettingModal.tsx, react/src/components/ManageAppsModal.tsx, react/src/components/ManageImageResourceLimitModal.tsx, react/src/components/ProjectResourcePolicyList.tsx, react/src/components/ServiceLauncherPageContent.tsx, react/src/components/UserResourcePolicyList.tsx, react/src/pages/MyEnvironmentPage.tsx
resolves https://github.com/lablup/backend.ai-webui/issues/2546
Refactored multiple components for better error handling.
- Updated `ContainerRegistryEditorModal`, `ContainerRegistryList`, `KeypairResourcePolicyList`, `ProjectResourcePolicyList`, `ManageAppsModal`, `ManageImageResourceLimitModal` to utilize `App.useApp` for message and modal usage.
- Removed unnecessary useMessage and useModal hook calls.
- Enhanced error message display with detailed error information from responses.
1. Trigger various actions that would invoke message and modal displays, such as creating, modifying or deleting registries, resource policies, etc.
2. Verify the error messages are displayed correctly.
To simplify and unify the error handling approach by leveraging `App.useApp` for message and modal …
=> refactor: error feedback UX

react/data/schema.graphql, react/src/components/ModelCardModal.tsx, react/src/pages/ModelStoreListPage.tsx
related PR: https://github.com/lablup/backend.ai/pull/2570
This pull request includes the following changes:
1. **Error message handling:**
- Added error message (`error_msg`) field to `ModelCard`, and `ModelStoreListPage` components. This error messages are displayed only to superadmin and owners.
- Updated `ModelCardModal`, `ModelStoreListPage`, and other related components to properly display error messages when they are present.
- Added `Alert` and `Empty` components to provide better user feedback in case of errors. 
2. **Architecture default value update:**
- Changed the default value for the `architecture` field in various GraphQL types (`Queries`, `Mutations`) from "aarch64" to "x86_64".
1. core part: checkout https://github.com/lablup/backend.ai/pull/2570
2. add a model store …
=> feat: Individual `error_msg` for cards to prevent total list fetch disruption

react/src/components/BatchSessionScheduledTimeSetting.tsx
The `BatchSessionScheduledTimeSetting` component has been updated to enhance date handling and error messaging. The key changes include:
- Added `localFormat` prop to date picker for consistent date formatting.
- Refined conditional rendering for schedule time messages.
- Introduced new error message when the scheduled time is in the past.
- Improved user feedback with contextual messages based on the current state of the `scheduleTime`.
1. Navigate to the component and enable the schedule time setting.
2. Verify that the date picker only allows future dates and uses local date formatting.
3. Check that appropriate messages are displayed based on the selected schedule time:
- A warning message if no schedule time is set.
- A secondary message indicating the time remaining if the schedule …
=> feat: Disable the time before the current HH:MM:SS for today's date

react/src/hooks/useResourceLimitAndRemaining.tsx
=> feat: add property for calculating resource without per container option

react/src/helper/graphql-transformer.test.ts
=> fix: unitended `only` condition of graphql transformer test code

src/components/backend-ai-session-list.ts
Added support for requested slots and improved resource utilization display in the session list.
- Added 'requested_slots' to the list of fields fetched for sessions
- Implemented logic to use requested slots when occupied slots are empty
- Updated resource slot calculations to use the new resourceSlots variable
- Modified the session list UI to handle cases where live stats are not available
- Improved the display of resource utilization (CPU, RAM, GPU, etc.) in the session list
1. Create sessions with different resource configurations (Create maximum of resources to make at least one or two session(s) remain in `PENDING` status)
2. Verify that the session list displays correct resource information for both running and non-running sessions
3. Check that resource utilization is shown …
=> add: requested_slots usage for resource display when occupied_slots are empty

react/src/pages/ResourcesPage.tsx
Added Suspense and Skeleton components to improve loading experience for the AgentList.
| blank white screen | <img width="647" alt="image" src="https://github.com/user-attachments/assets/8afb0918-8ce2-4b21-b1c7-e7e9a4b365d7"> |
=> ui: wrap AgentList with Suspense

e2e/test-util-antd.ts, e2e/test-util.ts, e2e/vfolder.test.ts
=> e2e: vfolder invitation

react/src/pages/EndpointListPage.tsx
=> feat: add endpoint status filtering

react/src/components/BAITable.tsx
This PR improves the BAITable component by implementing dynamic column resizing functionality and refactoring. The changes allow for more flexible and responsive table layouts.
**Key Changes:**
1. **Improved handling of initial column widths when not explicitly specified**.
2. Implemented a `ResizableTitle` component that handles column resizing.
3. Added state management for column widths using `resizedColumnWidths`.
4. Updated the `mergedColumns` logic to incorporate resizable functionality.
These enhancements provide users with a more interactive and customizable table experience, allowing them to adjust column widths according to their needs.
- Use `BAITable` with the `resizable` prop instead of `Table`.
- You should see the same initial column width.
- You can change the column width …
=> feat: resizable columns without specifying width

react/src/components/ImageInstallModal.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/th.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json
**Changes:**
This PR enhances the ImageInstallModal component by:
1. Importing Typography from antd.
2. Improving the layout and styling of the image list:
- Removed border from the List component. Because previous list looks like input field.
- Set width to 100% for better responsiveness.
- Added pagination with 5 items per page.
3. Using Typography.Text to make list items bold.
4. Combining description texts into a single Typography.Text component.
**Rationale:**
These changes improve the visual presentation and user experience of the image installation modal. The pagination feature helps manage long lists of images more effectively, while the styling changes create a cleaner, more modern look.
**Effects:**
Users will experience a more polished and user-friendly interface when …
=> style: improve install image list

react/package.json, react/pnpm-lock.yaml, react/src/components/ComputeSessionNodeItems/ContainerLogModal.tsx, react/src/components/ComputeSessionNodeItems/SessionActionButtons.tsx, react/src/components/SessionDetailContent.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/th.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json
Introduce NEO session container log modal.
This PR adds a new container log viewer feature that allows users to:
- View real-time container logs for compute sessions
- Switch between different kernel roles in multi-container sessions
- Download log contents
- Search through logs with case-insensitive text search
- Auto-scroll to follow new log entries
- Copy session IDs directly from the log viewer
The log viewer uses the `@melloware/react-logviewer` component which provides an efficient virtualized view for handling large log files.
=> feat: NEO session log modal 

react/src/App.tsx, react/src/components/AgentList.tsx, react/src/components/AgentSummaryList.tsx, react/src/pages/AgentSummaryPage.tsx, src/components/backend-ai-webui.ts
Migrates the agent summary view from Web Components to React
This PR migrates the agent summary page to React, providing a modern implementation with improved features:
- Adds new AgentSummaryList component with filtering, sorting and column customization
- Shows detailed resource allocation status with progress bars
- Provides segmented control to switch between connected/terminated agents
- Implements pagination and dynamic data loading
- Removes legacy Web Component implementation
**Checklist:**
The new implementation provides a more maintainable codebase while improving the user experience with modern UI patterns and interactions.
=> refactor: new agent summary page

react/src/components/AgentSummaryList.tsx
resolves https://github.com/orgs/lablup/projects/24/views/12?pane=issue&itemId=88401920&issue=lablup%7Cgiftbox%7C763
Hide sFTP upload agents from the agent summary list
This PR filters out agents that belong to sFTP scaling groups from being displayed in the agent summary list. It fetches the sFTP scaling group configuration via the `/config/get` endpoint and excludes any agents that match those scaling groups from the displayed results.
- Access `sftp_scaling_groups` through the `get` method in the network tab.
- Verify `agent_list` requests by checking `agent_summary_list` in gql.
- Implement frontend-only filtering for agents using `sftp_scaling_groups` in `agent_summary_list`, as they are not yet filtered in server-side.
> endpoint: dogbowl
- Hide agents in the agent …
=> feat: hide sFTP upload agents from agent summary page

react/src/components/BAINotificationButton.tsx, react/src/components/MainLayout/WebUIHeader.tsx
=> fix: notification badge theme color

react/src/components/BAIPropertyFilter.tsx
**Changes:**
Added validation and error handling to the BAIPropertyFilter component:
- Introduced `strictSelection` property to enforce selecting only from provided options
- Added custom validation rules with error messages
- Implemented visual error states and tooltips for invalid inputs
- Added focus handling to control error message display
- Enhanced filter value handling with new merge and combine functions
**Rationale:**
These changes improve form validation and user feedback, ensuring data integrity by:
- Preventing invalid entries when strict selection is enabled
- Providing clear error messages through tooltips
- Supporting custom validation rules per property
- Maintaining consistent error states during user interaction
=> feat: strict selection mode of BAIPropertyFilter

pnpm-lock.yaml, react/pnpm-lock.yaml
This PR resolves [#2959](https://github.com/lablup/backend.ai-webui/issues/2959).
> Prerequisites: you need to install pnpm in target machine. (Install guide: https://pnpm.io/installation)
1. Execute command `pnpm i` 
2. Check whether installation is successfully done or not.
=> update: pnpm-lock file to apply  properly

react/src/components/AgentDetailModal.tsx
resolves https://github.com/lablup/backend.ai-webui/issues/2946
**Changes:**
- Improved decimal precision in percentage displays by adding `.toFixed(1)` to ensure consistent one decimal place
- Increased network traffic (TX/RX) decimal precision from 1 to 2 places for more accurate readings
**Impact:**
These changes provide more precise numerical representations in the Agent Detail Modal, particularly for percentage values and network traffic measurements, leading to better monitoring accuracy.
1. Visit Resources page.
2. Click the info icon of any agent.
**Checklist:**
=> fix: Update resource acquisition notation elements.

react/src/components/UserInfoModal.tsx
Removes unused Button import from antd in UserInfoModal component
=> fix: lint error

react/src/components/BAIPropertyFilter.tsx
Resolves #3095 (FR-460)
In the `BAIPropertyFilter` component, when the `value` is explicitly set to `undefined`, it should be treated as having no value rather than being in an uncontrolled mode. Currently, this causes issues where the component's internal state does not update when the `value` is changed via props from the parent, rather than being reset by the user. This issue needs to be addressed to ensure proper state management.
Replaces `useDynamicList` with `useControllableValue` in the BAIPropertyFilter component to improve filter state management. This change:
- Introduces key-based filter tracking for more reliable tag removal
- Simplifies filter value updates through a centralized update function
- Fixes empty string handling in filter parsing
- Removes unnecessary effect hook …
=> refactor(FR-460): handle undefined value as controlled value in BAIPropertyFilter

react/src/components/MainLayout/MainLayout.tsx, react/src/components/WebUIBreadcrumb.tsx, react/src/pages/InteractiveLoginPage.tsx
resolves [FR-439](https://lablup.atlassian.net/browse/FR-439?atlOrigin=eyJpIjoiYjJhMmQ0NzBjYjIxNDc5ZGE3NTQwOGEzZjQwOTlhZDEiLCJwIjoiaiJ9)
Exports the `NotificationForAnonymous` component from MainLayout and adds it to the InteractiveLoginPage to ensure anonymous users receive proper notifications during interactive login sessions.
**Checklist:**
1. Visit `interactive-login`.
2. Enter invalid login info.
1. Check you can see the notification.
[FR-439]: https://lablup.atlassian.net/browse/FR-439?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(FR-439): Silent error in interactive-login

react/src/RelayEnvironment.ts, react/src/components/MainLayout/MainLayout.tsx, react/src/components/MainLayout/WebUIHeader.tsx, react/src/components/NetworkStatusBanner.tsx, react/src/components/SiderToggleButton.tsx, react/src/components/UserDropdownMenu.tsx, react/src/pages/SessionLauncherPage.tsx, src/lib/backend.ai-client-esm.ts, src/lib/backend.ai-client-node.ts
resolves #3056 (FR-408)
> [!NOTE]  
>This PR implements the Global soft timeout section from the Network Timeout UX guide written in Loop document.
Implements network status monitoring improvements and request timeout handling:
1. Added a soft timeout notification that appears after 15 seconds of waiting for network requests
2. Moved the NetworkStatusBanner below the WebUIHeader for better visual hierarchy
3. Standardized request timeout handling:
- Default timeout: 30 seconds
- Soft timeout: 15 seconds
- Removed hardcoded timeout values across the codebase
- only [`recalculate_usage`](https://github.com/lablup/backend.ai-webui/blob/4fceaeaafcf23c3ab9acb45999c5aaae813eff7d/src/lib/backend.ai-client-esm.ts#L4520-L4530) request remain specific hardcoded timeout.
The soft timeout alert view …
=> feat(FR-408): add soft timeout feature to NetworkStatusBanner

src/lib/backend.ai-client-esm.ts
resolves #3165 (FR-524)
Increases the request soft timeout from 15 seconds to 20 seconds to provide more time for API requests to complete before triggering timeout warnings.
=> chores(FR-524): increase default soft-timeout to 20s

index.html, manifest.json, package.json, react/package.json, version.json
Bump version to 25.3.0-alpha.0
=> chore: bump version to 25.3.0-alpha.0 for dev

react/src/helper/index.tsx, react/src/pages/ComputeSessionListPage.tsx
=> refactor(FR-492): row selection change handling

react/src/components/BAIMenu.tsx, src/components/lablup-activity-panel.ts
resolves #NNN (FR-467)
**changes**
* add margin to sidebar menu
* add `overflow: hidden` to card css
=> feature(FR-467): Enhance Sidebar and Card UI

react/craco.config.js, react/package.json, react/pnpm-lock.yaml, react/src/components/Chat/EndpointLLMChatCard.tsx, react/src/components/FluentEmojiIcon.tsx, react/src/pages/AIAgentPage.tsx, resources/ai-agents.json
resolves #3239 (FR-553)
- Add FluentEmojiFlat Component to display fluent-emoji from json resource
=> feat(FR-533): Add fluent-emoji-flat component

react/src/pages/AIAgentPage.tsx, resources/ai-agents.json
resolves #3281 (FR-609)
Adds a new Lablup Customer Support Bot agent and fixes title wrapping in AI agent cards.
=> feat(FR-609): Add lablup customer service agent

react/package.json, react/pnpm-lock.yaml
resolves #3290 (FR-611)
- Fix that failed error from Jest test
=> fix(FR-611): add babel-preset-react-app

react/src/components/ResourcePresetList.tsx
resolves [FR-659](https://lablup.atlassian.net/browse/FR-659)
This PR adds a new column to display the scaling group name (resource group) in the Resource Preset List component. The column is conditionally rendered based on whether the backend client supports the 'resource-presets-per-resource-group' feature.
Key changes:
- Added `scaling_group_name` field to the GraphQL query with a version constraint (`@since(version: "25.4.0")`)
- Created a proper TypeScript type for resource presets
- Refactored the table columns definition to use `filterEmptyItem` for conditional rendering
- Improved column sorting functionality
- Added proper type definitions using `ColumnType` from Ant Design
1. Login dogbowl with admin.
2. Visit `/environment?tab=preset`
**Checklist:**
[FR-659]: …
=> feat(FR-659): show resource group to resource preset list

pnpm-lock.yaml, react/package.json, react/src/components/AgentList.tsx, react/src/components/BAISider.tsx, react/src/components/Chat/LLMChatCard.tsx, react/src/components/DatePickerISO.tsx, react/src/components/ErrorLogList.tsx, react/src/components/Flex.tsx, react/src/components/ImageList.tsx, react/src/components/InferenceSessionErrorModal.tsx, react/src/components/SessionLauncherPreview.tsx, react/src/components/SettingList.tsx, react/src/components/ShellScriptEditModal.tsx, react/src/components/SummaryPageItems/SummaryItemInvitation.tsx, react/src/pages/StartPage.tsx
resolves #3385 (FR-687)
This pull request includes various improvements and fixes to the React codebase, focusing on ESLint configuration updates, adding `displayName` to components, and ensuring unique keys in lists. The most important changes are summarized below:
* Added `eslint-plugin-react` to the ESLint configuration and updated rules to disable `react/react-in-jsx-scope` and `react/prop-types` checks. (`react/package.json`) [[1]](diffhunk://#diff-5a3f058f37c9436d08fa97bd30209f67c9a1a61d041b0ce27e48613dfb3a1a10L82-R88) [[2]](diffhunk://#diff-5a3f058f37c9436d08fa97bd30209f67c9a1a61d041b0ce27e48613dfb3a1a10R137)
* Added `displayName` to `BAISider`, `DatePickerISO`, and `Flex` components to improve debugging and component identification. (`react/src/components/BAISider.tsx`, …
=> chore(FR-687): set up `react/recommended` lint plugin

pnpm-lock.yaml, react/src/components/DynamicUnitInputNumber.tsx, react/src/components/ResourceAllocationFormItems.tsx
resolves #3400 (FR-701)
The main purpose of this PR is to resolve the bug related to the MEM value changing unexpectedly when blurring a form item.
In `DynamicUnitInputNumber`, 
🔑 Key change:
- Adds proper handling of `ref` prop to allow external components to access the input element
Additional improvement:
1. Improves the rounding logic in the `onBlur` handler to respect min/max boundaries
2. Adds validation to prevent setting invalid values when using the roundStep feature
3. Converts min/max values to the current unit for proper boundary validation
4. Removes commented-out code in ResourceAllocationFormItems component
The changes ensure that when users input values that need to be rounded according to the roundStep parameter, the component properly validates against minimum and …
=> fix(FR-701): MEM value changed unexpectedly issue when blurring form item

react/src/components/AvailableResourcesCard.tsx, react/src/components/BAIPanelItem.tsx
resolves [#3372](https://github.com/lablup/backend.ai-webui/issues/3372) ([FR-675](https://lablup.atlassian.net/browse/FR-675))
This PR refactors the AvailableResourcesCard component to use Ant Design's Row and Col components instead of custom Flex layouts. The changes include:
- Replaced custom Flex containers with Row and Col components for better responsive layout
- Added proper dividers between resource sections
- Improved styling for resource cards with consistent padding and overflow handling
- Removed hardcoded height constraints for better responsiveness
- Added special styling for accelerator slots with proper background highlighting
These changes improve the layout consistency and responsiveness of the resource display cards.
| Before …
=> bug(FR-675): Resource items are overlapped when window size is narrow.

react/src/components/Chat/Conversation.tsx
resolves #3380 (FR-681)
This PR adds a filter to the query that retrieves `endpoint_list` in `Conversation` component, so that only active endpoints are fetched.
**changes**
* add `lifecycle_stage == "created"` filter to query that retrieves `endpoint_list` in `Conversation` component.
=> fix(FR-681): Add lifecycle_stage filter to endpoint_list query to get active endpoints

react/src/components/Chat/ChatCard.tsx
Resolves #3435 (FR-748)
This PR refactors the ChatCard component to better handle custom models and endpoints. Key changes:
- Added state management for chat ID with a unique identifier based on endpoint, agent, and model
- Replaced the static `providerSettings` object with a dynamic form value getter function
- Moved the ID generation logic into a useEffect to ensure proper updates when dependencies change
- Improved code organization for fetching custom model settings from the form
These changes make the chat component more robust when switching between different models and endpoints.
=> fix(FR-748): Update chat id as model changed

src/components/backend-ai-login.ts
resolves #NNN (FR-556)
This PR trim for all values required for login.
**changes**
* In the `_login()` function, perform a trim on all values required for login.
=> feat(FR-556): trim to all input fields used during login

react/src/components/ResourcePresetSettingModal.tsx
resolves https://github.com/lablup/backend.ai-webui/issues/3582 (FR-906)
=> fix(FR-906): cannot create and modify resource preset when memory is null

react/src/components/VFolderTable.tsx
resolves #3592 (FR-917)
> The vfolder list REST API does not support filtering based on group_id.
Since the vfolder list REST API does not support filtering by group_id, I perform filtering based on the current project id through a separate filter in the response of the vfolder list API.
=> fix(FR-917): Restrict `VFolderSelect` component to show vfoldes by current project

react/src/components/AboutBackendAIModal.tsx, react/src/components/MainLayout/WebUISider.tsx, react/src/components/UserDropdownMenu.tsx, src/components/backend-ai-splash.ts
resolves #NNN (FR-993)
Migrate the `About Backend.AI` modal from that PR to a React component in NEO Style.
**changes**
* add `AboutBackendAIModal`
* Changed the existing logo to NEO Style's logo
* delete `backend-ai-splash.ts`
|before|after|
|----|----|
|![CleanShot 2025-05-14 at 15.36.49@2x.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/xbCemO1RqqcSjEXCRK3p/8dc41844-bd91-4e2f-a8aa-12f625d7dd85.png)| ![CleanShot 2025-05-14 at 15.36.42@2x.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/xbCemO1RqqcSjEXCRK3p/792e4c51-64c7-415c-baee-c1b608bbb30c.png)|
=> refactor(FR-993): migrate About Backend.AI modal to NEO Style react component

src/components/backend-ai-folder-explorer.ts
Resolves #3710 ([FR-1031](https://lablup.atlassian.net/browse/FR-1031))
This PR enhances the SSH session creation process by dynamically using resource limits defined in system role images. Instead of hardcoding CPU and memory values, it now:
1. Adds TypeScript interfaces for `ResourceLimit` and `SystemRoleImage` to improve type safety
2. Extracts minimum CPU and memory requirements from the selected system role image
3. Falls back to default values (1 CPU, 256MB memory) if limits aren't defined in the image
This change ensures SSH sessions are created with appropriate resource allocations based on the image's requirements rather than using fixed values.
**Checklist:**
[FR-1031]: https://lablup.atlassian.net/browse/FR-1031?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwI …
=> feat(FR-1031): Resource allocation of SFTP session based on Image limit

react/src/components/ResourceAllocationFormItems.tsx
resolves #3822 [(FR-1115)](https://lablup.atlassian.net/browse/FR-1115)
In that PR, I fixed the shmem form item for the resource preset in the session launcher to display properly.
**changes**
* Fixed `updateResourceFieldsBasedOnPreset` function to also change `enabledAutomaticShmem` value based on shmem.
* Excluded shmem Form.item from conditional rendering for better validation.
**how to test**
1. Set the preset with shmem set to 1st.
2. Make sure the shmem switch is manual when the corresponding preset is set to automatic in the session launcher.
3. Verify that the validator works when the shmem is more than half of the application memory.
=> fix(FR-1115): Modify to display the appropriate form item for shmem based on the resource preset in the session launcher

package.json
resolves (FR-1205)
This PR enhances our pre-commit hooks by adding ESLint auto-fix with zero warnings tolerance to our lint-staged configuration. The changes apply to:
- React source files
- General source files
- End-to-end test files
- Backend.ai-ui package source files (newly added to lint-staged)
This ensures code quality issues are automatically fixed before commit and prevents committing code with ESLint warnings.
=> chore(FR-1205): run prettier and eslint at pre-commit

react/src/components/ActionItemContent.tsx, react/src/pages/VFolderNodeListPage.tsx
This PR enhances the UI layout in the VFolderNodeListPage by:
1. Adding a `style` prop to the `ActionItemContent` component to allow custom styling
2. Improving the responsive layout with better column sizing (adding xxl breakpoint)
3. Making cards maintain consistent height with `minHeight` instead of fixed height
4. Using flex display for columns to ensure cards fill the available space
5. Simplifying the layout structure by removing unnecessary nested Flex container
These changes ensure a more consistent and responsive layout across different screen sizes.
**Before:**
Too wide
Cannot see the bottom button
**After:**
**Checklist:**
=> style(FR-1242): folder create panel layout was broken

packages/backend.ai-ui/src/components/BAICard.tsx, react/src/App.tsx
Resolves #4035 ([FR-1309](https://lablup.atlassian.net/browse/FR-1309))
Enhance user experience by improving component styling and loading state handling in the React application.
- **BAICard.tsx**: Remove unnecessary `marginBlock` styling that may cause layout inconsistencies
- **App.tsx**: Add Suspense wrapper with Skeleton loading fallback for DashboardPage to provide better user feedback during component initialization
[FR-1309]: https://lablup.atlassian.net/browse/FR-1309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> style(FR-1309): improve UI loading states and component styling

resources/i18n/ko.json, src/components/backend-ai-summary-view.ts
Follow-up of #2786 and resolves #4039 (FR-1312)
| ------- | ----- |
| <img width="734" height="526" alt="image" src="https://github.com/user-attachments/assets/4e7d2246-56de-4ab9-949b-8174ab60e565" /> | <img width="734" height="526" alt="image" src="https://github.com/user-attachments/assets/b2039d1b-6e1f-4a0b-b3b9-213b4589426f" /> |
=> fix(FR-1312): align label in invitations summary panel

src/components/backend-ai-app-launcher.ts
resolves #3972 (FR-1258)
In this PR, I have centered the guide image and enhanced the responsiveness to make the layout more natural.
=> fix(FR-1258): center guide image and improve layout on narrow pages

e2e/environment.test.ts, e2e/utils/test-util-antd.ts
resolves #4092 (FR-1337) (FR-1339)
This PR enhances the environment test suite by:
1. Refactoring the test setup to use a common beforeEach hook for login and navigation
2. Improving the resource limit modification test with more precise input handling:
- Using direct input fields instead of sliders for CPU and memory values
- Adding explicit verification of form values before and after changes
- Properly handling memory unit selection (GiB)
3. Adding proper waiting for network idle states to ensure test stability
4. Fixing menu item selection by using exact matching and selecting the first match
**Checklist:**
=> e2e(FR-1337): fix broken e2e test of envrionments

react/src/components/BaseResourceItem.tsx, react/src/components/MyResource.tsx, react/src/components/RecentlyCreatedSession.tsx, resources/i18n/de.json, resources/i18n/el.json, resources/i18n/en.json, resources/i18n/es.json, resources/i18n/fi.json, resources/i18n/fr.json, resources/i18n/id.json, resources/i18n/it.json, resources/i18n/ja.json, resources/i18n/ko.json, resources/i18n/mn.json, resources/i18n/ms.json, resources/i18n/pl.json, resources/i18n/pt-BR.json, resources/i18n/pt.json, resources/i18n/ru.json, resources/i18n/th.json, resources/i18n/tr.json, resources/i18n/vi.json, resources/i18n/zh-CN.json, resources/i18n/zh-TW.json
Resolves #4160 ([FR-1383https://lablup.atlassian.net/browse/FR-1383))
Fix missing i18n key and HTML rendering issues in tooltip components.
- **Missing i18n key**: The tooltip was not displayed correctly due to the missing RecentlyCreatedSessionsTooltip key
- **HTML rendering**: i18n messages containing HTML tags (e.g., p tags) were displayed as plain strings instead of rendered HTML
- ✅ Added missing RecentlyCreatedSessionsTooltip key to all 21 language files
- ✅ Modified MyResource.tsx to use Trans component for proper HTML rendering in tooltips
- ✅ Updated BaseResourceItem.tsx tooltip prop type from string to ReactNode to support React components
- ✅ Enhanced RecentlyCreatedSession.tsx to support parameterized tooltips with count values
- ✅ Added i18n-ally regex patterns to …
=> fix(FR-1383): add missing i18n key and fix HTML tooltip rendering

react/src/components/BAIBoard.tsx
Removes unnecessary CSS class from BAIBoard component
=> fix: remove unexpected class name

react/src/components/ServiceLauncherPageContent.tsx, react/src/components/SessionFormItems/ResourceAllocationFormItems.test.ts, react/src/components/SessionFormItems/ResourceAllocationFormItems.tsx, react/src/components/SessionFormItems/SharedMemoryFormItems.tsx, react/src/hooks/useResourceLimitAndRemaining.tsx, react/src/pages/SessionLauncherPage.tsx
Resolves #4302 ([FR-1492](https://lablup.atlassian.net/browse/FR-1492))
This PR refactors the ResourceAllocationFormItems component structure to improve code organization and maintainability.
- **Moved** `ResourceAllocationFormItems` component from `react/src/components/` to `react/src/components/SessionFormItems/` directory for better organization
- **Extracted** shared memory form logic into a separate `SharedMemoryFormItems` component (~240 lines) to improve code modularity and reusability
- **Updated** import paths in all dependent files and test files
- **Reduced** main component complexity by ~335 lines while maintaining all existing functionality
- Better code organization with grouped session form components
- Improved separation of concerns between resource allocation and shared …
=> refactor(FR-1492): extract SharedMemoryFormItems from ResourceAllocationFormItems

packages/backend.ai-ui/package.json, packages/backend.ai-ui/src/components/BAINotificationItem.tsx, packages/backend.ai-ui/src/components/index.ts, pnpm-lock.yaml, react/package.json, react/src/App.tsx, react/src/components/BAIGeneralNotificationItem.tsx, react/src/components/BAINodeNotificationItem.tsx, react/src/components/BAISessionNotificationItem.tsx, react/src/components/ComputeSessionNodeItems/AppLauncherModal.tsx, react/src/components/ComputeSessionNodeItems/SessionActionButtons.tsx, react/src/components/ComputeSessionNodeItems/SessionStatusTag.tsx, react/src/components/WEBUINotificationDrawer.tsx, react/src/components/__snapshots__/DomainSelector.test.tsx.snap, react/src/hooks/useBAINotification.tsx, react/src/pages/ComputeSessionListPage.tsx, react/src/pages/SessionLauncherPage.tsx
This PR adds a new `BAINotificationItem` component to the UI library and enhances the notification system to support node-specific notifications. It also upgrades the Ant Design library from 5.24.5 to 5.27.4.
Key changes:
- Added `BAINotificationItem` component to the UI library for consistent notification styling
- Created specialized notification components for different types:
- `BAIGeneralNotificationItem` for standard notifications
- `BAINodeNotificationItem` for node-specific notifications (sessions, folders)
- `BAISessionNotificationItem` for session-specific notifications
- Enhanced `SessionActionButtons` to support hiding specific buttons and improved small size display
- Updated notification drawer to use the appropriate notification item based on content type
- Fixed React …
=> feat(FR-1494): improve UX for session creation related to enqueueOnly and App launcher

react/src/hooks/useIntervalValue.tsx
**Changes:**
- Fixed dependency array in the callback effect to prevent unnecessary re-renders
- Simplified page visibility handling logic
- Created an `effectiveDelay` variable to centralize the delay calculation logic
- Removed redundant conditional checks in the interval effect
- Improved code organization with clearer separation of concerns
=> fix(FR-1552): fix infinite re-rendering in useInterval hook
