- src/components/backend-ai-resource-monitor.ts
- src/components/backend-ai-session-list.ts
* Fix broken image parsing for images without namespace (eg: `registry.test.io/gpp:test-t114`).
* Handle registry with port number. For example, now it is possible to correctly parse a registry like `127.0.0.1:8888`.
* Add default image information for custom images which are not registered in `image_metadata.json`.
* Fix version number is displayed twice for NGC images.
* Hide registry text from session info since it may expose the IP address of private docker registry.
* Display image namespace, if exists, of custom a image.
* I set custom image's version string color with grey.
Before this PR:
After this PR:
> Fix broken image registry/name/tag parsing for custom images

- src/components/backend-ai-session-list.ts
This pull request resoles #373.
The root cause of this problem is that the [`item` in `sessionInfoRenderer `](https://github.com/lablup/backend.ai-console/blob/master/src/components/backend-ai-session-list.ts#L1069) always contains the same `tag`, regardless of the real version (which is stored in `rowData.item.baseversion`). For example, when I launched two `python-tensorflow` sessions each with version 1.13 and 2.0, the `item.tag` is always 2.0 even for 1.13 session:
I don't know the logic behind displaying those items and tags (it's too complex in my opinion), so I just override the `tag` with real `rowData.item.baseversion`.
> Use baseversion for version tag, only when category exists

- src/components/backend-ai-resource-preset-list.ts
Two consecutive creation of resource presets fail since some values of input controls are set to numbers after the first creation, which causes error in the following line:
```javascript
const wrapper = v => v !== undefined && v.includes('Unlimited') ? 'Infinity' : v;
```
If `v` is number, then there is no `includes` method. This pull-request just converts `v` to `string` before calling `includes` method:
```javascript
const wrapper = (v) => {
v = v.toString();
return v !== undefined && v.includes('Unlimited') ? 'Infinity' : v;
};
```
> fix: variable v should be a string to call includes method

- src/components/backend-ai-storage-list.ts
In folder explorer dialog, there is a folder navigation bar over UPLOAD FILES and NEW FOLDER icons. The home folder is represented here as dot (`.`), and it is so small to click.
This pull-request simply changed the dot (`.`) into a larger folder icon.
before:
after:
> style: larger home folder icon in folder explorer path navigator

- src/components/backend-ai-session-list.ts
* Destroying PREPARING/PULLING kernel has no effect since the session will be created anyway. This confuses user.
* In API v4, it is not possible to see logs for PREPARING/PULLING sessions. So, I just disabled show log button as well.
> fix: prevent PREPARING/PULLING deletion

- src/components/backend-ai-resource-monitor.ts
- src/components/backend-ai-resource-preset-list.ts
This PR resolves https://github.com/lablup/backend.ai-console/issues/555.
* Explicitly set cpu/mem values for corresponding components while updating resource indicator.
* Fix a bug that maxmum value of # of sessions is set to zero in initial opening of session launch dialog.
- Disable session launch button for 1 second. Without this waiting, `_aggregateResourceUse` may not be eecuted due to `lastQueryTime` block.
- Reduce query interval of `_aggregateResourceuse` from 2 s to 1 s to quickly enable session launch button.
* Fix a bug that shared memory sometimes cannot be set in resource preset creation / modification.
- e.g.: It was not possible to set 2 g of shared memory for 10 g of memory.
- `"2g" > "10g"` is judged as `true`, so error message raised that states shared memory cannot be …
> fix: explicitly set cpu/mem values for corresponding components

- src/components/backend-ai-resource-monitor.ts
This PR resolves https://github.com/lablup/backend.ai-console/issues/581.
ref: OP#493
> fix: fallback to current gpu mode if there is a gpu request but without gpu type.

- resources/i18n/en.json
- resources/i18n/ko.json
- src/components/backend-ai-resource-preset-list.ts
This PR resolves #626.
* During creation, memory and shared memory values are compared as string, like `"1g" > "11g"`, which is evaluated as `true`. This PR fixed it to `parseInt` before comparison.
* Add more i18n support in creating/updating resource preset.
> bugfix: error when creating resource preset

- src/components/backend-ai-session-list.ts
This PR resolves #640.
Related: OP#675.
> fix: add sessionUuid to work dialog when fetching first logs

- src/components/backend-ai-storage-list.ts
I tried to find out the best way to ignore when the user clicks rapidly in the directory access icon(button) except using setTimeout, since setTimeout triggers unexpected results sometimes, and gives extra loads. Unfortunately, I couldn't get a decent solution to this. At least the main purpose of this PR is to avoid accessing non-existing sub-directory from the current directory path, and about that purpose, this PR works OK.
Still, there are some minor issues left.
Some click events are ignored when the user clicks the button, not often but it occurs.
If there is any idea to just fit in this issue, I would gladly replace from current commits.
> fix: Multiple clicks cause duplicated directory path

- resources/i18n/en.json
- resources/i18n/ko.json
- src/components/backend-ai-environment-list.ts
After merging this PR, there are several things will be changed in Images tab of 'Environments & Presets' page.
※ NOTICE: This feature is available in admin or super-admin account only.
You can see the detail below. (unchecked features are WIP.)
> fix: checkbox feature downsize in image downloading

- src/components/backend-ai-console.ts
> fix: backend.AI logo routes to the summary page

- src/components/backend-ai-credential-view.ts
> NOTICE: only admin or super-admin have an access to 'Users' page.
This is the hotfix for force activating inner-tabs(active and inactive) of 'Users' page.
After this PR, when the user clicks the tab with inner-tab in the 'Users' page will automatically activates inner 'active' tab of each tab.
> fix: show inner tab of users page properly

- src/components/backend-ai-usersettings-general-list.ts
This is a hotfix for public SSH key initialized issue after refreshing the page.
After merging this PR, the public keypair will be remained whether there's page refreshing operation occurred or not, except for generating new SSH keypair by user.
> fix: remain SSH keypair after generation

- src/backend-ai-app.ts
- src/components/backend-ai-console.ts
Refreshing from admin pages always result in redirection to the summary page, even for admins.
> fix: remove logic where is_amdin is not defined

- src/components/backend-ai-login.ts
- src/components/backend-ai-painkiller.ts
This PR resolves https://github.com/lablup/backend.ai-console/issues/860.
When API keypair is not accessible in `_connectViaGQL`, just automatically logout to invalidate existing session information.
> fix: automatic logout when API keypair is not accessible

- src/components/backend-ai-console-styles.ts
- src/components/backend-ai-console.ts
- src/components/backend-ai-credential-view.ts
- src/components/backend-ai-session-view.ts
- src/components/lablup-notification.ts
This PR contains two minor bug fix.
- notification error exposed in browser console in Safari (version: 14.0).
screenshot: 
- limit max-width of sidebar and preserve logo ratio and size in the header of sidebar. (reported by @adrysn)
> fix: notification error in safari and limit max-width of sidebar

- src/components/lablup-slider.ts
After merging this PR, the value error will be handled, which triggered by the status that min value greater than max value
in lablup-slider component.
> fix: monkeypatch for min, max value force adjustment in lablup-slider

- src/components/backend-ai-app-launcher.ts
- src/components/backend-ai-console-styles.ts
- src/components/backend-ai-console.ts
- src/components/backend-ai-credential-view.ts
- src/components/backend-ai-permission-denied-view.ts
- src/components/backend-ai-resource-policy-list.ts
- src/components/backend-ai-signup.ts
After merging this PR, several cosmetic issues will be solved.
You can see the details below.
- make an equal ratio of each input field in creating user dialog.
- centered align for each label in resource policy create/update dialog
- centered align for checkbox and text for terminal guide dialog
- prevent overlapping from screen height shorter than the drawer menu
- support responsive layout for permission-denied page.
> fix: rearrange layout

- src/components/backend-ai-storage-list.ts
This PR is a hotfix for filebrowser related bug, which occurred by accessing and changing the property of the non-existing element.
> fix: disable filebrowser button only when it is visible

- src/components/backend-ai-session-list.ts
Per-container GPU utilization is 0 or 100 due to multiplication by 100 to the percentage value.
> fix: invalid calculation logic for GPU utilization

- src/components/backend-ai-usersettings-general-list.ts
This PR is hotfix for #934 due to unexpected config file saving request on clicking "SAVE" button after clicking the close button (``x``)on the right top of the user config dialog.
> fix: update previously selected rcfile to currently selected rcfile

- src/components/backend-ai-app-launcher.ts
Before fixing, the web terminal guide is cropped because the dialog size is fixed.
So I changed the size of the terminal guide dialog according to screen size.
this closes #988
> bugfix: resize the web terminal guide according to window size

- src/components/backend-ai-app-launcher.ts
> fix: Replace the link detail view in the Web Terminal Guide with the correct url

- src/components/backend-ai-session-launcher.ts
> fix: overlapping environment section in session launcher dialog

- src/components/backend-ai-registry-list.ts
the password masking on the "Add Registry" dialog is a triangle because the Roboto font does not support the circle icon. 
So, I added a font style to add-registry-password.
this PR closes #993
> change the password icon

- README.md
- config.toml.sample
- src/components/backend-ai-login.ts
- src/components/backend-ai-session-launcher-legacy.ts
- src/components/backend-ai-session-launcher.ts
This PR resolves two things.
- issue #1063 
- new config value for the maximum value of memory per container. (`maxMemoryPerContainer`)
Also, `maxMemoryPerContainer` will be added to README file and sample config file.
> fix: Clamp resource value in session launcher

- src/components/backend-ai-session-launcher-legacy.ts
- src/components/backend-ai-session-launcher.ts
- src/components/lablup-progress-bar.ts
- src/components/lablup-slider.ts
This PR resolves #1069.
Also for better user experiences, Environment and Version selection are disabled when the input field of the manual image is not empty.
> fix: apply manual image name in session creating

- src/components/backend-ai-storage-proxy-list.ts
Rename properties and method to make sure that it is about storage-proxy, not about agents. 
I did not change the names related to notification which is translated to various languages (e.g. line 141 `this.storageProxyDetailDialog = this.shadowRoot.querySelector('#agent-detail');` ).
> feat: rename property and method

- src/components/backend-ai-session-view.ts
resolve #1113 
* cause
`width : auto;` is not work in flex container
* solution
1. add `style="width: 100%"` to `<lablup-activity-panel title="${_t('summary.ResourceStatistics')}" elevation="1" autowidth>`
ex)
`<lablup-activity-panel title="${_t('summary.ResourceStatistics')}" elevation="1" style="width">`
2. remove a div element which contains `<lablup-activity-panel title="${_t('summary.ResourceStatistics')}" elevation="1" autowidth>` with a class attribute with the value of "horizontal layout wrap"
* conclusion
I chose solution 2.
* result
screen width ≥ 1418px
700px ≤ screen width < 1418px
screen width < 700px
> feat : change width Resource Statics panel

- resources/i18n/en.json
- resources/i18n/ko.json
- src/components/backend-ai-settings-view.ts
- Add overlay network setting dialog on the setting page.
- When clicking the `Config` button, you can change the MTU option.
- For code reusability, I changed some properties and functions like `schedulerOptionsAndId`,`_showEnvDialog()`.
Internal Ticket: OP#1458
Related PR: [manager#475](https://github.com/lablup/backend.ai-manager/pull/475)
> feat: add overlay network settings dialog and increase code flexibility

- src/components/backend-ai-session-launcher.ts
Only when the OpenMPswitch is not checked, HPC option fields can be filled out and they are shown.
If users didn't fill out the HPC option, then set it to 1.
> feat: hide HPC optimization option group

- src/components/backend-ai-settings-view.ts
Fix: Make the text of the config button horizontally.
Is your feature request related to a problem? Please describe.
On the configurations page, when the system language setting is Korean, the text of the config button looks vertical. Make the text of the config button horizontally whatever the language environment it is.
I fix to make the text of the config button horizontally.
> Fix: Make the text of the config button horizontally

- src/components/backend-ai-data-view.ts
- src/components/backend-ai-storage-list.ts
This resolves https://github.com/lablup/backend.ai-webui/issues/1158.
This PR needs manger's [PR to allow users to get/set vfolder quota](https://github.com/lablup/backend.ai-manager/pull/492).
> fix: use user-accessible API for getting storage backend information

- package.json
This PR resolves regression of missing package, [`@vaadin/vaadin-text-field`](https://github.com/vaadin/web-components/tree/master/packages/text-field)
> update: node.js packages

- src/components/backend-ai-data-view.ts
- src/components/backend-ai-resource-monitor.ts
- src/components/backend-ai-scaling-group-list.ts
- src/components/backend-ai-settings-view.ts
- src/components/backend-ai-user-list.ts
- `mwc-switch` doesn't use checked property and overrides click method (not change).
> fix: mwc-switch not working

- src/components/backend-ai-app-launcher.ts
- this resolves #1175 
- If you click the icon button, then the controller was set to the image, not `mwc-icon-button`.
- So I force to set the controller to `mwc-icon-button`.
> fix: can't run app by clicking the app icon.

- config.toml.sample
- src/components/backend-ai-login.ts
- src/components/backend-ai-signup.ts
---------
This PR resolves #1185.
---------
No options about hiding unnecessary input fields and messages in signup dialog, such as "token" and "email sent msg".
---------
Now `allowSignupWithoutConfirmation` stands for the visibility "token" input field and "emails sent msg".
if the value of `allowSignupWithoutConfirmation` in configuration file (`config.toml`) is `true`, then it will be regarded as "sign up without confirmation" as is, so signup dialog will not display "token" input field or "email sent msg" after registration.
> feat: toggle token email confirmation option

- src/components/backend-ai-session-launcher.ts
This resolves https://github.com/lablup/backend.ai-webui/issues/1191.
> fix: do not disable the gpu resource slider when the min and max value of it is the same

- src/components/backend-ai-session-list.ts
This PR will resolve errors that originated from multi-node session creation.
Some of the error msg didn't have a key `collection`, therefore accessing the `collection` key triggered error.
Now users can see error msg regardless of the hierarchy of error msg.
**Screenshot:**
> hotfix: support displaying error when multi-node session creation failed

- src/components/backend-ai-session-list.ts
- Adjust the height to remove the wide blanks in the log dialog.
- Adjust the width to increase the consistency
[Screenshot]
- wide screen
-narrow screen
> style: change width and height of log dialog

- src/components/backend-ai-login.ts
- src/components/backend-ai-session-launcher.ts
- src/components/backend-ai-session-list.ts
- src/components/backend-ai-signup.ts
- src/components/lablup-codemirror.ts
This PR will resolve overflowing list-items in the environment selection UI in session launcher.
When items in the supported environment list exceed 7 or more, the scrollbar triggers extra width for each item(environment) and causes overflow.
Width of each item in the supported environment list stays still regardless of scrollbar.
- When the number of item in supported environment list exceeds more than 10
> ⚠️ &nbsp; NOTE: `mwc-list-item` and `mwc-select` element internally use their own hierarchy, so it doesn't allow flexible custom layouts. Therefore I need to use arbitrary code to circumvent the overflow problem.
> fix: monkeypatch style manipulation according to the number of list-items in environment

- src/components/backend-ai-session-launcher.ts
Resolve: lablup/backend.ai-webui #1199
Original default shared memory setting code
Shared memory type value of this case is object.
This is fixing code, but it is not activated mostly because of no shared memory limit in most cases. 
All session below don't have any shared memory limit
So I changed preferred value to 0.0625GB(64MB) which is enough for single core CPU.
> fix: session resource allocation doesn't match

- src/components/backend-ai-session-launcher.ts
- src/components/lablup-slider.ts
- this PR resolves #1094 
- change weightless to material and add a prefix, suffix in `lablub-slider`
- Use `_text` in the label
- Using `_t` in label param is binding a non-primitive type.  This could result in binding the string "[object Object]".
- Unify the spaces.
**[Before]**
- There were too many items in one line.
- Colorful info icon
**[After]**
- For easy customization, the title and resource changes were divided.
- Unify the color
> style: resource type of session launcher

- src/components/backend-ai-webui.ts
**1. bugfix for auto logout feature**
- This bug is caused by changing the 'auto logout' setting on the 'UserSettings' page does not change value of 'this.auto_logout' accordingly.
- The reason why the value of 'this.auto_logout' does not change is that it continues to receive the value only from element 'autoLogout' of config.toml.
> fix: change auto_logout value set logic

- src/components/backend-ai-session-view.ts
Resolve: lablup/backend.ai-webui #1198
- This bug is caused by inner block in 'session tab' h3 block is overflowed when window size is narrow.
- Add scroll to session list tab in session tab to prevent overflow
**test image**
> fix: add scroll to session list tab in session tab

- resources/i18n/ko.json
- The Korean version translation related to the session rename does not work properly because it is under `session.launcher`
- It resolves #1229 
- this PR follows up #1181
> bugfix: session rename translation (ko)

- src/components/backend-ai-dialog.ts
- src/components/backend-ai-login.ts
Resolve: lablup/backend.ai-webui #1168 
- This bug caused by auto closing backend-ai-dialog when press esc button
- add 'escapeKeyAction' attribute to mwc-dialog in backend-ai-dialog
- change 'escapeKeyAction' attribute value from 'close'  to '' only when open cluster dialog
**Currently, If you press the esc key right after the 'login page' opens, you can see the 'cluster dialog'.**
> fix: prevent esc key close login dialog

- src/components/backend-ai-agent-list.ts
- src/components/backend-ai-scaling-group-list.ts
- src/components/backend-ai-storage-proxy-list.ts
- all endpoints in the agent page can be checked by adding the resizable attribute.
- Match `vaadin-grid` height in resource group tab to `vaadin-grid` in same page, different tab.
[Screenshot]
**Before**
**After**
👆 resizable endpoint
> style: make endpoint resizable and unify heights of vaadin-grid

- src/components/backend-ai-session-list.ts
Related: [backend.ai-manager#537](https://github.com/lablup/backend.ai-manager/pull/537)
Before significant changes occurred in mounts column information in session list when receiving requests from manager server, mounts information always contain information that exactly corresponded to mounts column in kernels.
Since there have been updates in manager server, the column name remains but the format of the result has been changed.
If user mounts "**test-folder**" and "**test-data**" in a session
then, response data in "mount" key contains data like this:
`[ 
"['test-folder', 'storagehost:name', 'actual-vfolder-path', 'permission', 'kernel-path']",
"['test-data', 'storagehost:name', 'actual-vfolder-path', 'permission', 'kernel-path']",
]`
If user mounts "**test-folder**" and …
> Refactor: reformat legacy mounts information on each session list

- src/components/backend-ai-session-launcher.ts
For better user experience, show Path & Alias only when the user clicks the info icon.
I also hide the checkbox by commenting out the `setPathContent` function.
[Before]
[After]
> refactor: show path dialog only when clicking the icon

- src/components/backend-ai-import-view.ts
Support to select folder hosts for import Github/Gitlab repository.
If you import Github/Gitlab repository, It only saves default host storage.
However, one of Some customers needs to select some storage
not only default host storage but one of custom host storage.
As a result, We support to select folder hosts for import Github/Gitlab repositories.
related #1278
> Support to select folder hosts for import Github/Gitlab repo

- src/components/backend-ai-settings-view.ts
fix setting page's config button horizontally
In Korean case, If you resize the width of the setting page,
sometimes the config button is displayed vertically.
I solved the issue using the CSS's `word-break` feature.
close https://github.com/lablup/backend.ai-webui/issues/1110
> fix setting page's config button horizontally

- src/components/backend-ai-summary-view.ts
Unable to set environment because weightless/textfield was not imported.
> add: import weightless textfield to summary view

- src/components/backend-ai-resource-policy-list.ts
- src/components/backend-ai-session-launcher.ts
- src/components/lablup-slider.ts
There have been several annoying issues lingering on the resource allocation panel in session launcher, which degrades user experience. Please refer to the content below.
Issue 1. User cannot Input any value on textfield area of each resource section.
Issue 2. Minimum value of each resource changes (e.g. the min value of cpu-resource was `1` but it changed to `0`)
Issue 3. Selected resource preset doesn't match actual allocation and knob in every slider doesn't move even resource preset is selected.
Issue 4. The number of containers in the total allocation section doesn't match the actual allocation.
Issue 5. If maximum number of container count in each session is zero, then it breaks the condition.
- Only trigger value changes when the previous value is not null and it exceeds the …
> Fix: allocate resource according to selected resource preset

- resources/i18n/en.json
- resources/i18n/fr.json
- resources/i18n/id.json
- resources/i18n/ko.json
- resources/i18n/mn.json
- resources/i18n/ru.json
- src/components/backend-ai-login.ts
- src/components/backend-ai-webui-styles.ts
- src/components/backend-ai-webui.ts
this resolves #1183 
- User will see the password update request message in every page of the header bar when `need_password_change` is true.
- User can close the message, but if refresh the page, then the message will show up again.
- If the user changes the password and refresh, this message disappear.
[Screenshot]
> feat: notify update password

- src/components/backend-ai-session-list.ts
- Relocate columns of the session list like below.
- User ID / SessionInfo / Status / Control / Configuration / Usage / Reservation / **SessionType / Architecture** / Agent
- Remove `auto-width` property in `Status` column.
[Screenshots]
> style: relocate columns of session list

- src/components/backend-ai-login.ts
This is a follow-up of https://github.com/lablup/backend.ai-webui/pull/1300.
> fix: override webserver configs only in the Electron app

- resources/i18n/en.json
- resources/i18n/fr.json
- resources/i18n/id.json
- resources/i18n/ko.json
- resources/i18n/mn.json
- resources/i18n/ru.json
- src/components/backend-ai-resource-group-list.ts
This PR resolves configuring`num_retries_to_skip` value in resource group([scaling_groups in backend.ai-manager](https://github.com/lablup/backend.ai-manager/blob/e30c75bfd4b8eabb66ff20e5e731f3ba6cf3ff7d/src/ai/backend/manager/models/scaling_group.py#L96-L111)) in webUI.
Related: [manager#527](https://github.com/lablup/backend.ai-manager/pull/527)
> ⚠️ NOTE: 
> - If the value is empty, then It fallbacks to `num_retries_to_skip` value in default setting in etcd (manager).
> - If the intial value in default setting is "3" (ref: [sample.etcd.config.json](https://github.com/lablup/backend.ai-manager/blob/b2362d3871a7a594f89469be5f6a5cbe256613bc/config/sample.etcd.config.json#L44-L48)).
> - This feature is available from `22.03`.
- Create Resource Group Dialog
- Modify Resource Group Dialog
- …
> Feature: num retries config in resource group

- src/components/backend-ai-agent-list.ts
https://github.com/lablup/backend.ai-webui/issues/1309
fix: extend resources page control detail popup width.
cause: resources page's Control detail information popup layout is broken.
> fix: extend resources control detail popup width

- src/components/backend-ai-environment-list.ts
Refactor: querySelector with leading Number id string(#1321)
Changed the querySelector's value to explicitly stating id values `querySelector("[id='1']")`
example) id value: `10-20-30-10...blahblah`
If the first character of an identifier is numeric, you’ll need to escape it based on its Unicode code point.
However, If you don't change string to Unicode code point,
you would have to do this: `querySelector("[id='1']")`
Ref: Using querySelector with IDs that are numbers
https://stackoverflow.com/questions/20306204/using-queryselector-with-ids-that-are-numbers
> Refactor: querySelector with leading Number id string(#1321)

- src/components/backend-ai-session-launcher.ts
Due to the unnecessary close brace `}`, some description dialog does not appear on the session launcher.
> fix: some session description dialog does not appear.

- src/components/backend-ai-resource-broker.ts
- src/components/backend-ai-session-list.ts
distinguish image tag for Custom Environments (#1255)
If you register a custom gitlab docker url, The tag shows to get only uri path's first path name or namespace's first '/' splited string
Ex) <registry URL>/<namespace>/<project>/<image>
10.20.30.10:7055/root/test/r-base:4.1
shows custom Environemts' tag: root
However, custom image name uses the path's '/' splited last string.
So, custom image's tag used as <namespace> and <project> except for the last splited string in url path.
Ex1) 10.20.30.10:7055/root/test1/r-base:4.1 -> tag: root/test1
Ex2) 10.20.30.10:7055/root/test2/r-base:4.1 -> tag: root/test2
#1255
> Feat: distinguish image tag for Custom Environments(#1255)

- src/components/backend-ai-change-forgot-password-view.ts
- src/components/backend-ai-credential-list.ts
- src/components/backend-ai-environment-list.ts
- src/components/backend-ai-general-styles.ts
- src/components/backend-ai-login.ts
- src/components/backend-ai-maintenance-view.ts
- src/components/backend-ai-pipeline-view.ts
- src/components/backend-ai-registry-list.ts
- src/components/backend-ai-resource-group-list.ts
- src/components/backend-ai-resource-policy-list.ts
- src/components/backend-ai-resource-preset-list.ts
- src/components/backend-ai-session-launcher-legacy.ts
- src/components/backend-ai-session-launcher.ts
- src/components/backend-ai-signup.ts
- src/components/backend-ai-summary-view.ts
- src/components/backend-ai-user-list.ts
- src/components/backend-ai-usersettings-general-list.ts
- src/components/backend-ai-usersettings-view.ts
- src/components/backend-ai-webui-styles.ts
This PR fixes a minor typo error of CSS variable used in [mwc(material web component)](https://github.com/material-components/material-web).
Before: `--mdc-on-theme-primary`(X)
After: `--mdc-theme-on-primary` (O)
> Fix: css variable typo error on `mwc`

- src/components/backend-ai-data-view.ts
- src/components/backend-ai-storage-list.ts
This PR adds a storage host that supports directory-based quota (e.g. [Weka.io](https://docs.weka.io/fs/quota-management#directory-quotas))
Also, for further implementation goal is to make quota setting to "optional", not "mandatory".
related PR: #1328.
> add: storage host that supports directory based quota setting

- src/components/backend-ai-resource-broker.ts
allow mounting shared folders that are not allowed by the host when creating a new session.
> fix: mount shared folders when creating a session

- README.md
- Clarify that we should run `build:d` and `server:d` simultaneously.
- Update the submodule checkout command with the new mono-repo.
- Make the number of spaces between shell commands and comments
to 2, just like Python's PEP-8 style comments, to improve readability.
And also align the beginning column of comments within the same subsection.
- Properly apply code-block syntax declarations (console, html, json, etc.)
- In code-blocks with the "console" syntax, the shell commands must start with "$"
while the outputs of commmands should start without it.
- The JSON syntax only uses double quotes, so fixed wrong example codes.
> docs: Clarify dev-setup guide and fix code-block formats

- src/components/backend-ai-session-list.ts
Allows the user to force-terminate the session to prevent the session from remaining in the PREPARING, TERMINATING status.
Related PR: https://github.com/lablup/backend.ai/pull/525
> feat: allow user to force termination of sessions

- README.md
- package-lock.json
- package.json
- src/components/backend-ai-app-launcher.ts
- src/wsproxy/local_proxy.js
- src/wsproxy/manager.js
* Add `dotenv` as a dependency
* Perform more careful (type-aware) env-var parsing in the local wsproxy
* Fix misuse of `proxyListenIP` and replace them with `proxyBaseHost` -- confirmed working on VM-based dev setup
- We need to carefully and explicitly distinguish the binding IP address and the hostname sent to the clients, as they may be completely different in remote development setups.
Related: lablup/backend.ai#501
Example:
> feat(wsproxy): Add dotenv support and parse env-vars more carefully

- src/components/backend-ai-resource-monitor.ts
- src/components/backend-ai-session-view.ts
I just added a resource group selection to the summary page. (The design is the same as the Resource Group checkbox on the Session page.)
Now, you can view resources by selecting a resource group on the Summary page.
<table>
<tr>
<td><strong>Before</strong></td>
<td><strong>After</strong></td>
</tr>
<tr>
<td><img width="742" alt="before" src="https://user-images.githubusercontent.com/65989401/178208363-c1b2af95-05ff-4c45-9487-02a5067ffb92.png"></td>
<td><img width="1115" alt="after" src="https://user-images.githubusercontent.com/65989401/178208573-e7c1b8eb-2bd7-43fc-a3ad-dfb329aad461.png"></td>
</tr>
</table>
issue: #1124
> fix: show resource statistics about current resource group

- src/components/backend-ai-indicator.ts
I just increased the length of the dialog to prevent scrolling in the text.
<table>
<tr>
<td><strong>Before</strong></td>
<td><strong>After</strong></td>
</tr>
<tr>
<td><img width="245" alt="after" src="https://user-images.githubusercontent.com/65989401/179739359-f7defffc-0a6a-44ce-8e50-9e3aebce91e5.jpg"></td>
<td><img width="245" alt="after" src="https://user-images.githubusercontent.com/65989401/179738827-5227bcfe-4f21-4c13-b9d5-805cf1072bff.png"></td>
</tr>
</table>
resolve: #1349
> fix: change the size of the popup to fit the text

- src/components/backend-ai-webui-styles.ts
The **Material Web Component**'s **`<icon-button />`** has default ripple component its inside. The problem is the background focus ripple after clicked button is show by default but it does not disappear even user click button's outside after `display: block` -> `display: none`. I think this is mwc's wrong behavior. So I changed background focus not to disappear by default.
- remove remaining ripple from menu drawer's icon button
**before**
> icon button's background focus ripple remained
**after**
> icon button's background focus ripple does not appear
---
related issue: #1352
> fix: side menu icon button ripple to disappear after click

- src/components/backend-ai-webui.ts
Recent server PR https://github.com/lablup/backend.ai/pull/599 introduces bare unicode for some text items in composing the toml config file. For example, if an admin sets a string `JPark's Test Node` for `api.text` item in `webserver.conf`, the the resulting text would be `JPark\u0027s Test Node`.
This PR manually handles this case by parsing the unicode text in loading the config.
Affected config items:
- `config.general.apiEndpointText`
- `config.general.siteDescription`
> fix: parse unicode strings for some items in the toml config

- src/components/backend-ai-session-launcher.ts
* An error occurred because manualImageName.value is used as kernalname even though manualimagename field is empty in debug mode.
So I modified the manual image name field to be used as a kernal name only when it is not empty.
* In Session launcher, manual image name is not required but optional (in debug mode or when allowManualImageNameForSession is true)
resolve #1365
> fix: Manual image name is not required in Session launcher

- src/components/lablup-codemirror.ts
This PR adds a new property `required`, for doing a validation check which regards as `invalid` when the input value is empty.
Also, It's been raised during the implementation of PR #1221.
Therefore It should be merged before #1221.
> add: Required field for validation whether input field in command area

- src/components/backend-ai-dialog.ts
- src/components/backend-ai-login.ts
The login page has some issue related between SESSION and IAM login type. I cherry picked commit that patches login page typing from #1359
I fixed the SESSION and IAM login form to use same component (mwc-textfield).
**(after)**
| SESSION | IAM |
|------|-------|
| <img width="475" alt="image" src="https://user-images.githubusercontent.com/5039744/184501005-caafde4d-1c8c-4244-95fe-9440ec7c19c8.png"> | <img width="463" alt="image" src="https://user-images.githubusercontent.com/5039744/184501010-a04611a4-7f92-49e3-a356-024d64ba2034.png"> |
**(before)**
| E-mail | IAM |
|--|--|
| ![image](https://user-images.githubusercontent.com/5039744/184501661-05416b07-2529-49e1-9fac-2ff090e0e961.png)  | ![image](https://user-images.githubusercontent.com/5039744/184501708-62da1a24-f68d-4847-8cfa-af78a3be8 …
> fix: inconsistent login style

- src/components/backend-ai-session-list.ts
This PR fixes and applies minor updates which haven't been applied via #1412 by accident.
1. Regression of disabling container commit request icon button in certain situations:
- when container commit is ongoing
- when the corresponding session is terminated
2. Only add `commit_status` when requesting and receiving the session list for `RUNNING` tab, not in all tabs.
- FINISHED tab which lists TERMINATED Sessions
- When container commit operation is available; no container commit operation is on-going
- When container commit operation is in progress
> Hotfix: Temporally disable terminate and container commit on running session

- src/components/backend-ai-general-styles.ts
This PR resolves #1434.
- before
- after
> fix: automatically set the height of `list-wrapper`, which wraps grids, to avoid the height mismatch between the two elements

- src/components/backend-ai-agent-list.ts
Server reports the `cuda_util.capacity` to 0. In this case, the GPU
utilization per node is displayed as `Infinity`.
> fix: CUDA utilization was displayed as `Infinity`

- src/components/backend-ai-session-list.ts
This PR fixes two things, disable container commit icon when the session is `BATCH` type and adjust the width of Controls column depending on whether the version and configuration support container commit.
> fix: disable container commit when session is batch type

- src/backend-ai-app.ts
- src/components/backend-ai-login.ts
- src/components/backend-ai-webui.ts
This PR manually blocks pages that are related to pipeline, which needs second phase implementation.
I applied two parts so that user cannot access the pipeline menu by chance.
It will be enabled when we support key features of the MLOps(AIOps).
- pipeline page
- pipeline-job page
> refactor: temporally block pages related to pipeline menu

- src/components/backend-ai-login.ts
This PR fixes human error based on calling the number parsing function(e.g. `ParseInt`, `ParseFloat`, etc.) on wrong data.
Also, there was an issue with sanitizing the whitespace when reading from configuration values with commas(`,`), which are regarded as an array. when there are no values (undefined or null or empty string), It was treated as an empty string(`''`). But when appending `split(',')` function at the end, it changed to `['']`, which is different from an empty array(`[]`). Therefore I added extra conditional logic to set an empty array when the value is nullish.
> hotfix: remove wrong parsing number logic in initial configuration

- resources/i18n/en.json
- resources/i18n/fr.json
- resources/i18n/id.json
- resources/i18n/ko.json
- resources/i18n/mn.json
- resources/i18n/ru.json
- src/components/backend-ai-storage-list.ts
#1384 
<br/>
Previously, it wasn't able to get the information before clicking the Control icon.
So, add title attribute to show what the Control icons do.
<br/>
https://user-images.githubusercontent.com/50884017/188849124-2a0cb21a-6d80-4bc3-9a7f-f1dce176def8.mov
It showed nothing when I screenshot, so I upload the recording.
<br/>
Refer to language converter(ko.json) 
if it exists, I used it, but if it does not exist, write it in English
> fix: add title to show what the Control icons do

- src/components/backend-ai-session-launcher.ts
- call `updateResourceAllocationPane()` on cluster mode selection handler
I think `updateResourceAllocationPane()` method need code refactoring. The method cause logical confusion, but I didn't do this because I don't know all intent of condition statement and variables behavior.
---
related issue: #1347
> fix: cluster size slider to be active by cluster mode selection

- src/components/backend-ai-information-view.ts
Adjust the License Key button size to be the same as the other buttons.
> style: adjust the License Key button size

- resources/i18n/en.json
- resources/i18n/fr.json
- resources/i18n/id.json
- resources/i18n/ko.json
- resources/i18n/mn.json
- resources/i18n/ru.json
- src/components/backend-ai-general-styles.ts
- src/components/backend-ai-login.ts
#1468  
<br/>
Previously, it's hard to know what endpoint means.
So, add an info icon and helper dialog about endpoint.
<br/>
Added the info icon next to endpoint text field in the login page. (@Sujin-Kim1 suggested grey color) <img width="1133" alt="image" src="https://user-images.githubusercontent.com/50884017/189901362-a34c531e-30c6-4c61-9ec3-bdb44bf0bc94.png">
When clicking the info icon button, the helper dialog appears. 
It contains the meaning and examples of endpoints. <img width="1133" alt="image" src="https://user-images.githubusercontent.com/50884017/189902814-e6e5be02-e71b-48ed-9e8e-9511e31d7282.png">
I added descriptions in English and Korean according to [Backend.AI Web-UI User Guide](https://webui.docs.backend.ai/en/latest/login/login.html). <img width="1133" alt="image" …
> fix: add helper dialog for endpoint

- src/components/backend-ai-webui.ts
- src/plugins_sample/test-plugin.ts
* This PR allows plugins to act as API endpoint
* When parsing the sidebar items, menu handling routine ignores `page` type plugins if its' menu item name is empty.
> feature: allow plugins work as hidden page plugin.

- src/components/backend-ai-login.ts
This PR fixes typo in configuration read logic, preventing to set the maximum shared memory size via configuration.
> fix: Cannot set the maximum shared memory size via configuration

- resources/app_template.json
When I try to launch a `vnc-web` application, Web-UI opens up the invalid redirect URL, which contains `<proxy-host>` and `<port-number>` like below:
This PR removes the URL since it is not working and prevent the loading of the `url_template` in service definition file.
> fix: remove the invalid redirect URL for vnc-web

- .github/workflows/label.yml
The sync-labels option of the labeler, which syncs the current label according to this change, is not working properly.
It was an issue raised 2 months ago, but it is an issue that is not being dealt with and left unattended.
https://github.com/actions/labeler/issues/404
A branch with a bug-fixed version exists and changes to that version
https://github.com/actions/labeler/pull/405
> ci: Fix sync-labels option error

- src/components/backend-ai-session-launcher.ts
resolves #1488 
- fix: session language info disappears
- Reset `_helpDescriptionIcon` to prevent unrelated icons and descriptions from appearing together as shown below.
> fix: show session language description

- src/components/backend-ai-app-launcher.ts
It solves the problem of sending port information together without checking the preferred port when launching the session app in the WebUI.
> fix: send preferred port when only checked

- src/components/backend-ai-signup.ts
In the signup dialog, all of the Terms Of Service dialog doesn't show because of the id mismatching.
> fix: TOS dialog doesn't show because of id mismatching

- src/components/backend-ai-dialog.ts
If the dialog length is long, users have to scroll up to close the dialog. So I added the `stickyTitle` option to `backend-ai-dialog`. With this option, the user can always see the dialog's title and close the dialog without scrolling.
> feat: add sticky title option to `backend-ai-dialog`

- src/components/backend-ai-app-launcher.ts
- src/wsproxy/lib/console-appproxy.js
- src/wsproxy/manager.js
This PR is a follow-up of #1521, allowing wsproxy also to communicate with webserver by using header based authentication instead of traditional cookie based mode.
> feat: add support for header based authentication on wsproxy

- src/components/backend-ai-resource-broker.ts
- src/components/backend-ai-session-launcher.ts
resolve #1523 
- show all of the preset lists (resource templates) when `alwaysEnqueueComputeSession` is true.
- set allocatable resource limit according to `total_resource_group_slot` when `alwaysEnqueueComputeSession` is true to prevent automatically canceling the creation of a new session because of the lack of resources.
- reference image
> feat: show all resource templates when `alwaysEnqueueComputeSession` is true

- src/components/backend-ai-resource-monitor.ts
resolves https://github.com/lablup/backend.ai-webui/issues/1541 
reason of this bug: the progress value is `NaN`
> bugfix: gpu, fgpu progress bar are always zero

- src/components/backend-ai-summary-view.ts
This PR resolves #1557.
- before
- after
> fix: wrapping notice-ticker to fit in the layout with bigger font-size

- resources/i18n/en.json
- resources/i18n/fr.json
- resources/i18n/id.json
- resources/i18n/ko.json
- resources/i18n/mn.json
- resources/i18n/ru.json
- src/components/backend-ai-agent-list.ts
- src/components/backend-ai-storage-proxy-list.ts
resolves https://github.com/lablup/giftbox/issues/6
agent tab (add disk column)
storage tab (display the capacity value)
> feat: add disk column on agent tab and display the total capacity of the storage

- src/components/backend-ai-import-view.ts
remove '.git' suffix about both github & gitlab repos Because Checking Both github & gitlab repo use https APIs
I checked the git repo's URL issue. However, If importing feature get `***.git` URL, The feature removes `***.git`'s postfix `.git`. So I'll improve the importing repo both github and gitlab repo.
> Fix: remove '.git' suffix about git repos

- src/components/backend-ai-environment-list.ts
- fix: deprecated import
**Before**
**After**
> hotfix: broken environment list UI because of the unmatched tag

- src/components/backend-ai-agent-list.ts
- src/components/backend-ai-session-list.ts
- style: display cuda mem info just below the cuda util
- follows https://github.com/lablup/backend.ai-webui/pull/1572
> fix: display cuda mem info if cuda util exist

- src/components/backend-ai-login.ts
- src/components/backend-ai-resource-broker.ts
This PR resolves #1592.
> you need more than one account to test this in your environment.
> For convenience's sake, I'll call them as account A and account B.
> Also, you need to set `hideAgents` option in configuration file(webUI, webserver, manager) to false. (you may need to restart some process.)
1. Login to account A.
2. Create a session with the maximum resources that you can allocate on behalf of account A.
3. Login to account B.
4. See each gauge in resource monitor.
|      | Before | After |
| ---| --- | --- |
|resource monitor of account A | <img width="378" alt="Screenshot 2023-02-17 at 10 59 25 AM" src="https://user-images.githubusercontent.com/46954439/219530262-8b223247-39c7-4d78-81bd-1e483868626b.png"> | <img width="378" alt="Screenshot 2023-02-17 at 10 55 15 AM" …
> feature: show total resource group amount in resource monitor gauge

- src/components/backend-ai-agent-summary-list.ts
- src/components/backend-ai-resource-broker.ts
If there are over 20 Agents in a reosurce group, #1593 will not work properly. this PR increases the fetch item count by 100.
:warning: Let's assume that the number of agents is less than 100 for user-accessible resource group. This will meet our immediate need, but we need to fix this when refactoring the resource indicator.
> fix: increase item count 20 -> 100 for agent summary list query

- resources/i18n/en.json
- resources/i18n/fr.json
- resources/i18n/id.json
- resources/i18n/ko.json
- resources/i18n/mn.json
- resources/i18n/ru.json
- src/components/backend-ai-user-dropdown-menu.ts
- src/components/backend-ai-user-list.ts
- src/lib/backend.ai-client-esm.ts
resolves #1598 
---
1. clone [backend.ai-totp-plugin](https://github.com/lablup/backend.ai-totp-plugin) to backend.ai/plugins.
2. install totp plugin
`./py -m pip install -e plugins/backend.ai-totp-plugin`
3. checkout backend.ai's branch to `feature/totp-created-at-column` (related PR: https://github.com/lablup/backend.ai/pull/1072)
4. upgrade db `./py -m alembic upgrade head` (maybe you need twice. the header should be `3efd66393bd0`)
---
- Is correct the 2fa enabled column data?
- Is correct the value of 2fa in the info dialog?
- Is possible to remove the 2fa in the edit dialog?
- Is possible to set my own 2fa in the setting dialog on the credential page?
---
- add 2fa status
- add 2fa column to info dialog
- remove users' totp (superadmin, admin only)
- cannot activate 
- but it can …
> feature: 2fa management

- .github/workflows/add-to-project.yml
Use add-to-project workflow to automatically register with the project board when you create an issue.
To use that workflow, you need to add a secret called `ADD_TO_PROJECT_PAT`.
> ci: add an `add-to-project` workflow

- src/components/backend-ai-resource-broker.ts
- src/components/backend-ai-session-launcher.ts
resolves https://github.com/lablup/giftbox/issues/187
> fix: display all available presets when `always_enqueue_compute_session` options is configured

- src/components/backend-ai-resource-broker.ts
This PR displays the value of the resource group indicator as the total **remaining** slots in the current resource group, only when `hideAgents` is set to `false`.
> refactor: display total remaining resources in resource group indicator

- src/components/backend-ai-registry-list.ts
Some columns such as Enabled are impossible to recognize the full column name if the window size is narrow.
So I set columns in the registry list page to be resizable.
> feat: set columns in the registry-list page to be resizable

- config.toml.sample
- resources/i18n/en.json
- src/components/backend-ai-login.ts
- src/components/backend-ai-user-dropdown-menu.ts
- src/components/backend-ai-user-list.ts
- src/lib/backend.ai-client-esm.ts
resolves https://github.com/lablup/giftbox/issues/200
If the `hide2FA` flag is true, users can hide 2FA-related columns and don't call the totp API
> feat: add the flag to hide 2fa

- src/components/backend-ai-user-dropdown-menu.ts
- src/components/backend-ai-user-list.ts
The logic of setting `totpSupported` option is incorrect, and I found a problem that the totp-related columns are not visible. Resolve the above error by getting the `totpSupported` option asynchronously.
> fix: get `totpSupported` flag asynchronously

- src/components/backend-ai-user-dropdown-menu.ts
This PR resolves #1621.
* applying long user-id(email)
* applying full name of user info filled with whitespace (display user-id instead)
|   | Before|After|
|---|---|---|
|long user-id|<img width="200" alt="Screenshot 2023-03-08 at 2 55 28 PM" src="https://user-images.githubusercontent.com/46954439/223631004-c0c1b347-9207-4c44-8943-4b7df5f843e7.png">|<img width="200" alt="Screenshot 2023-03-08 at 2 47 25 PM" src="https://user-images.githubusercontent.com/46954439/223630925-390fbc83-a48f-420d-ab90-71ff1e01da24.png">|
|fullname filled with whitespace|<img width="582" alt="Screenshot 2023-03-08 at 3 02 45 PM" src="https://user-images.githubusercontent.com/46954439/223632342-584f9af6-23fe-4520-a5cf-a02e85388617.png">|<img width="582" alt="Screenshot 2023-03-08 at 3 01 35 PM" …
> fix: apply ellipsis when username or userid exceeds total width of user dropdown menu

- package-lock.json
- package.json
- resources/i18n/en.json
- resources/i18n/fr.json
- resources/i18n/id.json
- resources/i18n/ko.json
- resources/i18n/mn.json
- resources/i18n/ru.json
- src/components/backend-ai-session-list.ts
This PR resolves #1632.
Also, I replaced `wl-tooltip` with `vaadin-tooltip` to provide a better user experience by unifying the tooltip component.
> NOTE:
> IMO, when any element is set to "disabled", it shall not receive or invoke an event unless it's necessary for a specific situation. Therefore I didn't add any "workaround" code on "icons" with disabled status.
* Before
* After
> feature: show tooltips on every icon in controls tab

- src/components/backend-ai-app-launcher.ts
- src/components/backend-ai-data-view.ts
- src/components/backend-ai-storage-list.ts
- src/lib/backend.ai-client-esm.ts
This PR resolves #1629.
> NOTE: you may need to change `allowed_vfolder_hosts` values to test the visibility of icon-button related to `vfolder sharing`. They will show-up when `invite-others` are allowed at least in one of the policies(`domain`, `project(group)`, `keypair resource policy`).
> feature: hide vfolder sharing when invite others disabled

- src/components/backend-ai-data-view.ts
follows https://github.com/lablup/backend.ai-webui/pull/1640
`storageProxyInfo` is not defined as a property. So below errors occurs.
And `volumeInfo` actually acts `storageProxyInfo`. So I rename `volumeInfo` property to `storageProxyInfo` and renamed the related function.
> hotfix: rename `volumeInfo` property to `storageProxyInfo`

- src/components/backend-ai-storage-list.ts
follow-up of https://github.com/lablup/backend.ai-webui/pull/1636
> fix: use SI unit (e.g., GB not GiB) for quota-related fields

- src/components/backend-ai-environment-list.ts
This PR resolves #1652 
Ordered the environment page item as installed / others
> fix: sorting installed environments up when visiting environment menu

- src/components/backend-ai-session-launcher.ts
This PR resolves #1664 
In Korean language UI, OK button on the session launcher's environment variable editor dialog was broken. This PR resolves the problem by fixing the button width.
> fix: session launcher's environment variable editor dialog button is broken in Korean

- resources/i18n/en.json
- resources/i18n/fr.json
- resources/i18n/id.json
- resources/i18n/ko.json
- resources/i18n/mn.json
- resources/i18n/ru.json
- src/components/backend-ai-resource-group-list.ts
This commit updates resource group list page to allow adding `inference` session type as allowed session type of scaling group.
| --- | --- |
|<img width="272" alt="Screenshot 2023-03-30 at 1 15 43 PM" src="https://user-images.githubusercontent.com/46954439/228727853-b89a2f33-244a-4ea2-90f4-b7900e0cf750.png">|<img width="272" alt="Screenshot 2023-03-30 at 1 15 10 PM" src="https://user-images.githubusercontent.com/46954439/228727839-778247c4-3834-4406-aae2-d95f53f12017.png">|
> feat: add support for setting `inference` as allowed session type

- resources/i18n/en.json
- resources/i18n/ko.json
- src/components/backend-ai-session-launcher.ts
When a user tries to create a new compute session with the same name as another running session, it silently fails since the backend returns 200 OK. This is due to the query execution mode having to specify the session's name to reuse an already existing one to execute a related, but different code piece.
However, this confuses the Web UI users since there is no message indicating the session creation request was not successful. Even worse, some users may think the previous session is terminated, and a session with the same name is newly created.
So, this PR displays an explicit message when the `created: false` is delivered in the response body that the session with the same name already exists.
> fix: display explicit message when a user tries to create a session with the same name of a running session

- src/components/backend-ai-app-launcher.ts
Setting `active = false` for this component blocks the opening of app
launcher diloag.
> fix: unable to open app launcher dialog

- src/components/backend-ai-session-list.ts
Converts remaining idle check seconds to 'ddhh:mm:ss' format correctly.
> fix: incorrect display of grace idle period over one day

- resources/i18n/en.json
- resources/i18n/ko.json
- src/components/backend-ai-app-launcher.ts
- src/lib/backend.ai-client-esm.ts
- Unable to open the VSCode app in the web version.
+ Previous implementation always opens the VSCode Remote Connection dialog when the VSCode icon is clicked, even in the web version.
+ Separate `vscode-desktop` app from the legacy `vscode` app. The legacy code-server application is needed even in the Web UI desktop app. We cannot assume every user installs the Visual Studio Code application on their local machine. Even worse, in some cases, the users may not be allowed to install any application. So, in the desktop Web UI application, there will be two icons, one for the code-server and the other for the local VSCode.
- Do not expose the VSCode Desktop icon for the core version less than 23.03.
+ The core's [counterpart PR](https://github.com/lablup/backend.ai/pull/751) is for 23.03, …
> fix: unable to launch VSCode in web version

- .github/workflows/label.yml
The size label was added while the label was recently reorganized.
Automatically manage the corresponding size label through actions.
> ci: Add size label automation actions job

- src/components/backend-ai-session-launcher.ts
> fix: regression of manually setting HPC optimization value in session launcher

- src/components/backend-ai-session-list.ts
duplicate renderings in the idle checker column occur invalid utilization of idle checker values. When filtering the session list, there is a problem with taking advantage of the idle checker value of the session that was at the top of the list before filtering.
> fix: utilization values in idle checker pop-up are not updated after the initial rendering

- resources/i18n/en.json
- resources/i18n/ko.json
- src/components/backend-ai-session-list.ts
Since the policy of the session can be known, only the description of the set Idle checker is visible.
resolves https://github.com/lablup/giftbox/issues/361
+ Updated)
Hide idle checker column if manager doesn't support idle checks or no configuration
Example
> feat: show idle check information based on only applied configurations#361

- .gitignore
- .vscode/i18n-ally-custom-framework.yml
This PR adds two `.yaml` files to the `.vscode` directory, which include settings for the [i18n-ally extension](https://marketplace.visualstudio.com/items?itemName=Lokalise.i18n-ally) for VS Code.
To use this feature, follow these steps:
1. Install the [i18n-ally extension](https://marketplace.visualstudio.com/items?itemName=Lokalise.i18n-ally).
2. Open the VS Code settings (Mac: `cmd` + `,`) and search for `ally`. Then, make the following changes:
- `I18n-ally: Dir Structure`: `auto`
- `I18n-ally: Enabled Frameworks`: `react`, `custom`
- (optional) `I18n-ally: Display Language`: If you set this to `ko`, you can see Korean instead of English (which is the default).
- (optional) `I18n-ally: Annotation In Place`: you can change the annotation in place. please check the snapshot below.
This …
> feat: support i18n ally extension for VS Code

- src/components/backend-ai-session-list.ts
- src/lib/backend.ai-client-esm.ts
This PR adds a simple user interface for "shared memory" allocated in each session.
Please note that shared memory also follows the policy; which aggregates all allocated amounts of the same resources in each container on multi-container conditions; as the other resources do.
related PR: [backend.ai#1282](https://github.com/lablup/backend.ai/pull/1282)
* Before
* After
> feat: display allocated shared memory in session config column

- src/lib/backend.ai-client-esm.ts
The sftp-scaling-group feature was released in [manager v23.03.3](https://github.com/lablup/backend.ai/releases/tag/23.03.3).
> hotfix: enable sftp-scaling-group feature from manager v22.03.3

- resources/i18n/en.json
- resources/i18n/fr.json
- resources/i18n/id.json
- resources/i18n/ko.json
- resources/i18n/mn.json
- resources/i18n/ru.json
- src/components/backend-ai-app-launcher.ts
This PR resolves #1726.
* before
* after
> NOTE: By suggestion of @adrysn, I updated description area to be collapsible. you can expand/shrink by clicking `Read more.../Read less` button.
| Folded(Read more...) | Expanded(Read less)|
| ------------- | ------------- |
| <img width="404" alt="Screenshot 2023-06-07 at 5 53 30 PM" src="https://github.com/lablup/backend.ai-webui/assets/46954439/cf084e5e-5f88-453a-abbd-de5822209092"> | <img width="404" alt="Screenshot 2023-06-07 at 6 21 36 PM" src="https://github.com/lablup/backend.ai-webui/assets/46954439/15e72a9c-9e5e-474c-9a2f-590efddbaec0"> |
> fix: touchup description for ssh sftp session

- src/components/backend-ai-storage-list.ts
This PR fixes SFTP scaling group session not being created when user is not a member of `default` project.
> fix: SFTP scaling group session refusing to be created

- resources/i18n/de.json
- resources/i18n/el.json
- resources/i18n/en.json
- resources/i18n/es.json
- resources/i18n/fi.json
- resources/i18n/fr.json
- resources/i18n/id.json
- resources/i18n/it.json
- resources/i18n/ja.json
- resources/i18n/ko.json
- resources/i18n/mn.json
- resources/i18n/ms.json
- resources/i18n/pl.json
- resources/i18n/pt.json
- resources/i18n/pt_BR.json
- resources/i18n/ru.json
- resources/i18n/tr.json
- resources/i18n/vi.json
- resources/i18n/zh_CN.json
- resources/i18n/zh_TW.json
When used as a logo, it is nVIDIA, and when written, NVIDIA seems to be the correct expression.
https://www.nvidia.com/en-us/about-nvidia/legal-info/logo-brand-usage/
> docs: Modified to fit nvidia brand notation

- src/components/backend-ai-agent-list.ts
- src/components/backend-ai-agent-summary-list.ts
resolves https://github.com/lablup/giftbox/issues/429
> fix: parse fgpu slots to float

- src/components/backend-ai-storage-list.ts
resolves https://github.com/lablup/giftbox/issues/451
follows #1713 
This PR hides directory-based quota info(usage) according to the `directoryBasedUsage` option.
> feat: remove per-vfolder usage stats in Web UI

- src/lib/backend.ai-client-esm.ts
Because of changes to throwing X-BackendAI-SessionID instead of cookies, it occurs a 401 error because the `newSignedRequest` or authentication header does not pass. To resolve this, change to use `newSignedRequest` when importing resource-slots.
> fix: `newPublicRequest` -> `newSignedRequest` when getting resource-slots

- src/components/backend-ai-session-launcher.ts
There is an error when setting the content of a lit element using textContent.
> Uncaught (in promise) Error: This `ChildPart` has no `parentNode` and therefore cannot accept a value. This likely means the element containing the part was manipulated in an unsupported way outside of Lit's control such that the part's marker nodes were ejected from DOM. For example, setting the element's `innerHTML` or `textContent` can do this.
- update the text of launch button using @property
- set _text() value using `textNode` instead of `innnerHTML`
> fix: update the text of launch button using @property

- src/components/backend-ai-session-list.ts
- version.json
There was a bug that the session was not deleted when the wsproxy address of the scaling group was invalid.
This PR is related to this PR in backend.ai repository. [#1423](https://github.com/lablup/backend.ai/pull/1423)
In order to prevent side effects caused by server-side code modification, it was modified to handle exceptions in the web UI-side code.
> fix: unable to terminate a compute session when wsproxy address is not properly

- resources/i18n/ko.json
Fix typo on "Smaller Resource Then Image Requires" text
> update: fix '자원를' to '자원을' for smaller resource text

- react/src/components/DefaultProviders.tsx
- react/src/components/ServiceLauncherModal.tsx
> fix: set the popup container to shadowRoot always

- src/components/backend-ai-session-launcher.ts
This PR resolves [#1809](https://github.com/lablup/backend.ai-webui/issues/1809#issue-1820069285)
**Before PR**
**After PR**
The element `'Not Selected'` of the default `version` array is pushed to the `info` array of the `_getVersionInfo()` function and displayed in the `version` list.
I've made the wrong tags invisible (they still exist in `info` array), would it be better to fix them so that the function `_getVersionInfo()` doesn't include them in the `info` array at all?
> fix: version label overlapping

- package.json
- react/src/components/DomainSelector.test.tsx
- react/src/components/Flex.test.tsx
- react/src/components/__snapshots__/Flex.test.tsx.snap
I'd like to resolve the issue: test codes of react components
Before starting the tasks, I hope to check if I am doing properly.
---
I found two test methods of rendering components: using either "@testing-library/react" or "react-test-renderer"
I think it would be ok that using "react-test-renderer" just for rendering a specific component because my main goal is to leave its snapshot.("react-test-renderer" has good utilities for snapshots)
On the other hand, when I have to make some codes for testing user's interaction or relay-test(graphql reqeust and response) in the component, I will choose "@testing-library/react" with other mocking libraries.
So, can I mix these ways for testing? Aren't there any side effects?
> test: Flex component rendering test & snapshot

- resources/i18n/en.json
- resources/i18n/fr.json
- resources/i18n/id.json
- resources/i18n/ko.json
- resources/i18n/mn.json
- resources/i18n/ru.json
- src/components/backend-ai-general-styles.ts
- src/components/backend-ai-session-launcher.ts
- src/components/lablup-codemirror.ts
By adding validation to the `lablup-codemirror`, it was prevented from moving on to the next step without entering the startup command in the batch session.
> feat: Do not allow batch session startup command to have an empty string.

- .github/workflows/auto-label-in-issue.yaml
This project is an open source project and uses many labels for pr and issue management.
However, managing labels is time consuming and needs to be automated.
If there is an issue linked to pr, add an action that automatically adds the label added to the issue to pr.
> ci: Add auto-label-in-issue action

- react/data/schema.graphql
- react/package-lock.json
- react/package.json
- react/src/helper/index.tsx
- react/src/helper/types.tsx
- react/src/hooks/reactPaginationQueryOptions.tsx
- react/src/pages/ServingListPage.tsx
- react/src/react-app-env.d.ts
- resources/i18n/en.json
- resources/i18n/fr.json
- resources/i18n/id.json
- resources/i18n/ko.json
- resources/i18n/mn.json
- resources/i18n/ru.json
This PR resolves #1887.
> ⚠️ NOTE: ~~pagination filter goes to `created_at` as a default.~~
> There's a bit changed in `package.json` and `package-lock.json`. You need to update installed node packages in `src/react` by `npm i` before reviewing the code and UI whether it works properly or not.
> We need to implement pagination right after implementing monitoring by access-control(e.g. admin user can see all of the services that user(s) have been created) as a future feature.
> feature: add sorting filter in new column `created_at` in serving list

- src/components/backend-ai-webui-styles.ts
- src/components/backend-ai-webui.ts
- style: change the color of the disabled menu icon
- fix: typo error (session -> serving)
- fix: naming convention (blockedMenuitem -> blockedMenuItem)
resolves https://github.com/lablup/backend.ai-webui/issues/1878
> **Note**
> How to test: add some pages that you want to test to the [blocklist](https://github.com/lablup/backend.ai-webui/blob/fd033e0cafcb8eff58785a214ef01f8aa4bbea2b/config.toml.sample#L38)
> feat: redirect to error page if it is `blockedMenuItem`

- resources/device_metadata.json
This PR changes a typo in `display_icon` field from WARBOY device metadata.
Refs
- lablup/backend.ai#1546
> fix: Change WARBOY resource display icon to FuriosaAI

- .github/workflows/codeql-analysis.yml
- .github/workflows/package.yml
As nodejs v16 ends support on September 11th, we will upgrade checkout v3, which uses nodejs v16, to checkout v4, which uses nodejs v20.
https://endoflife.date/nodejs
> ci: Bump checkout from v3 to v4

- resources/device_metadata.json
This PR updates a legacy key `ram` to `mem`, following the manager.
https://github.com/lablup/backend.ai/blob/dc6b85868fe5cb8b5aea5ba58c62d579fd38d101/src/ai/backend/manager/api/etcd.py#L36-L43
> feat: update legacy key(`ram`) from device metadata

- resources/storage_metadata.json
- src/components/backend-ai-data-view.ts
- resolves https://github.com/lablup/giftbox/issues/502
- Add 'auto' vhost when creating or cloning a data folder. (Auto volume is added only when there are multiple hosts.)
- The auto-selected folder is the lowest usage folder.
- If the usage percentage of the vhost is empty, set auto-selected vhost to the default folder.
- create `autoSelectedVhostFolder` folder with auto host.
- The auto-selected folder is set to the ceph which is the lowest usage.
- But after creating a new folder, the original host name (ceph) will be displayed on the storage list.
- Info description. The usage info will follow the original host's (ceph).
> feat: add an auto selected volume in creating and cloning a data folder

- react/src/components/DefaultProviders.tsx
- react/src/fix_antd.css
resolve #1923 
How to test:
- Open the service launcher modal.
- Change the browser window size to narrow (like the screen below, the modal has to be displayed over the the sider of mwc-drawer)
- Hover over the `?` icon next to the CPU label."
After:
> fix: the ant.d tooltip is covered in modal with mwc drawer

- .github/dependabot.yml
Manage the version of github actions with dependabot.
First, only actions officially provided by the github actions team are applied first.
In the case of other external actions, there may be unknown update history, so I think it is necessary to check.
> ci: Manage actions version with dependabot

- react/src/components/ImageEnvironmentSelectFormItems.tsx
After updating Antd to version 5.9.1 via #1932 , the block type label of a Select UI has broken.
> fix: broken `Select` UI by using inline-flex (since ant.d 5.9.1)

- src/components/backend-ai-resource-broker.ts
- src/components/backend-ai-resource-monitor.ts
- src/components/backend-ai-session-launcher.ts
- src/components/backend-ai-session-list.ts
resolve https://github.com/lablup/giftbox/issues/521
- fix: typo error so that displaying the allocated IPU
- When the user changed the resource group, the custom allocation items were updated to indicate the accelerators supported by the resource group.
- Resolved the mismatch between the selected resource preset and custom allocation and the requested resources when there are multiple accelerators.
- style: fix the broken UI of resource gauge (IPU)
| <img width="327" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/28584164/196beda4-7206-45b4-82e0-591cc2ca313e"> | <img width="274" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/28584164/f6753229-6f72-47c4-ad88-7d5d046f7177"> | 
> **Note**
The required resources …
> fix: resolve resource allocation related errors in session launchers when there are multiple AI accelerators.

- app-packager.js
This PR changes signing behavior to bypass signing Windows / Linux packages with macOS signing key.
> fix: signing only macOS packages with apple signing system on GitHub Action

- graphql.config.js
- react/src/components/ResourceGroupSelect.tsx
- react/src/index.tsx
- src/components/backend-ai-resource-broker.ts
- src/components/backend-ai-resource-monitor.ts
- hide sftp resource group from `ResourceGroupSelect` and `backend-ai-resource-broker`.
- user cannot check the sftp resource group from resource monitor and resource group selector of creating model service modal.
- `ResourceGroupSelect`: replace resource group list with graphql
> feature: hide sftp resource group

- react/data/schema.graphql
- react/src/components/ProjectResourcePolicySettingModal.tsx
- react/src/components/ResourcePolicyCard.tsx
- react/src/components/StorageStatusPanel.tsx
- react/src/components/UserResourcePolicySettingModal.tsx
- src/components/backend-ai-credential-list.ts
- src/components/backend-ai-credential-view.ts
- src/components/backend-ai-resource-policy-list.ts
- src/components/backend-ai-storage-list.ts
- src/lib/backend.ai-client-esm.ts
resolves #1970 
related PR: https://github.com/lablup/backend.ai/pull/1417
`max_vfolder_count` management UI will be handled by #1971 
- I just removed the keypair's `max_vfolder_count` related info to avoid errors that occur when trying to query vfolder list or CRUD `keypair_resource_policy`.
- Update schema
> fix: remove `max_vfolder_count` from keypair resource policy

- resources/i18n/en.json
- resources/i18n/ko.json
- src/components/backend-ai-app-launcher.ts
- src/components/backend-ai-session-list.ts
- src/components/backend-ai-storage-list.ts
This PR is extension of #1984.
This PR mainly do...
| After | Before|
|------| -------|
| <img width="399" alt="Screenshot 2023-10-24 at 7 20 58 PM" src="https://github.com/lablup/backend.ai-webui/assets/46954439/3d22bb9c-b327-4680-93b0-2c66a8b7a0d5"> | ![Screenshot 2023-10-24 at 5 22 32 PM](https://github.com/lablup/backend.ai-webui/assets/46954439/b63cd1d5-1d2b-41c6-8553-b17d8ca8f02d) |
> feature: split copy to clipboard in sftp session connection dialog

- src/components/backend-ai-storage-list.ts
resolves https://github.com/lablup/backend.ai-webui/issues/2006
By removing unnecessary logic that checks whether the image name contains `sftp-upload` or not, I have modified the fallback image to be properly selected even if `systemSSHImage` is not specified.
(image: any) =>
**~~image['name'].toLowerCase().includes('sftp-upload') &&~~**
image['installed'],
> Need sftp setting farm (`system` role  image, isolated storagy proxy node, sftp_scaling_groups, etc.): 10.82.230.101
1.  Remove the `systemSSHImage` option.
2. Open the ssh/sftp image by clicking the ssh icon on the folder dialog.
3. Check upload session is created without error.
1. Set `systemSSHImage` option.
2. Launch upload session in the same way as above.
3. Check the requested session image is the same as the set image. …
> fix: remove image naming checking when selecting sftp image

- src/components/backend-ai-app-launcher.ts
follows #1986 
Current SSH/SFTP connection command example does not work on MacOS. To fix this problem, I modified the example so that the host input goes to the end of the sentence and added missed options such as `-o`, and `-p <port>`.
+) style: added `break-word` to avoid overlapping.
| sftp -i ./id_container -P ${this.sshPort} **work@${this.sshHost}** -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null | sftp -i ./id_container -P ${this.sshPort} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null **work@${this.sshPort}** |
|scp -i ./id_container -o StrictHostKeyChecking=no UserKnownHostsFile=/dev/null -P ${this.sshPort} -rp /path/to/source work@${this.sshHost}:~/${this.mountedVfolderName}|scp -i ./id_container -o …
> fix: touchup sftp connection example text

- config.toml.sample
- src/components/backend-ai-login.ts
- src/components/backend-ai-session-launcher.ts
resolves #1997 
How to test:
1. add `allowCustomResourceAllocation` option to config.toml
2. Check the custom allocation is hidden when `allowCustomResourceAllocation` is false.
Hide custom allocation if `allowCustomResourceAllocation` is false.
> feat: add config option that can hide custom resource allocation

- src/components/backend-ai-app-launcher.ts
This PR updates app launcher's icon display logic to hide inference app being shown at the UI. App launcher is meant to display interactive apps only, so printing out inference apps here can make confusion to the user. To test this PR you have to create a model service session, move on to sessions tab and click app launcher icon.
> fix: hide inference app from app launcher

- react/src/components/UserInfoModal.tsx
- react/src/components/UserSettingModal.tsx
- resources/i18n/de.json
- resources/i18n/el.json
- resources/i18n/en.json
- resources/i18n/es.json
- resources/i18n/fi.json
- resources/i18n/fr.json
- resources/i18n/id.json
- resources/i18n/it.json
- resources/i18n/ja.json
- resources/i18n/ko.json
- resources/i18n/mn.json
- resources/i18n/ms.json
- resources/i18n/pl.json
- resources/i18n/pt-BR.json
- resources/i18n/pt.json
- resources/i18n/ru.json
- resources/i18n/tr.json
- resources/i18n/vi.json
- resources/i18n/zh-CN.json
- resources/i18n/zh-TW.json
- src/lib/backend.ai-client-esm.ts
resolves #1978 
- Query `sudo_session_enabled`
- Setting `sudo_session_enabled`
- Minimum manager version: `23.09.0b1`.
- Go to Users (credential) page -> check the user info and setting dialog.
- Checklist
> feat: add passwordless sudo user management UI

- src/components/backend-ai-resource-broker.ts
- src/components/backend-ai-resource-monitor.ts
- src/components/backend-ai-resource-panel.ts
Some fixes for UI with multiple types of accelerators. The changes are far from optimal solutions, but rather points out that they require changes. Please check if the updates are compatible with other environments.
**Broken accelerator allocation bar layout in the summary page**
**Broken resource monitor texts**
**Hide sFTP upload resource group from session launcher dialog**
**User's max session concurrency is displayed after 20 seconds**
> fix: UI with multiple types of accelerators

- react/src/components/ContainerRegistryEditorModal.tsx
- react/src/components/ContainerRegistryList.tsx
After https://github.com/lablup/backend.ai/pull/1670 merged, you can test.
There are two changes
- Set the password to `undefined` when no change is desired.
- <img width="514" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/621215/1ebca27b-87dc-421d-88cc-e86fdcf3e3c5">
- display the masked password if the password is set.  
- <img width="572" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/621215/d55a3b34-72bc-4aa3-b568-0bd97e842367">
How to test
- Create a registry with a username and password
- Click the "Edit" button in the registry. Check "비밀번호 변경" and leave the password field blank. Finally, click "Save".
> feature: set password to `undefined` when no change is desired.

- Makefile
- index.html
- package-lock.json
- package.json
- react/package.json
- src/components/backend-ai-webui.ts
- version.json
Add stand-alone binary for easy installation / runtime / setup
> **Warning**
> You should run `make` without parallelization. Set `-j1` or `\make` if aliased.
```
npm i
\make mac_arm64
```
or
```
npm i
\make linux_arm64
```
In Linux, install `zip` first.
> update: stand-alone local proxy packaging

- src/components/backend-ai-login.ts
- src/components/backend-ai-webui.ts
This PR is a counterpart to lablup/backend.ai#1692
This PR updates the `FastTrack` button to use `pipeline.frontendEndpoint`(frontend server) rather than `pipeline.endpoint`(API server) to redirect users to the right service.
Required manager version: >= 23.09.**6**
> feat: Link FastTrack button to frontend server

- react/src/components/ImageEnvironmentSelectFormItems.tsx
- react/src/components/ServiceLauncherModal.tsx
- react/src/components/SliderInputFormItem.tsx
- react/src/hooks/backendai.tsx
This PR provides multiple supported AI accelerator on service launcher modal, which formerly supported CUDA only.
After merging this PR, user can create a service with any AI accelerator that supported by both environment(image) and resource group.
| Warboy supported environment | FGPU supported environment |
|---------------------------------|-------------------------------|
| <img width="551" alt="Screenshot 2023-11-08 at 5 40 20 PM" src="https://github.com/lablup/backend.ai-webui/assets/46954439/777d598f-5007-4d67-84bc-a9264bab4334"> | <img width="551" alt="Screenshot 2023-11-08 at 5 40 14 PM" src="https://github.com/lablup/backend.ai-webui/assets/46954439/23d16091-35a0-4e47-bca9-abfecb76e921"> |
You can find the test environment setting via …
> add: a draft for updated sliderInputItem with selectable AI accelerator

- react/data/schema.graphql
- src/components/backend-ai-credential-view.ts
- src/components/backend-ai-resource-policy-list.ts
follows https://github.com/lablup/backend.ai-webui/pull/2011
Updating `max_vfolder_count` in keypair is allowed only up to API 23 version or lower.
But the `max_vfolder_count` setting UI is always shown on the resource policy modification dialog.
- If the core version is greater than 23, hide the `max_vfolder_count` setting UI in the Modify Resource Policy dialog.
- Update schema.
1. Go to the Users - Resource Policies page.
2. Check the `Max. # of folder` setting UI is displayed when only the API version is 23 or lower.
3. 23.09 endpoint: http://10.82.230.94:8090
> Fix: hide `max_vfolder_count` setting according to the api version

- react/src/components/VFolderPermissionTag.tsx
- react/src/components/VFolderTable.tsx
This component can display vFolder permissions by using a permission string or GraphQL fragment.
> feat: VFolderPermissionTag component

- react/src/components/ImageEnvironmentSelectFormItems.css
- react/src/components/ImageEnvironmentSelectFormItems.tsx
- react/src/components/ResourceAllocationFormItems.tsx
- Display Tag on Select
- Add a gradient to the end of the Tags when width is small
| <img width="378" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/621215/53a9a0c0-4c24-4be3-aa20-5e2d28a414e3"> | <img width="364" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/621215/6dd6452a-814e-4455-a943-faa81401c0e2"> |
| Cell | Cell | 
- Add opacity to image and tag when `Select` is opened (check a PyTorch icon below)
| <img width="348" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/621215/c49912a0-89d0-4635-a0d5-635ab5c28b99"> | <img width="352" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/621215/f7fa60fa-da56-41b3-81c0-217e4a64e80a"> | …
> feature: Response style for `ImageEnvironmentSelectFormItems`

- config.toml.sample
- src/components/backend-ai-webui.ts
- src/types/backend-ai-console.d.ts
This PR partially resolves #1938
- renames `blockedMenuItem` to `inactiveMenuItem`
- preserves `blockedMenuItem` for future use (hiding menu items)
> feature: rename `blockedMenuItem` to `inactiveMenuItem`

- src/components/backend-ai-session-list.ts
This PR resolves issue https://github.com/lablup/backend.ai-webui/issues/2022
CANCELLED session's log button is disabled
> Feat:Cancelled session's log button is disabled

- react/src/components/SessionListColums/SessionInfoCell.tsx
- react/src/components/SessionNameFormItem.tsx
Place the hyphen (`-`) in the input element's regex pattern at the start of the character class to prevent it from being misinterpreted as a range indicator, which raises the following error in the browser's inspector console.
> fix: Correct hyphen usage in input validator regex

- src/components/backend-ai-storage-list.ts
This PR is regression of missing Actions columns in folder explorer came from missing HTML tag.
| <img width="1101" alt="Screenshot 2023-11-27 at 9 10 42 PM" src="https://github.com/lablup/backend.ai-webui/assets/46954439/43e420d1-ea53-4b83-b6fd-ea2afc0592a7"> | <img width="1101" alt="Screenshot 2023-11-27 at 9 13 05 PM" src="https://github.com/lablup/backend.ai-webui/assets/46954439/bf7f4425-b9c3-4aef-8139-eccc76ef0f1c"> |
> fix: add omitted html tag in folder explorer

- src/components/backend-ai-session-launcher.ts
Due to the typo error, it is not available to check the env value when creating a new session.
> you can check throw the Amplified Hosting :)
- click the start session button from summary / session page.
- set `Environment Variable`
- click `CONFIRM AND LAUNCH` button.
- check the set envs are displayed well in the `Environment variables to set (optional)` part.
| ![image](https://github.com/lablup/backend.ai-webui/assets/28584164/6a3bfe78-9430-4a1b-a0b5-fd20159d6ccc) | ![image](https://github.com/lablup/backend.ai-webui/assets/28584164/79eaa57a-4711-4cb2-898d-812683e22601) |
> fix: typo error

- src/components/backend-ai-storage-list.ts
This PR is regression of missing Controls columns in vfolder list came from commenting out wrong HTML tags.
| <img width="1358" alt="Screenshot 2023-11-29 at 2 08 21 PM" src="https://github.com/lablup/backend.ai-webui/assets/46954439/00d58fae-c6a1-4ace-b8d1-b268c363d83e"> | <img width="1358" alt="Screenshot 2023-11-29 at 2 08 34 PM" src="https://github.com/lablup/backend.ai-webui/assets/46954439/fceda96a-6a95-4cfc-b3e7-09f66b7204f9"> |
> fix: remove comment applied in controls column in vfolder list

- Makefile
- index.html
- src/components/backend-ai-webui.ts
- version.json
For better traceability, use the build number per branch as the build version information. Currently, the time of build is used, but there is an issue where builds of the same source at different points are treated as different builds.
> add: BUILD_NUMBER as a number of commits on build target branch

- react/data/schema.graphql
- react/src/components/ModelCardModal.tsx
- react/src/pages/ModelStoreListPage.tsx
- src/components/backend-ai-data-view.ts
This PR 
- follows up on changes to the GraphQL Schema, which involve renaming from model_info to model_card.
- prevent sending a model metadata GraphQL query if the manager doesn't support the model store.
> fix: rename to mode_card

- react/data/schema.graphql
- react/src/components/UserInfoModal.tsx
- resources/i18n/de.json
- resources/i18n/el.json
- resources/i18n/en.json
- resources/i18n/es.json
- resources/i18n/fi.json
- resources/i18n/fr.json
- resources/i18n/id.json
- resources/i18n/it.json
- resources/i18n/ja.json
- resources/i18n/ko.json
- resources/i18n/mn.json
- resources/i18n/ms.json
- resources/i18n/pl.json
- resources/i18n/pt-BR.json
- resources/i18n/pt.json
- resources/i18n/ru.json
- resources/i18n/tr.json
- resources/i18n/vi.json
- resources/i18n/zh-CN.json
- resources/i18n/zh-TW.json
- src/components/backend-ai-credential-list.ts
- src/components/backend-ai-user-list.ts
- src/lib/backend.ai-client-esm.ts
- related: [backend.ai#1761](https://github.com/lablup/backend.ai/pull/1761)
- required Core version: `24.03.0` or newer version
- You need to upgrade alembic version to the latest by executing the following command in Core directory: 
```
./py -m alembic upgrade head
```
> FYI:
> User management in Backend.AI has two groups, user and keypair.
> The relationship btw user and keypair is 1:N relationship, but we regarded as 1:1 relationship.
> Both user and keypair has each status and works independently.
In this This PR, most of implementation is mainly focused on "main_access_key", considering the relationship between user and keypair (user can have multiple keypairs.)
> feature: Disable primary keypair deletion

- react/src/components/KeypairInfoModal.tsx
- react/src/components/UserProfileSettingModal.css
- react/src/components/UserProfileSettingModal.tsx
- react/src/index.tsx
- resources/i18n/de.json
- resources/i18n/el.json
- resources/i18n/en.json
- resources/i18n/es.json
- resources/i18n/fi.json
- resources/i18n/fr.json
- resources/i18n/id.json
- resources/i18n/it.json
- resources/i18n/ja.json
- resources/i18n/ko.json
- resources/i18n/mn.json
- resources/i18n/ms.json
- resources/i18n/pl.json
- resources/i18n/pt-BR.json
- resources/i18n/pt.json
- resources/i18n/ru.json
- resources/i18n/tr.json
- resources/i18n/vi.json
- resources/i18n/zh-CN.json
- resources/i18n/zh-TW.json
- src/components/backend-ai-usersettings-general-list.ts
* related: #2083 
- required Core version: `24.03.0` or newer version
- You need to upgrade alembic version to the latest by executing the following command in Core directory: 
```
./py -m alembic upgrade head
```
In this PR, keypair in user account information has been moved to user settings menu, since keypair is not maintained by user, but only for admin, which may confuses user if the fields is remaining in user account modal. 
Therefore, there are two things to check during this PR review:
> feature: re-arrange my account dialog

- src/components/backend-ai-general-styles.ts
This PR resolves https://github.com/lablup/backend.ai-webui/issues/2090
Now the activated and disabled mwc-switch is shown shadow colors.
> fix:activated and disabled mwc-switch's color is shown shadow color

- src/components/backend-ai-credential-view.ts
This PR resolves issue https://github.com/lablup/backend.ai-webui/issues/2050
Admin can see right active list-view whether admin move to other main menu.
> fix:The Credential View displays a list that does not match the sub-tab

- react/src/components/ImageEnvironmentSelectFormItems.tsx
- react/src/components/ImageMetaIcon.tsx
- react/src/components/ModelCardModal.tsx
- react/src/components/SessionKernelTag.tsx
- react/src/hooks/index.ts
resolve https://github.com/lablup/giftbox/issues/578
This PR
- resolve parsing error when image name has more than two `/`. ([ref](https://github.com/lablup/backend.ai-webui/pull/2109/files#diff-0c3eda30e966d59fcc7f298b411bdf4671271d6ff721e2395f9985d638a98e37R199-R202))
```
{
"name": "abc/def/tranining",
"humanized_name": "abc/def/tranining",
"tag": "01-py3-abc-v1",
"registry": "192.168.0.1:7080",
"architecture": "x86_64",
```
- fix typo related requirement tag (use `requirement` instead of `requirements`, [ref](https://github.com/lablup/backend.ai-webui/pull/2109/files#diff-0c3eda30e966d59fcc7f298b411bdf4671271d6ff721e2395f9985d638a98e37R505-R518))
- remove unnecessary useSuspensedBackendaiClient (resovled by [#1999](https://github.com/lablup/backend.ai-webui/pull/1999/files#diff-e1757eca …
> fix: Image name exceptions of `ImageEnvironmentSelectFormItem`

- react/src/components/ContainerRegistryEditorModal.tsx
This PR resolves https://github.com/lablup/backend.ai-webui/issues/2089
Modal.confirm is pop up when user isn't set username or check isChangePassword but user isn't write password
> fix:modiy condition of registry user config validation

- react/src/components/AnnouncementAlert.tsx
- react/src/index.tsx
- src/components/backend-ai-general-styles.ts
- src/components/backend-ai-summary-view.ts
This PR resolves https://github.com/lablup/giftbox/issues/570 and https://github.com/lablup/backend.ai-webui/issues/2118
This PR remove notice-ticker and announcement-panel and Implement announcement alert
if you want to long notice text, check this comment [ref](https://teams.microsoft.com/l/message/19:14c484402d874dafb15806d093b95a82@thread.skype/1702432562106?tenantId=13c6a44d-9b52-4b9e-aa34-0513ee7131f2&groupId=74ae2c4d-ec4d-4fdf-b2c2-f5041d1e8631&parentMessageId=1702284207118&teamName=devops&channelName=Frontend&createdTime=1702432562106)
Before
After
> feat:Implement notice alert and delete notice-ticker and announcement panel.

- react/src/components/AnnouncementAlert.tsx
follows https://github.com/lablup/backend.ai-webui/pull/2098
resolves #2124 
Before - include unexpected spaces
After - removed unexpected spaces
1. setup announcement with the control panel dashboard page.
``` Base system is upgraded to Enterprise R2/23.09. <lablup-shields app="status" color="green" description="Running" ui="round"></lablup-shields>```
2. refresh webui
> style: remove `whiteSpace` to fix the broken UI of the announcement.

- react/src/components/ImageEnvironmentSelectFormItems.tsx
- react/src/components/ResourceAllocationFormItems.tsx
- react/src/components/ServiceLauncherModal.tsx
ref: https://github.com/lablup/giftbox/issues/569
This PR introduces the feature user can input the image name manually when `allow_manual_image_name_for_session` config is true.
How to test
- Set `allow_manual_image_name_for_session` of config.toml  to true
- Open service launcher, 
- Input image name manually
- Start service
If you need a test server that has a private image, please let me know.
Review Check List
```[tasklist]
```
> feat: `allow_manual_image_name_for_session` option in ServiceLauncher

- react/data/schema.graphql
- react/src/components/EndpointOwnerInfo.tsx
- react/src/pages/RoutingListPage.tsx
- react/src/pages/ServingListPage.tsx
- resources/i18n/de.json
- resources/i18n/el.json
- resources/i18n/en.json
- resources/i18n/es.json
- resources/i18n/fi.json
- resources/i18n/fr.json
- resources/i18n/id.json
- resources/i18n/it.json
- resources/i18n/ja.json
- resources/i18n/ko.json
- resources/i18n/mn.json
- resources/i18n/ms.json
- resources/i18n/pl.json
- resources/i18n/pt-BR.json
- resources/i18n/pt.json
- resources/i18n/ru.json
- resources/i18n/tr.json
- resources/i18n/vi.json
- resources/i18n/zh-CN.json
- resources/i18n/zh-TW.json
- src/lib/backend.ai-client-esm.ts
This PR resolves owner of model session always being shown as the email of current logged in user, by pulling out user information from the new GQL fields introduced at lablup/backend.ai#1831. Previous approach can cause confusion to the system admin, as they are possible to also take a look at the status of model service created by other users. 
Now this displays the true information correctly.
Whenever there's a difference between model service creator and actual model session owner, by hovering the cursor over question mark webui will show a tooltip mentioning about these facts. 
Testing this PR will require a Backend.AI server with lablup/backend.ai#1831 patch applied.
> fix: model service owner always represented as logged in user

- react/src/components/DynamicUnitInputNumberWithSlider.tsx
- react/src/components/InputNumberWithSlider.tsx
- The sliders of `InputNumberWithSilder` and `DynamicUnitInputNumberWithSlider` display the mark outside the slider when the mark value is greater than the max of the slider.
Open the service launcher modal in a local dev environment, you can see this bug on the slider for cluster size.
> fix: omit the mark if it is greater than the max

- src/components/backend-ai-edu-applauncher.ts
- src/components/backend-ai-environment-list.ts
resolves https://github.com/lablup/giftbox/issues/614
Follow-up #1993 
- Get `sessionTemplate` query string and launch a session with a session template with the given name
- Close edu-applauncher's indicator when any error raises
- remove `sleep` before launching rstudio image because the issue resolved
[Follow this link
](https://lablup.sharepoint.com/:fl:/s/b334cd9f-0792-4007-b883-78ef6adfbd9b/EQDtlPsQToxBmeDOi1zljvkBOBxPK00g8cciC60spr_vbA?e=iqkT98&nav=cz0lMkZzaXRlcyUyRmIzMzRjZDlmLTA3OTItNDAwNy1iODgzLTc4ZWY2YWRmYmQ5YiZkPWIlMjFLZDR5eDFONkUwMnN5cG5Kd3dXTnhMbHFzYU12SDlkS2xLeTZHa29tcVUyUTBZcTdyUFJDVEpZdkxqVktWU2h3JmY9MDFLU1JMSFhZQTVXS1BXRUNPUlJBWlRZR09STk9PTERYWiZjPSUyRiZhPUxvb3BBcHAmcD0lNDBmbHVpZHglMkZsb29wLXBhZ2UtY29udGFpbmVyJng9JTdCJTIydyUyMiUzQSUyMlQwUlRVSHhzWVdKc2RYQXVjMmhoY21Wd2IybHVk …
> feature: Improve edu-applauncher scalability for adding session templates

- src/components/backend-ai-edu-applauncher.ts
follows #2147 
Mapping `servicePorts` instead string array when get services.
Before
```js
const servicePorts = JSON.parse(_sess.service_ports || '{}');
const services = Object.keys(servicePorts).map((s) => s.name) || [];
```
After
```js
const services = Object.keys(servicePorts).map((s) => servicePorts[s].name) || [];
```
> fix: mapping `servicePorts` instead string array when get services.

- react/src/components/VFolderTable.tsx
- react/src/components/VFolderTableFormItem.tsx
- react/src/pages/SessionLauncherPage.tsx
resolve #2171
This PR introduces `filter` props of `VFolderTableFormItem` and sets filter to neo session launcher vFolder form item to show only `ready` folders.
> feat: filter props of VFolderTableFormItem

- react/src/components/ContainerRegistryEditorModal.tsx
- react/src/components/ContainerRegistryList.tsx
- react/src/components/EndpointTokenGenerationModal.tsx
- react/src/components/ModelCloneModal.tsx
- react/src/components/ModelServiceSettingModal.tsx
- react/src/components/ProjectResourcePolicySettingModal.tsx
- react/src/components/QuotaSettingModal.tsx
- react/src/components/SessionListColums/SessionInfoCell.tsx
- react/src/components/SignoutModal.tsx
- react/src/components/TableColumnsSettingModal.tsx
- react/src/components/UserResourcePolicySettingModal.tsx
This bug was found during the review of #2121.
The `initialValues` props don't work in the specific case below:
- In Electron, the modal has the `<Form/>` with `initialValues` prop. This is the case even when `destroyOnClose` of Modal and `preserve=false` of Form are set.
This PR has the following changes:
- Use `ref` of Form instead of `form` if available. (FYI, `Form.useWatch` cannot be used with `ref` because `ref` can be null)
- Set the row key to the table of ContainerRegistryList
- Please check the electron environment and browser environment. For the election environment, you can build `make clean` and `make mac_arm64` (other [platforms](https://github.com/lablup/backend.ai-webui/blob/main/Makefile#L54-L60) are available.)
- Please check the modals that have been changed. …
> fix: `initialValues` props of `<Form/>` under Modal doesn't work in Electron

- src/components/backend-ai-resource-monitor.ts
This PR removes undesired ROCm icon from `backend-ai-resource-monitor` component.
> fix: remove ROCm icon from resource monitor

- react/src/components/ContainerRegistryEditorModal.tsx
- resources/i18n/de.json
- resources/i18n/el.json
- resources/i18n/en.json
- resources/i18n/es.json
- resources/i18n/fi.json
- resources/i18n/fr.json
- resources/i18n/id.json
- resources/i18n/it.json
- resources/i18n/ja.json
- resources/i18n/ko.json
- resources/i18n/mn.json
- resources/i18n/ms.json
- resources/i18n/pl.json
- resources/i18n/pt-BR.json
- resources/i18n/pt.json
- resources/i18n/ru.json
- resources/i18n/tr.json
- resources/i18n/vi.json
- resources/i18n/zh-CN.json
- resources/i18n/zh-TW.json
There are some chances that user could use customized hostname with port number, but antd input form validation on URL type doesn't work properly on these cases. URL validation need to accept the addresses like "bai-repo:####".
1. use new URL for url validation
2. Set Error Message for Invalid type URL
> feat: set RegExpression for validating URL pattern

- react/src/pages/RoutingListPage.tsx
feature:
- Gets the status data and uses it for the button disable property.
> feat: prevent modifying DESTROYING status services

- react/src/components/BAINotificationItem.tsx
- react/src/hooks/useBAINotification.tsx
feature :
- Added allowEllipsis prop to control ellipsis property. (allowEllipsis (boolean))
- Users can use the ellipsis feature by clicking on the text.
> feat: apply ellipsis into notification

- src/components/backend-ai-credential-view.ts
- src/components/backend-ai-summary-view.ts
This PR resolves https://github.com/lablup/backend.ai-webui/issues/2175
After this PR, it is need to implement antd's tab instead of using mwc-tab and add routing each tab.
> fix: display credential-list when `keypair`button in `summary` page is clicked

- react/src/pages/UserSettingsPage.tsx
- Refresh the browser on the /summary page.
- Click the user dropdown in the top right corner.
- Click the "log / error" item.
- After navigating to the "Settings & Logs" page, click the "General" tab.
You will see that the tab content is blank.
> fix: general setting page is empty after navigation from log tab

- src/components/backend-ai-credential-view.ts
- src/components/backend-ai-summary-view.ts
This PR resolve to fix `credential` in sidebar is shown keypair-list after merging https://github.com/lablup/backend.ai-webui/pull/2194
How to reproduce this bug:
- Login and go to the credential page to click `credential` in sidebar
- You can show keypair-list
> fix: when user menu is clicked, credential tab is shown instead of user.

- react/src/components/MainLayout/WebUIHeader.tsx
- react/src/components/VFolderTable.tsx
- react/src/hooks/index.tsx
resolve https://github.com/lablup/backend.ai-webui/issues/2217
This PR makes:
- Updates the current project based on the Project Select component in WebUIHeader.
- Persists the selected current project.
> fix: current project doesn't apply to vfolder list and session list

- react/src/index.tsx
- src/components/backend-ai-resource-monitor.ts
This PR resolves resource-monitor's layout issue that is occurred after merging https://github.com/lablup/backend.ai-webui/pull/2166
How to reproduce this bug:
- make long resource group name
- Go to the session page(/job)
- Reduce the browser window size as possible.
Before
After
> fix: resource-monitor is shown at out of layout

- react/src/components/MainLayout/MainLayout.tsx
(cherry picked from commit fa84a860dae37fc3fd3e16a2155abca92e441fba)
This PR resolves UI bug where main layout header appears behind fixed column.
How to reproduce this bug:
- Go to the page that has a fixed header table, such as `/session/start?step=2` and `/serving`.
- Reduce the browser window size until it has a scroll bar.
- Scroll to the bottom until the table header overlaps the table content.
> fix:  main layout header appears behind fixed column table

- main.js
This PR introduces 
- `LIVE_DEBUG`: Set to `1` if you want to live debug mode for Electron. The default value is `undefined`
- `LIVE_DEBUG_ENDPOINT`: This variable allows developers to dynamically specify the endpoint URL that the application should connect to during live debugging. The default value is `http://127.0.0.1:9081`
```
LIVE_DEBUG=1 npm run electron:d
```
```
LIVE_DEBUG=1 LIVE_DEBUG_ENDPOINT=http://warboy-15-local.backend.ai:9081 npm run electron:d
``` 
> fix: Electron live debug mode using `LIVE_DEBUG` and `LIVE_DEBUG_ENDPOINT`

- react/src/App.tsx
- react/src/components/PasswordChangeRequestAlert.tsx
resolves #2229 
1. Log in with admin account.
2. Click Users tab.
3. Click the setting icon of the control column.
4. Enable `Require password change?`.
5. Log in with the account you just set up.
> feat: add password change request alert to summary page

- react/src/App.tsx
- react/src/components/MainLayout/MainLayout.tsx
The password change request alert is displayed on all pages, according to the traditional implementation method.
follows https://github.com/lablup/backend.ai-webui/pull/2238
> feat: display announcement alert to every page.

- react/src/hooks/useBAINotification.tsx
- rollup.plugins.config.ts
> fix: unintended console log and import `glob`

- react/src/pages/RoutingListPage.tsx
- react/src/pages/ServingListPage.tsx
- src/components/backend-ai-session-launcher.ts
This PR fixes two thing,
- Core(manager) version: `23.9.9~`
How to test:
1. Go to Serving page
2. Click `Start service` button.
3. Service launcher modal pops up.
4. Create a service with two cases:
5. Click `Create` button.
6. Click Endpoint Name you just created from step 4.
7. See image info in Routing page.
| <img width="1229" alt="Screenshot 2024-03-06 at 12 02 14 PM" src="https://github.com/lablup/backend.ai-webui/assets/46954439/112fdeee-f19d-4eec-93a8-881b13b1a7c0"> | <img width="1229" alt="Screenshot 2024-03-06 at 12 24 07 PM" src="https://github.com/lablup/backend.ai-webui/assets/46954439/2dbcb7e8-5d54-48d6-bf2a-df1b18282f90"> |
> hotfix: regression of image info display in serving page

- src/components/backend-ai-session-launcher.ts
- src/components/lablup-slider.ts
- change disabled slider color.
- change total allocation conditional rendering logic in session launcher. 
(Before, If user has multiple clusters or sessions selected, the launcher shows multiple Total Resource Allocation panels.)
> fix: change disabled slider color and total allocation conditional rendering

- src/components/backend-ai-session-launcher.ts
The nested background color of the total allocation panel in the session launcher now changes depending on the dark mode theme. 
> feat: fixed to be able to dynamically change colors.

- src/components/backend-ai-session-launcher.ts
The font-size of session launcher button is increased after #2193 .
Afte this PR
> fix: font-size of the session launcher button

- main.js
- src/components/backend-ai-app-launcher.ts
This PR fixes bug when built-in app in session execution fails when refreshes app itself inside Desktop application especially in Windows environment.
- Manager version: `23.09.10rc2`~
> fix: regression of built-in app in session execution when app itself is refreshed in Windows Desktop app

- .husky/pre-commit
- package.json
- react/src/components/ResourcePolicyCard.tsx
- react/src/pages/ModelStoreListPage.tsx
Original pre-commit doesn't affect the react components.
Fix the pre-commit command to format both lit(web) components and react components.
> fix: modify husky config to format both lit and react components

- src/components/backend-ai-resource-broker.ts
This PR fixes regression issue of missing categories in "environment select UI" inside session-launcher.
All of image except custom image, which is without description in metadata, should be grouped with the title defined in
[metadata.json](https://github.com/lablup/backend.ai-webui/blob/main/resources/image_metadata.json).
For more details, please look through the code below.
https://github.com/lablup/backend.ai-webui/blob/fe8209a0b6e060f4e03b6f5b1aef7c173033c1de/src/components/backend-ai-resource-broker.ts#L1096-L1108
| After | before |
| <img width="341" alt="Screenshot 2024-03-22 at 3 33 51 PM" src="https://github.com/lablup/backend.ai-webui/assets/46954439/12c4b93b-4cd1-42e4-a1d3-2f75f46efb54"> | <img width="341" alt="Screenshot 2024-03-22 at 3 34 08 PM" …
> fix: regression of imageInfo initialization for categorizing environments by label in metadata

- react/src/components/StorageStatusPanel.tsx
- resources/i18n/de.json
- resources/i18n/el.json
- resources/i18n/en.json
- resources/i18n/es.json
- resources/i18n/fi.json
- resources/i18n/fr.json
- resources/i18n/id.json
- resources/i18n/it.json
- resources/i18n/ja.json
- resources/i18n/ko.json
- resources/i18n/mn.json
- resources/i18n/ms.json
- resources/i18n/pl.json
- resources/i18n/pt-BR.json
- resources/i18n/pt.json
- resources/i18n/ru.json
- resources/i18n/tr.json
- resources/i18n/vi.json
- resources/i18n/zh-CN.json
- resources/i18n/zh-TW.json
- show quota scope id (user id) in storage status panel.
- change antd's descriptions column because 2 line representation is visually better than 3 line representation.
(I've tried showing text at the bottom of the card without using descriptions.item, but it doesn't feel consistent.)
- modify the way render descriptions items that is appropriate for the current antd version. The old way was used in versions 5.8.0 and earlier.
> feat: Quota Scope ID in data page's storage status panel

- src/components/backend-ai-agent-list.ts
Sometimes there has a chance of receiving NULL value in `live_stat` in agent status, but since now It's been treated as if always has value, which caused runtime-error. Therefore I added conditional statement so that parsing `live_stat` value is only available when it's not NULL.
> fix: regression of listing connected agent with null-check on live_stat from response

- react/src/components/ForceTOTPChecker.tsx
- react/src/components/MainLayout/MainLayout.tsx
- react/src/components/TOTPActivateModal.tsx
- react/src/components/UserDropdownMenu.tsx
- react/src/components/UserInfoModal.tsx
- react/src/components/UserProfileSettingModal.tsx
- react/src/components/UserSettingModal.tsx
- react/src/hooks/backendai.tsx
This PR introduces `ForceTOTPChecker` to open `TOTPActivateModal` for users who have not activated TOTP when the `forceTotp` configuration is true.
This part was missing during the transition to React.
- Install the TOTP plugin.
- Set the following config.toml variables:
```
[general]
enable2FA = true
force2FA = true
```
- Try to log in using a user who has not activated TOTP.
- You will see the TOTPActivateModal (refer to the screenshot above) right after logging in.
> Fix: TOTP activation modal not opening for non-TOTP users with `forceTotp`

- react/src/components/StorageStatusPanel.tsx
- src/components/backend-ai-data-view.ts
This PR fix the bug related to the count of created vFolders in `StorageStatusPanel`
Before this PR,
- the count does not include vfolders in the trash bin with 'delete-pending' status.
- the count is not updated right after creating/deleting(forever) vfolders.
> fix: created count in `StorageStatusPanel`

- react/src/components/ServiceLauncherModal.tsx
In Service endpoint editing,
- The vFolder field value is always the first option.
This PR 
- displays the correct value as read-only.
- uses `VFolderLazyView` and show Skeleton when `VFolderLazyView` is suspended.
| <img width="508" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/621215/031f7c3f-6854-4cd7-8c46-7831d8e00e98"> | <img width="531" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/621215/2a01c397-671c-4308-a038-3e781a3b3e64"> | 
> fix: vFolder field has incorrect value in editing

- src/components/backend-ai-session-list.ts
fix: fetch `image_object` when supporting `per-user-image` to fix the error that occurs fetching the session list in 23.09
> fix: session list fetch error

- react/src/components/ResourceAllocationFormItems.tsx
- react/src/pages/SessionLauncherPage.tsx
This PR resolves AI accelerator doesn't move when user selects resoruce preset from the list in neo session launcher and :
- [omit resource slot type which has no slots](https://github.com/lablup/backend.ai-webui/pull/2308/commits/3282e41ae3f4e2b087281115e19a7b4f27499dfd)
- [When applying a preset, use the first matched accelerator type](https://github.com/lablup/backend.ai-webui/pull/2308/commits/848271b305ebc9e2615877939ce814cf76a66a6b)
https://github.com/lablup/backend.ai-webui/assets/46954439/8b200a32-88e3-4b84-a4c5-c4b57db44d7b
> fix: apply AI accelerator allocation when selecting resource preset in neo session launcher

- react/src/components/ImageEnvironmentSelectFormItems.tsx
- react/src/components/ResourceAllocationFormItems.tsx
- react/src/components/SessionKernelTag.tsx
- react/src/hooks/index.tsx
- react/src/pages/SessionLauncherPage.tsx
- resources/i18n/de.json
- resources/i18n/el.json
- resources/i18n/en.json
- resources/i18n/es.json
- resources/i18n/fi.json
- resources/i18n/fr.json
- resources/i18n/id.json
- resources/i18n/it.json
- resources/i18n/ja.json
- resources/i18n/ko.json
- resources/i18n/ms.json
- resources/i18n/pl.json
- resources/i18n/pt-BR.json
- resources/i18n/pt.json
- resources/i18n/ru.json
- resources/i18n/tr.json
- resources/i18n/vi.json
- resources/i18n/zh-CN.json
- resources/i18n/zh-TW.json
- src/components/backend-ai-edu-applauncher.ts
- src/components/backend-ai-login.ts
- src/components/backend-ai-session-list.ts
This PR:
- changes the previous session launcher name from "Previous" to "Classic" 
- uses human-readable tags for images in Neo session launcher's final step
| <img width="372" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/621215/ef6f2fe1-5907-42fd-b957-dd2fae747009">|  <img width="664" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/621215/67b42ab5-0878-4c16-a138-84144aaae3a5"> | 
- disables presets based on the current image's accelerator limits
After
> hotfix: neo session launcher on cloud

- react/src/components/ResourceAllocationFormItems.tsx
- react/src/pages/SessionLauncherPage.tsx
Before this PR, if there is no remaining session count related to the session limit and no `always_enqueue_compute_session`, the form item displays an error, and the user is not allowed to create a (pending) session. 
- However, after this PR, the user can create a (pending) session even if there is no remaining session count, regardless of the `always_enqueue_compute_session` setting. **This behavior is the same as the classic session launcher.**
- [the session preparing notification remains on until the promise is re…](https://github.com/lablup/backend.ai-webui/pull/2312/commits/58366b4fecdca7f0737feb15eeeffe4668a0a1c4)
> remove remaining session limit validation error

- resources/i18n/de.json
- resources/i18n/el.json
- resources/i18n/en.json
- resources/i18n/es.json
- resources/i18n/fi.json
- resources/i18n/fr.json
- resources/i18n/id.json
- resources/i18n/it.json
- resources/i18n/ja.json
- resources/i18n/ko.json
- resources/i18n/mn.json
- resources/i18n/ms.json
- resources/i18n/pl.json
- resources/i18n/pt-BR.json
- resources/i18n/pt.json
- resources/i18n/ru.json
- resources/i18n/tr.json
- resources/i18n/vi.json
- resources/i18n/zh-CN.json
- resources/i18n/zh-TW.json
- src/components/backend-ai-session-list.ts
* Core version: 24.03.0 or later
This PR mainly fixes cosmetic issues in container commit dialog:
(For now, even if superadmin role tries to do container commit or push session to image, the server throws "No such session" response.)
| <img width="373" alt="Screenshot 2024-04-06 at 4 54 06 PM" src="https://github.com/lablup/backend.ai-webui/assets/46954439/d94fda64-2af8-468c-9cd2-7189765bf005"> | <img width="376" alt="Screenshot 2024-04-06 at 5 15 23 PM" src="https://github.com/lablup/backend.ai-webui/assets/46954439/961aa70f-95a4-4307-b8b6-67ce681e08cb">
|
* After 
* Before
> hotfix: touchup container commit feature

- src/components/backend-ai-session-list.ts
This PR is 
- related to #2314 
- update imageify availability status on `input` event
> fix: update imageify availability status on `input` event

- .github/workflows/package.yml
- app-packager.js
Follow-up of commit [ff1e179](https://github.com/lablup/backend.ai-webui/commit/ff1e1794194156c19f9c9b140254c5f5c99ee47a). This PR fixes notarization not working after upgrading our packager dependency to a new one.
> fix: notarization not working

- react/src/components/DynamicUnitInputNumber.tsx
When you input `mem` like this:
You can see the error like this:
> fix: check isNaN before set value of DynamicUnitInputNumber

- src/components/backend-ai-storage-proxy-list.ts
For plugin pages that use `backend-ai-storage-proxy-list.ts`, the grid size is too large. So I added CSS variable to `vaadin-grid`. The `--list-height` is already used in many plugin pages.
> style: add css variable to vaadin grid for plugin page

- src/components/backend-ai-webui.ts
- Fixed webui to follow the previously set language even if the connection happen again
- Added allow language without deleting validation logic to handle possible exceptions.
> fix: set supported language codes to allow all i18n languages

- react/src/components/ResourceAllocationFormItems.tsx
- react/src/components/ResourceGroupSelect.tsx
- react/src/hooks/useResourceLimitAndRemaining.tsx
- react/src/pages/SessionLauncherPage.tsx
This PR includes the following changes:
- Ignore the `/resource-preset` response error.
- Clear the value of `ResourceGroupSelect` when the value is not in the options.
- Validate and handle validation errors for no resource group.
- change the position of the resource item in the Neo Session Launcher preview step.
| <img width="655" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/621215/18113b7a-7fc6-4f62-94dd-5c4abe4fbb72"> | <img width="652" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/621215/afb897e1-5485-484d-9b76-c2f73de70076"> | 
This PR affects the pages that use `ResourceGroupSelect` and `ResourceAllocationFormItems`, such as the Neo Session Launcher, Service Launcher, and Resource Monitor. …
> fix: unkown scailing group error when user change the project

- react/src/components/MainLayout/WebUISider.tsx
- react/src/helper/customThemeConfig.ts
- resources/theme.json
- resources/theme.schema.json
- scripts/replace-with-brand-name.sh
related: https://github.com/lablup/backend.ai-webui/issues/2327
- add `branding` option to `theme.json`.
- the `companyName` will change the bottom text of the sidebar.
- `brandName` will be used to change all brand names (default: Backend.AI) in i18n at once.
- How to check: run `./scripts/replace-with-brand-name.sh` in webui root directory.
> feat: add branding config to theme.json

- src/components/backend-ai-agent-list.ts
- src/plastics/lablup-shields/lablup-shields.ts
- Change the color of the local icon on resource pages to white when in dark mode
- Fixed the regionRenderer function to rebind when isDarkMode is updated via the update lifecycle
- Remove the word-break attribute from text inside a shield
| Light Mode| Dark Mode| 
|---|---|
|![image](https://github.com/lablup/backend.ai-webui/assets/51399982/250ad7db-f05a-4aa6-8f89-628779e53ad1)|![image](https://github.com/lablup/backend.ai-webui/assets/51399982/c86e6154-389f-4836-96ca-b90105ea2c27)|
> feat: apply filter to png icon when theme is darkmode

- src/components/backend-ai-page.ts
This PR avoid calling `_viewStateChanged` for same `active` value in `attributeChangedCallback`.
Before the PR, every component extending the BackendAIPage component runs `_viewStateChanged` twice with the same active value, leading to multiple duplicated remote requests.
> fix: `_viewStateChanged` is called for same `active` value in `attributeChangedCallback`

- react/src/components/ProjectSelect.tsx
- Core Version: `23.09` or newer
This PR resolves showing only available "project(a.k.a. group)" list according to user info, not only for user role, but also in superadmin.
Please check out the previous version of the code
- [Getting allowed group list from user](https://github.com/lablup/backend.ai-webui/blob/16974db484321c6e9bd25dc2e1fceb2dc44ecff4/src/components/backend-ai-login.ts#L1689-L1733)
- [Filtering in Client-side to only allow accessible group from allowed group list](https://github.com/lablup/backend.ai-webui/blob/16974db484321c6e9bd25dc2e1fceb2dc44ecff4/src/components/backend-ai-login.ts#L1760-L1777)
> ⚠️ NOTE: Current admin user is only accessible to "default" project(group).
| <img width="457" alt="Screenshot 2024-04-15 at 7 39 48 PM" …
> hotfix: regression of showing project list according to allowed group in user info

- react/src/components/VFolderTable.tsx
- react/src/components/VFolderTableFormItem.tsx
- react/src/hooks/index.tsx
- react/src/pages/SessionLauncherPage.tsx
This PR contains changes related to vFolder validation in the Neo session launcher. Please review the commits one by one.
- remove console.log warning about `<form> cannot appear as a descendant of <form>`
- add missing name rule for vFolder alias map for preview step
- [exclude auto-mounted vFolders from the vFolder list in Neo session launcer](https://github.com/lablup/backend.ai-webui/commit/d6c8308bb8d032d5ff7ed4076027196cd63650d9)
- validate form after step changed using `useEffect` and set the last validation error time to re-render.
> fix: vFolder form item validation in Neo session launcher

- react/src/components/MainLayout/MainLayout.tsx
- src/components/backend-ai-login.ts
- Make modal's label text automatically wrap when it gets long.
- Adjust the font size of the MWC button.
- If the value type of antd token value is numeric, append 'px' after it. (e.g. fontSize)
> style: label wrapping, font resizing and numeric token formatting in login panel

- react/src/components/MainLayout/MainLayout.tsx
`--token-xxx` has already px from #2338, I removed the duplicated definition.
> style: remove `px` when calculating margin of WebUIHeader wrapper

- react/src/components/ResourceAllocationFormItems.tsx
- If there is no accelerator requirement in the image:
- Exclude accelerators presets.
- Disable the accelerator input field.
- If there is an accelerator requirement in the image:
- (After this PR) **Show non-accelerator presets also.** 
- Enable the accelerator input field.
> hotfix: enable non-accelerator preset when accelerator image

- react/src/components/MainLayout/MainLayout.tsx
This reverts commit 8ab862887725094c59ce51de0a5fae767b9eaffe.
> revert: "#2344 remove px when calculating margin of WebUIHeader wrapper"

- .github/workflows/jest.yml
ref: https://github.com/ArtiomTr/jest-coverage-report-action?tab=readme-ov-file#change-annotations
> ci: display failed-tests annotation only in jest-coverage-report-action

- index.html
- manifest.json
- package.json
- react/package.json
- react/src/components/ServiceLauncherModal.tsx
- src/components/backend-ai-webui.ts
- version.json
- Core Version: `23.09` or newer.
This PR resolves #2353.
For the test case, please refer to the issue mentioned above.
> hotfix: listup only ready status vfolder on service launcher

- react/src/components/ResourceAllocationFormItems.tsx
How to test:
- Select a preset in Neo session launcher.
- Refresh the browser.
Expected behavior:
- After refreshing, the preset should not change.
> fix: preserve the preset of session launcher using query parameters.

- react/src/components/ServiceLauncherModal.tsx
This PR is related to https://github.com/lablup/backend.ai-webui/pull/2345 and sets a default environment as the initial value of the service launcher.
> fix: default environment as a initial value of the service launcher

- react/src/components/VFolderTable.tsx
- react/src/pages/SessionLauncherPage.tsx
This is related to https://github.com/lablup/backend.ai-webui/pull/2334. But it doesn't fix all bugs.
In the final step of Neo Session Launcher, the bug that shows an error in vFolder validation when there is none. 
How to reproduce:
It occurs occasionally (you might see this after several tries.)
-  Start with the form that has no validation error
-  Select one vfolder and type a alias name to `ㄱ`)
-  Go to final step.
- And go back to the Data vFolder and unselect vfolder and go to the final step.
- You can see the error sometimes.
https://github.com/lablup/backend.ai-webui/assets/621215/9c6723e1-3c00-4861-8211-b786787cc916
> fix: wrong vFolder validation result occasionally.

- src/components/backend-ai-storage-list.ts
- Prevent delete/restore by users without delete permission.
1. Share vfolders to other users with different permissions.
2. After the sharing is successful, log in as the owner user and move the folders to the trash bin.
3. log in as the shared user account, and make sure that the permanent delete and restore features are enabled according to your permissions. (Only accounts with the delete permission can be permanently deleted and restored.)
> fix: prevent delete in shared vfolder by permission

- react/src/components/VFolderTable.tsx
This PR resolves #2368.
This is a side effect of https://github.com/lablup/backend.ai-webui/pull/2359
Before this PR, `VFolderTable` was triggering `onChangeSelectedRowKeys` on every render if the parent component passed `selectedRowKeys` as a new instance of an array. `VFolderTable` should consider this scenario.
> fix: `onChangeAliasMap` is triggered on every render

- react/src/components/MainLayout/WebUISider.tsx
The sider selection key value for the session page of the component's initial render is 'job'. Since `neo session launcher` uses 'session/start' as the query path, it needs to be changed to recognize it as the 'job' key. 
If the first query path is 'session', change it to 'job' so that it can be recognized as the key of the sider.
> fix: Change '/session' path to be used as sider's selectedKey 'job'

- react/src/components/VFolderTable.tsx
- react/src/components/VFolderTableFormItem.tsx
- react/src/pages/SessionLauncherPage.tsx
This PR adds functionality to show auto-mounted folders in the VFolderTable and resolve [#2371](https://github.com/lablup/backend.ai-webui/issues/2371)
- Added logic to display auto-mounted folders in the VFolderTable component
1. Run the application
2. Navigate to the VFolderTable component
3. Verify the auto-mounted folders section is displayed
The change was made to enhance the user experience by providing visibility into auto-mounted folders in the VFolderTable.
---
> feat: auto mounted vFolder in Neo session launcher

- react/src/components/ServiceLauncherModal.tsx
- react/src/pages/RoutingListPage.tsx
- react/src/pages/ServingListPage.tsx
This pull request introduces a change to the `onCancel` handling in the `ServiceLauncherModal` to resolve the issue of the modify service modal popping up when clicking the start service button.
In the `ServiceListPage`, the `onRequestClose` method is called to set the `editingModelService` to null and remove the `onCancel` prop. 
In the `ServiceLauncherModal`, the `onCancel` behavior has been changed to call `onRequestClose` when triggered.
1.  Navigate to the serving page.
2. Click the gear icon in the Control column and close the modal with the close button at the bottom (not the x button).
3. Click Create new service button.
4. The create modal should appear.
---
resolves https://github.com/lablup/backend.ai-webui/issues/2378
> fix: include cancel handler in ServiceLauncherModal

- react/src/components/EndpointTokenGenerationModal.tsx
This change fixes the inconsistency in the props of EndpointTokenGenerationModal.tsx.
Property 'onOK' is corrected to 'onOk' in EndpointTokenGenerationModal.tsx.
Pull the changes, and verify the property in the EndpointTokenGenerationModal.tsx component.
The change was necessary to align with the correct property name and prevent potential prop related issues.
---
> Omit `onOk` from `BAIModalProps` instead of `onOK`

- src/components/backend-ai-storage-list.ts
`auto mounted folder` is a folder that name begins with '.' in the folder name. I added folder name validation to the `isSharingAllowed` validation logic in the control button lander logic.
> fix: preventing sharing of auto-mounted folders

- .github/labeler.yml
- .github/workflows/label.yml
As the labeler became version v5, its usage has changed.
```
any: match ALL globs against ANY changed path
all: match ALL globs against ALL changed paths
```
From the existing two rules that could be used,
```
any-glob-to-any-file: ANY glob must match against ANY changed file
any-glob-to-all-files: ANY glob must match against ALL changed files
all-globs-to-any-file: ALL globs must match against ANY changed file
all-globs-to-all-files: ALL globs must match against ALL changed files
```
It has been added so that it can be used in 4 ways.
> ci: Bump actions/labeler from 4 to 5

- react/src/App.tsx
- react/src/components/BAIErrorBoundary.tsx
- react/src/components/MainLayout/MainLayout.tsx
This PR resolves error handling strategy to show "custom error boundary" rather than default error boundary page provided by react-router.
> fix: add ErrorBoundary on main layout when error occurred during fetching TOTP checker

- src/components/backend-ai-app-launcher.ts
resolves https://github.com/lablup/giftbox/issues/666
- Add `User work`
- Added styles for `ssh-connection-example` and `vscode-connection-example` classes.
- Updated handling of `window.__local_proxy.url` check.
- Refactored HTML structure and added conditional rendering.
- Modified checkbox and textfield behavior.
- Added checkbox for `allowPreferredPort`.
- style: For dark theme support, refactoring styling codes.
1. create a session in **electron mode**
2. click session app -> click vscode desktop
> feat: add `User work` to VSCode remote connection info

- src/components/backend-ai-session-list.ts
The `auto-width` property of vaadin grid scans all cells in that column and determines the column width to fit the widest cell. 
If the column item data is updated, the column will be resized with the new data, so the user-adjusted column width will be reset and the focus will be on the reset column.
Removed the `auto-width` attribute and fixed it to not recalculate the width even if the data is updated by specifying the width directly.
> bug: session list grid resized when data is refetched

- react/src/components/BAIModal.css
- react/src/components/BAIModal.tsx
This pull request prevents BAIModal from being draggable from its content.
Two lines of code have been added, one to BAIModal.css and one to BAIModal.tsx. 
The changes make the contents of the BAIModal un-draggable by adding the 'no-drag' value to the '-webkit-app-region' attribute. This prevents the modal from being dragged when clicked inside the content area.
To test these changes, open a ServiceLauncherModal and attempt to drag the modal by clicking within the content area in Electron app. It should not move.
This change improves the user experience by preventing unwanted behavior when interacting with BAIModals.
---
> fix: Modal header buttons are not clickable in the top area of Electron

- src/components/backend-ai-session-launcher.ts
This PR resolves setting `cuda.shares` as the first AI accelerator when multiple setting (`cuda.device`, `cuda.shares`) applied in server-side.
> hotfix: set cuda share first as an ai accelerator when both cuda device and shares available

- react/src/components/BAIErrorBoundary.tsx
This pull request modifies the BAIErrorBoundary component's refresh functionality to be compatible with the Electron environment.
The PR updates the onClick handler of the refresh button in the Error View. When the refresh button is clicked, the application checks whether it's running in an Electron environment. If so, it refers to the 'electronInitialHref' for reloading; otherwise, it uses the standard location.reload().
You can test this by triggering an error on the page and clicking the refresh button, in both web browser and Electron environments.
- Example of triggering an error: 
- Build electron app and launch
- turn off the network of you machine
- move the "Service" page and click "Start service"
- You can see the Error Boundary fallback view
This change ensures that the correct …
> fix: reload behavior of BAIErrorBoundary for Electron

- src/components/backend-ai-app-launcher.ts
When extracting the text of an `example command element`, the command was not copied correctly because there was no logic to remove line breaks in the element text. 
Changed extracting the text of an element to extract the command as a single line, removing any useless spaces or newlines.
> fix: normalize copied example command format in sFTP upload agent panel

- react/src/components/KeypairInfoModal.tsx
- src/components/backend-ai-credential-list.ts
This PR fixes cosmetic issue; showing main access key tag with appropriate color, instead of red color as if looks like expired.
* After
* Before
> misc: change color of main access key tag to green

- react/src/components/ErrorLogList.tsx
- react/src/components/TextHighlighter.tsx
This PR improves the performance issue of TextHighlighter and minor refactoring of `ErrorLogList` component.
To reproduce the issue:
- Open the Chrome browser developer tool.
- Type '1' in the Log List page's search field. `/usersettings?tab=logs`
- Delete '1'.
- Before this PR, you may have noticed the lagging.
> fix: TextHighlighter performance

- react/src/components/ProjectSelect.tsx
- react/src/hooks/backendai.tsx
- react/src/hooks/index.tsx
- resources/i18n/de.json
- resources/i18n/el.json
- resources/i18n/en.json
- resources/i18n/es.json
- resources/i18n/fi.json
- resources/i18n/fr.json
- resources/i18n/id.json
- resources/i18n/it.json
- resources/i18n/ja.json
- resources/i18n/ko.json
- resources/i18n/mn.json
- resources/i18n/ms.json
- resources/i18n/pl.json
- resources/i18n/pt-BR.json
- resources/i18n/pt.json
- resources/i18n/ru.json
- resources/i18n/tr.json
- resources/i18n/vi.json
- resources/i18n/zh-CN.json
- resources/i18n/zh-TW.json
Added new hooks and updated components in ProjectSelect to include new features.
- Updated queries in ProjectSelectorQuery
- Implemented filtering and grouping for projects in ProjectSelect
- Added type for supportModelStore to BackendAIConfig
- Updated i18n files with new translations for 'General' key
You can see these changes when passing [this condition]([url](https://github.com/lablup/backend.ai-webui/blob/bcde6ad0a6ebe31a6654444c5f9eea919595890b/react/src/components/ProjectSelect.tsx#L77-L78))
You can see the model-type project after setting `supportModelStore` of `config.toml` and loggin as admin or superadmin.
The changes were made to enhance the functionality and user experience of the ProjectSelect component. For managing the model store vfolders, the admin needs to select the …
> feat: the project select supports model store type for admin

- react/src/components/AgentList.tsx
- react/src/components/BAIPropertyFilter.stories.tsx
- react/src/components/BAIPropertyFilter.test.tsx
- react/src/components/BAIPropertyFilter.tsx
- react/src/helper/index.test.tsx
- react/src/helper/index.tsx
- resources/i18n/ko.json
Add a BAI property filter component to improve filtering functionality in agent list view. This PR is first phase of https://github.com/lablup/backend.ai-webui/issues/2027 .
- Added a new component BAIPropertyFilter.
- Implemented filtering based on properties like ID and endpoint.
1. Open the agent list view.
2. Use the BAIPropertyFilter to filter agents based on ID or endpoint.
To enhance the filtering capabilities for agents in the agent list view.
---
> feat: Property filter component

- react/src/components/BAIModal.css
- react/src/components/BAIModal.tsx
The styles applied to the BAIModal component have been refactored.
|  <img width="715" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/621215/8372437f-95d7-474c-affa-43992575643a">  |  ![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/XqC2uNFuj0wg8I60sMUh/3357767a-ed7a-4316-83f4-d4dbcfc18f10.png) | 
Now, BAIModal has `max-height`. BAIModal body has a scroll when contend is too long.
Also the declared styles in BAIModal.css file were removed and directly applied to BAIModal.tsx instead. Added new styles properties for content, footer, and body.
To test this change, do a visual inspection of the rendering of the BAIModal component in the UI and compare with the previous version.
This change allows for more …
> feat: set `maxHeight` to BAIModal

- react/src/components/ResourceAllocationFormItems.tsx
After this PR, the resource allocation form items do not apply when the preset is disabled.
(bug report from [Teams](https://teams.microsoft.com/l/message/19:14c484402d874dafb15806d093b95a82@thread.skype/1716362564395?tenantId=13c6a44d-9b52-4b9e-aa34-0513ee7131f2&groupId=74ae2c4d-ec4d-4fdf-b2c2-f5041d1e8631&parentMessageId=1716359409725&teamName=devops&channelName=Frontend&createdTime=1716362564395))
- Create two model services with different CPU numbers.
- Click the modify button and check if the CPU number is preserved or not.
This change was made to improve the user experience and meet the requirements of the project.
---
> fix: do not apply preset when disabled presets

- react/src/components/DynamicStepInputNumber.tsx
- react/src/components/DynamicUnitInputNumberWithSlider.tsx
- react/src/components/InputNumberWithSlider.tsx
This PR fixes the bug related to first update of `InputNumber` in Form.Item. 
- InputNumberWithSlider
- DynamicUnitInputNumberWithSlider
- DynamicInputNumber
- Change the CPU number in the Neo session launcher.
- Refresh the browser.
- If the CPU number is preserved after the refresh, it works fine.
---
> fix: `InputNumber` component does not update the value correctly at first

- react/src/components/BAINotificationItem.tsx
To prevent flickering issues in notifications when using ellipsis in Typography, we temporarily replace it with "truncated".
> hotfix: replace ellipsis in Notification with `_.turuncate`

- react/src/components/ProjectResourcePolicyList.tsx
- react/src/components/ProjectResourcePolicySettingModal.tsx
- react/src/pages/ResourcePolicyPage.tsx
- resources/i18n/de.json
- resources/i18n/el.json
- resources/i18n/en.json
- resources/i18n/es.json
- resources/i18n/fi.json
- resources/i18n/fr.json
- resources/i18n/id.json
- resources/i18n/it.json
- resources/i18n/ja.json
- resources/i18n/ko.json
- resources/i18n/mn.json
- resources/i18n/ms.json
- resources/i18n/pl.json
- resources/i18n/pt-BR.json
- resources/i18n/pt.json
- resources/i18n/ru.json
- resources/i18n/tr.json
- resources/i18n/vi.json
- resources/i18n/zh-CN.json
- resources/i18n/zh-TW.json
follows #2357 
Add Project Resource Policy Page
This pull request introduces changes related to FormItemWithUnlimited and ProjectResourcePolicyList components.
The changes include:
- Addition of FormItemWithUnlimitedProps in `FormItemWithUnlimited` component
- Updates to `ProjectResourcePolicyList` component with enhanced functionality and UI improvements
<table>
<tr>
<td></td>
<td>24.03.0b1 (10.82.230.101)</td>
<td>24.09.0dev1 (main)</td>
</tr>
<tr>
<td>List</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>Create Modal</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>Modify Modal</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>Table Setting</td>
<td>
</td>
<td>
</td>
</tr>
</table>
---
> feat: Project resource policy page

- react/src/components/ResourceAllocationFormItems.tsx
- react/src/components/ResourcePresetSelect.tsx
When the Resource Preset is modified, the item is moved to the end of the list. This makes it difficult for users to find the resource preset, so we provide sorting functionality by name for resource presets to improve the user experience.
> feat: provide sorted resource presets to NeoSessionLauncher when presets are modifed

- react/src/components/ServiceLauncherModal.tsx
Added error handling logic for when ModifyEndpoint GQL gets an error with a 200 response. [teams](https://teams.microsoft.com/l/message/19:14c484402d874dafb15806d093b95a82@thread.skype/1716362888818?tenantId=13c6a44d-9b52-4b9e-aa34-0513ee7131f2&groupId=74ae2c4d-ec4d-4fdf-b2c2-f5041d1e8631&parentMessageId=1716359409725&teamName=devops&channelName=Frontend&createdTime=1716362888818)
> fix: error handling for ModifyEndpoint GQL fails

- react/src/components/ResourceAllocationFormItems.tsx
This PR aims to enhance the validation trigger.
Use the `recursive` option for validation to limit the subpath.
- Open the Service launcher.
- Before the PR: You can see the validation error in the name field.
- After the PR: No validation error results right after opening the modal.
- In the Neo session launcher:
- Change the resource group. You can see the changed validation result in the resource allocation fields.
Without the `recursive` option, it's hard to limit the validation to the subpath. After introducing the `recursive` option, we can do it easily.
---
> fix: use `recursive` validation  option for `ResourceAllocationFormItems`

- src/components/backend-ai-session-list.ts
When the image commit dialog on the session page was opened, the information for that session was being reflected late, so I fixed it to request an update when the dialog is opened so that the information is reflected immediately. 
> fix: request update when commit session dialog is opened

- src/components/backend-ai-resource-group-list.ts
Resolves an issue where buttons on the Resource Group page are inconsistent with other pages. 
|before|after|
|---|---|
|![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/lSyr8xXz1wdXALkJKzVx/73ba5c7a-e4c3-41d8-8ddf-c12e970a481b.png)|![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/lSyr8xXz1wdXALkJKzVx/c766de21-0af0-4ecc-b865-79e73c378feb.png)|
> fix: align button consistency on Resource Group pages

- react/src/components/ManageAppsModal.tsx
- react/src/components/ManageImageResourceLimitModal.tsx
Depending on your version of Manager, the type of values that do not pass through to properties must be differentiated between undefined and null. [ref](https://github.com/lablup/backend.ai/pull/2028)
> fix: Mishandling of undefined value in the ModifyImage mutation

- src/components/backend-ai-session-list.ts
This PR fixes miscellaneous cosmetic issue in upload session list about realigning name of session to start-justified.
| <img width="930" alt="Screenshot 2024-05-27 at 2 13 43 PM" src="https://github.com/lablup/backend.ai-webui/assets/46954439/84edaa37-585c-4eff-8503-dee59bf4a2f5"> | <img width="930" alt="Screenshot 2024-05-27 at 2 14 50 PM" src="https://github.com/lablup/backend.ai-webui/assets/46954439/31e555e3-ddba-4f64-82c9-b88d156c6a37"> |
> misc: realign session name of upload session list

- react/src/components/BAIPropertyFilter.tsx
This PR removes the empty space (red line on the screenshot) when BAIPropertyFilter has no filter.
You can check this "Resources" menu(`/agent`).
| -- | -- |
|  ![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/XqC2uNFuj0wg8I60sMUh/04878b5f-1116-4daa-99cd-13b02bfca6db.png)   |  ![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/XqC2uNFuj0wg8I60sMUh/5b4b427b-243f-49eb-9e96-a208c4809fec.png)   |
> fix: empty filter layout of `BAIPropertyFiilter`

- react/data/client-directives.graphql
- react/src/helper/graphql-transformer.test.ts
- react/src/helper/graphql-transformer.ts
- src/lib/backend.ai-client-esm.ts
- src/lib/pep440.test.ts
- src/lib/pep440.ts
This PR implemented the compatibility check function that supports multiple conditions.
After this PR:
- the `version` argument of `isManagerVersionCompatibleWith(version)` can be `Array<string>`
- New GraphQL directives
```
directive @sinceMultiple(versions: [String!]!) on FIELD
directive @deprecatedSinceMultiple(versions: [String!]!) on FIELD
```
```
this.isManagerVersionCompatibleWith(['24.03.4', '23.09.11'])
```
```
my_list {
edges {
node {
newField @sinceMultiple(versions:['24.03.4', '23.09.11'])
}
}
}
```
> feat: compatibility check function supports multiple conditions

- react/src/components/MainLayout/WebUISider.tsx
- react/src/components/ProjectResourcePolicyList.tsx
- react/src/components/UserResourcePolicyList.tsx
- react/src/helper/index.test.tsx
- react/src/helper/index.tsx
- react/src/hooks/index.tsx
- react/src/pages/ResourcePolicyPage.tsx
This PR has two changes:
- The `supports` function of Backend.AI client returns a boolean type. Before this PR, there was no return type definition for `supports`, so TypeScript handled it as an `any` type. However, this is not ideal for checking type errors.
- The item type of `Menu` and `Column` cannot handle boolean values, so we need a function to filter and preserve TS types. This PR introduces `filterEmptyItem` for that.
> fix: `supports` type of `useSuspendedBackendaiClient`

- .github/workflows/jest.yml
After changing to GitHub Enterprise, the default permission setting has been changed. Therefore, it's necessary to set the permissions in the GitHub Actions YAML file.
> ci: add permissions to Jest report github action

- react/package.json
- react/src/App.tsx
- react/src/components/BAIContentWithDrawerArea.tsx
- react/src/components/BAINotificationButton.tsx
- react/src/components/MainLayout/MainLayout.tsx
- react/src/components/NeoSessionLauncherSwitchAlert.tsx
- react/src/hooks/useBAINotification.tsx
- react/src/hooks/useBAISetting.tsx
- react/src/pages/SessionLauncherPage.tsx
- src/components/backend-ai-settings-store.ts
This PR replaces Recoil with Jotai because Recoil is unmaintained and has a bug in React 19.
> refactor: replace Recoil with Jotai

- src/components/backend-ai-credential-list.ts
I've set the `fixedMenuPosition' property to true and specified width.
|before|after|
|---|---|
|![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/lSyr8xXz1wdXALkJKzVx/58cf847f-f08b-4e0e-b666-271ced4f411b.png)|![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/lSyr8xXz1wdXALkJKzVx/6e1609cc-b7f5-4199-92e6-5b4daa6945a8.png)|
> fix: adjust the position of mwc selection menu items

- react/src/pages/MyEnvironmentPage.tsx
Adds a copyable text component to the control column in the My Environment Page table.
- Added `Typography` import from `antd`
- Modified the table's control column to include a `Typography.Text` component that allows copying of the image full name
- Applied styling to ensure proper padding
- Navigate to the `My Environment Page`
- Verify that the control column now includes a copyable text element for the image full name
- Ensure that the copying functionality works as expected
This change enhances the user experience by providing a convenient way to copy the full name of the image directly from the table.
---
> Add copyable button to My Environment page

- react/src/pages/SessionLauncherPage.tsx
Fix text overflowing outside the card when inserting manual image
> Fix overflow issue in manual image tag

- src/lib/pep440.test.ts
- src/lib/pep440.ts
> fix: PEP440 suffix normalization for `alpha` and `beta`

- react/src/components/DefaultProviders.tsx
- src/components/backend-ai-dialog.ts
Implemented automatic dialog closure on route changes to ensure dialogs do not persist incorrectly.
Resolve https://github.com/lablup/backend.ai-webui/issues/2176
- Added `useLocation` from `react-router-dom` to the `RoutingEventHandler` component.
- Implemented `useUpdateEffect` from `ahooks` to dispatch `locationPath:changed` custom event on route change.
- Subscribed `BackendAIDialog` to `locationPath:changed` event to trigger `hide` method.
1. Navigate to a route that opens a dialog.
2. Change routes and verify that the dialog closes automatically and clickable elements work properly.
This change was made to prevent dialogs from persisting incorrectly when navigating between routes.
---
Reslove https://github.com/lablup/backend.ai-webui/issues/2176
> Fix: all elements are NOT clickable after a page transition with openped modal

- react/src/components/ResourceAllocationFormItems.tsx
This pull request ensures that when the 'resource' field is validated when preset is changed, the validation is conducted recursively. It addresses an issue where non-recursive validation could have missed nested fields under 'resource'. The change involves modifying the validateFields method to include the 'recursive: true' option. This update impacts the ResourceAllocationFormItems component in the React codebase.
---
> fix: run form validation after changing preset

- react/src/App.tsx
- react/src/components/FolderExplorerOpener.tsx
- react/src/components/VFolderLazyView.tsx
- react/src/pages/EndpointDetailPage.tsx
- src/components/backend-ai-data-view.ts
- src/components/backend-ai-storage-list.ts
The PR enhances folder navigation by integrating `FolderExplorerOpener` component and fixing several bugs.
You can open the FolderExplorer directly for the folder using the folder id, as shown in the following address: `http://127.0.0.1:9081/data?folder=47b6463ba3de4480b968e3e0df9b6fb6`. By linking this URL to the folder name, users can directly access the contents of the folder.
1. Introduced `FolderExplorerOpener` component for opening folders using a UUID.
2. Modified `EndpointDetailPage` to make folder names clickable and navigate to the folder view.
3. Added new query parameters handling in `FolderExplorerOpener`.
4. Updated `VFolderLazyView` to navigate based on `vFolder.id` instead of `vFolder.name`.
5. Added event listeners to `BackendAIData` for opening Folder Explorer.
6. …
> feat: vFolder explorer permarlink

- react/src/components/AgentList.tsx
- react/src/components/ResourceAllocationFormItems.tsx
- react/src/components/ResourceNumber.tsx
- react/src/hooks/backendai.tsx
- react/src/pages/EndpointDetailPage.tsx
Add functionality to use `resourceSlotsDetails` for better resource information display in `ResourceAllocationFormItems` and `ResourceNumber` components.
- Imported `useResourceSlotsDetails` from `backendai` hooks
- Added `resourceSlotsDetails` usage in `ResourceAllocationFormItems`
- Updated `ResourceNumber` component to use `resourceSlotsDetails` for better display of resources
- Adjusted stale time for `useResourceSlotsDetails` query
1. Ensure that the resource display reflects human-readable names and units as provided by `resourceSlotsDetails`.
2. Check the display of CPU and memory resources in the `ResourceAllocationFormItems`.
3. Verify the `ResourceNumber` component displays the updated format and units.
Enhances the clarity and accuracy of resource information displayed to the …
> refactor: improve resource allocation form item labels with resource details API

- react/package-lock.json
- react/package.json
- react/patches/@cloudscape-design+board-components+3.0.60.patch
- react/src/App.tsx
- react/src/components/BAIBoard.tsx
- react/src/components/SummaryItem.tsx
- react/src/components/SummaryPageItems/SummaryItemDownloadApp.tsx
- react/src/components/SummaryPageItems/SummaryItemInvitation.tsx
- react/src/components/SummaryPageItems/SummaryItemStartMenu.tsx
- react/src/pages/SummaryPage.tsx
> [!CAUTION]
> **The PR associated with #2170 was not created with graphite from the beginning! There is some code that was committed from the PR on an earlier stack. Please read the Description carefully to see all the code that is included in the PRs on that stack!**
The scope of this PR stack is to apply `cloudScape's board-component` into the summary page. I used the `patch-package` library to apply the css because that `CloudScape's board-component` doesn't provide any properties for changing the style. 
- Applied cloudscape-design's `board component`
- Modified `board component`'s UI design by using patch-packages.  
- Supports `Dark Mode`
>You don't need to review the components that go into the children of a board item; that's covered in other stacks.
- Remove comments about …
> feat: Apply Cloudscape's `Board Component` into Summary Page 

- src/components/backend-ai-session-list.ts
|light|dark|
|---|---|
|![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/lSyr8xXz1wdXALkJKzVx/c3c5a5a3-e109-45c7-a79a-62eb517372e4.png)|![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/lSyr8xXz1wdXALkJKzVx/64df73fd-c491-4da1-987b-6b056d2fc5b4.png)|
> bug: set dark theme color for error panel in session detail modal

- src/lib/backend.ai-client-esm.ts
follow up #2490 
Increase the request timeout in `backend.ai-client-esm.ts` from 5 seconds to 15 seconds to improve network reliability.
The value of `this.requestTimeout` was changed from `5000` to `15000` milliseconds in the `Client` class.
Verify that network requests initiated by the `Client` class can now succeed within a 15-second window instead of 5 seconds.
This change was made to reduce the likelihood of network timeouts for operations requiring more than 5 seconds, thereby enhancing user experience and system robustness.
> feat: Adjust fetch timeout to 15s for improved user experience (cllient-esm)

- react/src/components/SourceCodeViewer.tsx
- react/src/pages/SessionLauncherPage.tsx
Replaced the Command component with the SourceCodeViewer component
|before|after|
|---|---|
|![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/lSyr8xXz1wdXALkJKzVx/80a09b84-e282-446f-9519-7a17cfbe68f9.png)|![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/lSyr8xXz1wdXALkJKzVx/19c0f13e-35d0-450e-b7b7-9fcdb0104c89.png)|
> bug: Neo session launcher summary page UI is broken for long execution commands in batch sessions

- react/src/components/BAIBoard.tsx
- react/src/hooks/useBAISetting.tsx
- react/src/pages/SummaryPage.tsx
> [!CAUTION]
> **The PR associated with #2170 was not created with graphite from the beginning! There is some code that was committed from the PR on an earlier stack. Please read the Description carefully to see all the code that is included in the PRs on that stack!**
The scope of this PR stack is to allow changes to Summary page items to be saved via using local-storage and to display item loading indicators via using Suspense.
- Enable local storage so that changes to items on the Summary page can be saved. 
- Use Suspense to show an indicator for slow rendering of Board Item Components.
>You don't need to review the components that go into the children of a board item; that's covered in other stacks.
- Restore the Commented out SummaryPage component in App.tsx.
- Remove …
> feat: memorize board's items by using local storage in SummaryPage

- react/patches/@cloudscape-design+board-components+3.0.60.patch
- react/src/components/BAIBoard.tsx
> [!CAUTION]
> **The PR associated with #2170 was not created with graphite from the beginning! There is some code that was committed from the PR on an earlier stack. Please read the Description carefully to see all the code that is included in the PRs on that stack!**
The scope of this PR stack is to prevent the entire item from resizing and moving within the BAIBoard via the `customizable` property.
- Since the event triggers for resize and move are tied to the icon, I specified a className that is accessible via patch-package. 
- Used antd's `createStyles` to apply conditionally created styles.
> You don't need to review the components that go into the children of a board item; that's covered in other stacks.
- Since it uses patch package to change the modules, you should delete the …
> feat: disable customize board items in BAIBoard component

- react/src/components/FolderExplorerOpener.tsx
- src/components/backend-ai-storage-list.ts
> feature: add a link to open a folder explorer in notification

- react/data/schema.graphql
- react/src/components/ModelCardModal.tsx
- react/src/components/ModelCloneModal.tsx
- react/src/pages/ModelStoreListPage.tsx
- resources/i18n/de.json
- resources/i18n/el.json
- resources/i18n/en.json
- resources/i18n/es.json
- resources/i18n/fi.json
- resources/i18n/fr.json
- resources/i18n/id.json
- resources/i18n/it.json
- resources/i18n/ja.json
- resources/i18n/ko.json
- resources/i18n/mn.json
- resources/i18n/ms.json
- resources/i18n/pl.json
- resources/i18n/pt-BR.json
- resources/i18n/pt.json
- resources/i18n/ru.json
- resources/i18n/tr.json
- resources/i18n/vi.json
- resources/i18n/zh-CN.json
- resources/i18n/zh-TW.json
> [!CAUTION]
> This PR should be merged after  https://github.com/lablup/backend.ai/pull/2161
This PR includes
- Background task notification for cloning a model folder 
- Modify frontend components to reflect schema changes and improve user interaction with vFolders.
- Update internationalization files to include messages related to folder cloning and handling errors in multiple languages.
- Make sure related core PR: https://github.com/lablup/backend.ai/pull/2161
- Create a 'model' project folder in the 'model-store' project.
- Upload `model-definition.yml`.
- [model-definition.yml.zip](https://github.com/user-attachments/files/15982404/model-definition.yml.zip)
- Navigate to the model store list on the `/data` page.
- Click on a model card item and then click the "Clone" button.
- You …
> feat: background task notification for cloning a model folder

- react/src/components/BAINotificationItem.tsx
- react/src/components/FolderExplorerOpener.tsx
- react/src/components/ModelCardModal.tsx
- react/src/components/ModelCloneModal.tsx
- react/src/helper/graphql-transformer.ts
- react/src/hooks/useBAINotification.tsx
- src/components/backend-ai-data-view.ts
- src/components/backend-ai-storage-list.ts
Adds a feature that utilizes a link to open the folder explorer directly from a notification.
- Updated `BAINotificationItem` component to use `notification.toText` property before falling back to other properties.
- Adjusted `FolderExplorerOpener` to watch both `isDataViewReady` and `folderId` states.
- Modified `ModelCloneModal` component to include new properties in mutation response and make use of them.
- Extended `NotificationState` interface to include `toText` property.
- Enhanced `BackendAIData` to handle folder explorers for different tabs.
- Refactored folder explorer opening logic in `BackendAiStorageList` and introduced two new methods: `triggerOpenFilebrowserToReact` and `triggerCloseFilebrowserToReact`.
1. Clone folder in the Model store page.
2. Check if the clone result …
> feat: add a link to open a cloned folder in a notification

- .husky/pre-commit
- package.json
.husky/pre-commit and package.json have been updated to fix the husky prepare script. The prepare script has been simplified from 'husky install' to 'husky' to ensure compatibility with newer husky versions. Additionally, some redundant lines in .husky/pre-commit have been removed for cleanup.
1. remove Husky from the project.
2. reinstall husky via `npm i`, and commit any changes to make sure it works.
---
> fix: migrate husky command to v9

- src/components/backend-ai-login.ts
Added input validation for the login form to ensure that the user ID is either a valid email address or a username that matches specified patterns.
- Introduced `_validateInput` function in `backend-ai-login.ts`.
- Updated the `<mwc-textfield>` element to use the `_validateInput` function for validation.
- Modified the input field to adhere to the validation patterns specified for email and username.
1. Open the login form.
2. Try entering an invalid email or username. Ensure that the validation message is shown.
3. Enter a valid email or username. Ensure that no validation message is shown and the form can be submitted.
`email type` : Beginning with uppercase and lowercase letters of the alphabet, numbers, dots, underscores, and minus signs. The @ symbol followed by uppercase and …
> fix: change login input validation logic to support both email and non-email types

- src/components/backend-ai-session-list.ts
- src/components/lablup-notification.ts
Removed unnecessary console log statements and improved notification handling by adding a unique key parameter to avoid duplicate notifications.
- Removed `console.log` statements in `backend-ai-session-list.ts` and `lablup-notification.ts` files.
- Enhanced the `show` method in `LablupNotification` component to include a `key` parameter for uniquely identifying notifications.
- Added logic to prevent dispatching duplicate notifications and handled the 'Network disconnected' message specifically.
1. Trigger an error in the application and verify that console log statements no longer appear.
2. Check that notifications are correctly displayed without duplication.
3. Ensure the 'Network disconnected' message is handled by the `NetworkStatusBanner` component.
To clean up the console output …
> feature: prevent stacking of duplicate notifications

- src/components/backend-ai-session-list.ts
- src/components/lablup-notification.ts
The existing web component notification does not output any accompanying description when a text field is provided for the title. [ref](https://github.com/lablup/backend.ai-webui/blob/119f64e320befec545680934722a05cce00ede65/src/components/lablup-notification.ts#L196)
However, most of the usage of notifications in web components is providing the notification title through the painkiller, so even if the title of the error is undefined, the painkiller will always provide a specific string (e.g. `problem occured`). Therefore, a description of the error is never provided.
- Changed the logic for checking if description is visible to a comparison to see if it is the same as title.
- Fixed an issue where the same notification would appear twice when deleting a session.
1. After causing an error …
> fix: change description validating logic in lablup-notification

- src/components/backend-ai-session-list.ts
Updates the display of `io_read` and `io_write` values to show up to one decimal place in the `backend-ai-session-list` component.
- Modified the template literals in `backend-ai-session-list.ts` to format `io_read.current` and `io_write.current` values with `toFixed(1)`.
1. Start the backend AI session and navigate to the session list.
2. Observe the `io_read` and `io_write` values in the session list.
3. Ensure the values are displayed with one decimal precision.
Ensures consistency and readability in the display of data, particularly for values with variable precision.
---
> fix: Apply one decimal place rounding to per session I/O stat

- src/components/backend-ai-resource-monitor.ts
> NOTE: This issue has been reported by @kyujin-cho. 
This PR fixes displaying ROCm device in resource monitor gauge, which was missing due to wrong value assigning.
| <img width="293" alt="Screenshot 2024-07-04 at 5 15 38 PM" src="https://github.com/lablup/backend.ai-webui/assets/46954439/723f2c66-facc-44aa-b06e-baef3718b49d"> | <img width="293" alt="Screenshot 2024-07-04 at 5 16 28 PM" src="https://github.com/lablup/backend.ai-webui/assets/46954439/c34e6477-9916-473b-89f1-ab9ce29157da"> |
> fix: correct mistaken 'rocm_device' in resource monitor

- react/src/pages/SummaryPage.tsx
- src/components/backend-ai-session-list.ts
- src/lib/backend.ai-client-esm.ts
related: [backend.ai#2364](https://github.com/lablup/backend.ai/pull/2364)
This diff contains changes across several TypeScript files within a React project. Key updates include:
1. **SummaryPage.tsx:**
- Modified a mapping function to access a potentially undefined `id` property with optional chaining.
2. **backend-ai-session-list.ts:**
- Added `mwc-select` import.
- Removed unused imports (`translateUnsafeHTML`).
- Introduced several new properties (`selectedKernels`, `selectedKernelId`).
- Updated constructor to initialize new properties.
- Adjusted `_showLogs` function to support kernel-specific logs fetching using `selectedKernelId`.
- Added `_setSelectedSession` and `_updateLogsByKernelId` methods to manage selected session state.
- Updated UI components and event handling to …
> add: kernel_id param on fetching container log by kernel id in session

- src/components/backend-ai-session-list.ts
Added functionality to display agent IDs alongside their corresponding truncated container IDs for superadmin users in the session list.
- Modified `backend-ai-session-list.ts` to include a new field `agents_ids_with_container_ids` that concatenates agent IDs with truncated container IDs and displays them in a preformatted text block for superadmin users.
1. Log in as a superadmin user.
2. Navigate to the session list page.
3. Verify that the `agents_ids_with_container_ids` field is visible and displays the agent IDs with truncated container IDs.
This change enhances the visibility of agent-to-container mappings for superadmin users, providing more concise yet complete information in the session list.
Before: Show unique agent ID even though user made multi-node session.
After: Show all …
> refactor: Show as many agent IDs as the number of agents.

- react/src/components/ResourceAllocationFormItems.tsx
This pull request updates the `ResourceAllocationFormItems` component to dynamically configure the display of custom and minimum required resource options based on `allowCustomResourceAllocation`configuration.
- The `ResourcePresetSelect` component's `showCustom` and `showMinimumRequired` props are now set based on the `allowCustomResourceAllocation` field in `config.toml`.
1. Ensure that the application is running.
2. Navigate to the form where the resource allocation is done.
3. Verify that the custom resource option is not visible only if `allowCustomResourceAllocation` of `config.toml` is false.
This change ensures that the visibility of custom resource options is configurable through the client's settings, providing more flexibility and control in resource allocation.
--- …
> fix: `allowCustomResourceAllocation` options in Neo session launcher

- config.toml.sample
- react/src/components/ProjectSelect.tsx
- react/src/hooks/index.tsx
- react/src/pages/VFolderListPage.tsx
- src/components/backend-ai-data-view.ts
- src/components/backend-ai-login.ts
This pull request updates the configuration and codebase to replace the `supportModelStore` flag with `enableModelStore`([ref](https://github.com/lablup/backend.ai/blob/24491df67eded42cebf4c109fe9aabf254ec4592/src/ai/backend/web/config.py#L67-L68)). This affects multiple files including configuration samples, React components, and various TypeScript and JavaScript files.
> fix: rename `enableModelStore` configuration

- src/components/backend-ai-session-list.ts
related https://app.graphite.dev/github/pr/lablup/backend.ai-control-panel/804/fix-Correct-CPU-util-ratio-for-cluster-sessions
resolves https://github.com/lablup/giftbox/issues/697
Adjusts the calculation for the cpu utilization ratio in backend-ai-session-list component.
Modified the cpu utilization calculation by multiplying the current utilization ratio with the length of the containers array for each session, fixing potential miscalculations.
Verify the cpu utilization ratio is accurately reflecting the multiplied value of current utilization and container length in session statistics.
Ensures accurate representation of CPU utilization by accounting for the number of containers in sessions.
> fix: Correct CPU util ratio for cluster sessions

- src/components/backend-ai-session-list.ts
- src/lib/backend.ai-client-esm.ts
This pull request fixes the bug occurred when opening container log dialog which originated by #2510 by adding support for fetching logs on a per-kernel basis if the backend supports it. It introduces a new property `_isPerKernelLogSupported` to determine the backend capability and modifies the `_showLogs` method to utilize this feature if available.
- Added `_isPerKernelLogSupported` property.
- Modified `_showLogs` method to fetch per-kernel logs if supported.
- Updated `Client` class to check for backend support for per-kernel logs.
- Made UI changes to support the selection and display of per-kernel logs.
1. Ensure that your backend supports the 'per-kernel-logs' feature.
2. Initiate sessions and try fetching logs to see if the logs are fetched on a per-kernel basis.
3. Validate the …
> fix: workaround of considering version-compatibility for fetching per container(kernel) logs

- react/src/components/ServiceLauncherPageContent.tsx
- react/src/components/ServiceValidationView.tsx
- react/src/components/VFolderSelect.tsx
- src/components/backend-ai-storage-list.ts
- Added the `model` parameter to start the service immediately with the folder mounted when pressing the play button in the Model tab.
- Replaced all occurrences of `vFolderName` with `vFolderID` in `ServiceLauncherPageContent.tsx` and related files to ensure consistency and correct usage of virtual folder identifiers.
- Updated `ServiceLauncherPageContent.tsx` to use `vFolderID` instead of `vFolderName`.
- Modified form items and fields to reflect the change from `vFolderName` to `vFolderID`.
- Adjusted the `VFolderSelect` component to support selecting by ID instead of name.
- Added a query parameter handler for `model` in `ServiceLauncherPageContent`.
- endpoint: 10.100.64.15 
- enable `enableModelStore` of config.toml
1. Verify that the Service Launcher page loads correctly without …
> feature: Add `model` query param to start the service with folder mounting

- react/src/components/ImageResourceFormItem.tsx
- react/src/components/KeypairResourcePolicySettingModal.tsx
- react/src/components/ResourceAllocationFormItems.tsx
- react/src/components/ResourceNumber.tsx
- react/src/hooks/backendai.tsx
This PR introduces optional chaining for `resourceSlotsDetails` across various components to ensure that property access does not cause runtime errors when `resourceSlotsDetails` is undefined.
- Added optional chaining for `resourceSlotsDetails` in `ImageResourceFormItem.tsx`, `KeypairResourcePolicySettingModal.tsx`, `ResourceAllocationFormItems.tsx`, `ResourceNumber.tsx`, and `backendai.tsx`.
- Ensure that components render correctly even when `resourceSlotsDetails` is undefined.
- Check if the appropriate display labels and input components are rendered.
- Validate that no runtime errors occur due to property access on potentially undefined `resourceSlotsDetails`.
This change is necessary to prevent runtime errors that can disrupt the user experience. By using optional chaining, we …
> fix: add `undefined` type to `useResourceSlotsDetails`

- react/package-lock.json
- react/package.json
- react/src/components/DefaultProviders.tsx
- react/src/components/MainLayout/WebUISider.tsx
- react/src/index.css
- react/src/index.tsx
Add `lucide-react` dependency to the project.
This PR change a  only one icon for testing and improving UI.
| -- | -- |
|  ![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/XqC2uNFuj0wg8I60sMUh/92a511a7-b276-430f-93f6-9a010ffc47ae.png) |  ![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/XqC2uNFuj0wg8I60sMUh/d8c0ed05-b34e-4ba7-9b42-05bb71dc92a3.png) |
FYI, only the icons that are imported into your project are included in the final bundle.
This PR adds the `lucide-react` library (version ^0.383.0) as a dependency in both `package.json` and `package-lock.json` files. The `lucide-react` library provides a set of SVG icons for React.
1. Run `npm install` to update your local dependencies.
2. Ensure there are no installation …
> feat: Lucide icon with custom svgs

- src/components/backend-ai-session-list.ts
Corrected potential runtime errors caused by null values in container_id and namespace slicing operations.
- Added null checks before slicing `container_id` in `backend-ai-session-list.ts`
- Implemented safe slicing for `namespace` by adding null checks.
1. Run the application and monitor the session list component to ensure no errors occur.
2. Verify that the session list displays correctly without any slicing errors.
To prevent runtime errors caused by null values, improving the stability and robustness of the session list feature.
> fix: Cannot read properties of null (reading 'slice') error

- react/src/components/ImageEnvironmentSelectFormItems.tsx
Added CSS class `image-environment-select-form-item` to `Form.Item` components in `ImageEnvironmentSelectFormItems.tsx`.
| -- | -- |
|  ![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/XqC2uNFuj0wg8I60sMUh/8972879d-b3b5-4b3b-8509-34b52e2cbf7f.png) | ![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/XqC2uNFuj0wg8I60sMUh/4330f7de-68d9-49ea-9085-19d43727b807.png)   ![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/XqC2uNFuj0wg8I60sMUh/bfac69fe-60df-4d18-8f30-a76d090bcfd3.png) |
- Added the CSS class `image-environment-select-form-item` to `Form.Item` components in the file `react/src/components/ImageEnvironmentSelectFormItems.tsx`.
1. Run the application in small size of browser window.
2. Navigate to …
> fix: Image environment select form item's wrap style

- react/src/components/FolderExplorerOpener.tsx
- react/src/components/ResourceGroupSelect.tsx
- react/src/components/VFolderLazyView.tsx
- react/src/components/VFolderSelect.tsx
- react/src/components/VFolderTable.tsx
- react/src/hooks/backendai.tsx
Replaced string concatenation with `URLSearchParams` for constructing query parameters in several GET requests.
- Refactored various components such as `FolderExplorerOpener`, `ResourceGroupSelect`, `VFolderLazyView`, `VFolderSelect`, `VFolderTable`, and `backendai` hook to use `URLSearchParams` instead of manual string concatenation for query parameters.
1. Verify that the `FolderExplorerOpener` component correctly fetches folders using the updated URL search parameters.
2. Check that the `ResourceGroupSelect` component functions as expected with the new query parameter construction.
3. Ensure the `VFolderLazyView`, `VFolderSelect`, and `VFolderTable` components properly retrieve folder data with the updated URL structure.
4. Test the `backendai` hook's functionality, particularly the …
> fix: handle search params using `URLSearchParams`

- react/src/components/ModelCardModal.tsx
- react/src/pages/ModelStoreListPage.tsx
Updated the layout of `ModelCardModal` and the styling in `ModelStoreListPage` to improve the user interface and experience.
- `ModelCardModal.tsx`
- Changed the width setting from responsive percentages to a fixed pixel value for better consistency.
- Simplified the layout by removing redundant `Card` components
- Conditionally rendered the README section only if available.
- `ModelStoreListPage.tsx`
- Introduced custom styles using `antd-style`.
- Applied these styles to the card list for uniform height and improved spacing.
1. Open the ModelCardModal and verify the new layout.
2. Check the ModelStoreListPage for consistent card heights and proper styling.
To provide a more consistent user experience and address UI issues related to varying screen sizes and element styling.
--- …
> style: dynamic model card ui

- react/src/App.tsx
- react/src/components/ImportNotebook.tsx
- react/src/components/LocationStateBreadCrumb.tsx
- react/src/helper/index.tsx
- react/src/pages/ImportAndRunPage.tsx
- react/src/pages/SessionLauncherPage.tsx
- react/src/react-app-env.d.ts
- resources/i18n/de.json
- resources/i18n/el.json
- resources/i18n/en.json
- resources/i18n/es.json
- resources/i18n/fi.json
- resources/i18n/fr.json
- resources/i18n/id.json
- resources/i18n/it.json
- resources/i18n/ja.json
- resources/i18n/ko.json
- resources/i18n/mn.json
- resources/i18n/ms.json
- resources/i18n/pl.json
- resources/i18n/pt-BR.json
- resources/i18n/pt.json
- resources/i18n/ru.json
- resources/i18n/tr.json
- resources/i18n/vi.json
- resources/i18n/zh-CN.json
- resources/i18n/zh-TW.json
- src/components/backend-ai-import-view.ts
- src/components/backend-ai-webui.ts
This PR adds new components and lazy loading to the Neo session launcher. It also introduces a new `ImportAndRunPage` for importing and running notebooks directly from a URL, along with a breadcrumb component for navigation.
- Added `ImportAndRunPage` component for notebook imports.
- Added `LocationStateBreadCrumb` component for breadcrumb navigation.
- Introduced lazy loading for `ImportAndRunPage` and other components to optimize performance.
- Updated `SessionLauncherPage` to integrate breadcrumbs and lazy loading.
- Refactored session launcher form to include a hidden bootstrap script input.
- Added various utility functions such as `generateRandomString`.
1. Navigate to the `/import` route in the application.
2. Test the notebook import functionality by providing a valid notebook …
> feat: Import notebook using Neo Session Launcher

- react/src/components/ServiceLauncherPageContent.tsx
Filtered out vfolders with usage mode 'model' and names starting with a period(auto mounted folder) in ServiceLauncherPageContent to ensure they are not selectable.
- Added an additional condition in the 'filter' function to check for vfolder names starting with a period (.)
- Navigate to the Service Launcher Page.
- Check the available vfolders in the selection list.
- Verify that vfolders with usage mode 'model' and names starting with a period (.) are not displayed.
This change is made to prevent users from selecting hidden or model-specific vfolders which could lead to potential issues.
> fix: hide auto mounted vfolder in the service launcher

- react/src/components/KeypairResourcePolicySettingModal.tsx
Refactor KeypairResourcePolicySettingModal component to use React's useRef hook for managing form instance instead of useForm hook.
- Replaced useForm with useRef for managing the form instance.
- Reorganized import statements to include FormInstance from antd.
1. Open the KeypairResourcePolicySettingModal component.
2. Ensure the form behaves as expected when setting resource policies.
3. Validate that there are no errors related to form management.
The change aims to optimize the way the form instance is managed within the KeypairResourcePolicySettingModal component by utilizing the useRef hook. This can offer better performance and cleaner code structure.
---
> fix: Setting initial values for antd form instances

- react/src/components/ServiceLauncherPageContent.tsx
Include the `runtime_variant` property in the payload when launching the service to ensure the correct variant is used.
- Added `runtime_variant` field to the service payload in `ServiceLauncherPageContent.tsx`
1. Open the existing service launcher.
2. Change the desired `runtime_variant`.
3. Save the service and observe that the correct `runtime_variant` is included in the payload.
This change ensures that the correct runtime variant is passed to the backend, allowing for more precise service configuration.
> fix: modify runtime variant

- react/src/components/ResourceAllocationFormItems.tsx
Follow up : https://github.com/lablup/backend.ai-webui/pull/2522
Conditional rendering of a Card component in ResourceAllocationFormItems.tsx based on the allowCustomResourceAllocation configuration setting.
- Added a condition to the style of the Card component to render it only if baiClient._config.allowCustomResourceAllocation is set to true.
1. Set baiClient._config.allowCustomResourceAllocation to true and verify that the Resource slot form items displayed.
2. Set baiClient._config.allowCustomResourceAllocation to false and verify that the Resource slot form items are hidden.
To ensure that the Card component in the ResourceAllocationFormItems is only rendered when custom resource allocation is permitted, improving the flexibility and configuration of the application.
--- …
> fix: hide resource slots form items when `allowCustomResourceAllocation` is false

- react/src/components/ServiceLauncherPageContent.tsx
Make the 'mounts' attribute optional in the ServiceLauncherInput interface and add GraphQL directives to specific model attributes in the ServiceLauncherPageContent component.
reported from [Teams](https://teams.microsoft.com/l/message/19:fceea950220e430ca12c3040d152efe9@thread.tacv2/1721282677260?tenantId=13c6a44d-9b52-4b9e-aa34-0513ee7131f2&groupId=b1f3bcf4-facf-40d3-94ab-169abb4f0f52&parentMessageId=1721282297006&teamName=customers%20%26%20clients&channelName=KT%20Cloud&createdTime=1721282677260)
- Updated the 'ServiceLauncherInput' interface, making the 'mounts' attribute optional.
- Added GraphQL directives `@since(version: "24.03.4")` to 'model_definition_path', 'model_mount_destination', and 'extra_mounts'.
1. Ensure that updating service modal  without errors in before 24.03.4 …
> fix: backward compatibility for extra mounts of a service

- react/src/components/ServiceLauncherPageContent.tsx
Added support for resource presets in the Resource Allocation Form.
- Modified the `ServiceLauncherPageContent` component to enable resource presets by default in the `ResourceAllocationFormItems` component.
1. Navigate to the Service Launcher page in the application.
2. Verify that the Resource Allocation Form now supports and displays resource presets.
3. Set `allowCustomResourceAllocation=false` in `config.toml` 4. Check
- if the resource slot form items have disappeared.
- if the `custom` option of the preset select has disappeared.
This change improves the user experience by allowing users to quickly select predefined resource settings in the Resource Allocation Form.
> feat: resource preset in Service Launcher

- react/package.json
- react/src/components/BAIModal.tsx
- react/src/components/lablupTalkativotUI/ChatMessageContent.tsx
- react/src/components/lablupTalkativotUI/ChatMessageList.tsx
- react/src/components/lablupTalkativotUI/ScrollBottomHandlerButton.tsx
This PR primarily focuses on cleaning up unused dependencies and improving the linting script of files related to https://github.com/lablup/backend.ai-webui/pull/2553
- Removed unused imports in several components (`BAIModal.tsx`, `ChatMessageContent.tsx`, `ChatMessageList.tsx`).
- Updated `lint` script in `package.json` to remove redundant `pnpm dlx` for eslint.
Ensure all components render and function as expected without any errors or warnings. Run the linting script to verify no linting issues.
Removing unused imports and redundant commands helps in keeping the codebase clean and improving the efficiency of the development process.
> fix: eslint error of Chat UI components

- react/src/components/VFolderSelect.tsx
After https://github.com/lablup/backend.ai-webui/pull/2520 , the search feature of `VFolderSelect` component doesn't work in Service Launcher.
> fix: `VFolderSelect` component search feature

- src/components/backend-ai-credential-list.ts
The delete button that was visible in the active tab of credentials has been moved to the inactive tab. This change is to align with the vfolder list and improve usability.
| <img width="1657" alt="image" src="https://github.com/user-attachments/assets/294d8c40-d66a-4c04-ae10-5878eb456fab"> | <img width="1649" alt="image" src="https://github.com/user-attachments/assets/780fde81-ed01-4db9-b5de-978126f58e13"> | 
| <img width="1656" alt="image" src="https://github.com/user-attachments/assets/77d19eb2-ce60-44b7-9428-96c34f3f4549"> | <img width="1650" alt="image" src="https://github.com/user-attachments/assets/4b798ff8-9649-41d6-a5ce-1ef5f9a0664c"> |
1. Log in with the superadmin user.
2. Navigate to the user's credentials tab.
3. Check the control column …
> feat: move credential delete forever button to inactive tab

- react/src/components/DefaultProviders.tsx
- react/src/index.tsx
- src/components/backend-ai-session-list.ts
Added a session reservation timer to the session list UI.
- Updated `index.tsx` in helper to include a new function `addSecondsToParsedDate`.
- Modified `index.tsx` to add a new custom element `<backend-ai-session-reservation-timer>`.
- Implemented a new React component `ReservationTimeCounter` to handle the display of the timer.
- Updated `backend-ai-session-list.ts` to incorporate the new reservation timer element.
1. Start the application.
2. Navigate to the session list view.
3. Verify that each session has a timer indicating the elapsed time since reservation.
This change enhances the session list UI by providing real-time feedback on the elapsed time for each session reservation.
---
> feat: Introduce react elapsed time renderer

- react/src/components/EndpointSelect.tsx
- react/src/components/lablupTalkativotUI/ChatMessageContent.tsx
- react/src/components/lablupTalkativotUI/EndpointLLMChatCard.tsx
- react/src/components/lablupTalkativotUI/LLMChatCard.tsx
- react/src/components/lablupTalkativotUI/LLMPlaygroundPage.tsx
This pull request introduces the `fetchKey` prop to `EndpointSelect` and `EndpointLLMChatCard` components to support more dynamic querying and better state management.
1. **EndpointSelect Component**: Added `fetchKey` prop to refresh queries dynamically.
2. **EndpointLLMChatCard Component**: Implemented `fetchKey` and adjusted state management with `useTransition` and `useFragment`.
3. **ChatMessageList Component**: Wrapped the component with `Suspense` for better loading handling. 
4. **LLMPlaygroundPage Component**: Added relay query for initial endpoint data and wrapped `EndpointLLMChatCard` with `Suspense`.
5. **LLMChatCard Component**: Removed unused initial form values for `baseURL`.
1. Check dropdown options in `EndpointSelect` component.
2. Ensure `EndpointLLMChatCard` dynamically …
> refactor: EndpointSelect

- react/src/hooks/backendai.tsx
fix error that resource icon and unit are not displayed on KeyPairResourcePolicyList
Added `isImportingDeviceMetaData` in `ResourceNumber.tsx`. `isImportingDeviceMetaData` determines whether to import device meta data
Modified  `KeyPairResourcePolicyList` to pass true to `isImportingDeviceMetaData` prop 
Importing deviceMetaData directly into the `KeyPairResourcePolicyList `was not implemented in that way due to duplication and flow of data
> fix: resource icon and unit are not displayed on KeypairResourcePolicyList

- react/src/components/UserProfileSettingModal.tsx
Allow superadmins to bypass password patterns in password reset and profile settings.
Related PR: https://github.com/lablup/backend.ai-webui/pull/1716
- Imported and used `useCurrentUserRole` hook.
- Modified password validation rules in `ResetPasswordRequired` and `UserProfileSettingModal` components to bypass pattern checks for superadmins.
1. Log in as a superadmin.
2. Try to reset the password and update the profile.
3. Verify that the password pattern validation is bypassed.
To allow superadmins more flexibility when resetting passwords or updating profiles.
> feat: remove password validation for superadmin

- .github/workflows/add-to-project.yml
Update `add-to-project.yml` github workflow to add [Frontend Daily Board]([url](https://github.com/orgs/lablup/projects/24)) project.
> ci: add Frontend Daily Board project automatically

- src/components/backend-ai-page.ts
- src/components/backend-ai-session-list.ts
Added a 'requiresUpdateWhenInactive' flag to ensure the `backend-ai-page` component updates at least once when it becomes inactive.
The BackendAIPage component now includes a 'requiresUpdateWhenInactive' flag. This ensures that an update is triggered once when the component goes inactive. Additionally, updated the BackendAISessionList component to render the session list grid dynamically based on the 'active' state.
1. Navigate to the page using the BackendAIPage component.
2. Visit session list and move to other page to trigger active/inactive state and observe if the session list updates accordingly.
- When inactive, the `ReservationTimeCounter` React component in the session list should be unmounted. You can ensure it to check 
whether the [`useIntervalValue` hook is …
> feat: re-render once when `backend-ai-page` is inactive

- react/src/components/AgentList.tsx
- react/src/components/DefaultProviders.tsx
Introduce a debug mode in development environment and add functionality to make i18n keys copyable. This feature woks in React parts only.
1. Added `Typography` from `antd` and `GlobeIcon` from `lucide-react`.
2. Introduced a debug mode which can be toggled via URL parameter `debug`. You can add `?debug=true` in any page. It works only in development environment.
3. Added a post-processor to `i18n` configuration to make i18n keys copyable in debug mode.
1. Run the application in development mode.
2. Add `?debug=true` to the URL parameters. (or add `debug=true` in genera section of `config.toml`
3. Check if i18n keys(Glob Icon) are copyable.
To enhance debugging capabilities and allow developers to easily copy i18n keys for translation or reference.
- [Teams …
> feat: copyable i18n key for debug mode

- react/src/components/BAICodeEditor.tsx
- react/src/components/BAIPropertyFilter.tsx
- react/src/components/DynamicStepInputNumber.tsx
- react/src/components/DynamicUnitInputNumber.tsx
- react/src/components/DynamicUnitInputNumberWithSlider.tsx
- react/src/components/InputNumberWithSlider.tsx
- react/src/components/NonLinearSlider.tsx
- react/src/components/ProjectSelect.tsx
- react/src/components/ResourceGroupSelect.tsx
- react/src/components/ResourceGroupSelectForCurrentProject.tsx
- react/src/components/ResourcePresetSelect.tsx
- react/src/components/ShellScriptEditModal.tsx
- react/src/components/StorageSelect.tsx
- react/src/components/VFolderSelect.tsx
- react/src/components/VFolderTable.tsx
- react/src/hooks/useControllableState.test.ts
- react/src/hooks/useControllableState.ts
implement useControllableState hook 
The overall implementation is based on [useControllableValue](https://github.com/alibaba/hooks/blob/master/packages/hooks/src/useControllableValue/index.ts), and the code to determine whether it is controlled is based on [useControlledState](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-stately/utils/src/useControlledState.ts)
1.  isControlled :  `useControllableValue` of ahooks treats a component as a controlled component if the value exists for props object . But `useControllableState` treats a component as a uncontrolled component  If value is undefined, even if value exists like `useControlledState` of react-spectrum hook 
so I changed the code to determine whether component is controlled 
2. display a warning if the value of …
> feat: introduce `useControllableState`

- src/components/backend-ai-session-list.ts
https://github.com/lablup/backend.ai-webui/pull/2519 PR is missing when https://github.com/lablup/backend.ai-webui/pull/2581 is merged.
This PR is about adding missing parts of 2519 PR 
- Replaced `vaadin-grid-column` with `vaadin-grid-selection-column` for session list selection
- Added `_clearCheckboxes` method call to ensure checkboxes are cleared
1. Verify session list displays selection column correctly
2. Test checkbox auto-selection functionality
3. Perform operations that utilize checkboxes and ensure they are cleared appropriately
To improve the user experience by providing auto-selection in the session list and ensuring that checkboxes do not retain stale state after operations.
---
> fix: add missing checkbox PR in session list page

- src/components/backend-ai-session-list.ts
Because the `backend-ai-session-list` shares a single description stored variable with the notification, it is displaying the description as it is if it was stored by another action.
So, in the part that shows the notifications, if you don't want a description, you have to explicitly put in an empty string value.
> fix: set notification's description field to empty string

- react/src/hooks/reactQueryAlias.tsx
This pull request introduces the `useSuspenseQuery` custom hook that wraps the `useQuery` hook from `react-query`, enabling suspense mode refetch using a `fetchKey`.
- Added a new custom hook `useSuspenseQuery` to the `reactQueryAlias.tsx` file.
- This hook adds support for suspense mode refetching using a `fetchKey`.
1. Import and use the `useSuspenseQuery` hook in a component.
2. Pass the necessary options including an optional `fetchKey` to the hook.
3. Observe that the query refetches correctly in suspense mode when the `fetchKey` is updated.
> You can test this in #2591 . There is [a use case ](https://github.com/lablup/backend.ai-webui/pull/2591/files#r1698071491)for `fetchKey` 
This change enables more advanced data fetching patterns, allowing for smoother user experiences with …
> feat: introduce `useSuspenseQuery` with support for `fetchKey`.

- react/src/index.tsx
- src/components/backend-ai-session-list.ts
This PR resolves issue that session reservation time and session elapsed time were incorrectly displayed 
session reservation time should mean session start time, not session creation time
session elapsed time should be  caculated by session start time,  not session creation time
session reservation time means session start time
session elapsed time is calculated based on the session start time and session terminate time
session elapsed time is displayed only after the session starts
1. set a session start time
2. start a session
3. check that reservation time is displayed correctly
4. check that elapsed time is displayed after the session starts and elapsed time is calculated correctly
> fix: use starts_at instead of created_at for session reservation & elapsed time

- react/src/components/AgentList.tsx
- react/src/helper/index.test.tsx
- react/src/helper/index.tsx
- src/components/backend-ai-resource-monitor.ts
- src/components/backend-ai-resource-panel.ts
Handle visible decimal points according to [backend.ai writing rules](https://loop.cloud.microsoft/p/eyJ3Ijp7InUiOiJodHRwczovL2xhYmx1cC5zaGFyZXBvaW50LmNvbS8%2FbmF2PWN6MGxNa1ltWkQxaUlXZG1ZbUpTWDA1eFMxVnhkblpoY0hrd2MyeDFaV05ZTnkxVmJ6TlRXVkpCZFdod1dFNUJiMGhxTFVOWVRqRjJSRVZrY3poVWNFeEpNR1JvVWt0bWRuTW1aajB3TVVkTlQwaEpVVk5WUjBOYVJGQllOa3hTTlVKWlYwNVVOMUJSVjA1S1F6ZFhKbU05Sm1ac2RXbGtQVEUlM0QiLCJyIjpmYWxzZX0sInAiOnsidSI6Imh0dHBzOi8vbGFibHVwLnNoYXJlcG9pbnQuY29tL2NvbnRlbnRzdG9yYWdlL0NTUF80N2RiZjY4MS02YWYzLTRhMjktYWZiZC1hYTcyZDJjOTZlNzk%2FbmF2PWN6MGxNa1pqYjI1MFpXNTBjM1J2Y21GblpTVXlSa05UVUY4ME4yUmlaalk0TVMwMllXWXpMVFJoTWprdFlXWmlaQzFoWVRjeVpESmpPVFpsTnprbVpEMWlJV2RtWW1KU1gwNXhTMVZ4ZG5aaGNIa3djMngxWldOWU55MVZiek5UV1ZKQmRXaHdXRTVCYjBocUxVTllUakYyUkVWa2N6aFVjRXhKTUdSb1VrdG1kbk1tWmowd01VZE5UMGhKVVZKU1RsRk1 …
> fix: apply decimal place rounding

- react/src/components/KeypairResourcePolicyList.tsx
- react/src/components/ProjectResourcePolicyList.tsx
- react/src/components/UserResourcePolicyList.tsx
- react/src/helper/index.tsx
- resources/i18n/de.json
- resources/i18n/el.json
- resources/i18n/en.json
- resources/i18n/es.json
- resources/i18n/fi.json
- resources/i18n/fr.json
- resources/i18n/id.json
- resources/i18n/it.json
- resources/i18n/ja.json
- resources/i18n/ko.json
- resources/i18n/mn.json
- resources/i18n/ms.json
- resources/i18n/pl.json
- resources/i18n/pt-BR.json
- resources/i18n/pt.json
- resources/i18n/ru.json
- resources/i18n/tr.json
- resources/i18n/vi.json
- resources/i18n/zh-CN.json
- resources/i18n/zh-TW.json
This PR adds CSV export functionality to the Keypair, Project, and User Resource Policy Lists, along with associated UI updates.
- Added `exportAsCSV` and `exportCSVWithFormattingRules` functions to helper.
- Integrated CSV export options into the UI of Keypair Resource Policy list, Project Resource Policy list, and User Resource Policy List.
- Updated translations to support new CSV export functionalities.
1. Navigate to each Resource Policy List in the UI.
2. Use the new 'Tools' dropdown and select 'Export CSV'.
3. Verify the CSV file content and format.
To provide users with an easy way to export and share resource policy data.
> feat: introduce exporting CSV module

- src/components/lablup-notification.ts
Since we've decided to show the details of the notification, we need to take care of handling the detail value of the notification in the web component. [ref](https://github.com/lablup/backend.ai-webui/pull/2503)
Since the web component shares a single variable for the detail text of the notification, an initialization process is required for the detail variable. In this PR, I change that detail text to be initialized after the notification's `show()` function is called.
> fix: initialize detail text after the notification is shown

- src/components/backend-ai-change-forgot-password-view.ts
- src/components/backend-ai-edu-applauncher.ts
- src/components/backend-ai-email-verification-view.ts
- src/types/backend-ai-console.d.ts
This PR fixed blank `/chage-password` page
Removed lines of code related to setting the visibility of `appBody` in various components. `appBody` has been deleted in https://github.com/lablup/backend.ai-webui/pull/2350
- In `backend-ai-change-forgot-password-view.ts`, removed code setting `this.webUIShell.appBody.style.visibility`.
- In `backend-ai-edu-applauncher.ts`, removed the commented-out code for setting `webUIShell.appBody.style.visibility`.
- In `backend-ai-email-verification-view.ts`, removed code setting `this.webUIShell.appBody.style.visibility`.
- In `backend-ai-console.d.ts`, removed the declaration of `appBody`.
1. Access `/change-password?token=sometoken` page.
2. If you want to get the link, you can use `cloud.backend.ai`
The visibility setting of `appBody` was redundant …
> fix: blank `/change-password` page

- src/components/backend-ai-general-styles.ts
- src/components/backend-ai-resource-group-list.ts
resolves https://github.com/lablup/backend.ai-webui/issues/2597 
This pull request addresses a cosmetic issue by fixing a typo in the variable naming convention for resourceGroupWSProxyAddressInput. It also includes enhancements to the styling of the input fields by using the token value for the text label color in disabled and secondary states. Moreover, the validation pattern and auto-validation for wsproxy address input have been added to ensure correct URL format.
1. go to resources - resource group tab
2. click the setting icon
3. check validation of the wsproxy address.
---
> feat: improve wsproxy address validation

- src/lib/backend.ai-client-esm.ts
This PR resolves #2607.
In `backend.ai-client-esm.ts` file, modified the HTTP request method from GET to POST for the download and download_single endpoints.
> NOTE: need to be tested on both version `23.09` and `24.03`.
1. Ensure backend server is running
2. Trigger the download and download_single functionalities
3. Verify if the files are downloadable using the modified POST request
Changing the HTTP method to POST for file downloading can provide better security and support for larger payloads.
---
> refactor: replace REST method from  to  function when download from session info

- .github/workflows/add-to-project.yml
This pull request updates the GitHub Actions workflow configuration to automatically add new issues and pull requests to specific project boards. It updates the 'add-to-project' action version from 'v0.5.0' to 'v1.0.2' and adjusts the workflow to handle both issue and pull request events.
ref: https://github.com/actions/add-to-project
follows #2585 
> ci: update `add-to-project` github action to add PRs to project

- resources/i18n/de.json
- resources/i18n/el.json
- resources/i18n/en.json
- resources/i18n/es.json
- resources/i18n/fi.json
- resources/i18n/fr.json
- resources/i18n/id.json
- resources/i18n/it.json
- resources/i18n/ja.json
- resources/i18n/ko.json
- resources/i18n/mn.json
- resources/i18n/ms.json
- resources/i18n/pl.json
- resources/i18n/pt-BR.json
- resources/i18n/pt.json
- resources/i18n/ru.json
- resources/i18n/tr.json
- resources/i18n/vi.json
- resources/i18n/zh-CN.json
- resources/i18n/zh-TW.json
- src/components/backend-ai-storage-list.ts
Changed the action label for moving a folder to trash in various languages and added a confirmation dialog for the delete(move to the trash bin) button.
- Updated the label "Move to trash bin" to "Move to trash" in translation files for multiple languages.
- Added a description asking for confirmation before moving a folder to the trash in the UI.
1. Attempt to move a folder to the trash.
2. Confirm the appearance of the confirmation dialog with the updated text.
3. Validate the folder is moved to the trash upon confirming the action.
To improve user experience by providing a clear and concise action description and ensuring users confirm their intent before moving a folder to the trash.
---
> feat: add confirm dialog before moving to trash bin tab

- src/components/backend-ai-resource-monitor.ts
Fixes an issue with the `_prefixFormat` method default parameter and optimizes CUDA GPU description formatting.
- Fixed default parameter value in `_prefixFormat` method from `'0;'` to `'0'`.
- Optimized the CUDA GPU description formatting using the `_prefixFormat` helper method.
- Verify that the `_prefixFormat` method functions correctly with default and custom parameters.
- Ensure that CUDA GPU descriptions are formatted as expected in the resource monitor component.
The change corrects the default parameter value in the `_prefixFormat` method and streamlines the GPU description formatting for consistency and clarity.
---
> fix: missed prefix function usage in resource panel

- react/src/components/lablupTalkativotUI/EndpointLLMChatCard.tsx
Updated the style of the Button component in EndpointLLMChatCard to use token.colorIcon instead of token.colorBgMask for the icon color, ensuring consistency with design tokens.
> style: change `EndpointLLMChatCard` close button color

- react/src/pages/SessionLauncherPage.tsx
Set the `setValidationTourOpen` state to `false` across multiple locations in the `SessionLauncherPage` component.
- Added `setValidationTourOpen(false);` to various `onClickExtraButton` event handlers in the `SessionLauncherPage` component.
1. Navigate to the `SessionLauncherPage` in the application.
2. Trigger the buttons associated with the `onClickExtraButton` event.
3. Verify that the validation tour does not open when these buttons are clicked.
This change ensures that the validation tour does not open inadvertently when certain actions are performed on the `SessionLauncherPage`. This is to improve the user experience by preventing unintended distractions.
---
> fix: TOUR error when HTML elements are missing

- react/src/App.tsx
This PR resolves the bug related to the Login modal disappearing in the Electron environment. 
This pull request introduces a new React component `RedirectToSummary` to centralize and handle the redirection logic to the `/summary` path across various routes. Previously, the redirection was performed inline within routing configurations. This refactor enhances code maintainability and ensures that any future changes to the redirection logic only need to be made in one place.
- Added `RedirectToSummary` component to handle redirection logic.
- Updated `/`, `/build/electron-app/app/index.html`, and `/app/index.html` routes to use the new component for redirection.
1. Build Electron app.
2. Before installing the Electron app, make sure to delete the Electron app and related files. (MacOS: …
> fix: Login modal is disappeared in Electron env

- react/src/components/BatchSessionScheduledTimeSetting.tsx
- react/src/components/DatePickerISO.tsx
This PR resolves two bugs related to `BatchSessionScheduledTimeSetting` in the Classic Session Launcher.
1. Unexpected closing: When a user clicks the calendar twice, the picker popup is closed unexpectedly.
- Solution: A new `useRef` hook was introduced to handle the focus on the `DatePickerISO` component. The `DatePickerISO` component itself was modified to accept a forwarded ref, allowing the `datePickerRef` to focus on the date picker when the calendar changes. This should resolve issues related to automatic focus handling and date selection.
2. This pull request addresses an issue in the `BatchSessionScheduledTimeSetting` component where the checkbox change was handled incorrectly. The `onClick` event was replaced with `onChange` for the `Checkbox` component, ensuring the state …
> fix: batch session schedule date picker in the Classic session launcher

- react/src/components/EndpointSelect.tsx
- react/src/components/lablupTalkativotUI/LLMPlaygroundPage.tsx
- react/src/pages/EndpointListPage.tsx
The purpose of this pull request is to refactor the `EndpointSelect` component and related files by removing the filter `name != 'koalpaca-test'` from the `endpoint_list` queries. This filter was deemed unnecessary and has been removed to clean up the code. The changes span across `EndpointSelect.tsx`, `LLMPlaygroundPage.tsx`, and `EndpointListPage.tsx`.
> fix: remove an unintended condition from `endpoint_list`

- react/src/components/AgentList.tsx
- react/src/components/BAIPropertyFilter.stories.tsx
- react/src/components/BAIPropertyFilter.tsx
- react/src/components/EndpointSelect.tsx
- react/src/components/lablupTalkativotUI/LLMPlaygroundPage.tsx
- react/src/pages/EndpointListPage.tsx
- resources/i18n/de.json
- resources/i18n/el.json
- resources/i18n/en.json
- resources/i18n/es.json
- resources/i18n/fi.json
- resources/i18n/fr.json
- resources/i18n/id.json
- resources/i18n/it.json
- resources/i18n/ja.json
- resources/i18n/ko.json
- resources/i18n/mn.json
- resources/i18n/ms.json
- resources/i18n/pl.json
- resources/i18n/pt-BR.json
- resources/i18n/pt.json
- resources/i18n/ru.json
- resources/i18n/tr.json
- resources/i18n/vi.json
- resources/i18n/zh-CN.json
- resources/i18n/zh-TW.json
Added support for boolean options in BAIPropertyFilter component.
Related core PR: https://github.com/lablup/backend.ai/pull/2605
1. `AgentList.tsx`: Added `type` and `options` properties to filter properties.
2. `BAIPropertyFilter.stories.tsx`: Updated story to include boolean type property.
3. `BAIPropertyFilter.tsx`: Major updates to support boolean options including default boolean filter options and enhanced value handling.
4. Updated i18n files for new labels.
1. Go to the AgentList component and verify the filter functionality with boolean options.
2. Check the storybook for BAIPropertyFilter and ensure the new boolean property works as expected.
3. Verify i18n changes reflect correctly in the UI.
To enhance the filtering capabilities by allowing boolean options, providing more …
> feat: BAIProperty filter supports `boolean` type

- react/src/pages/EnvironmentPage.tsx
manage tab as URL 
since we didn't manage the tab as a URL, it doesn't persist on refresh. 
modify to use useQueryParam to manage tabs
` curTabKey === 'registryList'`  This is unnecessary code, so I deleted it
because if curTabKey is not registryList, the parent component's display is none
```
curTabKey === 'registryList' ? (
<Suspense>
<ContainerRegistryList />
</Suspense>
) : null
```
1. enter the environment page
2. click preset or registry and check it's working well
3. refresh and check the tab is preserved
> feat: persist current Tab on the Environment page using search param

- config.toml.sample
- react/src/hooks/index.tsx
- react/src/pages/ServingPage.tsx
- src/components/backend-ai-login.ts
Add `enableLLMPlayground` config to show/hide LLM Playground tab in the model serving page.
1. Go to model serving page
2. Toggle `enableLLMPlayground` option from `config.toml`.
3. If `enableLLMPlayground` is true, LLM playground tab will appear. 
> feat: add `enableLLMPlayground` config

- react/src/components/ResourceAllocationFormItems.tsx
Add a validation step for the accelerator type in the ResourceAllocationFormItems to ensure the type is set to a supported value.
reported from [Teams](https://teams.microsoft.com/l/message/19:3c0acc0825024daeb2211f55c4e7f4aa@thread.skype/1723432646506?tenantId=13c6a44d-9b52-4b9e-aa34-0513ee7131f2&groupId=74ae2c4d-ec4d-4fdf-b2c2-f5041d1e8631&parentMessageId=1723432646506&teamName=devops&channelName=Backend.AI%20Talks&createdTime=1723432646506)
Introduced the `ensureValidAcceleratorType` function to validate and set a supported accelerator type in the form values if the current type is unsupported. Updated `updateAllocationPresetBasedOnResourceGroup` to call this validation function when necessary.
1. Open the Resource Allocation Form.
2. Select `Custom allocation` on Resource Presets
3. …
> fix: eunsure valid acceleartorType in Session Launcher

- react/src/components/BAIPropertyFilter.tsx
- resources/i18n/el.json
- resources/i18n/en.json
- resources/i18n/es.json
- resources/i18n/fi.json
- resources/i18n/fr.json
- resources/i18n/id.json
- resources/i18n/it.json
- resources/i18n/ja.json
- resources/i18n/mn.json
- resources/i18n/ms.json
- resources/i18n/pl.json
- resources/i18n/pt-BR.json
- resources/i18n/pt.json
- resources/i18n/ru.json
- resources/i18n/tr.json
follows #2603 
- Fix overlapped clear icon.
- According to the writing rules, change Reset Filter -> Reset filters.
Before
After
- Go to the searchable page such as Agent.
> style: update `BAIPropertyFilter` label and fix overlapped clear icon

- src/components/backend-ai-app-launcher.ts
Resolves [Teams threads](https://teams.microsoft.com/l/message/19:56185f8ff32e4393bff26c11ce37a5d1@thread.tacv2/1723192390168?tenantId=13c6a44d-9b52-4b9e-aa34-0513ee7131f2&groupId=b1f3bcf4-facf-40d3-94ab-169abb4f0f52&parentMessageId=1723182202872&teamName=customers%20%26%20clients&channelName=NHNCloud-AICA&createdTime=1723192390168).
The maximum width is the same as the `vscode-connection-example` div container (just below the SSH password).
Before:
After:
1. Run backend.ai application
2. Create a new session
3. Launch the vscode desktop app.
Check if the SSH password does not overlap.
> fix: overlapping vscode desktop passwords.

- react/src/components/LegacyFolderExplorer.tsx
- src/components/backend-ai-folder-explorer.ts
Remove the inline style for the LegacyFolderExplorer component and introduce `vaadin-grid` elements to the BackendAIFolderExplorer component with fixed width for the action columns.
Fixed the width of the last column of the vaadin table used in `backend-ai-folder-explorer` to output the full width of the content even when scrolling occurs.
1. Move to `Data & Storage` Page
2. Open folder explorer by clicking folder icon 
3. Resize the screen so that `folder explorer` scrolls.
4. Verify that all the contents of `folder explorer` are printed correctly.
There is currently an issue where scrolling in a vaadin table inside the `backend-ai-folder-explorer` used as a modal on the `Data & Storage` page, or any other page that uses storage, does not output the full width of the content.
--- …
> fix: vaadin table in `backend-ai-folder-explorer` does not output some content when there is scrolling

- react/src/components/ResourceNumber.tsx
This pull request is a follow-up of #2504.
- Update device name for Rebellions ATOM PLUS device from `ATOM` to `ATOM+`.
> fix: Wrong device name for Rebellions ATOM+

- react/src/components/SSHKeypairGenerationModal.tsx
- react/src/components/SSHKeypairManagementModal.tsx
Fix unnecessary POST request in SSH keypair generation modal
SSH keypair generation modal has an unnecessary POST request
1. Open the SSH Keypair Generation dialog
2. Click the close button
3. Open the confirmation dialog
4. Click the OK button
5. Unnecessary POST API requests
Delete unnecessary POST request
1. Open the SSH Keypair Generation dialog
2. Click the close button
3. Open the confirmation dialog
4. Click the OK button
5. Check for unnecessary POST requests
> fix: unnecessary POST request in SSH keypair generation modal

- src/components/backend-ai-data-view.ts
- src/components/backend-ai-storage-list.ts
After https://github.com/lablup/backend.ai-webui/pull/2529, vFodler share button has disappeared.
- restore functionality to retrieve and process allowed vFolder hosts for the current user.
- Removed folder explorer event listener which event are not used.
- Removed `openFolderExplorer` method and its associated event listeners from `BackendAIData` class.
- Restore methods in `BackendAiStorageList` class:
- `_getCurrentKeypairResourcePolicy`: Fetches the current keypair's resource policy.
- `_getAllowedVFolderHostsByCurrentUserInfo`: Retrieves and processes allowed vFolder hosts for the current user, considering domain, group, and resource policy permissions.
- Restore `_viewStateChanged` and `connectedCallback` methods to call `_getAllowedVFolderHostsByCurrentUserInfo`.
1. Navigate to …
> fix: vfolder share button has disappeared

- src/components/backend-ai-session-list.ts
resolves [Teams threads](https://teams.microsoft.com/l/message/19:56185f8ff32e4393bff26c11ce37a5d1@thread.tacv2/1723792481934?tenantId=13c6a44d-9b52-4b9e-aa34-0513ee7131f2&groupId=b1f3bcf4-facf-40d3-94ab-169abb4f0f52&parentMessageId=1723784330896&teamName=customers%20%26%20clients&channelName=NHNCloud-AICA&createdTime=1723792481934)
Make it possible to search agent and container id in session list page.
- Modified the `agents_ids_with_container_ids` property to join the array elements with newline characters.
- Updated the rendering of `agents_ids_with_container_ids` in the grid to display the pre-formatted string.
- Added a `path` attribute to the `lablup-grid-sort-filter-column` for agent and container IDs.
1. Log in as a superadmin user.
2. Navigate to the session list.
3. Verify that …
> fix: cannot search agents in session list

- react/src/helper/react-to-webcomponent.tsx
The "Cannot update an unmounted root." in development environment. 
How to reproduce?
- Visit the "Import & Run" page.
- Before the resource static panel is loaded, navigate to the "Serving" page.
- Please wait few seconds.
- You will see the following error:
Added a check for element connection before re-rendering in attributeChangedCallback.
The `attributeChangedCallback` method in the web component class now checks if the element is connected to the DOM (`this.isConnected`) before re-rendering the React component. This prevents unnecessary re-renders when the element is not actually in the document.
- Follow "How to reproduce" again,
- Please make sure there is no dev error.
This change improves performance by avoiding unnecessary re-renders when the web component is not actually in …
> fix: "Cannot update an unmounted root" error of `react-to-webcomponent`

- react/src/components/AgentList.tsx
- react/src/components/BAIProgressWithLabel.tsx
resolves [Teams threads](https://teams.microsoft.com/l/message/19:56185f8ff32e4393bff26c11ce37a5d1@thread.tacv2/1723792019070?tenantId=13c6a44d-9b52-4b9e-aa34-0513ee7131f2&groupId=b1f3bcf4-facf-40d3-94ab-169abb4f0f52&parentMessageId=1723784330896&teamName=customers%20%26%20clients&channelName=NHNCloud-AICA&createdTime=1723792019070)
reference
- https://github.com/lablup/backend.ai-control-panel/blob/main/frontend/src/pages/hub-resource-agents.js#L1038
- https://github.com/lablup/backend.ai-control-panel/blob/main/frontend/src/hub-utils.js#L541
Fix incorrect resource utilization calculation in AgentList component.
- Modified CPU and memory utilization ratio calculations to remove unnecessary multiplication by 100.
- Updated BAIProgressWithLabel component to handle percentages exceeding …
> fix: incorrect agent utilization stats

- react/src/components/ResourceAllocationFormItems.test.ts
- react/src/components/ResourceAllocationFormItems.tsx
- react/src/hooks/useResourceLimitAndRemaining.tsx
fix the bug on resource allocation logic for presets and accelerators in the ResourceAllocationFormItems component.
- Optimized the calculation of `currentImageAcceleratorLimits` using useMemo for better performance.
- Refactored the `allocatablePresetNames` logic to:
- Use the `allocatable` field if present in the preset.
- Improve checks for resource slots against resource limits.
- Handle special cases for mem, shmem, cpu, and accelerators.
- Updated the filtering logic for presets based on image accelerator limits.
- Simplified the intersection of preset filters for better readability.
- Separate a comparing logic into a `getAllocatablePresetNames`
- Add test codes for `getAllocatablePresetNames` function
1. Open the resource allocation form.
2. Verify that presets are correctly …
> fix: the conditions of allocatablePresetNames

- react/src/components/SummaryPageItems/SummaryItemDownloadApp.tsx
- src/components/backend-ai-summary-view.ts
- src/lib/backend.ai-client-esm.ts
resolves [Teams Threads](https://teams.microsoft.com/l/message/19:18bc1a6cadc74b0c9e7807209ecdf76f@thread.tacv2/1724229202285?tenantId=13c6a44d-9b52-4b9e-aa34-0513ee7131f2&groupId=b1f3bcf4-facf-40d3-94ab-169abb4f0f52&parentMessageId=1724226512054&teamName=customers%20%26%20clients&channelName=KT%20AI&createdTime=1724229202285).
Fixing Windows architecture mismatch issue when downloading the app.
- Updated the 'os' identifier for Windows in the appDownloadMap from 'win' to 'win32'.
- Introduced a new feature flag 'use-win-instead-of-win32' for manager versions 23.09.5 and above.
- After 23.09.5, use 'win'. Before that, use 'win32'.
1. Upgrade the backend.ai manager to version 23.09.5 or later.
2. Check if the app download functionality works correctly for Windows systems.
3. Verify that …
> fix: Windows architecture mismatch issue when downloading the app.

- src/components/backend-ai-session-list.ts
modify the locale of reservation time to the language of Backend.AI
The locale of the reservation time in the session list is the OS default language, not the Backend.AI set language. 
So when the OS default is Korean, no matter how I set the language, the reservation time displays Korean. 
Set the toLocaleString function's parameter Locales to the general.language of Backend.AI
1. change language to ko  in settings
2. Verify reservation time looks like this `2024. 8. 21. 오전 2:45:26`
3. change language to en in settings
4. Verify reservation time looks like this `8/21/2024, 2:45:26 AM`
> fix: modify the locale of reservation time to the language of Backend.AI

- src/components/backend-ai-session-list.ts
Refactored event listener placement and removed auto-select from grid selection column.
- Moved the 'selected-items-changed' event listener from `_refreshJobData` to `_handleSelectedItems` method.
- Added optional chaining to the event listener in `firstUpdated` method.
- Removed `auto-select` attribute from the `vaadin-grid-selection-column`.
- Removed `_clearCheckboxes` call after terminating sessions.
1. Open the session list page.
2.Verify that all existing behaviors are working correctly.
3. Verify that the checkbox is enabled when you click on something other than the checkbox portion.
4. Verify that receiving an auto-refresh network request response does not clear the checkbox.
- Prevent clicking on a non-checkbox part of the webui session list to activate the checkbox, and prevent …
> fix: checkboxes in the webui session list are unchecked on auto-refresh, or clicks are not scoped

- react/src/hooks/useBackendAIImageMetaData.test.tsx
Added a new test case for handling exceptions in the `getImageMeta` function.
This is test code for https://github.com/lablup/backend.ai-webui/pull/2109
- Imported the `getImageFullName` function from the helper module.
- Added a new test case `getImageMeta handle exception` to the `useBackendAIImageMetaData` test suite.
- The new test case verifies that `getImageMeta` correctly handles and processes complex image metadata.
1. Run the test suite for `useBackendAIImageMetaData`.
2. Verify that the new test case passes successfully.
3. Ensure that the `getImageMeta` function correctly extracts the `key` and `tags` from the provided image metadata.
This change improves the test coverage for the `getImageMeta` function, specifically for handling complex image metadata scenarios. It ensures …
> chore: add test code for `getImageMeta`

- src/components/backend-ai-session-list.ts
Disable the session log button only when the status is 'RESTARTING', 'PENDING', or 'PULLING'. The difference from the previous version of this PR is the disabling condition for the 'PREPARING' status. After this PR, the button is enabled.
Updated the condition for displaying the control button in the session list. Replaced multiple status checks with a single array inclusion check for 'RESTARTING', 'PENDING', and 'PULLING' statuses.
1. Navigate to the session list view.
2. Create sessions with various statuses.
3. Verify that the control button appears correctly for running sessions.
4. Ensure the button doesn't appear for sessions with 'RESTARTING', 'PENDING', or 'PULLING' status.
> fix: enable a session log button when `PREPARING`

- react/src/helper/index.tsx
- src/components/backend-ai-resource-monitor.ts
- src/components/backend-ai-resource-panel.ts
- src/components/backend-ai-session-list.ts
follows #2518 
resolves [Teams threads](https://teams.microsoft.com/l/message/19:eedd90a03a4d44b181161b0241b68a64@thread.tacv2/1724737890117?tenantId=13c6a44d-9b52-4b9e-aa34-0513ee7131f2&groupId=b1f3bcf4-facf-40d3-94ab-169abb4f0f52&parentMessageId=1724640841809&teamName=customers%20%26%20clients&channelName=SEC%20GTR&createdTime=1724737890117)
Improved formatting of RAM and GPU memory usage display in session list.
- Added a new static method `_prefixFormatWithTrailingZeros` to format numbers with a fixed number of decimal places.
- Updated the RAM and GPU memory usage display to use the new formatting method, ensuring consistent decimal places.
1. Open the session list view.
2. Create or connect to a session with active resource usage.
3. Verify that the RAM and GPU memory usage values …
> fix: apply decimal place rounding to session usage

- .prettierignore
- e2e/.prettierrc.json
- e2e/agent.test.ts
- e2e/environment.test.ts
- e2e/login.test.ts
- e2e/session.test.ts
- e2e/test-util-antd.ts
- e2e/test-util.ts
- e2e/vfolder.test.ts
- package.json
e2e test for NEO session creation and `imageList`
Test:
- create and terminate a session without setting anything except the session name.  
- rendering image list
- install image
- modify image resource limit
- manage apps
> e2e: test NEO session launcher and imageList 

- react/src/components/MainLayout/WebUISider.tsx
- react/src/pages/StartPage.tsx
- resources/theme.json
> refactor: replace svg as customIcon component

- e2e/test-util.ts
- react/src/hooks/index.tsx
- react/src/hooks/useBackendAIImageMetaData.test.tsx
Refactored useBackendAIImageMetaData hook and improved its test suite.
This will solve [the GitHub Action failure.](https://github.com/lablup/backend.ai-webui/runs/29470763524)
- Simplified the useSuspenseTanQuery in useBackendAIImageMetaData hook by removing unnecessary type casting and promise chaining.
- Updated the test suite for useBackendAIImageMetaData:
- The handler of the `waitFor` function in `@testing-library/react` should return a promise if it's an async action. [ref](https://testing-library.com/docs/dom-testing-library/api-async/#waitfor)
- For the `waitFor`, use `toBeTruthy` instead of `toBeDefined` because `expect(null).toBeDefined();` pass the test. 
1. Run the existing test suite for useBackendAIImageMetaData.
2. Verify that all tests pass and cover the expected …
> fix: useBackendAIImageMetaData test code related to `waitFor`

- config.toml.sample
- react/src/components/MainLayout/WebUIHeader.tsx
- react/src/components/TimeContainer.tsx
- react/src/hooks/index.tsx
- resources/i18n/de.json
- resources/i18n/el.json
- resources/i18n/en.json
- resources/i18n/es.json
- resources/i18n/fi.json
- resources/i18n/fr.json
- resources/i18n/id.json
- resources/i18n/it.json
- resources/i18n/ja.json
- resources/i18n/ko.json
- resources/i18n/mn.json
- resources/i18n/ms.json
- resources/i18n/pl.json
- resources/i18n/pt-BR.json
- resources/i18n/pt.json
- resources/i18n/ru.json
- resources/i18n/tr.json
- resources/i18n/vi.json
- resources/i18n/zh-CN.json
- resources/i18n/zh-TW.json
- src/components/backend-ai-login.ts
- src/lib/backend.ai-client-esm.ts
Related: [backend.ai#2456](https://github.com/lablup/backend.ai/pull/2456)
This PR refactors TimeContainer component to be used as counting down valid login session time received from server.
> Prerequisites: 
> 1. Apply your Core version to [backend.ai#2456](https://github.com/lablup/backend.ai/pull/2456)
> 2. add `login_session_extension_sec` in  "[session]" section of webserver configuration file. (for test, please input short amount of time such as 30sec or 15sec.)
> 3. restart Backend.AI Webserver process.
1. See until the time passes on right side of header.
2. Click `Extend` button on the right top of header.
3. Wait until 5 or 3 seconds left and Click the `Extend` button again.
4. See session login time extension works.
> add: login session extension feature with UI button

- react/src/components/ImageList.tsx
- react/src/components/ResourceNumber.tsx
After #2615, the Resource Number displays an infinity symbol unexpectedly.
This PR fixes that bug and refactors the code related to the `max` display.
> Fix: Resource Number displays an infinity symbol unexpectedly

- src/components/backend-ai-login.ts
This PR resolves the bug where `maxGaudi2DevicesPerContainer` was not being applied.
- Load the client configuration to include the `maxGaudi2DevicesPerContainer` value.
> fix: missing load the `maxGaudi2DevicesPerContainer`

- src/components/backend-ai-session-launcher.ts
Updated NPU device handling for Gaudi2 in session launcher
Modified the condition for handling Gaudi2 devices in the session launcher. The check for 'gaudi.device' has been removed, leaving only the check for 'gaudi2.device'.
1. Navigate to the session launcher
2. Verify that Gaudi2 devices are correctly recognized and handled
3. Ensure that 'gaudi.device' is no longer treated the same as 'gaudi2.device'
This change likely aims to differentiate between Gaudi and Gaudi2 devices, ensuring that only Gaudi2 devices are processed with the specific logic in this section. This may be necessary for accurate resource allocation or performance optimization specific to Gaudi2 hardware.
---
> fix: Remove unused device `gaudi.device`

- src/components/backend-ai-session-list.ts
> After https://github.com/lablup/backend.ai-webui/pull/2640/files PR, With the use of ternary operators, the traditional string '/' has been marked as an arithmetic operation to represent Ratio.
Updated session list display to show absolute memory usage instead of percentage.
- Modified the memory usage display in the session list to show absolute values in GiB instead of percentages.
- Removed the calculation that divided current memory usage by total capacity.
- Adjusted the decimal precision for memory display from 2 to 1 for system memory and kept it at 2 for CUDA memory.
- Added a console log statement to output row data for debugging purposes.
1. Navigate to the session list view.
2. Create or observe existing sessions in 'batch', 'interactive', 'inference', or 'running' states.
3. …
> fix: Change resource display basis from Ratio to current amount
